aws/aws-sdk-js-v3

README.md

Operation methods return a `Promise` since they are asynchronous.

Added missing "await" in README example

---

.travis.yml
packages/middleware-stack/src/index.spec.ts
packages/node-http-handler/src/node-http-handler.spec.ts
packages/service-model/src/TreeModel/deepCopy.fixture.ts

fix #154 
* remove [type-unsafe-ly](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#caveats) using of `.bind()`;
* fix a generic issue with `deepCopy()`;
Could ping the `typescript` dependency version of `middleware-stack` package, but It's better to update the test

Support Typescript 3.2 and enable Travis-CI

---

lerna.json

Current Lerna 2.0.0 is too old to support bumping prerelease version.

Update lerna version

---

package.json

Moving jest, lerna and typescript under devDependencies where they belong.
As described in Contributing.md, the following commands were successfully run:
* npm install
* npm run bootstrap
* npm test

Move jest, lerna and ts to devDependencies

---

packages/service-types-generator/src/clientReadme.ts

Fix for import statement on generated readme
also update Stack Overflow url

fix import in generated readme

---

CONTRIBUTING.md

Improvement for https://github.com/aws/aws-sdk-js-v3/issues/172

clarify setup steps for using package-generator

---

packages/client-sqs-node/README.md
packages/client-sqs-node/commands/AddPermissionCommand.ts
packages/client-sqs-node/commands/ChangeMessageVisibilityBatchCommand.ts
packages/client-sqs-node/commands/ChangeMessageVisibilityCommand.ts
packages/client-sqs-node/commands/CreateQueueCommand.ts
packages/client-sqs-node/commands/DeleteMessageBatchCommand.ts
packages/client-sqs-node/commands/DeleteMessageCommand.ts
packages/client-sqs-node/commands/DeleteQueueCommand.ts
packages/client-sqs-node/commands/GetQueueAttributesCommand.ts
packages/client-sqs-node/commands/GetQueueUrlCommand.ts
packages/client-sqs-node/commands/ListDeadLetterSourceQueuesCommand.ts
packages/client-sqs-node/commands/ListQueueTagsCommand.ts
packages/client-sqs-node/commands/ListQueuesCommand.ts
packages/client-sqs-node/commands/PurgeQueueCommand.ts
packages/client-sqs-node/commands/ReceiveMessageCommand.ts
packages/client-sqs-node/commands/RemovePermissionCommand.ts
packages/client-sqs-node/commands/SendMessageBatchCommand.ts
packages/client-sqs-node/commands/SendMessageCommand.ts
packages/client-sqs-node/commands/SetQueueAttributesCommand.ts
packages/client-sqs-node/commands/TagQueueCommand.ts
packages/client-sqs-node/commands/UntagQueueCommand.ts
packages/client-sqs-node/model/ServiceMetadata.ts
packages/service-types-generator/src/Components/Command/command.ts
packages/service-types-generator/src/SmokeTestGenerator.ts
packages/service-types-generator/src/internalImports.ts

You can now export useful interfaces from commands.
Previously you need to import interfaces else where
```javascript
import { AddPermissionCommand } from '@aws-sdk/client-sqs-client/commands/AddPermissionCommand';
import {AddPermissionInput, AddPermissionOutput, AddPermissionExceptionsUnion} from '@aws-sdk/client-sqs-client';
```
Now you can just:
```javascript
import { 
AddPermissionCommand,
AddPermissionInput, 
AddPermissionOutput, 
AddPermissionExceptionsUnion
} from  '@aws-sdk/client-sqs-client/commands/AddPermissionCommand';
```
The first commit is the actual code change.

Export more interfaces from command

---

packages/package-generator/src/clientModuleIdentifier.spec.ts
packages/package-generator/src/clientModuleIdentifier.ts
packages/package-generator/src/commands/ImportModelsCommand.ts

Currently, V3 SDK supports generating service client for all the major API versions. For example, DynamoDB model has to major versions: 2011-12-05 and 2012-08-10. The SDK will generate 2 service clients accordingly: client-dynamodb-node and client-dynamodb-v2-node. This change will make codegen to generate client only with the newest API version, which mean, there won’t be client-dynamodb-v2-node client but only client-dynamodb-node client. Here’s the rationale:
* Different major API versions are usually backward compatible. There’s no need to generate client for older API version. Other SDKs(like Ruby) never ship the older version, they never get customer requesting for older clients.
* Some services have excessive api versions(CloudFront has 9), that could make excessive number of …

fix: remove api version number in client identifier

---

CONTRIBUTING.md
scripts/rebuildClients.js
scripts/utils/ModelFinder.js
scripts/utils/constants.js

Add a script to re-generate service client in batch. This will make regenerating clients easier. And running is will be required before opening a pull request
/cc @klaytaybai

chore: batch rebuild clients script

---

packages/client-sqs-node/model/ServiceMetadata.ts
packages/service-types-generator/src/Components/Model/ServiceMetadata.ts
packages/types/src/protocol.ts

Fix the type discrepency of xmlNamespace. Currently services like ec2 will generate xmlNamespace like `[object Object]`.

fix: generate model metadata xmlNamespace properly

---

models/importexport/2010-06-01/service-2.json
packages/package-generator/src/ModuleGenerator.spec.ts
packages/package-generator/src/ModuleGenerator.ts
packages/package-generator/src/commands/ImportModelsCommand.ts
packages/package-generator/src/importModule.ts

When generating any model, the changelog within to model shouldn't be reset. This change will preserve the CHANGELOG.md when regenerating the package.

feat: make client changelog preservable

---

CONTRIBUTING.md
package.json
packages/package-generator/src/commands/ImportClientPackageCommand.ts
packages/package-generator/src/commands/ImportModelsCommand.ts
scripts/rebuildClients.js

I also updated the package generator's import-all command to make it able to specify the run time and version of generated clients; The removed imports are because of no reference.

chore: rename npm script and update package generation command

---

packages/xml-body-parser/src/index.spec.ts
packages/xml-body-parser/src/index.ts

Now when there is only one item in a flattened list in an xml response, the parser will mistakenly give undefined result. This is because the xml body parser uses the wrong reference to refer the list entry in the parsed object from xml response. This fixes the issue.

fix(xml-body-parser): handle parsing flattened list

---

packages/client-codecommit-node/README.md
packages/client-cognito-identity-browser/README.md
packages/client-dynamodb-browser/README.md
packages/client-dynamodb-node/README.md
packages/client-glacier-node/README.md
packages/client-kinesis-browser/README.md
packages/client-kms-browser/README.md
packages/client-kms-node/README.md
packages/client-lambda-node/README.md
packages/client-pinpoint-browser/README.md
packages/client-s3-browser/README.md
packages/client-s3-node/README.md
packages/client-sqs-node/README.md
packages/client-xray-node/README.md
packages/service-types-generator/src/clientReadme.ts

Fixes a few typo/wording issues in the client README generator.

fix typos in readme generator

---

package.json

Docs:
* Prettier pre-commit hook https://prettier.io/docs/en/precommit.html
* Using lint-staged in a multi package monorepo http://bit.ly/2DFStRB
N/A
* PR for running prettier on existing files is posted at https://github.com/aws/aws-sdk-js-v3/pull/224
* This PR ensures that prettier is automatically run on pre-commit, as shown in the example below

Enable running prettier on precommit using husky and lint-staged

---

packages/build-types/package.json
packages/package-generator/package.json
packages/service-model/package.json
packages/service-types-generator/package.json

*Description of changes*
We shouldn't publish code generator packages to NPM. So mark them private. Each of the 4 packages only have dependents within the 4 packages. In other word, the 4 packages are self contained. So marking them as private should break any other packages

feat: mark code generator packages as private

---

packages/middleware-stack/src/index.spec.ts
packages/middleware-stack/src/index.ts
packages/types/src/middleware.ts

Add a filter function to middleware stack class. This enables you to make copy of middleware stack with specific stats(priority, step, tags). 

 feat(middleware-stack): add filter() function to middleware stack

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

default workspace settings:
* editor.tabSize: 2
* editor.formatOnSave: true
N/A
add vscode extension recommendation for prettier along with default workspace settings
The below modal will be shown to the developer when the workspace is opened in VSCode:
On clicking "Show recommendations", Prettier code formatter will be shown:

chore: add vscode extension recommendation for prettier

---

package.json

N/A
* Prettier was run on TS, MD and JSON files in packages folder in #227
* Support for running prettier on precommit was added in #225, but we MD files weren't added
* This PR adds MD extension for prettifying on precommit

fix: prettify markdown files on precommit

---

packages/util-create-request/README.md

N/A
* The npm badges were added to all packages in #251
* The package `util-create-request` was under development in parallel in #257
* This PR adds the npm badge for `@aws-sdk/util-create-request`, the package version number and downloads will appear once it's publish to npm

fix: add npm badge for @aws-sdk/util-create-request

---

.github/lock.yml

N/A
* This adds settings for [lock bot](https://github.com/apps/lock)
* Once this PR is merged, we'll enable the bot on this repo. It'll automatically lock closed issues and PRs after 14 days of inactivity.
* This change is done to avoid discussions on closed issue like https://github.com/aws/aws-sdk-js/issues/2553 or closed PRs like https://github.com/aws/aws-sdk-js/pull/1391, we plan to introduce it on v2 once it successfully works on v3

chore: add settings for lock bot

---

.github/lock.yml

As discussed internally
N/A
reduces daysUntilLock from 14 to 7 in lock bot settings

doc: reduce daysUntilLock from 14 to 7

---

packages/client-codecommit-node/CodeCommitConfiguration.ts
packages/client-cognito-identity-browser/CognitoIdentityConfiguration.ts
packages/client-dynamodb-browser/DynamoDBConfiguration.ts
packages/client-dynamodb-node/DynamoDBConfiguration.ts
packages/client-glacier-node/GlacierConfiguration.ts
packages/client-kinesis-browser/KinesisConfiguration.ts
packages/client-kms-browser/KMSConfiguration.ts
packages/client-kms-node/KMSConfiguration.ts
packages/client-lambda-node/LambdaConfiguration.ts
packages/client-pinpoint-browser/PinpointConfiguration.ts
packages/client-s3-browser/S3Configuration.ts
packages/client-s3-node/S3Configuration.ts
packages/client-sqs-node/SQSConfiguration.ts
packages/client-xray-node/XRayConfiguration.ts
packages/service-types-generator/src/ServiceCustomizations/customizationsFromModel/signatureCustomizations.ts

#283 
Fix the wrong configuration in Service client config as well as in code generator. This bug can result in any request with path containing special characters results in `SignatureMismatch`.

Fix SigV4 signer configuration in service clients

---

packages/package-generator/src/ClientModuleGenerator.ts
packages/service-types-generator/src/SmokeTestGenerator.ts

This is will be caught when we reintroduce client generation scripts in CI
They were removed in https://github.com/aws/aws-sdk-js-v3/pull/231
The CodeGen will be updated along with dependencies when CI fails
N/A
Updates dependencies in CodeGen
Confirmed that package.json is not updated when `node scripts/rebuildClients.js` is run

chore: update dependencies in CodeGen

---

greenkeeper.json

N/A
* This PR adds jasmine and karma-* to ignore array in greenkeeper
* This is done to avoid PRs like #301 temporarily to fix CodeGen
* These dependencies can be remove from ignored dependencies, when we reintroduce CodeGen script in CI or remove the dependencies

chore: ignore jasmine and karma-* in greenkeeper

---

packages/client-codecommit-node/CodeCommitConfiguration.ts
packages/client-codecommit-node/model/ServiceMetadata.ts
packages/client-dynamodb-node/DynamoDBConfiguration.ts
packages/client-dynamodb-node/model/ServiceMetadata.ts
packages/client-glacier-node/GlacierConfiguration.ts
packages/client-glacier-node/model/ServiceMetadata.ts
packages/client-kms-node/KMSConfiguration.ts
packages/client-kms-node/model/ServiceMetadata.ts
packages/client-lambda-node/LambdaConfiguration.ts
packages/client-lambda-node/model/ServiceMetadata.ts
packages/client-s3-node/S3Configuration.ts
packages/client-s3-node/model/ServiceMetadata.ts
packages/client-sqs-node/SQSConfiguration.ts
packages/client-sqs-node/model/ServiceMetadata.ts
packages/client-xray-node/XRayConfiguration.ts
packages/client-xray-node/model/ServiceMetadata.ts
packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts
packages/service-types-generator/src/ServiceCustomizations/customizationsFromModel/httpConfigurationProperties.ts
packages/service-types-generator/src/ServiceCustomizations/customizationsFromModel/index.ts
packages/types/src/http.ts

https://github.com/aws/aws-sdk-js/issues/2571
* added keepAlive in NodeHttpOptions
* modified node-http-handler to accept keepAlive
* set default keepAlive to true
* ran `node scripts/rebuildClients.ts` to update node clients

feat: node-http-handler set default keep-alive to true

---

packages/client-s3-browser/S3Client.ts
packages/client-s3-browser/model/ServiceMetadata.ts
packages/client-s3-browser/package.json
packages/client-s3-node/S3Client.ts
packages/client-s3-node/package.json
packages/middleware-sdk-s3/.gitignore
packages/middleware-sdk-s3/.npmignore
packages/middleware-sdk-s3/LICENSE
packages/middleware-sdk-s3/README.md
packages/middleware-sdk-s3/package.json
packages/middleware-sdk-s3/src/index.ts
packages/middleware-sdk-s3/src/validate-bucket-name.spec.ts
packages/middleware-sdk-s3/src/validate-bucket-name.ts
packages/middleware-sdk-s3/tsconfig.json
packages/middleware-sdk-s3/tsconfig.test.json
packages/service-types-generator/src/ServiceCustomizations/s3/index.ts
packages/service-types-generator/src/ServiceCustomizations/s3/validateBucketName.ts
packages/service-types-generator/src/internalImports.ts

https://github.com/aws/aws-sdk-js/issues/1046
https://github.com/aws/aws-sdk-js/issues/1035
https://github.com/aws/aws-sdk-js/issues/1572
S3 client will throw error if the `Bucket` parameter contains `/` that would interfere the signature V4.

feat: throw error when bucket name contains "/"

---

packages/service-types-generator/src/clientReadme.ts

Corrects TypeScript import example in client readme

fix(service-types-generator): correct readme import examples

---

packages/client-documentation-generator/package.json

This package is marked as private in #238. But it is a dev dependency of all service clients. It's now preventing users from building docs locally. This PR publish the package again.

fix(client-documentation-generator): make package public

---

.travis.yml
package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/335
While running tests, only include packages that have been updated since master
Doc: https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref
If there are no changes, it takes less than 1 min to run `yarn test` ([yarn-test.log](https://github.com/aws/aws-sdk-js-v3/files/3531549/yarn-test.log))

test: only include packages updates since master

---

.travis.yml

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/340
As per build log yarn is already present before before_install is run
Example log: https://travis-ci.org/aws/aws-sdk-js-v3/builds/575606372#L203-L243
Also, Travis CI supports yarn
Announcement: https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

chore: remove installation of yarn from travis

---

package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/342
travis-ci/push fails with `fatal: bad revision 'master'`, so switching to HEAD instead.
Testing done as follows:
* Confirmed that travis-ci/push will succeed by following the steps from https://travis-ci.org/aws/aws-sdk-js-v3/builds/575606345 on dev machine
* Confirmed that travis-ci/pr will succeed by following the steps from https://travis-ci.org/aws/aws-sdk-js-v3/builds/575606372 on dev machine

fix: lerna pretest --since HEAD

---

package.json

Reverts aws/aws-sdk-js-v3#343
This is causing empty diff
Example build log https://travis-ci.org/aws/aws-sdk-js-v3/builds/575946746

chore: revert "fix: lerna pretest --since HEAD"

---

package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/342
travis-ci/push fails with `fatal: bad revision 'master'`, so switching to `HEAD^` instead as per https://github.com/aws/aws-sdk-js-v3/issues/342#issuecomment-524439104
Testing done along with fix as follows:
* performed operations from travis-ci/push ([travis-ci-push-yarn-test.log](https://github.com/aws/aws-sdk-js-v3/files/3535983/travis-ci-push-yarn-test.log))
* performed operations from travis-ci/pr ([travis-ci-pr-yarn-test.log](https://github.com/aws/aws-sdk-js-v3/files/3535985/travis-ci-pr-yarn-test.log))
* confirmed that build succeeds in workspace ([workspace-yarn-test.log](https://github.com/aws/aws-sdk-js-v3/files/3535987/workspace-yarn-test.log)) …

fix: lerna pretest --since HEAD^

---

lerna.json
packages/service-types-generator/scripts/buildInternalImportMap.js

N/A
When using yarn workspaces, packages in lerna.json are overridden by the value from package.json/workspaces ([doc](http://bit.ly/2MvPL7d))

chore: remove packages folder from lerna.json

---

README.md

GreenKeeper was removed in #331
we are now using dependabot

doc: remove greenkeeper badge

---

.github/lock.yml

N/A
This will lock all 14 inactive closed issues before 2019-02-01 ([search link](https://github.com/aws/aws-sdk-js-v3/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+closed%3A%3C2019-02-01))

chore: lock all inactive past issues

---

clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts

Deserialize errors using x-amzn-TypeError header instead of status code.

feat: deserialize with error header

---

clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts

re-introduces changes from https://github.com/aws/aws-sdk-js-v3/pull/385

feat: deserialize error from header

---

.travis.yml
buildspec.yml

Retry of #380 after setting token from aws-sdk-js-automation in our CodeBuild
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/346
Enabled github-codebuild-logs to make CodeBuild logs accessible
Refs: https://github.com/jlhood/github-codebuild-logs

chore: remove TravisCI

---

clients/node/client-rds-data-node/commands/ExecuteStatementCommand.ts

Remove stubbed `any` types for input/output and instead use generated commands.

fix: use generated types in commands

---

packages/retry-middleware/src/defaultStrategy.ts
packages/retry-middleware/src/index.spec.ts
packages/retry-middleware/src/index.ts
packages/retry-middleware/src/retryMiddleware.ts
packages/types/src/util.ts

Put retry logic into RetryStrategy itself. Keep retryMiddleware minimal.

feat: add RetryStrategy class and retryMiddleware implementation

---

buildspec.yml

N/A
experiment without installing yarn in buildspec

chore: use npm install -g yarn in buildspec

---

clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts
clients/node/client-rds-data-node/protocol/ExecuteStatement.ts
packages/protocol-rest-json/src/index.ts
packages/types/src/deserializer.ts
packages/types/src/serializer.ts

fix: remove duplicated declaration of endpoints

---

packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts
packages/signature-v4/src/getCanonicalHeaders.spec.ts
packages/signature-v4/src/getCanonicalHeaders.ts
packages/types/src/signature.ts

Add support to override the set of unsignableHeaders; in cases where signing those headers (such as user-agent) would be desirable.
Added a new set of signableHeaders, which is checked for inclusion before the specified header is removed for being an unsignable one.

feat(signature-v4): add support to override the set of unsignableHeaders

---

README.md

TravisCI was removed in https://github.com/aws/aws-sdk-js-v3/pull/386
* chore: replace TravisCI badge with that CodeBuild
* It currently shows "unknown", it could be because it was just created by following [these instructions](https://docs.aws.amazon.com/en_pv/codebuild/latest/userguide/sample-build-badges)
* AWS CDK badge for reference https://github.com/aws/aws-cdk/blob/master/README.md

chore: replace TravisCI badge with that CodeBuild

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1_1.java

This commit adds support for generating the bodies of functions that
serialize complex shapes that will be in an HTTP document body.

Add document shape serialization bodies

---

packages/util-user-agent-browser/src/index.spec.ts
packages/util-user-agent-browser/src/index.ts

*Issue #, if available:* N/A
Avoid appending to user agent header when the existing value is undefined or null to avoid getting header values as "undefined myUserAgent"

fix: do not append to undefined/null header values

---

clients/client-rds-data/RdsDataServiceClient.ts
packages/config-resolver/src/EndpointsConfig.ts
packages/config-resolver/src/RegionConfig.ts
packages/middleware-retry/src/configurations.ts
packages/middleware-retry/src/retryMiddleware.ts
packages/middleware-signing/src/configurations.ts
packages/middleware-signing/src/middleware.ts
packages/middleware-user-agent/src/configurations.ts
packages/middleware-user-agent/src/middleware.ts

Brings naming of input and resolved config interfaces in line with awslabs/smithy-typescript@a5734d2

fix: update input and resolved naming

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts

bumps smithy dependency to 0.9.5 to match smithy-typescript.

fix: bump smithy dependency to 0.9.5

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1_1.java

*Add deserialization support for rest-json-1.1*
This commit adds support for deserializing responses, including errors
and complex document contents for the aws.rest-json-1.1 protocol.
It also includes fixes for serialization functionality found in the
process of writing the above updates.
-----
*Add parseBody function generation*

Add deserialization support for aws.rest-json-1.1

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfigTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegrationTest.java
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/serviceid.smithy

This commit adds AWS runtime config integrations and fixes dependency
management to match smithy-typescript. It also fixes an issue where the
SymbolProvider decoration was not happening.

chore: fix AWS integrations and dependencies

---

packages/smithy-client/src/client.ts
packages/types/src/client.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/449
chore: remove unused client.send with callbacks

chore: remove unused client.send with callbacks

---

clients/client-rds-data/commands/ExecuteStatementCommand.ts
packages/smithy-client/src/command.ts

Makes ClientInput and ClientOutput generics optional on Command.
Matching update in Codegen: https://github.com/awslabs/smithy-typescript/pull/30/commits/2344f57fa1d18e1cbaf72c0eb3ac6fb955f642e4

feat: make command generic types optional

---

packages/smithy-client/src/client.ts
packages/types/src/client.ts

This reverts commit 60105ee5792aebbfa78a6b1a84714f881ed98be7.
N/A
We decided to reintroduce legacy style clients as discussed in https://github.com/aws/aws-sdk-js-v3/issues/364

chore: reintroduce client.send overloads with callbacks

---

.gitignore
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddProtocols.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1_0.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

This commit updates the support for `aws.rest-json-1.1` to build atop
the refactor of protocol generation done in smithy-typescript. It
also introduces support for the `aws.rest-json-1.0` protocol.
In doing so, general components were built atop the abstractions
provided. The aws.rest-json-1.* set of protocols serialize BigInteger
and BigDecimal shapes as JSON numbers on the wire, so an implementation
of the DocumentMember[Deser|Ser]Visitor was created to fail generation.
Implementations of the DocumentShape[Deser|Ser]Visitor classes are
also included to support serde of shapes in request and response
bodies.
A rest-json implementation of the `HttpBindingProtocolGenerator` has been
created to combine the above aspects and handling of document bodies.
By submitting this pull request, I …

Update HTTP binding protocol generation

---

packages/middleware-signing/src/configurations.ts
packages/middleware-signing/src/middleware.spec.ts
packages/middleware-signing/src/middleware.ts

N/A
Enables clockSkew correction by default
In v2:
* The `applyClockOffset` is called in name `HTTP_HEADERS` with eventName `httpHeaders` ([code](https://github.com/aws/aws-sdk-js/blob/1ca7b9894d72b01425852c079cb47e378e206886/lib/event_listeners.js#L360-L377))
* The code which adds listeners from AWS.EventListeners.Core (and others) to request ([code](https://github.com/aws/aws-sdk-js/blob/1ca7b9894d72b01425852c079cb47e378e206886/lib/service.js#L259-L285))
* The function which calls httpHeaders callback ([code](https://github.com/aws/aws-sdk-js/blob/1ca7b9894d72b01425852c079cb47e378e206886/lib/event_listeners.js#L270-L273))
* The callback is passed to handleRequest in executeSend …

feat: enable clockSkew correction by default

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
packages/middleware-sdk-api-gateway/src/index.spec.ts
packages/middleware-sdk-api-gateway/src/index.ts

Updates and applies middleware-sdk-api-gateway

Accepts header middleware

---

README.md

Refs: https://github.com/aws/aws-sdk-js-v3/issues/364
We decided to ship legacy interface in v3, adding this note so that customers are aware of the bundle size differences

doc: bundle style difference between non-modular and modular approaches

---

codegen/config/checkstyle/suppressions.xml
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsJsonRpc1_0.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsJsonRpc1_1.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1_0.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1_1.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

This commit adds support for the AWS JSON RPC protocols,
building on top of the `HttpRpcProtocolGenerator` via the
`JsonRpcProtocolGenerator` abstract class. Specific
implementations are provided for `aws.json-1.0` and
`aws.json-1.1`.
Shared code between the JSON-based `ProtocolGenerator`
implementations has been moved to a utils class, specific
implementations have been updated.
Insubstantial tweaks and documentation updates have also
been made for clarity.

Add support for AWS JSON RPC protocols

---

packages/middleware-stack/src/MiddlewareStack.spec.ts
packages/middleware-stack/src/MiddlewareStack.ts

fix: fix bugs when recursively appending middleware

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

Updates for awslabs/smithy-typescript#44

Update for error generation refactoring

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

Includes a minor refactoring of the `JsonProtocolUtils` to be a more generic `AwsProtocolUtils`.
Generated header shows up as follows:
```ts
export async function serializeAws_restJson1_1PutFooCommand(
input: BatchExecuteStatementCommandInput,
context: SerdeContext
): Promise<__HttpRequest> {
const headers: any = {};
headers['Content-Type'] = "application/json";
headers['x-amz-content-sha256'] = 'UNSIGNED_PAYLOAD';
let body: any = {};
if (input.foo !== undefined) {
body = input.foo;
}
return new __HttpRequest({
...context.endpoint,
protocol: "https",
method: "PUT",
path: "/PutFoo",
headers: headers,
body: body,
});
}
```

Add support for unsignedPayloads in SigV4

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java

Generated header shows up as follows:
```ts
export async function serializeAws_restJson1_1PutFooCommand(
input: PutFooCommandInput,
context: SerdeContext
): Promise<__HttpRequest> {
const headers: any = {};
headers['Content-Type'] = "application/x-amz-json-1.1";
headers['X-Amz-Target'] = "FooService.PutFoo";
let body: any = {};
if (input.foo !== undefined) {
body = input.foo;
}
return new __HttpRequest({
...context.endpoint,
protocol: "https",
method: "PUT",
path: "/PutFoo",
headers: headers,
body: body,
});
}
```

Add X-Amz-Target header to JsonRpc protocols

---

features/dms/step_definitions/dms.js
features/dynamodb/crc32.feature

N/A
* integ tests for database-migration-service from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @dms
```

feat: integ tests for database-migration-service from v2

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsJsonRpc1_0.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsJsonRpc1_1.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegrationTest.java

This commit includes assorted updates to the protocol generators
to improve reusability, set proper visibility, use an import alias
for SerdeContext, and other minor updates.
It also includes a fix for handling the unknown case when
deserializing a union.
-----
Use Model instead of deprecated ShapeIndex. This commit will require using the latest version of Smithy published locally.
-----
Use better name for document body shape serde gen

feat: update JSON protocol codegen for cleanliness

---

packages/middleware-expect-continue/src/index.ts

Adds missing unused argument to comply with codegen conventions for middleware/plugins

fix: add argument to getAddExpectContinuePlugin

---

packages/middleware-apply-body-checksum/src/applyMd5BodyChecksumMiddleware.spec.ts
packages/middleware-apply-body-checksum/src/applyMd5BodyChecksumMiddleware.ts
packages/middleware-apply-body-checksum/src/md5Configuration.ts

removes headerName config option on applyMd5BodyChecksumMiddleware.  Instead, this middleware only sets the "Content-MD5" header.

feat: remove headerName config option

---

packages/middleware-location-constraint/src/index.spec.ts
packages/middleware-location-constraint/src/index.ts

Resolve region before using in locationConstraintMiddleware

fix: resolve region

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java

Fixes md5-js dependency version

fix: md5-js version

---

packages/config-resolver/src/EndpointsConfig.ts

fix: parseurl in Node returns only pathname when protocol not specified

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
packages/middleware-host-header/.gitignore
packages/middleware-host-header/.npmignore
packages/middleware-host-header/LICENSE
packages/middleware-host-header/README.md
packages/middleware-host-header/package.json
packages/middleware-host-header/src/index.ts
packages/middleware-host-header/tsconfig.json
packages/middleware-host-header/tsconfig.test.json
packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts
packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/smithy-client/src/client.ts
packages/types/src/transfer.ts

1. Add a `metadata` property to `RequestHandler` interface that contains self-describing information of the handler. In this case, Node H1 handler and Node H2 handler can identify themselves as for H1 request or H2 request. 
2. Add a middleware adding `host` header or `:authority` header respectively, according to `RequestHandler`'s `metadata` for H1 or H2. Separating this functionality from SignatureV4 signer because Node H2 doesn't allow sending `host` header in H2 request specificly, so the signer shouldn't add the `host` header blindly.

feat: add a middleware inserting right host header

---

packages/middleware-sdk-api-gateway/src/index.ts

adds missing getAcceptsHeaderPlugin param used by convention in codegen

fix: missing getAcceptsHeaderPlugin param

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java

The servicePredicate is automatically set to false when the operationPredicate is used: https://github.com/awslabs/smithy-typescript/blob/5dffb8a0060023af4c0e1f809d116ab77492cdde/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L466
This merges the ServiceId check into the operationPredicate to only apply these plugins to specific operations on specific services.

fix: merge plugin predicates

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
packages/middleware-bucket-endpoint/src/index.spec.ts
packages/middleware-bucket-endpoint/src/index.ts

Fixes missing config resolution for BucketEndpointMiddleware.
Adds second plugin that applies the config resolution portion of the middleware to the S3 Client.

fix: add BucketEndpoint config plugin

---

features/dynamodb/step_definitions/dynamodb.js
features/dynamodb/tables.feature

* https://github.com/aws/aws-sdk-js/issues/2986
* https://github.com/aws/aws-sdk-js-v3/pull/480
* This code change deletes the table when dynamodb integration tests are completed
* It appends random string at the end of tableName, so that it doesn't the tableName is unique to particular run (say `aws-sdk-js-integration-shj93i6u6je`)
Confirmed that tests are successful:
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @dynamodb
```

fix: dynamodb integ test delete table

---

packages/middleware-bucket-endpoint/package.json
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.ts
packages/middleware-host-header/jest.config.js
packages/middleware-host-header/src/index.spec.ts
packages/middleware-host-header/src/index.ts

* Also fix issues in host-header middleware

fix: assure bucket endpoint middleware inserted before host-header-middleware

---

packages/util-format-url/src/index.spec.ts
packages/util-format-url/src/index.ts

Removes StreamType generic on HttpRequest and unused QueryParameterBag import.

fix: remove HttpRequest generic and unused import

---

features/cloudwatchlogs/step_definitions/cloudwatchlogs.js
packages/protocol-json-rpc/src/JsonRpcParser.ts

N/A
* integ tests for cloudwatchlogs from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cloudwatchlogs
```

feat: integ tests for cloudwatchlogs from v2

---

packages/middleware-expect-continue/src/index.spec.ts
packages/middleware-expect-continue/src/index.ts

Only set 100-continue header in node environment.
Uses runtime config added in https://github.com/awslabs/smithy-typescript/pull/64

fix: apply header only in node environment

---

packages/signature-v4/package.json
packages/signature-v4/src/SignatureV4.ts
packages/signature-v4/src/getCanonicalHeaders.spec.ts
packages/signature-v4/src/getCanonicalHeaders.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/585#issuecomment-569786412
* fixes issues with HTTPRequest while rebasing #474 to master
* confirmed that following command successfully executes:
```console
./node_modules/.bin/lerna run --scope '@aws-sdk/client-rds-data' --include-dependencies pretest
```

fix: issues with HTTPRequest while rebasing #474 to master

---

packages/middleware-bucket-endpoint/package.json
packages/middleware-sdk-api-gateway/package.json
packages/middleware-sdk-machinelearning/package.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/584
This dependency was missed in:
* https://github.com/aws/aws-sdk-js-v3/pull/473
* https://github.com/aws/aws-sdk-js-v3/pull/552
* https://github.com/aws/aws-sdk-js-v3/pull/553

fix: add @aws-sdk/protocol-http as a dependency

---

packages/remove-sensitive-logs/package.json
packages/remove-sensitive-logs/src/index.spec.ts
packages/remove-sensitive-logs/src/index.ts
packages/remove-sensitive-logs/src/shapes.fixture.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-569859880
remove usage of types from remove-sensitive-logs

fix: remove usage of types from remove-sensitive-logs

---

packages/response-metadata-extractor/package.json
packages/response-metadata-extractor/src/index.spec.ts
packages/response-metadata-extractor/src/index.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-569866333
import HttpResponse from protocol-http in response-metadata-extractor

fix: import HttpResponse from protocol-http

---

packages/util-error-constructor/src/index.spec.ts
packages/util-error-constructor/src/index.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-569868064
remove ServiceException from util-error-constructor

fix: remove ServiceException from util-error-constructor

---

packages/response-metadata-extractor/src/index.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-570065168
fix: update how HTTPResponse is created in response-metadata-extractor/src/index.spec.ts 

fix: update how HTTPResponse is created

---

packages/signature-v4/src/getCanonicalHeaders.spec.ts
packages/signature-v4/src/getCanonicalQuery.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/622
use httpRequestOptions in getCanonicalQuery.spec.ts

fix: use httpRequestOptions in signature-v4

---

buildspec.yml

N/A
* don't generate yarn.lock in CI
* Docs: https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile

chore: don't generate yarn.lock in CI

---

clients/client-rds-data/commands/BatchExecuteStatementCommand.ts
clients/client-rds-data/commands/BeginTransactionCommand.ts
clients/client-rds-data/commands/CommitTransactionCommand.ts
clients/client-rds-data/commands/ExecuteSqlCommand.ts
clients/client-rds-data/commands/ExecuteStatementCommand.ts
clients/client-rds-data/commands/RollbackTransactionCommand.ts
clients/client-rds-data/endpoints.ts
clients/client-rds-data/lib/smithy.ts
clients/client-rds-data/models/index.ts
clients/client-rds-data/protocols/Aws_restJson1_1.ts
clients/client-rds-data/runtimeConfig.browser.ts
clients/client-rds-data/runtimeConfig.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/615
* manually prettify client-rds-data
* this will happen on precommit hook once https://github.com/aws/aws-sdk-js-v3/pull/631 is merged 

chore: prettify client-rds-data

---

codegen/sdk-codegen/build.gradle.kts

Refs:
* Issue https://github.com/aws/aws-sdk-js-v3/issues/672
* Manual update https://github.com/aws/aws-sdk-js-v3/pull/666
* set initial version for packages to "0.1.0-preview.1"
* this should be later passed while calling typescript-codegen

chore: set initial version to 0.1.0-preview.1

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

Fixes parsing error returned without x-amzn-errortype header.
requires: https://github.com/awslabs/smithy-typescript/pull/83

fix: check error header

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
packages/middleware-sdk-api-gateway/src/index.spec.ts
packages/middleware-sdk-api-gateway/src/index.ts

Fixes Middleware for API Gateway to set the "accept" header, required to return the necessary content-type.
MDN for Accept header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

fix: accept header typo

---

scripts/generate-clients/code-prettify.js

Fixes https://github.com/aws/aws-sdk-js-v3/issues/707
* prettifies CODE_GEN_OUTPUT_DIR instead of each package to improve performance
* Tested on `c5.4xlarge` EC2 instance for generating 99 aws.json-1.1 clients:
* without this code change:
```console
$ time yarn generate-clients -m <dir-containing-json-1.1-models>
...
...
Done in 205.55s.
284.17s user 13.39s system 144% cpu 3:25.72 total
```
* with this code change:
```console
$ time yarn generate-clients -m <dir-containing-json-1.1-models>
...
...
Done in 132.67s.
177.20s user 7.31s system 138% cpu 2:12.84 total
```

fix: prettify CODE_GEN_OUTPUT_DIR to improve performance

---

packages/protocol-http/src/httpRequest.ts
packages/protocol-http/src/httpResponse.ts

This were introduced in prototyping proviously, but forgot to fix it.

fix(protocol-http): request/response object validation

---

package.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/690
* switch global version to 1.0.0-alpha
* Confirmed in node that
* `semver.inc("1.0.0-alpha.0", "prerelease")` returns `'1.0.0-alpha.1'`
* `semver.inc("1.0.0-beta.0", "prerelease")` returns `'1.0.0-beta.1'`

chore: switch global version to 1.0.0-alpha

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

Paired with https://github.com/awslabs/smithy-typescript/pull/66

fix: parse body only once for error response

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddProtocols.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java
packages/xml-builder/src/XmlNode.ts

Add support for AWS rest-xml protocol
This commit adds support for the `aws.rest-xml` protocol, building
on top of the `HttpBindingProtocolGenerator` for document and
payload serde.
Implementations of the `DocumentMember[Deser|Ser]Visitor` and the
`DocumentShape[Deser|Ser]Visitor` have been created that handle
Smithy's XML traits and their influence on protocol serde.
A minor update has been made to the `XmlNode` to allow for nodes to
be renamed, as the same structure may change XML node names when it
is bound to different locations.
-----
*Handles namespaces on payloads/services/structures:*
Payload:
```
if (input.Tagging !== undefined) {
contents = serializeAws_restXmlTagging(input.Tagging, context);
body = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
contents.addAttribute("xmlns", …
```

feat: add support for AWS rest-xml protocol

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java

Fixes awslabs/smithy-typescript#97
Use valueNode instead of keyNode for value's node.

fix: xml map serializer valueNode

---

packages/middleware-sdk-s3/jest.config.js

chore(middleware-sdk-s3): missing jest config

---

clients/client-s3-control/package.json

Adds missing package.json entry for s3-control middleware dependency.

fix: add missing middleware dep

---

packages/protocol-http/src/httpRequest.ts

Sometimes yarn/npm will install different version of protocol-http
package under individual clients and root node_modules because of
hoisting policy. Private class member will block the ts compiling
Reference: https://github.com/Microsoft/TypeScript/issues/18499

fix: remove private members in HttpRequest and HttpResponse

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddProtocols.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java

This commit adds support for the `aws.query` protocol, building
on top of the `HttpRpcProtocolGenerator` and `Xml[Member|Shape]DeserVisitor`
for document serde.
Implementations of the `Document[Member|Shape]SerVisitor` have been
created that handle form-urlencoded bodies, respecting Smithy's `@xmlName`
trait.
Assorted minor updates for abstraction and in coordination with updates
to the base class have also been made.
Depends on awslabs/smithy-typescript#102

feat: Add support for the aws.query protocol

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java

fixes: removes wrappedBody that is not required for JsonRPC requests

fix: remove wrapped body

---

packages/middleware-sdk-machinelearning/.gitignore
packages/middleware-sdk-s3-control/.gitignore
packages/middleware-sdk-s3/.gitignore

Fixes https://github.com/aws/aws-sdk-js-v3/issues/750
* add `*.tsbuildinfo` to `.gitignore`
* it's present in other packages, like https://github.com/aws/aws-sdk-js-v3/blob/abc42578e25c75668e147b32d96e78303fe8e9bc/packages/middleware-location-constraint/.gitignore#L5

chore: add *.tsbuildinfo to .gitignore

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java

This commit fixes a couple issues with generating code to deserialize
structure, union, or body members that target collection members.
1. Unflattened shapes that could return multiple entries in their
collection but only return one would result in an error at runtime
trying to iterate over an object like it was an Array.
2. Unflattened shapes that were not set in the provided output would
result in an error at runtime when trying to validate the entry exists
element without validating that its parent element existed.
This update also bumps the version of smithy-aws-traits to latest.
Fixes #765 

fix: multiple XML collection deserialization bugs

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/768
codegen with multiple XML collection deserialization bugs

fix: codegen with XML collection deserialization bugfixes

---

packages/middleware-sdk-rds/package.json
packages/middleware-sdk-rds/src/index.spec.ts
packages/middleware-sdk-rds/src/index.ts

fix for invalid query string parameter: uri escape presigned url in request

fix: uri escape presigned url

---

clients/client-iot-1click-projects/IoT1ClickProjects.ts
clients/client-iot-events-data/IoTEventsData.ts
clients/client-iot-jobs-data-plane/IoTJobsDataPlane.ts
clients/client-kinesis-video-archived-media/KinesisVideoArchivedMedia.ts
clients/client-lex-model-building-service/LexModelBuildingService.ts
clients/client-lex-runtime-service/LexRuntimeService.ts
clients/client-pinpoint-sms-voice/PinpointSMSVoice.ts
clients/client-sagemaker-a2i-runtime/SageMakerA2IRuntime.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/778
fix order of commands missed due to #778

chore: fix order of commands missed due to #778

---

clients/client-s3/runtimeConfig.browser.ts
clients/client-s3/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddStreamHasherDependency.java
packages/hash-blob-browser/src/index.spec.ts
packages/hash-blob-browser/src/index.ts
packages/hash-stream-node/src/index.spec.ts
packages/hash-stream-node/src/index.ts

Renames calculateSha256 to fileStreamHasher and blobHasher.  Each function takes a Hash constructor and thus can return other hashes beyond Sha256.
Updates S3 Client where these functions are currently used.

feat: rename calculateSha256 functions

---

packages/node-http-handler/src/node-http2-handler.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/487
commenting out flaky node-http2-handler test as it's failing multiple PRs

chore: comment out flaky node-http2-handler test

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
packages/middleware-sdk-ec2/.gitignore
packages/middleware-sdk-ec2/.npmignore
packages/middleware-sdk-ec2/CHANGELOG.md
packages/middleware-sdk-ec2/LICENSE
packages/middleware-sdk-ec2/README.md
packages/middleware-sdk-ec2/jest.config.js
packages/middleware-sdk-ec2/package.json
packages/middleware-sdk-ec2/src/fixture.ts
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-ec2/src/index.ts
packages/middleware-sdk-ec2/tsconfig.json
packages/middleware-sdk-ec2/tsconfig.test.json

Migrates and applies copySnapshotPresignedUrlMiddleware for EC2 clients

feat: migrate and apply copySnapshotPresignedUrlMiddleware

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddProtocols.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/Ec2ShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java

This commit adds support for the `aws.ec2` protocol, building on top
of the `HttpRpcProtocolGenerator`, `Xml[Member|Shape]DeserVisitor`,
and `Query[Member|Shape]SerVisitor` for document serde.
The `QueryShapeSerVisitor` has been opened up for re-use by the new
`Ec2ShapeSerVisitor` because `aws.ec2` is a specific version of the
`aws.query` protocol. Hooks have been made available to influence
the specific behavior that is updated.
This also fixes a critical bug with query list and map serialization
that would have resulted in runtime failues on serilaizing the member
target shape's contents.

feat: Add support for the aws.ec2 protocol

---

packages/util-create-request/package.json
packages/util-create-request/src/foo.fixture.ts
packages/util-create-request/src/index.spec.ts
packages/util-create-request/src/index.ts

fix: #788 
Use command.resolveMiddleware() to generate request instead of
concatenating middleware stacks manually. This fix
also includes `build` stage to creating request. Because build
stage sometimes contains necessary middleware to build a correct
request. For example, S3's bucket endpoint middleware is located
in build stage. Host header is also necessary, if users want to
sign the generated request directly.
Verify it works with s3 presigned url:
```js
const { createRequest } = require("@aws-sdk/util-create-request");
const {formatUrl} = require("@aws-sdk/util-format-url");
const {S3RequestPresigner} = require("@aws-sdk/s3-request-presigner");
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
(async () => { …
```

fix(util-create-request): fix creating undefined request

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java

This commit adds support for generating idempotency token values
when not set on input. These values are populated with a UUID v4
value provided by the `uuid` package.
This is done through setting the value on the provided input as to
not further complicate protocol specific member serialization.
-----
Related to awslabs/smithy-typescript#109
-----
Sample codegen:
```
import { v4 as generateIdempotencyToken } from "uuid";
if (input.ClientRequestToken === undefined) {
input.ClientRequestToken = generateIdempotencyToken();
}
```
-----

feat: Auto-fill idempotency token values

---

yarn.lock

Refs: https://github.com/aws/aws-sdk-js-v3/pull/815
* update yarn.lock with uuid dependency
* this was missed in https://github.com/aws/aws-sdk-js-v3/pull/815

chore: update yarn.lock with uuid dependency

---

packages/middleware-user-agent/src/configurations.ts
packages/middleware-user-agent/src/middleware.ts
packages/util-user-agent-browser/src/index.spec.ts
packages/util-user-agent-browser/src/index.ts
packages/util-user-agent-node/src/index.spec.ts
packages/util-user-agent-node/src/index.ts

For browser runtime, switch to `x-amz-user-agent` for user-agent header instead of `user-agent`.
Fixes: #792
Also cleans up unused functions.

feat: x-amz-user-agent for browser

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java

This commit updates some AWS protocols that wrap their error data
in additional elements.
Depends on awslabs/smithy-typescript#117
Fix for #763 
-----
Modeled error sample:
```
const deserializeAws_queryDBClusterEndpointNotFoundFaultResponse = async (
parsedOutput: any,
): Promise<DBClusterEndpointNotFoundFault> => {
const body = parsedOutput.body
const deserialized: any = deserializeAws_queryDBClusterEndpointNotFoundFault(body.Error, context); // <-- Note body.Error
const contents: DBClusterEndpointNotFoundFault = {
name: "DBClusterEndpointNotFoundFault",
$fault: "client",
$metadata: deserializeMetadata(parsedOutput),
...deserialized,
};
return contents;
};
```
Unmodeled error sample:
```
default:
const parsedBody = parsedOutput.body;
errorCode = errorCode || …
```

fix: Update AWS protocol error body locations

---

packages/middleware-location-constraint/src/index.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/838
`LocationConstraint` should not be set for us-east-1 region.
Also requires updated codgen from https://github.com/awslabs/smithy-typescript/pull/118

fix: no LocationConstraint for us-east-1

---

clients/client-s3/S3Client.ts
clients/client-s3/runtimeConfig.shared.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
packages/middleware-signing/src/configurations.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/845 and https://github.com/aws/aws-sdk-js-v3/issues/810
Enables escaping the path while signing for all clients and adds configuration to disable this for S3 only.

Enable path escaping for all clients except S3

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/871
Need to check that locations are not null before attempting to deserialize.

fix: check null locations

---

clients/client-personalize/package.json

Discussed internally in JS-1639, the release scripts are failing with the following error
```console
@aws-sdk/client-personalize: Package publishing exception
{ Error: Command failed: npm publish
npm WARN lifecycle @aws-sdk/client-personalize@1.0.0-alpha.17~prepublishOnly: cannot run in wd @aws-sdk/client-personalize@1.0.0-alpha.17 yarn build (wd=.)
npm notice 
npm notice package: @aws-sdk/client-personalize@1.0.0-alpha.17
```
* manually bump @aws-sdk/client-personalize
* this will skip `@aws-sdk/client-personalize@1.0.0-alpha.17` when release scripts are run, but release would succeed 

chore: manually bump @aws-sdk/client-personalize version

---

clients/client-personalize/package.json

Refs: https://github.com/aws/aws-sdk-js-v3/pull/886
* Due to some issue appears to be with npmjs, we'd manually bumped `@aws-sdk/client-personalize` version in #886 and did an npm publish of `1.0.0-alpha.18` locally (which was successful)
* This PR bumps the version to `1.0.0-alpha.18`  in package.json so that release script can release `1.0.0-alpha.19`

chore: manually bump @aws-sdk/client-personalize version again

---

scripts/generate-clients/copy-to-clients.js

chore: copy package.json properly

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java

Currently, the same `signingName` is written to `runtimeConfig.ts` `runtimeConfig.browser.ts`, and `runtimeconfig.shared.ts`.
Since this is the same across runtimes, it only needs to be written to the `runtimeConfig.shared.ts`.

fix: remove duplicate signingName config

---

packages/smithy-client/src/index.ts
packages/smithy-client/src/lazy-json.ts

This commit adds the `LazyJsonString` class that supports holding a
String with JSON contents, deserializing to JSON, and being built
from JSON like content.
[Sample of how this works in practice](https://typescript-play.js.org/#code/MYGwhgzhAEAyYC8CeApCB7AdgZQC4CcBLTAc2gFMAPXczAExjyNOgG8AoaaO8icosCEIJyKbAHkAcgAoAlAC5oYTEjacu0fOVwBXfJmhipAOgAOYfH2kQdp-sdzomxEnNkBudQF926x0ZkFaAgCFzUNTW09Axs7fAcnUNI5Ty4fdRCwXEJgaAAzfHQAW3EAIwArcmBcaXQKqtxFZSQg+GQ0LGcWDgjCPOha+uroYkzMYHJ0frbUDBwkkllwiMjdfWg6yurUjS8KED4R-sGt3BHMMYmp6C6yAB876FwkO2vNhugAXm-oAHIQ5gkX5LHorLRrAyYcgAdzgiFmnQWJwaHnUaTRq2i0ChsJmHXmgOkAWMAJcfSQyOqslR6PSwCwGBA5GMIHQrjxc1uxgKxTKp2krDy6HQigARKULKKvNTPOxiDR8HkwBNoAAxYUAJV4pgZ5GWQpFcPanIW0EetzNwQW7HS8v4SpV6vQWoAjjpeGdQQbFBzEYDLRbHqTSDbfL56Rd0EyWWzpKKADqYAC0ABFePwk4nRaj2BGQtByhALZ8-qxxZKxRKE …

feat: add LazyJsonString class

---

scripts/generate-clients/copy-to-clients.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/906
* sort deps/devDeps by keys
* verified that the changes in https://github.com/aws/aws-sdk-js-v3/commit/09659dad03a38b0c15665b3279db8fa402789382 were undone after this code change, will verify again by running codegen after lerna releases `v1.0.0-alpha.21`

fix: sort deps/devDeps by keys

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java

Fixes: #766
Self-closed xml tags returned by service:
```
<DescribeDomainsResult>
<DomainStatusList/>
</DescribeDomainsResult>
```
Will now result in the correct response:
```
{
...
},
__type: 'DescribeDomainsResponse',
DomainStatusList: []
}
```
XML for an unflattened list:
```
<DescribeDomainsResult>
<DomainStatusList>
<member>
...
<DomainName>foo</DomainName>
...
</member>
</DomainStatusList>
</DescribeDomainsResult>
```
Will still result in the correct list of Domains:
```
{
...
},
__type: 'DescribeDomainsResponse',
DomainStatusList: [
{
__type: 'DomainStatus',
...
DomainName: "foo".
...
}
]
}
```
Self-closed tags for map:
```
<ListDomainNamesResult>
<DomainNames/>
</ListDomainNamesResult>
```
Returned as correct, empty map:
```
{
...
__type: 'ListDomainNamesResponse',
DomainNames: {} …
```

fix: return empty array or map instead of undefined

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
packages/smithy-client/src/extended-encode-uri-component.ts
packages/smithy-client/src/extended-encode-uri.ts
packages/smithy-client/src/index.ts

Fixes: #866
Adds extendedEncodeURI function to wrap encodeURIComponent and encode additional characters, !, ', (, ), and *, to adhere to [RFC 3986](https://tools.ietf.org/html/rfc3986).

feat: extended URI encoding

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java

This commit serializes the Action and Version properties required
by `aws.query` and `aws.ec2` for operations that do not have input
shapes defined.
Depends on awslabs/smithy-typescript#131

fix: add bodies for undefined query/ec2 inputs

---

packages/credential-provider-cognito-identity/.gitignore

Adds /dist/ to .gitignore following es modules being generated starting with https://github.com/aws/aws-sdk-js-v3/pull/882

fix: ignore /dist

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java

Fix for CI failure in https://github.com/aws/aws-sdk-js-v3/pull/914 by using correct location for flattened XML.
`CloudSearch.describeDomains` returns an empty `array` for `DomainStatusList`.  `SQS.listQueues` still returns `undefined` for `QueueUrls` since the  `QueueUrl` is not set in the XML.

fix: handle flattened xml with self-closed tag

---

packages/signature-v4/src/constants.ts

`x-amz-user-agent` is equivalent to `user-agent` header but used only in browsers. If we don't sign `user-agent`, we shouldn't sign `x-amz-user-agent` either.
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/866#issuecomment-586481974

feat(signature-v4): unsign x-amz-user-agent header

---

packages/querystring-builder/src/index.ts
packages/signature-v4/package.json
packages/signature-v4/src/getCanonicalQuery.ts

Fixes SignatureV4's `getCanonicalQuery` to use consistent query encoding via the `escapeUri` function used in the `querystring-builder` package.
The `querystring-builder` is used by each of the handler packages (node-http-handler, fetch-http-handler) to convert a HttpRequest query property into an encoded query string.  `getCanonicalQuery` in SignatureV4 must use the same enocding to assure that signatures are calculated properly.
Also, removes unused `escapeUriPath` from `querystring-builder`.

fix: consistently encode query

---

packages/protocol-http/package.json
packages/protocol-http/src/httpRequest.ts

removes unused `HttpRequest` `getFormatedUrl` method and `buildQueryString` function

feat: remove unused HttpRequest method and function

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/Ec2ShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java

Fixes an issue where nested structure members were being flattened for `aws.ec2`.

fix: Only flatten lists, sets, and maps for aws.ec2

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts

Codegen for #951, #953 and https://github.com/awslabs/smithy-typescript/pull/137
* Only flatten lists, sets, and maps for aws.ec2
* Fix early return on empty xml tag, fixes #947
* Only apply error location adjustment for errors, fixes #949

chore: codegen for ec2 flattening, empty xml return, error location

---

packages/sha256-tree-hash/src/index.spec.ts
packages/sha256-tree-hash/src/index.ts

Fixes incorrectly calculated tree hashes of bodies equaling 1MB or multiples of 1MB.
Adds test for body = 1MB.

fix: treehash of whole MB body

---

packages/eventstream-serde-node/src/EventStreamMarshaller.ts
packages/eventstream-serde-node/src/utils.ts

In eventstream for NodeJS, users running the application on newer NodeJS version where the stream API supplies async iterator, they should get the original Readable stream. We shouldn't convert Readable stream to async iterator on the behalf of users. 
The previous implementation has a bug that returned async iterator is empty. Possibly because it returns from an async function. There was also a typo `throw` should be `return`. 
This PR fix the problem. Confirmed event stream works on Node >= 10

fix: return readable stream with async iterators properly

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
clients/client-sts/protocols/Aws_query.ts

Codegen for https://github.com/aws/aws-sdk-js-v3/pull/952
Adds function to decode escaped xml.
Updates generateXmlParseBody in code generation to use new function as tagValueProcessor for fast-xml-parser.
Fixes https://github.com/aws/aws-sdk-js-v3/issues/950

chore: codegen decode escaped xml

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java

Fixes XML map deserialzation by using correct key and value locations in wrapped map.
Currently, maps are returned incorrectly with array keys (0, 1, 2, etc) as the key instead of the actual key.
Current codegen:
```
const mapParams: any = {};
Object.keys(output).forEach(key => {
mapParams[key] = deserializeAws_queryMessageAttributeValue(
output[key],
context
);
});
return mapParams;
```
Fixed codegen:
```
const mapParams: any = {};
output.forEach((pair: any) => {
mapParams[pair["Name"]] = deserializeAws_queryMessageAttributeValue(pair["Value"], context);
});
return mapParams;
```

fix: xml map deser

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java

[`Set` doesn't have the ability to `.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) so using a loop instead.
Old:
```
return (input || []).map(entry =>
entry
);
```
New:
```
const contents = [];
for (let entry of input) {
contents.push(entry);
}
return contents;
```

fix: set serialization via loops

---

codegen/sdk-codegen/build.gradle.kts
codegen/sdk-codegen/gradle.properties
package.json
scripts/generate-clients/README.md
scripts/generate-clients/code-gen-dir.js
scripts/generate-clients/code-gen.js
scripts/generate-clients/index.js
yarn.lock

The purpose of this change is to do codegen from any path so that we can keep aws models in `codegen/sdk-codegen/aws-models` intact.
* Add a parameter to gradle codegen script so that the task can run codegen off from any folder. You can run the gradle task with `./gradlew build -PmodelsDirProp=path/to/model`. By default, it will use `codegen/sdk-codegen/aws-models`
* `yarn generate-clients` now supports generating clients more flexibly. You can:
- Generate clients from folder with models:
`yarn generate-clients -m path/to/model`
- Generate clients from a glob(e.g. generating S3, S3Control and DynamoDB clients):
`yarn generate-clients -g path/to/models/s3*.json path/to/another/dynamodb.2012-08-10.json`
- Generate all known AWS clients:
`yarn generate-clients` …

chore: add parameter to gradle task and update code-gen script

---

codegen/sdk-codegen/build.gradle.kts
scripts/generate-clients/code-gen-dir.js
scripts/generate-clients/code-gen.js
scripts/generate-clients/index.js

Fixes a bug in #976. It breaks the script calling Gradle task directly:
```
./gradlew clean build
```
This will result in empty directory because the default model path is `aws-models` but in reality should be `sdk-codegen/aws-models`. This is because Gradle defaults to use relative path from where `gradlew` is called. 
So this change fix the relative path root from  `gradlew` location to project root(`codegen/sdk-codegen`). Moreover, I changed the JS script to process the supplied path to make it relative path from the project root(`codegen/sdk-codegen`).

fix: use relative path in gradle codegen task

---

packages/middleware-location-constraint/src/index.spec.ts
packages/middleware-location-constraint/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/983
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/838
* no LocationConstraint for us-east-1 if not explicitly passed
* verified that this code change fixes both #983 and #838, verified by manually updating node_modules in test code

fix: no LocationConstraint for us-east-1 if not explicitly passed

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
clients/client-sts/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

Option 2 for fixing https://github.com/aws/aws-sdk-js-v3/issues/987
* fix(fast-xml-parser): populate contents from '#text' if available
* Verified the fix by updating `node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js` with the reproducible code given in https://github.com/aws/aws-sdk-js-v3/issues/987
* Ran integration tests in https://github.com/trivikr/aws-sdk-js-v3/tree/s3-bucketLocation-parser-fix-integ-test:
* Verified that the failing test in https://github.com/aws/aws-sdk-js-v3/issues/987 is successful
* Verified that all other tests succeeding before this code change are also succeeding after this code change
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(fast-xml-parser): populate contents from '#text' if available

---

packages/signature-v4/src/constants.ts
packages/signature-v4/src/getCanonicalHeaders.spec.ts

V2 doesn't mark the header as unsigned either:
https://github.com/aws/aws-sdk-js/blob/999ebda726224a67f0fe207702bf5b03609775a4/lib/signers/v4.js#L191-L199
Fixes #994 

fix(signature-v4): make x-amz-user-agent signable

---

packages/s3-request-presigner/src/index.spec.ts
packages/s3-request-presigner/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1000
Do not sign content-type in s3-request-presigner

fix: do not sign content-type in s3-request-presigner

---

packages/body-checksum-browser/src/index.ts
packages/body-checksum-node/src/index.ts
packages/chunked-stream-reader-node/src/index.ts
packages/client-documentation-generator/src/sdk-client-toc-plugin.ts
packages/credential-provider-cognito-identity/src/localStorage.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts
packages/middleware-retry/src/retryDecider.ts
packages/middleware-stack/src/MiddlewareStack.ts
packages/node-http-handler/src/node-http-handler.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/property-provider/src/chain.ts
packages/signature-v4/src/getCanonicalHeaders.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1015
Support for Optional Chaining was added in TS 3.7
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

chore: use optional chaining

---

packages/smithy-client/src/lazy-json.spec.ts
packages/smithy-client/src/lazy-json.ts

Because of https://github.com/microsoft/tslib/issues/95,
TS 'extends' shim doesn't support extending native types like String.
So here we create StringWrapper that duplicate everything from String
class including its prototype chain. So we can extend from here.
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1004

fix(smithy-client): string.toString requires this be a String

---

buildspec.yml

N/A
remove yarn install from buildspec, as it's already available on CodeBuild images with nodejs runtime
* Issue: https://github.com/aws/aws-codebuild-docker-images/issues/135
* Code for standard-3.0: https://github.com/aws/aws-codebuild-docker-images/blob/275b63f7d404d8da98f7f0b48c52d0d7521a2114/al2/x86_64/standard/3.0/Dockerfile#L310-L312

chore: remove yarn install from buildspec

---

packages/middleware-sdk-ec2/src/index.ts
packages/middleware-sdk-rds/src/index.ts
packages/s3-request-presigner/README.md
packages/s3-request-presigner/src/index.spec.ts
packages/s3-request-presigner/src/index.ts
packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts
packages/types/src/signature.ts

* Fixes https://github.com/aws/aws-sdk-js-v3/issues/1006
* Fixes https://github.com/aws/aws-sdk-js-v3/issues/1007
Move expiration under RequestSigningArguments

chore: move expiration under RequestPresigningArguments

---

codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/load-rest-json-error-code-stub.ts
packages/smithy-client/src/date-utils.ts
packages/smithy-client/src/extended-encode-uri-component.ts
packages/smithy-client/src/index.ts
packages/smithy-client/src/isa.ts

The following is a collection of fixes, broken down to individual commits, to AWS specific protocol code generation discovered while running the AWS protocol tests. Some of these commits are to the shared `smithy-client` package as well.
* Add RFC 7231 date formatter
* Update isa to work for errors
* Use + for spaces in encoding
* Use 0.4.3 smithy gradle plugin
* Fix request root node name
* Add timestamp input supplier helper
* Fix several aws.query serialization issues
This commit fixes naming and counting issues when serializing list,
set, and map types. It also fixes an issue with serializing timestamp
shapes within list, set, and map types.
* Fix issues with aws.rest-xml serialization
This commit fixes an issue with map serialization. It also fixes an
issue where timestamps were not …

Protocol tests

---

packages/middleware-sdk-ec2/src/index.ts
packages/middleware-sdk-rds/src/index.ts
packages/s3-request-presigner/src/index.spec.ts
packages/s3-request-presigner/src/index.ts
packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts
packages/types/src/signature.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1035
rename expiration to expiresIn in RequestPresigningArguments

chore: rename expiration to expiresIn in RequestPresigningArguments

---

packages/credential-provider-cognito-identity/src/fromCognitoIdentity.spec.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.spec.ts
packages/credential-provider-env/src/index.spec.ts
packages/credential-provider-env/src/index.ts
packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.spec.ts
packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.ts
packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts
packages/types/src/credentials.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/1037
chore: change credentials.expiration from number to Date

chore: change credentials.expiration from number to Date

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java

The following is a collection of fixes, broken down to individual commits, to AWS specific protocol code generation discovered while running the AWS protocol tests.
* Fix issue deserializing nested xml collections
* Fix issue in serializing nested xml collections
* Fix document body ser if no bindings present

fix: issues in protocol codegen

---

packages/smithy-client/src/index.ts
packages/smithy-client/src/split-every.spec.ts
packages/smithy-client/src/split-every.ts

Adds a function that given an input string, splits based on the delimiter after a given
number of delimiters has been encountered.
-----
This function is useful for splitting header lists of timestamps in the HTTP_DATE format.
-----

feat: Add util func to split over n delimiters

---

features/sts/step_definitions/sts.js
features/sts/sts.feature

N/A
* test getCallerIdentity instead of getSession for STS
* we're using temporary credentials for running integration tests in release pipeline, and this test is failing with `AccessDenied: Cannot call GetSessionToken with session credentials` ([docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#getSessionToken-property))

fix: test getCallerIdentity instead of getSession for STS

---

features/autoscaling/step_definitions/autoscaling.js
features/cloudformation/step_definitions/cloudformation.js
features/cloudfront/step_definitions/cloudfront.js
features/cloudsearch/step_definitions/cloudsearch.js
features/cloudwatch/step_definitions/cloudwatch.js
features/cloudwatchlogs/step_definitions/cloudwatchlogs.js
features/cognitoidentity/step_definitions/cognitoidentity.js
features/datapipeline/step_definitions/datapipeline.js
features/ec2/step_definitions/ec2.js
features/elasticache/step_definitions/elasticache.js
features/elasticbeanstalk/step_definitions/elasticbeanstalk.js
features/elastictranscoder/step_definitions/elastictranscoder.js
features/rds/step_definitions/rds.js
features/redshift/step_definitions/redshift.js
features/s3/objects.feature
features/s3/step_definitions/objects.js
package.json
yarn.lock

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1074
* chore(deps-dev): bump cucumber to 6.0.5
* Verified that integration tests are successful
```console
153 scenarios (153 passed)
534 steps (534 passed)
```

chore(deps-dev): bump cucumber to 6.0.5

---

packages/smithy-client/src/date-utils.ts
packages/smithy-client/src/isa.ts
packages/smithy-client/src/lazy-json.ts
packages/smithy-client/src/split-every.spec.ts
packages/smithy-client/src/split-every.ts

* prettier was never run on smithy-client ([history](https://github.com/aws/aws-sdk-js-v3/commits/master/packages/smithy-client))
* this was noticed while bumping the repo to prettier@2 in https://github.com/aws/aws-sdk-js-v3/pull/1079
chore: prettify smithy-client

chore: prettify smithy-client

---

features/dynamodb/step_definitions/dynamodb.js
features/extra/helpers.js

N/A
* remove unused world.response from integ tests
* integ tests now use values from `this.data.$metadata`
* verified that integ tests are successful

chore: remove unused world.response from integ tests

---

packages/middleware-stack/src/MiddlewareStack.ts

N/A
fixes typo in MiddlewareStack `geMiddlewareList` -> `getMiddlewareList`

chore: fix typo in MiddlewareStack

---

package.json

N/A
* fast failing integration tests helps with debugging
* verified that test fails and process exits:
```console
yarn test:integration
$ cucumber-js --fail-fast
.............F--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

chore: fast fail integration tests

---

.prettierignore

Fixes https://github.com/aws/aws-sdk-js-v3/issues/1115
* `codegen/*` was added to `.prettierignore` in #1083 as the checked-in code from codegen folder should not be prettified.
* This impacted prettification of temporary code which is stored in `codegen/sdk-codegen/build/smithyprojections/sdk-codegen` folder

fix: prettierignore only aws-models

---

packages/util-body-length-browser/src/index.spec.ts
packages/util-body-length-browser/src/index.ts
packages/util-body-length-browser/tsconfig.json

#1100 
Change implementation of calculateBodyLength for a browser so that multi byte body can be handled. 
Add a test for this change as well as ones for this function (since there was no test).

fix: multi-byte body lengths for browser

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
clients/client-sts/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberDeserVisitor.java
packages/smithy-client/src/get-value-from-text-node.spec.ts
packages/smithy-client/src/get-value-from-text-node.ts
packages/smithy-client/src/index.ts
protocol_tests/aws-ec2/protocols/Aws_ec2.ts
protocol_tests/aws-query/protocols/Aws_query.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

* Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1152
* PR which added checks for undefined in `["#text"]`: https://github.com/aws/aws-sdk-js-v3/pull/1077
* PR which removed `["#text"]` at root in parseBody: https://github.com/aws/aws-sdk-js-v3/pull/993
* Populate contents from '#text' recursively in parseBody
* Verified that:
* protocol tests are successful which tests fix in https://github.com/aws/aws-sdk-js-v3/pull/1077
* integration tests are successful which tests fix in https://github.com/aws/aws-sdk-js-v3/pull/993
* deserializer function:
* before:
```typescript
const deserializeAws_restXmlRenamedListMembers = (
output: any,
): string[] => {
return (output || []).map((entry: any) =>
entry["#text"] !== …
```

feat: populate contents from '#text' recursively in parseBody

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
protocol_tests/aws-ec2/models/index.ts
protocol_tests/aws-ec2/protocols/Aws_ec2.ts
protocol_tests/aws-query/models/index.ts
protocol_tests/aws-query/protocols/Aws_query.ts
protocol_tests/aws-restjson/models/index.ts
protocol_tests/aws-restjson/protocols/Aws_restJson1_1.ts
protocol_tests/aws-restxml/models/index.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/172
Use array for SetShape

feat: use array for SetShape

---

.dependabot/config.yml

Refs: https://github.com/aws/aws-sdk-js-v3/issues/625
* copy dependabot config from dashboard https://app.dependabot.com/accounts/aws/projects/131620
* we've been updating various settings on dependabot dashboard, and plan to stick with the following:
* update_schedule: "weekly" ([docs](https://dependabot.com/docs/config-file/#update_schedule-required))
* version_requirement_updates: "increase_versions_if_necessary" ([docs](https://dependabot.com/docs/config-file/#version_requirement_updates))

chore: copy dependabot config from dashboard

---

clients/client-s3-control/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

Similar to #1153
remove variables from xml serializeMap
Before:
```ts
const serializeAws_restXmlS3UserMetadata = (
input: { [key: string]: string },
): any => {
const collectedNodes: any = [];
Object.keys(input).forEach(key => {
const entryNode = new __XmlNode("entry");
const keyNode = new __XmlNode("NonEmptyMaxLength1024String")
.addChildNode(new __XmlText(key))
.withName("key");
entryNode.addChildNode(keyNode);
const node = new __XmlNode("MaxLength1024String").addChildNode(
new __XmlText(input[key])
);
entryNode.addChildNode(node.withName("value"));
collectedNodes.push(entryNode);
});
return collectedNodes;
};
```
After:
```ts
const serializeAws_restXmlS3UserMetadata = (
input: { [key: string]: string },
context: …
```

chore: remove variables from xml serializeMap

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
clients/client-sts/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
protocol_tests/aws-ec2/protocols/Aws_ec2.ts
protocol_tests/aws-query/protocols/Aws_query.ts

N/A
remove entries before buildFormUrlencodedString
Before:
```ts
const entries = serializeAws_queryAttachInstancesQuery(input, context);
body = buildFormUrlencodedString({
...entries,
Action: "AttachInstances",
Version: "2011-01-01"
});
```
After:
```ts
body = buildFormUrlencodedString({
...serializeAws_queryAttachInstancesQuery(input, context),
Action: "AttachInstances",
Version: "2011-01-01"
});
```

chore: remove entries before buildFormUrlencodedString

---

clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
protocol_tests/aws-ec2/protocols/Aws_ec2.ts
protocol_tests/aws-query/protocols/Aws_query.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

N/A
use destructuring in xml deserializeMap
* Before
```ts
const deserializeAws_queryDomainNameMap = (
output: any,
): { [key: string]: string } => {
return output.reduce((acc: any, pair: any) => {
acc[pair["key"]] = pair["value"];
return acc;
}, {});
};
```
* After
```ts
const deserializeAws_queryDomainNameMap = (
output: any,
): { [key: string]: string } => {
return output.reduce(
(acc: any, pair: any) => ({
...acc,
[pair["key"]]: pair["value"]
}),
{}
);
};
```
Verified by running the following in browser JavaScript console:
```js
const obj = [{ key: "one", value: "1" }];
obj.reduce((acc, pair) => {
acc[pair["key"]] = pair["value"];
return acc;
}, {});
obj.reduce((acc, pair) => ({ ...acc, …
```

chore: use destructuring in xml deserializeMap

---

features/cloudformation/step_definitions/cloudformation.js

Similar to https://github.com/aws/aws-sdk-js/pull/3252
enable termination protection in CloudFormation integ test
Verified that integration tests are successful:
```console
$ AWS_PROFILE=<profile> yarn test:integration --tags @cloudformation
$ cucumber-js --fail-fast --tags @cloudformation
.........
0m00.149s
Done in 2.13s.
```

test: enable termination protection in CloudFormation integ test

---

packages/service-error-classification/src/constants.ts
packages/service-error-classification/src/index.spec.ts
packages/service-error-classification/src/index.ts

N/A
The error codes were of type `{ [errorCode: string]: true }` which contains redundant boolean variable true. This code change simplifies error codes to be array of strings. 

chore: simplify error codes to be an array of strings

---

README.md

N/A
update beta->gamma in README.md

chore: update beta->gamma in README.md

---

packages/middleware-retry/src/retryDecider.ts
packages/service-error-classification/src/constants.ts
packages/service-error-classification/src/index.spec.ts
packages/service-error-classification/src/index.ts

Internally documented in JS-1810
The existing list of Throttling errors was added in Dec 2017 https://github.com/aws/aws-sdk-js-v3/commit/ae1aa480ca578879703c551e6b09a224e955a906
* Missed throttling errors added in this PR:
* `TransactionInProgressException`
* `LimitExceededException`
* `EC2ThrottledException`
* `PriorRequestNotComplete` is moved from StillProcessingError to `ThrottlingError`
* The API `isStillProcessingError` is being removed. It's internally only used in retryDecider, and low-level to be not used by pre-release users.

chore: add missing throttling errors 

---

scripts/generate-clients/copy-to-clients.js

There are 2 changes with this PR:
1. If a client's package.json contains a local NPM `scripts` or `devDependencies`, they would be removed by codegen because these new entries don't exist package.json's template. This change avoids removing these entries. 
What is not changed: for the entries in `scripts` or `devDependencies` and exist in both newly generated client and existing client, the script prefers the ones in existing client.
2. Temporarily pin the newly added internal dependencies version. We will review this before GA.(maybe re-introduce the range dependencies)

chore: allow un-overwritable scripts and devDependencies in package.json

---

clients/client-transcribe-streaming/package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1218
* The custom scripts required for client-transcribe-streaming were removed in codegen PR https://github.com/aws/aws-sdk-js-v3/pull/1213. This PR re-introduces them.
* The codegen was updated to not overwrite these scripts in https://github.com/aws/aws-sdk-js-v3/pull/1207

chore: re-add client-transcribe-streaming scripts

---

clients/client-accessanalyzer/models/index.ts
clients/client-accessanalyzer/protocols/Aws_restJson1_1.ts
clients/client-app-mesh/models/index.ts
clients/client-app-mesh/protocols/Aws_restJson1_1.ts
clients/client-codeguruprofiler/models/index.ts
clients/client-codeguruprofiler/protocols/Aws_restJson1_1.ts

Following PRs should be merged before this one:
* smithy-typescript: https://github.com/awslabs/smithy-typescript/pull/183
* retry if retryableTrait is set https://github.com/aws/aws-sdk-js-v3/pull/1238
codegen for adding $retryable in Error

chore: codegen for adding $retryable in Error

---

packages/middleware-retry/src/configurations.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/index.spec.ts
packages/middleware-retry/src/retryMiddleware.ts
packages/types/src/response.ts
packages/types/src/util.ts

To align with naming schema to be used in standard retry strategy (internal JS-1537) 
* BREAKING: rename maxRetries to maxAttempts
* verified that amplify team doesn't pass maxRetries while consuming gamma versions of SDK https://github.com/aws-amplify/amplify-js/search?q=maxRetries&unscoped_q=maxRetries

chore: rename maxRetries to maxAttempts

---

packages/middleware-serde/tsconfig.json

*Issue #, if available:* #1208
Targeting es2016 causes tsc to output arrow functions.  Those arrow functions are not supported in IE11.  Targeting es5 transpiles arrow functions so that IE11 will work.

fix(tsconfig): targeting es5 in middleware-serde

---

packages/fetch-http-handler/karma.conf.js
packages/fetch-http-handler/src/fetch-http-handler.browser.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts

https://github.com/aws/aws-sdk-js-v3/issues/1165
Removed the default mode to cors as this may not work in all environments like the browser. Added browser test to cover this. First PR please be kind 🙏 

feat(fetch-http-handler): remove cors mode for `fetch`

---

packages/middleware-retry/src/configurations.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/index.spec.ts

* To align with naming schema to be used in standard retry strategy (internal JS-1537)
* Similar to https://github.com/aws/aws-sdk-js-v3/pull/1244
* BREAKING: rename ExponentialBackOffStrategy to StandardRetryStrategy
* verified that amplify team doesn't pass maxRetries while consuming gamma versions of SDK https://github.com/aws-amplify/amplify-js/search?q=maxRetries&unscoped_q=maxRetries

chore: rename ExponentialBackOff to Standard for RetryStrategy

---

packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/index.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1155
* convert second param in StandardRetryStrategy to options
* verified that amplify team doesn't use custom StandardRetryStrategy while consuming gamma versions of SDK https://github.com/aws-amplify/amplify-js/search?q=maxRetries&unscoped_q=maxRetries

chore: convert second param in StandardRetryStrategy to options

---

packages/hash-node/src/index.ts
packages/util-buffer-from/src/index.ts

Minor issue with string buffer encoding type being exposed incorrectly. This change should not be breaking as it only impacts internal packages.

fix: type ironing with string buffer

---

packages/middleware-retry/src/constants.ts
packages/middleware-retry/src/defaultRetryQuota.spec.ts
packages/middleware-retry/src/defaultRetryQuota.ts
packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts

Internal tracking issue JS-1812
add retry quotas to StandardRetryStrategy

feat: add retry quotas to StandardRetryStrategy

---

packages/middleware-retry/package.json
packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/index.native.ts

Internal issue in JS-1816
add retry informational headers

feat: add retry informational headers

---

packages/region-provider/src/defaultProvider.spec.ts
packages/region-provider/src/defaultProvider.ts
packages/region-provider/src/fromEnv.spec.ts
packages/region-provider/src/fromEnv.ts
packages/region-provider/src/fromSharedConfigFiles.spec.ts
packages/region-provider/src/fromSharedConfigFiles.ts

Refactored while investigating Retry Configuration task (internal JS-1813)
add unit tests for region-provider

test(region-provider): add extensive unit tests for region-provider

---

scripts/generate-clients/copy-to-clients.js

Came across this bug while working on codegen to introduce retry-config-provider from  https://github.com/aws/aws-sdk-js-v3/pull/1282 in runtimeConfig
overwrite clients in protocol clients
The clients in protocol clients are not overwritten because they are prefixed with `aws-` and not `client-`
<details>
```js
const isPathnameClientInPackageName = (pathName, packageName) =>
pathName
.toLowerCase()
.indexOf(
packageName
.toLowerCase()
.replace("@aws-sdk/client-", "")
.replace(/-/g, "")
) >= 0;
// logs true
console.log(isPathnameClientInPackageName("S3.ts", "@aws-sdk/client-s3"));
console.log(isPathnameClientInPackageName("S3Client.ts", "@aws-sdk/client-s3"));
// logs false
console.log( …
```

fix: overwrite clients in protocol clients

---

package.json

Removed --include-dependency to speed up build time. 
Some stats:
Before (clean build, git clean -fxd && yarn)
```
real    46m50.258s
user    57m11.852s
```
After (clean build, git clean -fxd && yarn)
```
real    5m35.860s
user   6m6.196s
```

chore: faster build time

---

packages/credential-provider-node/src/index.spec.ts
packages/property-provider/src/memoize.spec.ts
packages/property-provider/src/memoize.ts

Refactored while going through region-provider in https://github.com/aws/aws-sdk-js-v3/pull/1280
refactor memoize to use arrow functions
* [TypeScript function overloads](https://dev.to/krzysztofzuraw/typescript-function-overloads-1iff)
* [expect .toStrictEqual(value) in Jest](https://jestjs.io/docs/en/expect#tostrictequalvalue)

chore(property-provider): refactor memoize to use arrow functions

---

features/efs/efs.feature

Refs: https://github.com/aws/aws-sdk-js/pull/3321
EFS started throwing `ValidationException` instead of `BadRequest` for `deleteFileSystem` operation on Saturday 06/20
Updating the tests after verifying that `ValidationException` is thrown also on AWS CLI:
```console
$ date
Mon Jun 22 09:42:00 PDT 2020
$ aws --version
aws-cli/1.16.226 Python/3.7.3 Darwin/18.7.0 botocore/1.12.216
$ aws efs delete-file-system --file-system-id fake-id
An error occurred (ValidationException) when calling the DeleteFileSystem operation: 1 validation error detected: Value 'fake-id' at 'fileSystemId' failed to satisfy constraint: Member must satisfy regular expression pattern: ^fs-[0-9a-f]{8,40}
```
Ensured that integration tests are successful for EFS: …

test(efs): check for ValidationException

---

packages/middleware-retry/src/configurations.spec.ts
packages/middleware-retry/src/configurations.ts
packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/retryMiddleware.spec.ts
packages/middleware-retry/src/retryMiddleware.ts
packages/types/src/util.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1284
read maxAttempts value from retry-config
* `maxAttempts` is now updated from `number` to `Provider<string>`
* Reason: The values in environment variables and config are stored as strings, and retry-config-provider utility functions are shared between maxAttempts (string) and retryMode (string)
* `maxAttempts` is removed from `RetryStrategy` interface
* retryMiddleware is always added in getRetryPlugin, as maxAttempts value is not available.
* retryMiddleware decides to not retry in case maxAttempts is less than or equal to 1

feat: read maxAttempts value from retry-config

---

package.json
packages/fetch-http-handler/package.json
packages/hash-blob-browser/karma.conf.js
packages/hash-blob-browser/package.json
packages/middleware-sdk-transcribe-streaming/src/websocket-handler.spec.ts
yarn.lock

This change remove karma/puppeteer related dependencies to project root so that individual package(`fetch-http-handler`, `hash-blob-browser`) doesn't come with chunky dependencies. So it accelerates the installation.

chore: move karma related devdeps to repo root

---

scripts/generate-clients/code-gen.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1312
use copyFileSync from node instead of fs-extra
* fs.copyFileSync docs in node: https://nodejs.org/api/fs.html#fs_fs_copyfilesync_src_dest_mode
* the API was added in `v8.5.0`, and we use Node.js 10+ for generating clients
* copyFileSync from fs-extra uses native node implementation https://github.com/jprichardson/node-fs-extra/pull/505
Verified that `yarn generate-clients` succeeds to fix the bug:
```console
$ yarn generate-clients -m ~/Downloads/temp
$ node ./scripts/generate-clients -m /home/trivikr/Downloads/temp
preparing models from /home/trivikr/Downloads/temp...
copying model s3.2006-03-01.json...
...
child process exited with code 0
copying @aws-sdk/client-s3 …
```

fix: use copyFileSync from node

---

clients/client-cognito-identity/.gitignore
clients/client-cognito-identity/.npmignore
clients/client-cognito-identity/e2e/CognitoIdentity.ispec.ts
clients/client-cognito-identity/karma.conf.js
clients/client-cognito-identity/package.json
clients/client-cognito-identity/tsconfig.json

Similar to #1296 but for cognito identity client.

test(client-cognito-identity): add cross platform integ tests

---

.github/ISSUE_TEMPLATE/---bug-report.md

chore: update bug report template for bugs in RN.

---

.gitignore
package.json
scripts/verdaccio-publish/index.js
verdaccio/config.yaml
yarn.lock

Add a command `yarn local-release` to release **ALL** the package locally. All the packages will be released as `1.0.0-ci.0` version. 
This change is required for end2end test where the test script will mimic installing the packages from npm local registry that released by the command above.

chore: add verdaccio local release

---

packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts
packages/credential-provider-imds/src/fromInstanceMetadata.ts

Done in preparation of IMDS v2 in JS-1802
* add extensive testing for fromInstanceMetadata
* also converts functions to arrow functions and uses async-await

test(credential-provider-imds): cases for fromInstanceMetadata

---

clients/client-cognito-identity/e2e/CognitoIdentity.ispec.ts
clients/client-cognito-identity/e2e/README.md
clients/client-cognito-identity/karma.conf.js
clients/client-s3/e2e/README.md
clients/client-s3/e2e/S3.ispec.ts
clients/client-s3/karma.conf.js
package.json
yarn.lock

Instead of creating resources(IAM, Identity pools) every time when e2e test suites run, we will call existing resources fixed in test account. This way we achieve low coupling with the test.

test: using existing resources in e2e tests

---

jest.config.base.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1323
run jest tests from all folders in cjs
```console
$ cd packages/credential-provider-imds
$ yarn test  
$ yarn build:cjs
$ tsc -p tsconfig.cjs.json
$ jest
PASS  dist/cjs/fromContainerMetadata.spec.js
PASS  dist/cjs/fromInstanceMetadata.spec.js
PASS  dist/cjs/remoteProvider/httpGet.spec.js
PASS  dist/cjs/remoteProvider/ImdsCredentials.spec.js
PASS  dist/cjs/remoteProvider/retry.spec.js
PASS  dist/cjs/remoteProvider/RemoteProviderInit.spec.js
Test Suites: 6 passed, 6 total
Tests:       33 passed, 33 total
Time:        1.147s
Done in 2.99s.
```
By submitting this pull request, I confirm that you can use, modify, copy, and …

fix: run jest tests from all folders in cjs

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/load-rest-json-error-code-stub.ts

This was noticed when dependabot updated prettier https://github.com/aws/aws-sdk-js-v3/pull/1200#pullrequestreview-428305930
* prettify load-rest-json-error-code-stub.ts
* it's currently prettified when merging into protocols file. For example: https://github.com/aws/aws-sdk-js-v3/blob/cd4813013063fc015678bfb1e71d7c1bbc26e2ab/clients/client-accessanalyzer/protocols/Aws_restJson1.ts#L3458-L3487

chore: prettify load-rest-json-error-code-stub.ts

---

packages/credential-provider-imds/src/remoteProvider/RemoteProviderInit.ts

N/A
converts providerConfigFromInit to an arrow function, and add a comment about DEFAULT_MAX_RETRIES
* DEFAULT_MAX_RETRIES is 0, as it's the default in AWS SDK for Python and CLI ([code](https://github.com/boto/botocore/blob/646c61a7065933e75bab545b785e6098bc94c081/botocore/utils.py#L273))
* AWS SDK for JavaScript v2 has two attempts though ([code](https://github.com/aws/aws-sdk-js/blob/adfbce5de94b4f06aea3ee4d3cd4f89ae87f8809/lib/credentials/ec2_metadata_credentials.js#L49-L52))

chore(credential-provider-imds): providerConfigFromInit arrow function

---

clients/client-lex-runtime-service/LexRuntimeService.spec.ts
clients/client-lex-runtime-service/package.json
clients/client-lex-runtime-service/protocols/Aws_restJson1.ts
clients/client-lex-runtime-service/tsconfig.json
clients/client-mediastore-data/MidiaStoreData.spec.ts
clients/client-mediastore-data/package.json
clients/client-mediastore-data/protocols/Aws_restJson1.ts
clients/client-mediastore-data/tsconfig.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

#1125 
Pending: add integration test to lex runtime service client

fix: fix incorrect x-amz-content-sha256 header

---

packages/middleware-sdk-transcribe-streaming/src/signer.spec.ts
packages/middleware-sdk-transcribe-streaming/src/signer.ts

Transcribe streaming's WebSocket request omits the request headers. So we should not sign any header other than `host`. Because if the header is signed, but not sent to the service, the signature is mismatch.

fix(middleware-sdk-transcribe-streaming): unsign the non host headers

---

packages/middleware-retry/package.json
packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/retry-config-provider/src/defaultProvider.spec.ts
packages/retry-config-provider/src/defaultProvider.ts

Internal JS-1909
use fromStatic to return default config values
Verified that integration tests no longer throw `No max_attempts found for profile default in SDK configuration files` error:
On master:
```console
$ yarn test:integration-legacy --tags @acm
$ cucumber-js --fail-fast --tags @acm
.(node:5683) UnhandledPromiseRejectionWarning: Error: No max_attempts found for profile default in SDK configuration files
at new ProviderError (/local/home/trivikr/workspace/aws-sdk-js-v3/packages/property-provider/dist/cjs/ProviderError.js:17:28)
at /local/home/trivikr/workspace/aws-sdk-js-v3/packages/retry-config-provider/dist/cjs/fromSharedConfigFiles.js:23:27
at step (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/tslib/ …
```

fix: use fromStatic to return default config values

---

features/extra/hooks.js

Internal JS-1910
Increase cucumber default timeout to 300s as some integration tests are failing intermittently

fix: increase cucumber default timeout to 300s

---

packages/property-provider/src/fromStatic.spec.ts
packages/property-provider/src/fromStatic.ts

Refactor while working on https://github.com/aws/aws-sdk-js-v3/pull/1341
use arrow function in fromStatic

chore(property-provider): arrow function in fromStatic

---

packages/eventstream-serde-universal/src/getUnmarshalledStream.spec.ts
packages/eventstream-serde-universal/src/getUnmarshalledStream.ts

When an event returns from response event stream is not defined in the model. The deserialize will parse it as `{$unknown: {Event: Payload}}`. In this case, the downstream event stream should omit this event, instead of emitting an event with name `$unknown`. 
This PR implements the change and unit test.

feat(eventstream-serde-universal): omit unknown event type

---

packages/credential-provider-imds/package.json
packages/credential-provider-imds/src/fromContainerMetadata.spec.ts
packages/credential-provider-imds/src/fromContainerMetadata.ts
packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts
packages/credential-provider-imds/src/fromInstanceMetadata.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.spec.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.ts
yarn.lock

Required for PUT operation in signed IMDS workflow (internal JS-1903)
* update httpGet to accept options.method
* uses nock for simplifying http request tests
* populates statusCode in ProviderError, as it would be consumed in signed IMDS workflow.

feat(credential-provider-imds): update httpGet to accept options.method

---

packages/middleware-sdk-transcribe-streaming/src/signer.spec.ts

follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1336
extensive tests for signer.ts

test(middleware-sdk-transcribe-streaming): extensive tests for signer.ts

---

packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/retryDecider.spec.ts

chore(middleware-retry): move mocks to beforeEach

---

features/extra/world.js

Was noticed while investigating https://github.com/aws/aws-sdk-js-v3/issues/1338
The environment variable `CONFIGURED_REGION` is used in v2 for setting up global AWS config, and it's not required in v3 integ tests
* v2 code which sets env var `CONFIGURED_REGION` https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/features/extra/world.js#L8
* v2 code which uses env var `CONFIGURED_REGION` https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/features/extra/cleanup.js#L106-L108
* In v3, the region is explicitly set where required during client creation
* Explicitly in JavaScript https://github.com/aws/aws-sdk-js-v3/blob/4bc605be4eda41b47ecf44bdea31d289f88aa699/features/inspector/step_defi …

chore: remove unused configuration from integ tests

---

package.json
packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.spec.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.spec.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.ts
packages/eventstream-serde-universal/src/fixtures/MockEventMessageSource.fixture.ts
packages/node-http-handler/src/stream-collector/index.ts
packages/node-http-handler/src/stream-collector/readable.mock.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1350 was linting files directly in the src folder and not child folders
lint all ts files in packages

feat: lint all ts files in packages

---

package.json

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1367
lint and fix on precommit
Verified by enduring that linter is run on precommit for `packages/**/src/**/*.ts`
(prevents creating an empty commit in the case tested):
<details>
<summary>Click to Expand</summary>
</details>

feat: lint and fix on precommit

---

packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts
packages/credential-provider-imds/src/fromInstanceMetadata.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.spec.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.ts

Internal JS-1903
signed IMDS workflow

feat(credential-provider-imds): signed IMDS workflow

---

package.json

Add a prehook to `test:e2e` command, to make sure all the command it needs already built when being executed. It makes `test:e2e` command more self-contain(by no requiring manually building the components before running it).

chore: add pretest:e2e script to make the command build itself

---

packages/middleware-retry/package.json
packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/retry-config-provider/package.json
packages/retry-config-provider/src/defaultProvider.spec.ts
packages/retry-config-provider/src/defaultProvider.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1352
move retry defaults to middleware-retry

fix: move retry defaults to middleware-retry

---

tests/e2e/get-integ-test-resources.js

This is a very minor change. We need to change the stack name here because the integ test resources stack name on backend is changed. 

chore: update integ test resources stack name

---

.gitignore

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1380
ignore build folders from codegen folder
Verified that:
* None of the folders mentioned in https://github.com/aws/aws-sdk-js-v3/issues/1380 are added to git
* changes in files with `build` in them (like `build.gradle.kts`) are added to git

fix: ignore build folders from codegen folder

---

README.md
packages/middleware-stack/README.md
packages/s3-request-presigner/README.md
packages/util-create-request/README.md

Reasons explained in https://github.com/aws/aws-sdk-js-v3/pull/1386
prettify README missed in #1185 done by running the following command in zsh:
```console
$ ./node_modules/.bin/prettier --write **/*.md 
```

chore: prettify *.md files missed in #1185

---

packages/config-resolver/src/EndpointsConfig.ts
packages/middleware-host-header/src/index.ts
packages/middleware-retry/src/retryMiddleware.spec.ts
packages/middleware-sdk-transcribe-streaming/src/signer.spec.ts
packages/middleware-stack/src/types.ts
packages/protocol-http/src/httpRequest.ts
packages/signature-v4/src/getCanonicalHeaders.ts
packages/smithy-client/src/client.ts

Prettify command was run to check if any TS files were missed similar to https://github.com/aws/aws-sdk-js-v3/pull/1386
But it caught prettify changes missed in https://github.com/aws/aws-sdk-js-v3/pull/1350
fix prettier formatting missed while linting in #1350, achieved by running following command in zsh:
```console
$ ./node_modules/.bin/prettier --write **/*.ts
```

chore: fix prettier formatting missed while linting in #1350

---

scripts/generate-clients/code-gen-dir.js
scripts/generate-clients/code-gen.js
scripts/generate-clients/code-prettify.js
scripts/generate-clients/copy-to-clients.js
scripts/generate-clients/index.js
scripts/generate-clients/spawn-process.js
scripts/verdaccio-publish/index.js

N/A
add @ts-check for scripts written in JavaScript so that we get benefits of TypeScript checking in JS files. Docs: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html
<details>
<summary>Screen recording</summary>
</details>

chore: add @ts-check for scripts written in JavaScript

---

packages/fetch-http-handler/src/stream-collector.ts
packages/util-body-length-browser/src/index.ts

*Issue #, if available:* Closes https://github.com/aws/aws-sdk-js-v3/issues/1378.
*Description of changes:* Removes `Blob` constructor usage from code paths where it's not necessary. I also found a past perf test when I was looking for alternative solutions to getting the string length and `Blob` is at least 130x slower than a for loop. Using `TextEncoder` would be even faster, but I'm assuming we want IE11 support natively without any polyfills.
Perf test: https://jsperf.com/utf-8-byte-length/36
Other possible solutions: https://stackoverflow.com/questions/5515869/string-length-in-bytes-in-javascript

fix: remove `Blob` usage

---

packages/config-resolver/src/EndpointsConfig.spec.ts
packages/config-resolver/src/EndpointsConfig.ts

From v2: https://github.com/aws/aws-sdk-js/pull/3368
Internal issue JS-1834
adds region validation using DNS Host label regex

fix: add region validation using DNS Host label regex

---

packages/credential-provider-cognito-identity/src/fromCognitoIdentity.spec.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.spec.ts
packages/eventstream-handler-node/package.json
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.ts
packages/middleware-eventstream/src/handling-middleware.ts
packages/middleware-sdk-s3-control/src/prepend-account-id.ts
packages/middleware-sdk-transcribe-streaming/src/middleware-endpoint.ts
packages/middleware-signing/src/middleware.ts
packages/middleware-stack/src/MiddlewareStack.spec.ts
packages/middleware-stack/src/MiddlewareStack.ts
packages/middleware-stack/src/types.ts
packages/smithy-client/src/client.ts
packages/smithy-client/src/command.ts
packages/types/src/middleware.ts
packages/util-create-request/src/foo.fixture.ts
packages/util-create-request/src/index.ts
yarn.lock

#1377 
* This change refactors the middleware stack class into a factory. So that the private data are stored in closure instead of class "private" members. Now, you can instantiate a middleware stack by `constructStack<Input, Output>();` instead of `new MiddlewareStack<Input, Output>()`.
* Remove `step` from the `addRelativeTo` options. This way the position of the middleware is solely depend on the `toMiddleware` and `relation`(before or after).
* Refactor the middleware stack resolution implementation. Now the resolution algorithm is easier to follow & maintain.
/cc @trivikr 

feat: refactor middleware stack

---

packages/eventstream-serde-browser/package.json

The `module` property of `eventstream-serde-browser/package.json` was not set to `./dist/es/index.js`, which is what Typescript (`tsconfig.es.json`) is configured to output the ES bundle to. This pull request updates it.
**Question:** should I version bump the package as well?

fix(eventstream-serde-browser): set `module` to dist output

---

packages/s3-request-presigner/README.md

* Signify that the second example is ES6-specific -- not Typescript
* Minor grammar corrections:
* "when instantiating" vs. "when instantiate"
* "the configuration of an" vs. "the configurations of an"
* "an existing client" vs. "an existing clients"

Copy tweaks in s3-request-presigner README

---

packages/middleware-sdk-s3/package.json
packages/middleware-sdk-s3/src/validate-bucket-name.spec.ts
packages/middleware-sdk-s3/src/validate-bucket-name.ts
packages/util-arn-parser/src/index.spec.ts

S3 bucket name validation middleware validates there's no `/` exists in bucket name. But is the bucket name is an ARN, this validation should not fail. 
This validation functionality should not be part of `@aws-sdk/middleware-bucket-endpoint` because this validation is applied to all the S3 operations, whereas later has some exceptions like `createBucket()`, `deleteBucket()`

feat(middleware-sdk-s3): bucket name validator skips ARN bucket name

---

packages/middleware-signing/src/middleware.spec.ts
packages/middleware-signing/src/middleware.ts
packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts
packages/types/src/signature.ts

**Description of changes:**
The PR makes change to SigV4 signer to support per-request region and service override. Specifically, users can specify `signingRegion` and `signingService` when signing a request, string, or event. The `signingRegion` and `signingService` will override the `region` and `service` configuration specified in SigV4 constructor. The override is only effective for one sign invocation. 
In the `@aws-sdk/middleware-signing`, the signing middleware will inspect the value in the [`HandlerExecutionContext`](https://github.com/aws/aws-sdk-js-v3/blob/9fedaa9696ff1ecf5d1e92b28b34d573583a7842/packages/types/src/middleware.ts#L368-L376) looking for `signing_region` and `signing_service` value. If the values are set by previous middleware, it mean the signer should use a …

feat: support per-request region and service override in signer

---

scripts/generate-clients/copy-to-clients.js

Internal issue JS-2016
removeSync in case of directory in copy-to-clients
As detailed in internal issue JS-2016, the current copy-to-clients script doesn't remove commands which could have been removed from models. This PR ensures that the directories are deleted before individual files are copied over. The command `ensureDirSync` doesn't need to be run, as `copySync` would create the directory.
*Testing:*
Verified that the files `GetPredictionCommand.ts` and `PutModelCommand.ts` were removed while generating client for frauddetector using updated models.

fix: removeSync in case of directory in copy-to-clients

---

.vscode/settings.json

N/A
Set workspace TypeScript version in VSCode settings so that VSCode uses workspace version all the time:
* TS in v3 was updated to 4.0 soon after the release on 8/20 in https://github.com/aws/aws-sdk-js-v3/pull/1456, but latest VSCode version 1.48.1 doesn't support 4.0 https://code.visualstudio.com/updates/v1_48#_typescript-40-support
* In future, if TS version updates get delayed for some reason than VSCode should use the version from the workspace by default.
Documentation: https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions
Screenshots:
<details>
</details>
<details>
<summary>During (one-time)</summary>
</details>
<details>
</details> …

chore: set workspace TypeScript version in VSCode settings

---

clients/client-transcribe-streaming/README.md
package.json
yarn.lock

* Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1456 for TypeScript 4.0 support
* Prettier 2.1 announcement blog post https://prettier.io/blog/2020/08/24/2.1.0.html
chore(deps-dev): bump prettier to 2.1.0
Ran following commands to get files formatted with prettier 2.1.0:
* `./node_modules/.bin/prettier --write **/*.{ts,js,md,json}`
* `yarn generate-clients`

chore(deps-dev): bump prettier to 2.1.0

---

tests/react-native/End2End/.gitignore

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1468
gitignore Android related files in react-native tests

chore: gitignore Android related files in react-native tests

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java

Fixes checkstyle error violations for `RegexpSingleline`, `LineLength` and `MemberName`.
Removes trailing spaces, lines longer than 150 chars and invalid member names.
These violations are returned as errors when running the `./gradlew build` from the `codegen` directory.

fix(codegen): checkstyle violations

---

packages/property-provider/src/memoize.spec.ts
packages/property-provider/src/memoize.ts

Resolves #1466 
This change makes the memoize function loads the value after the first invoke instead of immediately when calling `memoize()`.
Detailed root cause is stated in the original issue: https://github.com/aws/aws-sdk-js-v3/issues/1466#issuecomment-681147889. This issue was not caught because all of the environments we run CI, and developers machine, already has `AWS_REGION` value set. 
To prevent it happens again, we need to check and clean the environment of our CI

fix(property-provider): memoize provider after the first evoke

---

clients/client-iotsitewise/protocols/Aws_restJson1.ts
clients/client-servicediscovery/protocols/Aws_json1_1.ts
packages/protocol-http/src/isValidHostname.spec.ts
packages/protocol-http/src/isValidHostname.ts

Related: https://github.com/awslabs/smithy-typescript/pull/206
Currently, SDK will throw when serializing `client-iotsitewise` and `client-servicediscovery` clients requests, because of a bug in serializer. This change fixes the issue.
This change also update the regex used to validate the host name in `isValidHostname.ts`. The regex was originally added in https://github.com/aws/aws-sdk-js-v3/pull/774 but only validates host labels instead of the full host name. For example, `s3.amazonaws.com` was incorrectly detected as an invalid hostname with original regex. 

fix: serializer throws when hostname prefix is applied

---

packages/middleware-logger/src/loggerMiddleware.ts
packages/types/src/logger.ts

Internal JS-2037
log metadata/input/output/request/response

feat: log metadata/input/output/request/response

---

packages/middleware-logger/src/loggerMiddleware.ts

Internal JS-1790
Do not overwrite body while logging req/res
In the initial PoC of logger-middleware, the body was overwritten for request/response but the decision was reverted. The code in https://github.com/aws/aws-sdk-js-v3/pull/1478 didn't remove the code to overwrite body from original PoC

fix: do not overwrite body while logging req/res

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java

N/A
This PR removes duplicate code from AddAwsRuntimeConfig. Verified by running `yarn generate-clients` that no clients were updated.

chore(codegen): remove duplicate code from AddAwsRuntimeConfig

---

scripts/generate-clients/copy-to-clients.js

Similar to fix in https://github.com/aws/aws-sdk-js-v3/issues/1483, but in this case, the tests folder is protocol_tests is not getting updated:
* https://github.com/aws/aws-sdk-js-v3/tree/master/protocol_tests/aws-ec2/tests/functional
* https://github.com/aws/aws-sdk-js-v3/tree/master/protocol_tests/aws-json/tests/functional
* Verified that folders no tests folders in clients were overwritten after running `yarn generate-clients`
* Verified that when [HttpProtocolTestGenerator.java](https://github.com/awslabs/smithy-typescript/blob/0dd8c148e3b6d9fab6227a3f2a022bc3d4367c97/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java#L75) is edited, the tests folders in protocol_tests are …

fix(codegen): add tests folder in overwritablePathnames

---

scripts/generate-clients/copy-to-clients.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1485
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1482
use current versions of internal deps in new clients, and also order the dependencies like lerna does.
Testing:
* Verified that existing clients are not updated by running `yarn generate-clients`
* Verified by working on base commit of https://github.com/aws/aws-sdk-js-v3/pull/1481, that `client-braket` uses the current version of internal dependencies.

fix: use current versions of internal deps in new clients

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
scripts/generate-clients/spawn-process.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1497
exit generate-clients if child process errors or fails
* child_process documentation https://nodejs.org/api/child_process.html
* Success is traditionally represented with exit 0 in shell scripts https://www.shellscript.sh/exitcodes.html
Verified that generate-client fails with error code emitted by prettier in #1497 
<details>
<summary>error Command failed with exit code 1</summary>
```console
5 actionable tasks: 2 executed, 3 up-to-date
codegen/sdk-codegen/build/smithyprojections/sdk-codegen/braket.2019/build-info/smithy-build-info.json 43ms
codegen/sdk-codegen/build/smithyprojections/sdk-codegen/braket.2019/model/model.json 156ms …
```

fix: exit generate-clients if child process errors or fails

---

clients/client-cognito-identity/package.json
clients/client-lex-runtime-service/package.json
clients/client-mediastore-data/package.json
clients/client-s3/package.json
yarn.lock

Jest update was missed in some packages https://github.com/aws/aws-sdk-js-v3/pull/1295
This appears to be an issue with dependabot.
bump jest to 26.1.0 in missed packages

chore(deps-dev): bump jest to 26.1.0 in missed packages

---

packages/middleware-logger/src/loggerMiddleware.spec.ts
packages/middleware-logger/src/loggerMiddleware.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1488#issuecomment-692151662
adds loggerMiddleware in build step so that values populated in metadata by retryMiddleware (attempts and totalRetryDelay) are visible

fix: add loggerMiddleware in build step

---

clients/client-lex-runtime-service/LexRuntimeService.spec.ts
clients/client-mediastore-data/MidiaStoreData.spec.ts
clients/client-s3/S3.spec.ts
packages/s3-request-presigner/src/getSignedUrl.spec.ts
protocol_tests/aws-ec2/tests/functional/ec2query.spec.ts
protocol_tests/aws-json/tests/functional/awsjson1_1.spec.ts
protocol_tests/aws-query/tests/functional/awsquery.spec.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Some functional tests, unit tests and protocol tests constructs new clients
in test suites. If these tests run in environment without any AWS configs,
they will fail with region is missing or cannot resolve credentials. This
change add fake regions and credentials to this test so SDK won't try to
resolve them in the test. It enables the test:all script to be runnable on
for example, a fresh EC2 instance

chore: add fake credentials and regions to unit tests

---

packages/middleware-logger/src/loggerMiddleware.spec.ts
packages/middleware-logger/src/loggerMiddleware.ts
packages/middleware-serde/jest.config.js
packages/middleware-serde/src/deserializerMiddleware.spec.ts
packages/middleware-serde/src/deserializerMiddleware.ts
packages/middleware-serde/src/serializerMiddleware.spec.ts
packages/middleware-serde/src/serializerMiddleware.ts

Follow up to https://github.com/aws/aws-sdk-js-v3/pull/1478
move logging of input/output and req/res to serde
**What does it do?**
It moves logging of input before just before serializing and request just after serializing. It also moves logging of response just before deserializing, and output just after deserializing. It also converts deser to arrow functions and adds unit tests for them.
**Why is it helpful?**
The current logger middleware logs input/output/request/response in build step, and they may be edited by other middleware (like several s3 customization middleware now, or DynamoDB Document Client in future). This PR ensures that the actually sent/received values are logged.
<details>
<summary>Test code</summary>
```js
const { …
```

fix: move logging of input/output and req/res to serde

---

packages/util-dynamodb/.gitignore
packages/util-dynamodb/.npmignore
packages/util-dynamodb/LICENSE
packages/util-dynamodb/README.md
packages/util-dynamodb/jest.config.js
packages/util-dynamodb/package.json
packages/util-dynamodb/src/convertToAttr.spec.ts
packages/util-dynamodb/src/convertToAttr.ts
packages/util-dynamodb/src/index.ts
packages/util-dynamodb/src/marshall.spec.ts
packages/util-dynamodb/src/marshall.ts
packages/util-dynamodb/src/models.ts
packages/util-dynamodb/tsconfig.cjs.json
packages/util-dynamodb/tsconfig.es.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/1223
Adds utility function marshall to convert JavaScript object into DynamoDB Record
```js
const { DynamoDB } = require("@aws-sdk/client-dynamodb");
const { marshall } = require("@aws-sdk/util-dynamodb");
const client = new DynamoDB(clientParams);
const params = {
TableName: "Table",
Item: marshall({
HashKey: "hashKey",
NumAttribute: 1,
BoolAttribute: true,
ListAttribute: [1, "two", false],
MapAttribute: { foo: "bar" },
NullAttribute: null,
}),
};
await client.putItem(params);
```

feat(util-dynamodb): marshall to convert JavaScript object into DynamoDB Record

---

packages/middleware-host-header/src/index.ts

AWS Signer requires a request to contain a `host` header, mostly the same as the request's `hostname`. 
For the customizations that modifies the request's `hostname`, they need to be applied before this 
middleware, Otherwise the `hostname` and `host` header would mismatch. It mean these middleware
**must** be applied relatively before this middleware. By moving it low priority, it reduce the possibility 
of mistakenly adding customizations applied after this middleware. Developers only need to apply the
customizations to the `build` step, and they will be applied before this middleware by default.

chore(middleware-host-header): move to low priority

---

packages/util-dynamodb/src/convertToNative.spec.ts
packages/util-dynamodb/src/convertToNative.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1543
creates BigInt from string value instead of number

fix(util-dynamodb): create BigInt from string value instead of number

---

packages/util-dynamodb/src/convertToAttr.spec.ts
packages/util-dynamodb/src/convertToAttrToNative.spec.ts
packages/util-dynamodb/src/convertToNative.spec.ts

Will help catch issues like https://github.com/aws/aws-sdk-js-v3/issues/1543
test convertToAttr and back to convertToNative

test(util-dynamodb): marshall and unmarshall in convertToAttrToNative 

---

clients/client-s3/S3.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.ts
packages/middleware-bucket-endpoint/src/bucketHostname.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostname.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts
packages/middleware-bucket-endpoint/src/index.ts

This change implements the data plane for [S3 Outposts](https://aws.amazon.com/blogs/aws/amazon-s3-on-outposts-now-available/). Now `bucketHostname` also supports generating outpost endpoint if supplied with an Outpost ARN. It also export some internal util functions that would be useful when validating the other ARN-based features.(e.g. Outposts control plane)

feat(middleware-bucket-endpoint): support Outposts buckets

---

packages/config-resolver/src/EndpointsConfig.spec.ts
packages/config-resolver/src/EndpointsConfig.ts

Some customizations requires information that whether the endpoint
is explicitly set by the user, and behave accordingly. `isCustomEndpoint`
is added in inform these customizations.

feat(config-resolver): add isCustomEndpoint resolved config

---

packages/util-buffer-from/src/index.spec.ts
packages/util-buffer-from/src/index.ts

No longer required as we now target Node.js >=10.0.0 in https://github.com/aws/aws-sdk-js-v3/pull/1558
Node.js doc guide: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
* removes usage of deprecated Buffer constructor
* adds extensive tests for util-buffer-from
* throws more descriptive TypeError, referred from [ERR_INVALID_ARG_TYPE](https://nodejs.org/api/errors.html#errors_err_invalid_arg_type)

chore(util-buffer-from): remove usage of deprecated Buffer constructor

---

packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/write-request-body.ts

Resolves #1433 
Root cause is mentioned here: https://github.com/aws/aws-sdk-js-v3/issues/1433#issuecomment-705874894. This change converts non streaming binary data(string, Uint8Array, ArrayBuffer, ArrayBufferView) into a buffer before sending on the wire.
This change also move commented https unit tetss to http test to increase some test coverage.

fix(node-http-handler): fix type error sending Uint8Array as payload

---

protocol_tests/aws-ec2/package.json
protocol_tests/aws-ec2/tsconfig.json
protocol_tests/aws-json/package.json
protocol_tests/aws-json/tsconfig.json
protocol_tests/aws-query/package.json
protocol_tests/aws-query/tsconfig.json
protocol_tests/aws-restjson/package.json
protocol_tests/aws-restjson/tsconfig.json
protocol_tests/aws-restxml/package.json
protocol_tests/aws-restxml/tsconfig.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1559
Updates were missed in protocol_tests packages:
* https://github.com/aws/aws-sdk-js-v3/pull/1558
* https://github.com/aws/aws-sdk-js-v3/pull/1560
* https://github.com/aws/aws-sdk-js-v3/pull/1562
target Node.js >=10.0.0 and ES2018 in protocol_tests

chore(prototol_tests): target Node.js >=10.0.0 and ES2018

---

lerna.json

Move to Lerna's default [fixed versioning](https://github.com/lerna/lerna#fixedlocked-mode-default) from independent versioning. Reason outlined in #1248. This change also cleans up the lerna.json

chore: use lerna fixed versioning

---

packages/credential-provider-env/README.md
packages/credential-provider-imds/README.md
packages/credential-provider-ini/README.md
packages/credential-provider-node/README.md
packages/credential-provider-process/README.md
packages/eventstream-serde-browser/README.md
packages/eventstream-serde-node/README.md
packages/hash-blob-browser/README.md
packages/hash-node/README.md
packages/invalid-dependency/README.md
packages/middleware-host-header/README.md
packages/middleware-sdk-api-gateway/README.md
packages/middleware-sdk-s3-control/README.md
packages/middleware-sdk-s3/README.md
packages/middleware-sdk-sqs/README.md
packages/middleware-serde/README.md
packages/middleware-signing/README.md
packages/middleware-user-agent/README.md
packages/protocol-http/README.md
packages/shared-ini-file-loader/README.md
packages/smithy-client/README.md
packages/util-uri-escape/README.md

N/A
Standardizes the title in packages to list package name.
* Moved description title to below the badges if present.
* Removed redundant `@aws-sdk/`
* Added missing `@aws-sdk/`

fix(readme): highlight package name as standard

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/README.md.template

This was missed in PRs:
* https://github.com/aws/aws-sdk-js-v3/pull/1600
* https://github.com/aws/aws-sdk-js-v3/pull/1601
The code change was manually done in above to PRs, as the script `copy-to-clients` doesn't override README.md once generated.	
update client readme template

fix: update client readme template

---

scripts/generate-clients/code-prettify.js

It allows to run `scripts/generate-clients` outside of the aws-sdk root directory.
Before it was required to run the script always in the root (like with `yarn generate-clients`. By invoking prettier with relative path it can be executed from every directory like `node $HOME/aws-sdk-js-v3/scripts/generate-clients` which is helpful for building private clients.

fix(generate-clients): Invoke prettier relative to client-generation

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java

That changes makes `./grandlew build` pass. Otherwise it fails with checkstyle violations
```
> Task :smithy-aws-typescript-codegen:checkstyleMain
[ant:checkstyle] [ERROR] /Volumes/unix/aws-sdk-js-v3/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java:15: 'package' should be separated from previous statement. [EmptyLineSeparator]
[ant:checkstyle] [ERROR] /Volumes/unix/aws-sdk-js-v3/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java:21: Wrong lexicographical order for 'java.util.List' import. Should be before 'java.util.logging.Logger'. [CustomImportOrder]
[ant:checkstyle] [ERROR] …
```

chore(codegen): fix checkstyle violations in AddS3ControlDependency.java

---

clients/client-cognito-identity/commands/UnlinkIdentityCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java

> This is a public API. You do not need any credentials to call this API.
Cognito unlinkIdentity docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#unlinkIdentity-property
fix(cognito): remove auth for UnlinkIdentity

fix(client-cognito-identity): remove auth for UnlinkIdentity

---

packages/credential-provider-cognito-identity/src/fromCognitoIdentity.spec.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts

https://github.com/aws/aws-sdk-js-v3/issues/893
This change is done to preserve parity with V2. Returns identityId from fromCognitoIdentityPool calls 

fix(credential-provider-cognito-identity): return identityId as part of cognitoIdentityPool

---

clients/client-timestream-query/endpoints.ts
clients/client-timestream-write/endpoints.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/endpoint-prefix.json

fix(client-timestream-*): use correct endpoint prefix

---

packages/util-format-url/src/index.ts

Neither `path` or `headers` is required for generating url string, so remove them from input parameter

fix(util-format-url): remove headers or path from input

---

packages/middleware-stack/README.md

Follow up to #1393 that removed the `step` parameter from `addRelativeTo()`.
The README should reflect it.
TODO: add blog post link to readme

docs(middleware-stack): remove outdated README content

---

packages/s3-presigned-post/LICENSE
packages/s3-presigned-post/README.md
packages/s3-presigned-post/jest.config.js
packages/s3-presigned-post/package.json
packages/s3-presigned-post/src/constants.ts
packages/s3-presigned-post/src/createPresignedPost.spec.ts
packages/s3-presigned-post/src/createPresignedPost.ts
packages/s3-presigned-post/src/index.ts
packages/s3-presigned-post/src/types.ts
packages/s3-presigned-post/tsconfig.cjs.json
packages/s3-presigned-post/tsconfig.es.json

Add support for generating presigned post url and fields. Users can use them to upload file without AWS credentials. 
Resolves: #395 

feat(s3-presigned-post): support S3 object post

---

clients/client-s3/S3Client.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java

Right now `AddBuiltinPlugins.java` is a combination of customizations for several services. The change moves all the S3-related customizations to its own file `AddS3Config.java`. This is a continuing effort to move every customization from `AddBuiltinPlugins.java` to service-specific customization file.

chore(codegen): refactor S3 customizations to own class

---

packages/node-http-handler/src/node-http-handler.spec.ts

#1539
Just browsing, but it looks at first glance like the issue with the test is that `maxSockets` will sometimes be set to 0 – due to Math.random() and Math.round(). My guess is that a setting of `maxSockets = 0` gets turned into `Infinity` – so the test will fail in these cases. This change ensures `maxSockets` will always be at least `1` in this test.

fix(node-http-handler): set maxSockets above 0 in test

---

clients/client-s3/S3.spec.ts
clients/client-s3/commands/CompleteMultipartUploadCommand.ts
clients/client-s3/commands/CopyObjectCommand.ts
clients/client-s3/commands/UploadPartCopyCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
packages/middleware-sdk-s3/src/index.ts
packages/middleware-sdk-s3/src/throw-200-exceptions.spec.ts
packages/middleware-sdk-s3/src/throw-200-exceptions.ts
packages/middleware-sdk-s3/src/use-regional-endpoint.ts
packages/middleware-sdk-s3/src/validate-bucket-name.ts

In case of internal error or connection termination, some S3 operations(CopyObject, UploadPartCopy, CompleteMultiPartUpload) may return error with 200 status code. The change adds customization to throw exceptions when:
1. Status code is 200 but body contains `<Error>`;
2. Status code is 200 but body is empty(connection terminated);
Related PR: https://github.com/aws/aws-sdk-js/pull/3259

fix(client-s3): throw errors with 200 status code

---

packages/middleware-serde/src/deserializerMiddleware.spec.ts
packages/middleware-serde/src/deserializerMiddleware.ts
packages/middleware-serde/src/serializerMiddleware.spec.ts
packages/middleware-serde/src/serializerMiddleware.ts

Internal JS-2221
Disable logging of raw HTTP request/response, as it logs sensitive data in raw HTTP request/response.
<details>
<summary>Example code</summary>
```js
const { IAM } = require("@aws-sdk/client-iam");
(async () => {
const logger = console;
const client = new IAM({ region, logger });
await client.changePassword({
OldPassword: "OldPassword",
NewPassword: "NewPassword",
});
})();
```
</details>
<details>
<summary>Relevant logger output</summary>
```console
{ clientName: 'IAMClient', commandName: 'ChangePasswordCommand' }
{
input: {
OldPassword: '***SensitiveInformation***',
NewPassword: '***SensitiveInformation***'
}
}
{
httpRequest: HttpRequest {
method: 'POST',
hostname: 'iam.amazonaws.com',
port: …
```

fix(logger): disable logging of raw HTTP request/response

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts

Adds the `aws-iam-traits` dependency so that models that include these traits will be able to resolve the traits and successfully generate clients.

fix(codegen): add aws-iam-traits dependency

---

packages/service-error-classification/src/index.spec.ts
packages/service-error-classification/src/index.ts

* Noticed while debugging https://github.com/aws/aws-sdk-js-v3/issues/1196
* Examples where status code 429 is retried:
* JS SDK v2 https://github.com/aws/aws-sdk-js/pull/2895
* Ruby https://github.com/aws/aws-sdk-ruby/pull/1889
adds response with 429 status code as Throttling

feat(service-error-classification): add 429 response as Throttling

---

packages/node-http-handler/src/set-connection-timeout.spec.ts
packages/node-http-handler/src/set-connection-timeout.ts
packages/node-http-handler/src/set-socket-timeout.spec.ts
packages/node-http-handler/src/set-socket-timeout.ts

Debugged while going through https://github.com/aws/aws-sdk-js-v3/issues/1196
This PR makes the following changes:
* Adds tests for setConnectionTimeout.
* Removes references to `this`.
* Converts functions to arrow functions.
* Updates deprecated `.abort()` to `.destroy()`.
* Node.js docs: https://nodejs.org/api/http.html#http_request_abort
* Uses `Object.assign` during error creation to avoid using additional variable.

feat(node-http-handler): update timeout code and tests

---

packages/node-http-handler/src/constants.ts
packages/node-http-handler/src/node-http-handler.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1196
This PR throws TimeoutError for Node.js timeouts (`"ECONNRESET"`, `"EPIPE"`, `"ETIMEDOUT"`), so that retryMiddleware can retry them.
* Tested with repro code given in https://github.com/aws/aws-sdk-js-v3/issues/1196#issuecomment-634060411
* The node-http-handler tests are being refactored in https://github.com/trivikr/aws-sdk-js-v3/tree/node-http-handler-tests and the test for this PR would be added later. This PR is posted to ensure fix is pushed in **rc.7** release on 11/19.

fix(node-http-handler): throw TimeoutError for Node.js timeouts

---

packages/abort-controller/src/AbortSignal.ts
packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.spec.ts
packages/types/src/abort.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1159
Makes AbortSignal [WHATWG Spec](https://dom.spec.whatwg.org/#interface-abortcontroller) compliant.
Verified that no errors were thrown with the following code:
```js
const { DynamoDBClient, ListTablesCommand } = require("@aws-sdk/client-dynamodb");
// Commenting the import verifies the fix with AbortController Web API.
// Uncommenting the import verifies the fix with abort-controller npm package.
// const { AbortController } = require("abort-controller");
const abortSignal = new AbortController().signal;
const client = new DynamoDBClient({});
client.send(
new ListTablesCommand({}),
{ abortSignal }
);
```
By submitting this pull request, I confirm that you can use, modify, copy, and …

fix(abort-controller): make AbortSignal WHATWG Spec compliant

---

packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts

fixes: https://github.com/aws/aws-sdk-js-v3/issues/1633
Smithy pr: https://github.com/awslabs/smithy-typescript/pull/238

fix(fetch-http-handler): omit body for HEAD/GET methods

---

features/cloudwatchlogs/step_definitions/cloudwatchlogs.js

Refs: https://github.com/aws/aws-sdk-js/pull/3538
Passes logGroupNamePrefix in describeLogGroups in client-cloudwatch-logs integration tests.
The test fails if there are more than 50 logGroups, as it parses logGroups from
first page of results. This code change explicitly requests for the created logGroup
to ensure it doesn't return pages of results.
Verified that integration tests are successful:
```console
$ yarn test:integration-legacy --tags @cloudwatchlogs 
yarn run v1.22.5
$ cucumber-js --fail-fast --tags @cloudwatchlogs
..........
6 steps (6 passed)
0m00.095s
Done in 2.80s.
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

test(client-cloudwatch-logs): pass logGroupNamePrefix in describeLogGroups

---

packages/middleware-sdk-sqs/src/send-message-batch.ts

This PR fixes a bug in SendMessageBatch that make MD5 verifications against the hashes returned by AWS always fail.
## Note to maintainers
The test suite for this file mocks the MD5 factory, making this error non catchable and the test useless.

fix(middleware-sdk-sqs): Fix MD5 verification on SendMessageBatch.

---

packages/s3-request-presigner/README.md
packages/s3-request-presigner/src/presigner.spec.ts
packages/s3-request-presigner/src/presigner.ts
packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts
packages/signature-v4/src/moveHeadersToQuery.spec.ts
packages/signature-v4/src/moveHeadersToQuery.ts
packages/types/src/signature.ts

fix: https://github.com/aws/aws-sdk-js-v3/issues/1576
When `signature-v4` generate a presigned url, it will try to hoist the headers to query strings, so these headers will exist in the url, hense easy to use. However, S3 requres server-side encryption headers to be signed in headers due to [S3 limitation](https://github.com/aws/aws-sdk-ruby/issues/874#issuecomment-135596055). So this change solve the issue by 2 changes:
1. Add a new config to the `signature-v4` presign config `unhoistableHeaders`. The presigner won't hoist the given headers to query before presign it.
2. In `s3-request-presigner`, it detects all the server-side encryption headers, and supply them to the `unhoistableHeaders` config of the presigner.
By submitting this …

fix(s3-request-presigner): skip hoisting SSE headers

---

clients/client-sts/STSClient.ts
clients/client-sts/commands/AssumeRoleCommand.ts
clients/client-sts/commands/DecodeAuthorizationMessageCommand.ts
clients/client-sts/commands/GetAccessKeyInfoCommand.ts
clients/client-sts/commands/GetCallerIdentityCommand.ts
clients/client-sts/commands/GetFederationTokenCommand.ts
clients/client-sts/commands/GetSessionTokenCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1602
Disables auth requirement for STS operations assumeRoleWithSAML and assumeRoleWithWebIdentity

fix(client-sts): disable auth for public assumeRole commands

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java

The codegen-ci is failing in master https://github.com/aws/aws-sdk-js-v3/runs/1476861228#step:5:31
These errors were mistakenly introduced in PR https://github.com/aws/aws-sdk-js-v3/pull/1706
fix checkstyle errors in AddBuiltinPlugins.java

fix(codegen): checkstyle errors in AddBuiltinPlugins.java

---

packages/fetch-http-handler/src/fetch-http-handler.ts
packages/node-http-handler/src/node-http-handler.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/types/src/transfer.ts
protocol_tests/aws-ec2/tests/functional/ec2query.spec.ts
protocol_tests/aws-json/tests/functional/awsjson1_1.spec.ts
protocol_tests/aws-query/tests/functional/awsquery.spec.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1695
make handlerOptions optional in RequestHandler

chore(types): make handlerOptions optional

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java

Refs: https://github.com/aws/aws-sdk-js/pull/3543
The customization is no longer required as smithy `optionalAuth` was added to respective APIs in 11/20 models update.
* PR: https://github.com/aws/aws-sdk-js-v3/pull/1711
* Code: https://github.com/aws/aws-sdk-js-v3/blob/fdc692e0d872efea01a5a6ad21211dc5499d979e/codegen/sdk-codegen/aws-models/cognito-identity.2014-06-30.json#L760
Verified that running codegen doesn't update the client-cognito-identity:
```console
$ yarn generate-clients -g codegen/sdk-codegen/aws-models/cognito-identity.2014-06-30.json
```

chore(client-cognito-identity): remove auth customizations

---

features/iam/iam.feature
features/iam/step_definitions/iam.js

Refs: https://github.com/aws/aws-sdk-js/pull/3542
Checks for getUser instead of listUsers in IAM integration tests.
The test fails if there are more than 100 users, as it parses users from
first page of results. This code change explicitly requests for the created user
to ensure it doesn't return pages of results.
```console
$ yarn test:integration-legacy --tags @iam
yarn run v1.22.5
$ cucumber-js --fail-fast --tags @iam
...................
13 steps (13 passed)
0m01.277s
Done in 3.93s.
```

test(client-iam): check for IAM.getUser instead of listUsers

---

package.json
yarn.lock

The `@commitlint/config-conventional` was bumped to 11.0.0, but `@commitlint/cli` was missed in PR : https://github.com/aws/aws-sdk-js-v3/pull/1673
bump @commitlint/cli to 11.0.0

chore(deps-dev): bump @commitlint/cli to 11.0.0

---

packages/middleware-sdk-sqs/src/send-message-batch.spec.ts
packages/middleware-sdk-sqs/src/send-message-batch.ts
packages/middleware-sdk-sqs/src/send-message.spec.ts
packages/middleware-sdk-sqs/src/send-message.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1742
call next() exactly once in sendMessageMiddleware
Verified that the issue is not reproducible with code from https://github.com/aws/aws-sdk-js-v3/issues/1742#issuecomment-740401577

fix(middleware-sdk-sqs): call next() exactly once in sendMessageMiddleware

---

packages/credential-provider-imds/src/fromContainerMetadata.ts
packages/url-parser-node/src/index.spec.ts
packages/url-parser-node/src/index.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/999
use WHATWG URL instead of url.parse
* url.parse has been deprecated and it recommends using the WHATWG URL API https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost
* WHATWG URL has been available on Global Object since v10.0.0 https://nodejs.org/api/url.html#url_the_whatwg_url_api

chore(url-parser-node): use WHATWG URL instead of url.parse

---

packages/util-waiter/package.json
packages/util-waiter/src/createWaiter.spec.ts
packages/util-waiter/src/createWaiter.ts
packages/util-waiter/src/index.spec.ts
packages/util-waiter/src/index.ts
packages/util-waiter/src/poller.spec.ts
packages/util-waiter/src/poller.ts
packages/util-waiter/src/utils/index.ts
packages/util-waiter/src/utils/sleep.spec.ts
packages/util-waiter/src/utils/sleep.ts
packages/util-waiter/src/utils/validate.spec.ts
packages/util-waiter/src/utils/validate.ts
packages/util-waiter/src/waiter.ts

Refactors: https://github.com/aws/aws-sdk-js-v3/pull/1736
Refactor the original waiter util:
1. expose a createWaiter() only to clients in order to reduce the duplicated code-gen
2. fix infinite loop in job poller
3. fix potential number overflow
Example of how clients may use these utils:
```js
const waitForTableExists = (params: DynamoDBWaiter, input: DescribeTableInput): Promise<WaiterResult> => {
return createWaiter({...waiterServiceDefaults, ...params}, params.client, input, tableExistsPoller);
}
```

feat(util-waiter): add createWaiter()

---

packages/middleware-logger/src/loggerMiddleware.spec.ts
packages/middleware-logger/src/loggerMiddleware.ts
packages/middleware-serde/src/deserializerMiddleware.spec.ts
packages/middleware-serde/src/deserializerMiddleware.ts
packages/middleware-serde/src/serializerMiddleware.spec.ts
packages/middleware-serde/src/serializerMiddleware.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1785
Removal of logging clientName and commandName is tracked in:
* https://github.com/awslabs/smithy-typescript/pull/249
* https://github.com/aws/aws-sdk-js-v3/pull/1787
log clientName, commandName, input, output in addition to metadata
<details>
<summary>Test Code</summary>
```js
const { DynamoDB } = require("../aws-sdk-js-v3/clients/client-dynamodb");
(async () => {
const region = "us-east-1";
const logger = console;
const client = new DynamoDB({ region, logger });
await client.listTables({ Limit: 1 });
})();
```
</details>
<details>
<summary>Test output</summary>
```console
{
clientName: 'DynamoDBClient',
commandName: 'ListTablesCommand',
input: { Limit: 1 },
output: { …
```

feat(middleware-logger): log clientName, commandName, input, output

---

features/dynamodb/step_definitions/dynamodb.js
features/ec2/step_definitions/ec2.js
features/extra/helpers.js
features/s3/buckets.feature
features/s3/step_definitions/buckets.js

N/A
use waiters in integration tests
<details>
<summary>DynamoDB</summary>
```console
> yarn test:integration-legacy features/dynamodb
yarn run v1.22.5
$ cucumber-js --fail-fast features/dynamodb
...............................
6 scenarios (6 passed)
19 steps (19 passed)
1m00.205s
Done in 62.98s.
```
</details>
<details>
<summary>EC2</summary>
```
> yarn test:integration-legacy features/ec2     
yarn run v1.22.5
$ cucumber-js --fail-fast features/ec2
...............
9 steps (9 passed)
0m21.490s
Done in 24.31s.
```
</details>
<details>
<summary>S3</summary>
```
> yarn test:integration-legacy features/s3
yarn run v1.22.5
$ cucumber-js --fail-fast features/s3
............................................................. …
```

feat(cucumber): use waiters in integration tests

---

packages/signature-v4/src/credentialDerivation.spec.ts
packages/signature-v4/src/credentialDerivation.ts

Fixes #1002 
This change fix the issue that signing key is not refreshed between requests with only different secret access keys. I added a hash of both access key id and secrete access key as the cache key is signing keys. 
However, previously we cached pending promise of signing keys, but now we only cache the resolved promise of signing keys. So it's safer but may have wild performance implication. We can optimize this after we have benchmark metrics of this module.

fix(signature-v4): add secrets to signing key cache key

---

packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts

fixes #1772
#1772
*Description of changes:* 
Consider credential_process defined in profile passed in AWS_PROFILE

feat(credential-provider-node): use credential_process from profile

---

clients/client-connectparticipant/ConnectParticipantClient.ts
clients/client-iot-data-plane/IoTDataPlaneClient.ts
clients/client-iot/IoTClient.ts
clients/client-pinpoint-sms-voice/PinpointSMSVoiceClient.ts
clients/client-qldb/QLDBClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
packages/middleware-retry/src/constants.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/index.ts
packages/middleware-retry/src/omitRetryHeadersMiddleware.spec.ts
packages/middleware-retry/src/omitRetryHeadersMiddleware.ts

ConnectParticipant, IoT Data Plane, IoT, Pinpoint SMS Voice, QLDB doesn't
support retry headers per their CORS config. So remove the support for
these service to unblock the browser usage
request headers: 
✅  ConnectParticipant
✅  IoT Data Plane
✅  IoT
✅  Pinpoint SMS Voice
✅  QLDB
Request header
Fixes #1376 

fix(clients): remove retry headers for several services

---

clients/client-sso/models/models_0.ts
clients/client-sso/protocols/Aws_restJson1.ts

Depends on https://github.com/awslabs/smithy-typescript/pull/254
retain structure members' iteration order.
The codegen was run five times, and the Structure members' order was not updated.
```
$ yarn generate-clients
```

chore(clients): retain structure members' iteration order

---

clients/client-apigatewaymanagementapi/endpoints.ts
clients/client-codeguruprofiler/endpoints.ts
clients/client-connectparticipant/endpoints.ts
clients/client-iot/endpoints.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java
protocol_tests/aws-json/endpoints.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1831
The code generator ignores the [aws.auth#sigv4 trait](https://github.com/aws/aws-sdk-js-v3/blob/54e87151877dd5cf9a5f256698c088cc7a856225/codegen%2Fsdk-codegen%2Faws-models%2Fapigatewaymanagementapi.2018-11-29.json#L55) when inferring the signing name. With this change, SDK will use the trait and fall back to `arnNamespace`(for non-AWS clients).

fix(clients): use signing name from auth sigv4 trait

---

packages/util-waiter/package.json
packages/util-waiter/src/createWaiter.ts
packages/util-waiter/src/poller.ts
packages/util-waiter/src/utils/validate.ts
packages/util-waiter/src/waiter.ts

fix(util-waiter): fix compiling error with waiter

---

packages/util-dynamodb/src/convertToAttr.spec.ts
packages/util-dynamodb/src/convertToAttr.ts
packages/util-dynamodb/src/marshall.spec.ts
packages/util-dynamodb/src/marshall.ts
packages/util-dynamodb/src/models.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1816
Enables removal of undefined values in marshall by setting `removeUndefinedValues=true`

feat(util-dynamodb): enable undefined values removal in marshall

---

packages/util-waiter/src/createWaiter.spec.ts
packages/util-waiter/src/poller.spec.ts
packages/util-waiter/src/poller.ts
packages/util-waiter/src/utils/validate.spec.ts
packages/util-waiter/src/utils/validate.ts
packages/util-waiter/src/waiter.ts

Expose the options for minDelay and maxDelay through typescript
```js
import { DynamoDBClient, waitForTableExists } from "@aws-sdk/client-dynamodb"
(async () => {
const TableName = "MY-TEST-TABLE-1";
const maxWaitTime = 120;
const client: DynamoDBClient = new DynamoDBClient({});
let result = await waitForTableExists( { 
client,
minDelay: 20,
maxDelay: 80,
maxWaitTime: 25 } , { TableName });
console.log("Table exists", result);
})();
```
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/1806

fix(util-waiter): expose minDelay and maxDelay for waiters

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/README.md.template

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1794
The badge was updated in client README files in https://github.com/aws/aws-sdk-js-v3/pull/1794, but template was missed.

fix(readme): use latest for npm version badge in template

---

packages/util-user-agent-browser/package.json
packages/util-user-agent-node/package.json

Types module existing in runtime dependency causes the types to be pinned
in lock file. It will cause problem when they are not up-to-date in users 
node_modules.

fix(util-user-agent-*): move @aws-sdk/types to devDependencies

---

packages/s3-presigned-post/README.md
packages/s3-request-presigner/README.md

N/A
fix(readme): npm downloads tag
<details>
</details>
<details>
</details>

fix(readme): npm downloads tag

---

packages/s3-request-presigner/src/getSignedUrl.spec.ts
packages/s3-request-presigner/src/getSignedUrl.ts

fix(s3-request-presigner): not to throw when presign concurrently

---

packages/fetch-http-handler/karma.conf.js
packages/hash-blob-browser/karma.conf.js

These changes eliminate the warning when running these tests:
```console
13 01 2021 02:54:45.965:WARN [project.karma-typescript]: Tsconfig '/home/ec2-user/workspace/aws-sdk-js-v3/packages/fetch-http-handler/tsconfig.json' configured in karmaTypescriptConfig.tsconfig does not exist
```

test(karma): fix karma dependency karma test

---

yarn.lock

https://github.com/aws/aws-sdk-js-v3/issues/1842
@aws-crypto published type updates yesterday from https://github.com/aws/aws-sdk-js-crypto-helpers/pull/190. This updates the yarn.lock so that it brings in the correct version of @aws-sdk/types

chore(clients): update yarn lock with types from @aws-crypto

---

packages/util-waiter/src/poller.spec.ts
packages/util-waiter/src/poller.ts
yarn.lock

https://github.com/aws/aws-sdk-js-v3/issues/1909
Slightly modify waiters so that they call the underlying operation once before entering wait state

fix(util-waiters): waiters should call operation once before entering waiting

---

.github/workflows/lock.yml

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1881
remove exclude-created-before from lock config.
The config was added to test GitHub Action lock-threads, and limit the number of notifications watchers will get.
The test is now complete. The exclude-created-before will now [default to ''](https://github.com/dessant/lock-threads#inputs), and closed threads from June-October will get locked over the weekend.

chore: remove exclude-created-before from lock config

---

packages/credential-provider-imds/README.md

Refs https://github.com/aws/aws-sdk-js-v3/pull/103
The configuration option `profile` was removed in https://github.com/aws/aws-sdk-js-v3/pull/103, but the README wasn't updated. This PR updates the README.

docs(credential-provider-imds): profile not supported in config options

---

packages/credential-provider-imds/README.md

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1358
The support for Signed IMDS workflow was added in https://github.com/aws/aws-sdk-js-v3/pull/1358
This update explicitly calls out in README that both IMDSv1 and IMDSv2 are supported with a link to configuring instance metadata service documentation.

docs(credential-provider-imds): mention IMDSv1+IMDSv2 support

---

clients/client-pinpoint-sms-voice/PinpointSMSVoiceClient.ts
clients/client-qldb/QLDBClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1789
Adding retry headers for services which now support them: QLDB and Pinpoint SMS Voice.
Verified that `access-control-allow-headers` includes `amz-sdk-invocation-id` and `amz-sdk-request` for QLDB and Pinpoint SMS voice.
<details>
<summary>QLDB</summary>
```console
$ curl --insecure -i -X OPTIONS https://qldb.us-east-1.amazonaws.com/ledgers/stringvalue/journal-kinesis-streams/stringvalue -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" -H "Origin: https://foo.example" -H "Access-Control-Request-Method: DELETE" -H "Access-Control-Request-Headers: …
```

chore(clients): re-add retry headers for QLDB and Pinpoint SMS Voice

---

scripts/generate-clients/copy-to-clients.js

Refs: https://github.com/aws/aws-sdk-js-v3/issues/1919#issuecomment-764218895
In https://github.com/aws/aws-sdk-js-v3/issues/1919, we decided to use [downlevel-dts](https://www.npmjs.com/package/downlevel-dts) to create type definition files which support TS 3.4 or later. The configuration for [typesVersions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) contains an array which is replaced to an object by out copy-to-clients script as it returns true for typeof operation.
This PR changes the `typeof` check to `constructor.name` so that only objects are replaced in package.json
```console
$ node
Welcome to Node.js v14.15.4.
Type ".help" for more information.
> const arr …
```

fix(generate-clients): call mergeManifest when constructor.name is Object

---

protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Identified prior to https://github.com/aws/aws-sdk-js-v3/pull/1937
Running `yarn generate-clients` makes this code changes. Posting a PR so that they're not merged as part of a different PR.

chore(protocol_clients): update generated tests

---

packages/credential-provider-cognito-identity/tsconfig.cjs.json
packages/credential-provider-cognito-identity/tsconfig.es.json

Missed in https://github.com/aws/aws-sdk-js-v3/pull/1938
Remove duplicate declarationDir in credential-provider-cognito-identity

fix(credential-provider-cognito-identity): remove duplicate declarationDir

---

.gitignore

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1938
gitignore ignores packages/types in addition to types folders used for type definitions
```console
husky > pre-commit (node v14.15.4)
✔ Preparing...
✔ Running tasks...
✖ The following paths are ignored by one of your .gitignore files:
packages/types
Use -f if you really want to add them.
✔ Cleaning up...
husky > commit-msg (node v14.15.4)
```
This PR skips packages/types from gitignore.
Verified that:
* This change continues to gitignore `packages/types/types`
* This change doesn't ignore other changes in `packages/types`, like in `package.json`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

fix: allow packages/types in gitignore

---

package.json
scripts/generate-clients/code-prettify.js
yarn.lock

Fixes: #1947
runs prettier in parallel in generate-clients script by using MIT licensed third-party [@mixer/parallel-prettier](https://www.npmjs.com/package/@mixer/parallel-prettier) package
Metrics to generate all clients:
<details>
<summary>Existing setup takes ~360 seconds</summary>
```console
$ time yarn generate-clients
...
...
Done in 359.39s.
433.54s user 13.15s system 124% cpu 5:59.52 total
```
</details>
<details>
<summary>Disabling prettier takes ~17 seconds</summary>
```console
$ time yarn generate-clients
...
...
Done in 17.10s.
6.29s user 1.55s system 45% cpu 17.262 total
```
</details>
<details>
<summary>Using @mixer/parallel-prettier takes ~83 seconds</summary>
```console
$ time yarn generate-clients
...
...
Done in 83.25s. …
```

feat: run prettier in parallel in generate-clients

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/ISSUE_TEMPLATE/--documentation.md

N/A
Uses headings in bug report templates instead of bold, so that templates can be organize contents in a hierarchy.
<details>
<summary>Bug report template with bold</summary>
</details>
<details>
<summary>Bug report template with headings</summary>
</details>

chore: use headings in bug report templates

---

packages/util-dynamodb/src/convertToAttr.spec.ts
packages/util-dynamodb/src/convertToAttr.ts
packages/util-dynamodb/src/marshall.spec.ts
packages/util-dynamodb/src/marshall.ts
packages/util-dynamodb/src/models.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/1647
Closes: https://github.com/aws/aws-sdk-js-v3/issues/1535
Closes: https://github.com/aws/aws-sdk-js-v3/issues/1865
Closes: https://github.com/aws/aws-sdk-js-v3/issues/1534
Closes: https://github.com/aws/aws-sdk-js-v3/issues/1861
Closes: https://github.com/aws/aws-sdk-js-v3/issues/1102
Closes: https://github.com/aws/aws-sdk-js-v3/issues/1534
adds option to convert class instance to map in `@aws-sdk/util-dynamodb`
```js
convertToAttr(data, { convertClassInstanceToMap: true })
```
Unit tests for marshall and convertToAttr functions
---

feat(util-dynamodb): add option to convert class instance to map

---

.github/workflows/git-sync.yml

Follow-up to https://github.com/aws/aws-sdk-js/pull/3610
use git-sync action to sync with private mirror
*Testing:*
Testing done with the following packages:
* source: [`trivikr/git-sync-test`](https://github.com/trivikr/git-sync-test)
* destination: [`trivikr/private-git-sync-test`](https://github.com/trivikr/private-git-sync-test)
Config tested: https://github.com/trivikr/git-sync-test/blob/302d7d5cf429594757c9a32ead5e0816715f9b95/.github/workflows/git-sync.yml
Example GitHub Action run: https://github.com/trivikr/git-sync-test/runs/1778705960?check_suite_focus=true
Verified that secrets are not shown in the GitHub Action log
<details>
<summary>GitHub Action log</summary>
```
Cloning into '/root/source'... …
```

feat: use git-sync action to sync with private mirror

---

packages/util-user-agent-browser/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1992
Uses default import from bowser as suggested in README https://github.com/lancedikson/bowser#use-cases
Verified that snowpack build is successful and todo-app works after performing:
* `yarn local-publish` to publish packages from workspace using verdaccio.
* `./node_modules/.bin/verdaccio -c verdaccio/config.yaml` to start verdaccio server.
* Use published version `"3.4.2-ci.0"` in todo-app with snowpack.
---

fix(util-user-agent-browser): use default import from bowser

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddCrossRegionCopyingPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

Internal JS-2351, in preparation to add cross region copying to DocDB and Neptune.
Moves addition of cross region copying to `AddCrossRegionCopyingPlugin.java`
Running codegen did not update the clients
---

chore(codegen): move CrossRegionCopying to separate plugin

---

clients/client-docdb/commands/CopyDBClusterSnapshotCommand.ts
clients/client-docdb/commands/CreateDBClusterCommand.ts
clients/client-neptune/commands/CopyDBClusterSnapshotCommand.ts
clients/client-neptune/commands/CreateDBClusterCommand.ts
clients/client-rds/commands/StartDBInstanceAutomatedBackupsReplicationCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddCrossRegionCopyingPlugin.java

Internal JS-2351
supports cross-region-copying in DocDB and Neptune
Verified that generated code adds middleware for operations in DocDB and Neptune
The PR would be made ready, and base branch would be changed to master after https://github.com/aws/aws-sdk-js-v3/pull/1984 is merged.
---

chore(clients): support cross-region-copying in DocDB and Neptune

---

packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.ts
packages/middleware-bucket-endpoint/src/bucketHostname.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostname.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts
packages/middleware-bucket-endpoint/src/configurations.ts
packages/middleware-sdk-s3-control/src/configurations.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/plugin.spec.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/plugin.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/update-arnables-request.ts
packages/middleware-sdk-s3-control/src/redirect-from-postid.spec.ts
packages/middleware-sdk-s3-control/src/redirect-from-postid.ts
packages/protocol-http/src/isValidHostname.spec.ts
packages/protocol-http/src/isValidHostname.ts

Internal issue JS-2243
Support S3 & S3Control customizations with user passed endpoints
Manual integration testing in JS-2245
---

feat: add S3 and S3Control customizations for custom endpoints

---

packages/s3-request-presigner/src/presigner.spec.ts
packages/s3-request-presigner/src/presigner.ts

Previously, if user use `S3RequestPresigner` class to sign an existing request. The request is **required** to have a `host` header to get SigV4 signature properly. This change automatically injects the `host` header if not present, making the code less error prone.
---

feat(s3-request-presigner): automatically add host header

---

CONTRIBUTING.md

N/A
Just a simple URL adjustment to remove the macos route.
N/A - only readme changed.
---

docs(readme): use generic yarn install URL

---

packages/util-dynamodb/src/convertToNative.spec.ts
packages/util-dynamodb/src/convertToNative.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2014
Error states `options.wrapNumbers` when BigInt throws in unmarshall
Unit tests
---

fix(util-dynamodb): state options.wrapNumbers on BigInt error in unmarshall

---

packages/util-dynamodb/src/convertToAttr.spec.ts
packages/util-dynamodb/src/convertToAttr.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2008
adds support to marshall [JavaScript Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) into [DynamoDB Attribute Map](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html#DDB-Type-AttributeValue-M) 
Unit tests
---

feat(util-dynamodb): marshall JavaScript Maps

---

packages/util-dynamodb/src/convertToNative.spec.ts
packages/util-dynamodb/src/convertToNative.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1983
supports unmarshalling small numbers or those using scientific notation
Unit tests
---

fix(util-dynamodb): unmarshall small numbers or those in scientific notation

---

packages/smithy-client/src/client.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1869
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1986
marks `apiVersion` configuration as internal, and explicitly calls out that it is not to be used by customer code.
Tested by verifying that VSCode shows the message in Intellisense.
<details>
<summary>Screenshot</summary>
</details>
---

docs(clients): mark apiVersion as @internal

---

packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1959
set maxSockets=50 by default in node-http-handler
Unit tests
---

fix(node-http-handler)!: set maxSockets=50 by default

---

clients/client-kinesis-video-signaling/KinesisVideoSignalingClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1962
Use getOmitRetryHeadersPlugin in KinesisVideoSignalingClient 

fix(client-kinesis-video-signaling): remove retry headers

---

lib/storage/src/upload/Upload.ts
lib/storage/src/upload/service-clients/Uploader.ts

Keep the old name for now?
The name was introduced in b07e71986817d7781e12d9b687532c58d5ea6ba0
when the file was added
Fix typo in a method name
TODO
---

fix(lib-storage): fix typo in Upload.intialize (initialize)

---

clients/client-sso-oidc/SSOOIDCClient.ts
clients/client-sso-oidc/package.json
clients/client-sso/SSOClient.ts
clients/client-sso/package.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java

Now the client still imports signing dependencies if ALL of the operations has `optionalAuth` trait. The change remove all auth dependencies if non of the operations requires signing
---

feat(client-sso*): remove auth dependencies if client doesn't need

---

clients/client-docdb/package.json
clients/client-neptune/package.json

Missed in https://github.com/aws/aws-sdk-js-v3/pull/1985, probably because of dependency on intermediate PR.
add @aws-sdk/middleware-sdk-rds dependency in DocDB and Neptune
CI
Backlog issue for CI to catch such lack of dependency https://github.com/aws/aws-sdk-js-v3/issues/817
---

fix(deps): add @aws-sdk/middleware-sdk-rds in DocDB and Neptune

---

clients/client-appintegrations/AppIntegrationsClient.ts
clients/client-auditmanager/AuditManagerClient.ts
clients/client-connect-contact-lens/ConnectContactLensClient.ts
clients/client-customer-profiles/CustomerProfilesClient.ts
clients/client-devops-guru/DevOpsGuruClient.ts
clients/client-service-catalog-appregistry/ServiceCatalogAppRegistryClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2038
Remove unsupported CORS retry headers in new services
* Removal of CORS retry headers is already tested with existing services.
* Lack of support for CORS retry headers was found using latest update in report at https://github.com/AllanZhengYP/cors-test/blob/master/output.md
---

fix(clients): remove unsupported CORS retry headers in new services

---

packages/credential-provider-ini/src/index.ts
packages/credential-provider-node/package.json
packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts
packages/credential-provider-process/src/index.ts
packages/node-config-provider/src/fromSharedConfigFiles.ts

This change refactors node credential provider.
* load config and credentials INI files only once, instead of loading them in INI credentials, process credentials provider individually.
* mark `loadedConfig` parameters as internal to reduce the exposure of API.
* other minor code refactor.
These changes are required for new credential provider.
---

fix(credential-provider-node): read config and credentials files only once

---

packages/middleware-sdk-ec2/package.json

<none>
There is an undeclared dependency on `@aws-sdk/protocol-http` in https://github.com/blake-transcend/aws-sdk-js-v3/blob/patch-2/packages/middleware-sdk-ec2/src/index.ts#L1. This adds the dependency to the package.json file
tested locally
<none>
---

fix(middleware-sdk-ec2): add undeclared dependency @aws-sdk/protocol-http

---

protocol_tests/aws-ec2/tests/functional/ec2query.spec.ts
protocol_tests/aws-json/tests/functional/awsjson1_1.spec.ts
protocol_tests/aws-query/tests/functional/awsquery.spec.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/RestXmlProtocol.ts
protocol_tests/aws-restxml/RestXmlProtocolClient.ts
protocol_tests/aws-restxml/commands/XmlUnionsCommand.ts
protocol_tests/aws-restxml/index.ts
protocol_tests/aws-restxml/models/models_0.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

[Code generation for protocol test updates](https://github.com/awslabs/smithy-typescript/pull/268)
`yarn test:protocols`
awslabs/smithy-typescript#268
---

chore(protocol_tests): regenerate protocol test clients

---

packages/credential-provider-ini/src/index.ts
packages/credential-provider-process/src/index.ts

This change adds a  `SourceProfileInit` option interface for credential providers that consumes shared INI file but doesn't need to assume roles. As a result, the `ProcessCredential` only need to use `SourceProfileInit` rather than create its own interface. This change also makes traditional functions to arrow function.

fix(credential-provider-ini): refactor provider options interfaces

---

scripts/generate-clients/.gitignore

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2068
gitignore temporary folder .aws-models
Verified that folder `.aws-models` is not added to git untracked files.
```console
$ yarn generate-clients
...
...
./gradlew failed with { code: 1, signal: null }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ git status
On branch gitignore-temp-aws-models
Your branch is up to date with 'origin/gitignore-temp-aws-models'.
nothing to commit, working tree clean
```
---

fix: gitignore temporary folder .aws-models

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java

Writes an empty JSON object body for requests when an operation in an AWS JSON RPC protocol doesn't have an input.
Updated Smithy 1.6.x protocol tests.
Code generation PR reliant on awslabs/smithy#720 and awslabs/smithy-typescript#275. That will supersede #2072.
---

fix: write undefined JSON RPC input body

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventStreamHandlingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

Follow-up to https://github.com/awslabs/smithy-typescript/pull/257
Removes calls to deprecated model.getKnowledge
Regular expression used for search 'model.getKnowledge\(([^\.]*).class\)'
and replaced with $1.of(model)
Build is successful:
```console
./gradlew clean smithy-aws-typescript-codegen:build protocol-test-codegen:build -Plog-tests
```
---

chore(codegen): update calls to deprecated model.getKnowledge

---

buildspec.yml

Refs: https://github.com/aws/aws-codebuild-docker-images/pull/400
use runtime-versions nodejs in buildspec, as it's updated in ubuntu/standard/4.0/Dockerfile
Verify that CI is successfully run.
---

chore(buildspec): use runtime-versions nodejs

---

clients/client-sso/SSOClient.ts
clients/client-sso/package.json
clients/client-sso/runtimeConfig.browser.ts
clients/client-sso/runtimeConfig.ts
package.json
packages/credential-provider-node/package.json
packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts
packages/credential-provider-sso/LICENSE
packages/credential-provider-sso/README.md
packages/credential-provider-sso/jest.config.js
packages/credential-provider-sso/package.json
packages/credential-provider-sso/src/index.spec.ts
packages/credential-provider-sso/src/index.ts
packages/credential-provider-sso/tsconfig.cjs.json
packages/credential-provider-sso/tsconfig.es.json
packages/property-provider/src/ProviderError.spec.ts
packages/property-provider/src/ProviderError.ts
packages/shared-ini-file-loader/src/index.ts

Resolves: #1158 
Add a credential provider that resolves the cached SSO token by [cli-configure-sso](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html)
---

feat(credential-provider-sso): support resolving credentials from SSO token

---

protocol_tests/aws-ec2/EC2ProtocolClient.ts
protocol_tests/aws-json/JsonProtocolClient.ts
protocol_tests/aws-query/QueryProtocolClient.ts
protocol_tests/aws-restjson/RestJsonProtocolClient.ts
protocol_tests/aws-restxml/RestXmlProtocolClient.ts

Missed in https://github.com/aws/aws-sdk-js-v3/pull/2076
chore(protocol_tests): move auth to standalone plugin
---

chore(protocol_tests): move auth to standalone plugin

---

lib/lib-storage/example-code/file-upload.ts
lib/lib-storage/src/bytelength.ts
lib/lib-storage/src/chunker.ts
lib/lib-storage/src/chunks/getDataReadable.ts

Fixes #2100
#2100
Changes `import` and require `statements` to be consistent with the rest of the code base.
This commit contains no functional change.
---

chore(lib-storage): use consistent imports

---

clients/client-budgets/models/models_0.ts
clients/client-chime/models/models_0.ts
clients/client-chime/models/models_1.ts
clients/client-dynamodb/models/models_0.ts
clients/client-honeycode/models/models_0.ts
clients/client-organizations/models/models_0.ts
clients/client-rds-data/models/models_0.ts
clients/client-redshift-data/models/models_0.ts
clients/client-sagemaker/models/models_2.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/277
Added missing filterSensitiveLog operations for some structures.
---

fix: call filterSensitiveLog for missing structures

---

packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts

The commit 01bd1a073022eff77f003a3fd310bac2c54dbcb4 was mistakenly merged to main branch, we're investigating why it happened. It's part of PR which is not ready yet https://github.com/aws/aws-sdk-js-v3/pull/2093
This commit is causing CI to fail on main branch and PRs. Examples:
* https://us-west-2.console.aws.amazon.com/codebuild/home?region=us-west-2#/builds/sdk-staging-test:aca5254e-9f72-48ff-82a1-9103054d0242/view/new
* https://us-west-2.console.aws.amazon.com/codebuild/home?region=us-west-2#/builds/sdk-staging-test:4843e6bf-d55c-48d0-b14e-e4f4161baf9c/view/new
This reverts commit 01bd1a073022eff77f003a3fd310bac2c54dbcb4.
---

fix(middleware-bucket-endpoint): revert add support for s3 object lamdbas

---

clients/client-auto-scaling/package.json
clients/client-cloudformation/package.json
clients/client-cloudfront/package.json
clients/client-cloudsearch/package.json
clients/client-cloudwatch/package.json
clients/client-docdb/package.json
clients/client-ec2/package.json
clients/client-elastic-beanstalk/package.json
clients/client-elastic-load-balancing-v2/package.json
clients/client-elastic-load-balancing/package.json
clients/client-elasticache/package.json
clients/client-iam/package.json
clients/client-neptune/package.json
clients/client-rds/package.json
clients/client-redshift/package.json
clients/client-route-53/package.json
clients/client-s3-control/package.json
clients/client-s3/package.json
clients/client-ses/package.json
clients/client-sns/package.json
clients/client-sqs/package.json
clients/client-sts/package.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
protocol_tests/aws-ec2/package.json
protocol_tests/aws-query/package.json
protocol_tests/aws-restxml/package.json
yarn.lock

N/A
Pinning fast-xml-parser to v3.17.4 as the project switched to modified MIT License in >=v3.17.5 in https://github.com/NaturalIntelligence/fast-xml-parser/commit/5d4e95188c4d3bf57ee1b2f5489c017ca3be627c
CI. Integration tests.
---

fix(deps): pin fast-xml-parser to v3.17.4

---

packages/middleware-signing/package.json
packages/middleware-signing/src/configuration.spec.ts
packages/middleware-signing/src/configurations.ts

Resolves #2107
It turns out not difficult to fix. When resolving the credentails in the `resolveAwsAuthConfig()`, if the user supplies a customer credential provider, the client will memoize the resolved value. If the resolved value is expired, the credential will be reloaded. If the credential provider only returns a static credential(never expires), the credential will keep memoized.
---

fix(middleware-signing): memoize temporary credentials

---

codegen/LICENSE
codegen/NOTICE
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1.java

n/a
This updates the gradle build scripts to allow for publishing of the AWS protocol generators. Most of the java stuff had to be pulled up to the root since the maven plugin requires it to be there, but the actual contents haven't changed aside from javadoc getting run.
Ran a clean build that succeeded.
This isn't actually forcing you to publish to maven, just making it possible. In the short term it enables publishing to maven local so that somebody could run the AWS generators outside of this repo if the locally published the generator first.
The license copy is there because we need one under the java project root to be included in the built jar
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

chore: Enable publishing of the aws generator

---

codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2151
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2152
Pin smithy dependencies to minor version 1.6.x as both our Java CI as well as generate-clients scripts are failing.
Verified that Java CI and generate-clients script was successful.
---

fix(codegen): pin smithy dependencies to minor version 1.6.x

---

clients/client-auto-scaling/package.json
clients/client-cloudformation/package.json
clients/client-cloudfront/package.json
clients/client-cloudsearch/package.json
clients/client-cloudwatch/package.json
clients/client-docdb/package.json
clients/client-ec2/package.json
clients/client-elastic-beanstalk/package.json
clients/client-elastic-load-balancing-v2/package.json
clients/client-elastic-load-balancing/package.json
clients/client-elasticache/package.json
clients/client-iam/package.json
clients/client-neptune/package.json
clients/client-rds/package.json
clients/client-redshift/package.json
clients/client-route-53/package.json
clients/client-s3-control/package.json
clients/client-s3/package.json
clients/client-ses/package.json
clients/client-sns/package.json
clients/client-sqs/package.json
clients/client-sts/package.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
protocol_tests/aws-ec2/package.json
protocol_tests/aws-query/package.json
protocol_tests/aws-restxml/package.json
yarn.lock

Refs: https://github.com/awslabs/smithy-typescript/pull/290
The fast-xml-parser was pinned to v3.17.4 as the project switched to modified MIT License in >=3.17.5 in https://github.com/NaturalIntelligence/fast-xml-parser/commit/5d4e95188c4d3bf57ee1b2f5489c017ca3be627c
The license is now updated to MIT in [3.19.0](https://github.com/NaturalIntelligence/fast-xml-parser/blob/bbfecf97821c62685555c21a09e4071690899fef/package.json#L70)
CI and protocol_tests
---

chore(deps): pin fast-xml-parser to 3.19.0

---

lib/lib-storage/package.json
lib/lib-storage/src/bytelength.ts
lib/lib-storage/src/runtimeConfig.shared.ts
lib/lib-storage/src/runtimeConfig.ts

fixes: https://github.com/aws/aws-sdk-js-v3/issues/2136, https://github.com/aws/aws-sdk-js-v3/issues/2156
Ran manual tests on browser and in node 
Browser code: 
```
(async () => {
const creds = fromCognitoIdentityPool({
client: new CognitoIdentityClient({ region }),
identityPoolId: idPool,
});
const client = new S3Client({
region,
credentials: creds
});
const Key = `${Date.now()}-new-key`;
let upload = new Upload({
client,
tags: [{
Key: "my-tag-key",
Value: "my-tag-value"
}],
params: { Key, Bucket,
Body: "hello world!"
}
}); 
upload.on("httpUploadProgress", (progress ) => {
console.log(progress);
});
const uploadResult = await upload.done(); …
```

fix(lib-storage): fix fs error on browsers when using lib-storage upload

---

packages/s3-presigned-post/README.md

Amends example code in README: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_s3_presigned_post.html#generate-a-presigned-post
`client` is a required first argument for `createPresignedPost`.
---

docs(s3-presigned-post): fix to example in README

---

packages/credential-provider-web-identity/LICENSE
packages/credential-provider-web-identity/README.md
packages/credential-provider-web-identity/jest.config.js
packages/credential-provider-web-identity/package.json
packages/credential-provider-web-identity/src/fromTokenFile.spec.ts
packages/credential-provider-web-identity/src/fromTokenFile.ts
packages/credential-provider-web-identity/src/index.ts
packages/credential-provider-web-identity/tsconfig.cjs.json
packages/credential-provider-web-identity/tsconfig.es.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1808
Adds fromTokenFile credential provider to read credentials from EKS service account.
- Reads file location of where the OIDC token is stored from either provided option `webIdentityTokenFile` or environment variable `AWS_WEB_IDENTITY_TOKEN_FILE`.
- Reads IAM role wanting to be assumed from either provided option `roleArn` or environment variable `AWS_ROLE_ARN`.
- Reads optional role session name to be used to distinguish sessions from provided option `roleSessionName` or environment variable `AWS_ROLE_SESSION_NAME`.
If session name is not defined, it comes up with a role session name.
- Reads OIDC token from file on disk.
- Calls sts:AssumeRoleWithWebIdentity via `roleAssumerWithWebIdentity` option to get credentials.
| …

feat(credential-provider-web-identity): add fromTokenFile credentials provider 

---

packages/credential-provider-ini/README.md
packages/credential-provider-ini/package.json
packages/credential-provider-ini/src/index.spec.ts
packages/credential-provider-ini/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1808
~~The base branch for this PR would be changed to main after https://github.com/aws/aws-sdk-js-v3/pull/2177 is merged.~~ Done ✅
Call fromTokenFile in assumeRole chaining
Unit tests
---

feat(credential-provider-ini): call fromTokenFile in assumeRole chaining

---

packages/credential-provider-ini/src/index.ts

Simple typo in the docs/comments
Changing "returna" to returns
---

docs(credential-provider-ini): docs typo

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

SSDKs do not automatically fill idempotency tokens.
Local integration testing
---

fix: disable idempotency autofill import when not generating a client

---

README.md
UPGRADING.md

docs: add v2 to v3 API changes to UPGRADING.md

---

codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegrationTest.java

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2195
pass settings to createSymbolProvider
codegen-ci
---

fix(codegen): pass settings to createSymbolProvider

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
clients/client-sts/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
protocol_tests/aws-ec2/protocols/Aws_ec2.ts
protocol_tests/aws-query/protocols/Aws_query.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1893
Sets trimValues=false in fast-xml-parser configuration, so that values are not trimmed while parsing.
CI
---

fix(clients): trim values in parsed xml only if result is empty

---

packages/credential-provider-web-identity/README.md
packages/credential-provider-web-identity/src/fromTokenFile.spec.ts
packages/credential-provider-web-identity/src/fromTokenFile.ts
packages/credential-provider-web-identity/src/fromWebToken.spec.ts
packages/credential-provider-web-identity/src/fromWebToken.ts
packages/credential-provider-web-identity/src/index.ts

Add a new credential provider that wraps the `sts:AssumeRoleWithWebIdentity` API. This credential provider will be equivalent to the `AWS.WebIdentityProvider` in v2 SDK([getting started guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/config-web-identity-examples.html)).
---

feat(credential-provider-web-identity): support web federated identity

---

packages/util-user-agent-browser/package.json

Fix the react native entry point. Need to use the entry point
pattern in `react-native` field of package.json, instead of replace
pattern in clients. Because the later one isn't applicable to
entry point file like index.js
`x-amz-user-agent` is now `aws-sdk-js/3.11.0 os/other lang/js md/rn api/3.11.0`
<details>
<summary>Screen Shot</summary>
</details>
---

fix(util-user-agent-browser): react native useragent metadata

---

UPGRADING.md

Add documents for DynamoDB Document client and mention the endpoint discovery is not yet supported.
---

docs(upgrading): add doc client and endpoint discovery

---

packages/util-user-agent-browser/src/index.ts

In sandboxed environments (pure v8) `window` can be undefined. Should not fail.
Actually should always check for `globalThis` instead, but IE 11 is still alive....
---

fix(util-user-agent-browser): `window` can be undefined

---

packages/credential-provider-imds/src/fromContainerMetadata.ts

N/A
This PR uses the following in fromContainerMetadata:
* async-await instead of Promises
* arrow functions
CI
---

chore(credential-provider-imds): use arrow+async functions in fromContainerMetadata

---

CONTRIBUTING.md

na
The codegen link currently results in a 404 error, as the /codegen/sdk-codegen folder does not contain a README file.  
This change simply moves the link to the codegen/README file which correctly explains how to run the scripts.
Verified in github new link points to  a valid location that correctly explains codegen
---

docs(contributing): correct codegen link

---

packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.ts

In #1635, identityId was added to return value of `fromCognitoIdentity` and `fromCognitoIdentityPool` but not to the return type.
Check tsc does not report error.
---

fix(credential-provider-cognito-identity): add identityId to return type of fromCognitoIdentity

---

packages/util-user-agent-node/src/index.spec.ts
packages/util-user-agent-node/src/index.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2027
This change fix an issue that SDK need to read shared config files to load App ID for every request. Now this change only load the App ID once at the client instantiation. This will remove some performance overhead.
---

fix(util-user-agent-node): should memoize app id

---

README.md
packages/middleware-retry/package.json
packages/middleware-retry/src/index.native.ts
packages/middleware-retry/src/index.ts
packages/middleware-sdk-transcribe-streaming/package.json
packages/middleware-sdk-transcribe-streaming/src/index.native.ts
tests/react-native/End2End/App.tsx
tests/react-native/End2End/package.json
yarn.lock

Co-authored-by: Nicolas Perraut <n.perraut@gmail.com>
Related to #1536
Replaces https://github.com/aws/aws-sdk-js-v3/pull/2108
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1797
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2051
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2192
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2199
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2219
This PR marks react-native-get-random-values as optional peer dependency to prevent install on non React Native environments.
Verified that ReactNative E2E tests are successful.
<details>
<summary>Command line output</summary>
```console
$ pwd
/Users/trivikr/workspace/aws-sdk-js-v3/tests/react-native/End2End
$ node launch-app.js --local-publish
...
PASS  e2e/End2EndTest.spec.js (14.5s)
S3 …
```

fix(deps): request consumers to install react-native polyfills

---

clients/client-s3/protocols/Aws_restXml.ts
codegen/sdk-codegen/aws-models/s3.2006-03-01.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2040
Add smithy.api#httpPayload to GetBucketPolicyOutput.
Verified that the issue in https://github.com/aws/aws-sdk-js-v3/issues/2040 is not reproducible with this fix.
Verified that this issue is fixed in smithy models, and will not be reverted in the next models update.
---

fix(client-s3): return GetBucketPolicyOutput without parsing

---

protocol_tests/aws-restjson/protocols/Aws_restJson1.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

Internal JS-2492
Generated code to consume smithy [httpQueryParams](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpqueryparams-trait) trait. Codegen PR in https://github.com/awslabs/smithy-typescript/pull/311
CI, as well as with API Gateway client in https://github.com/aws/aws-sdk-js-v3/pull/2249
This PR will be merged to `pin-smithy-1.7.x` branch which would update PR https://github.com/aws/aws-sdk-js-v3/pull/2197
---

chore(protocol_tests): consume httpQueryParams trait

---

codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
protocol_tests/aws-restjson/RestJsonProtocol.ts
protocol_tests/aws-restjson/RestJsonProtocolClient.ts
protocol_tests/aws-restjson/commands/QueryParamsAsStringListMapCommand.ts
protocol_tests/aws-restjson/commands/QueryPrecedenceCommand.ts
protocol_tests/aws-restjson/index.ts
protocol_tests/aws-restjson/models/models_0.ts
protocol_tests/aws-restjson/protocols/Aws_restJson1.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/RestXmlProtocol.ts
protocol_tests/aws-restxml/RestXmlProtocolClient.ts
protocol_tests/aws-restxml/commands/QueryParamsAsStringListMapCommand.ts
protocol_tests/aws-restxml/commands/QueryPrecedenceCommand.ts
protocol_tests/aws-restxml/index.ts
protocol_tests/aws-restxml/models/models_0.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2153
Pins smithy to minor version 1.7.x
CI
---

chore(codegen): pin smithy to minor version 1.7.x

---

packages/core-packages-documentation-generator/src/sdk-index-link-client.ts

Fix the links to AWS clients in global.html: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/globals.html
---

docs(packages): fix aws client link in globals.html

---

packages/client-documentation-generator/src/sdk-client-toc-plugin.ts

Currently the API reference shows extra client of SSO and STS from the dependencies:
With this change, the extra client that not sourced from the same client folder will be filtered out from the table of content:
STS Client itself won't be affected:
---

docs(clients): remove excessive STS and SSO client from TOC

---

lib/lib-dynamodb/tsconfig.cjs.json
lib/lib-dynamodb/tsconfig.es.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2216
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2193
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2244
Remove `stripInternal=true` from tsconfig
The build succeeds with repro repo shared in https://github.com/JeremyDurnell/aws-sdk-js-v3-dynamo-ts-bug
---

fix(lib-dynamodb): remove stripInternal=true from tsconfig

---

tests/react-native/End2End/README.md
tests/react-native/End2End/package.json

Update ReactNative test project README to mention some papercuts that people may run into first-time setting up.
---

test(react-native): update end2end test project

---

packages/credential-provider-ini/README.md
packages/credential-provider-ini/package.json
packages/credential-provider-ini/src/index.spec.ts
packages/credential-provider-ini/src/index.ts

support credential_source in shared credential file
[JS-2536]
---

feat(credential-provider-ini): support credential_source in shared file

---

clients/client-lex-runtime-v2/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttp2Dependency.java

This cutomization should be merged with next Smithy model update. It adds Http2 support for Lex Runtime V2 client to support bidirectional streaming.
---

feat(client-lex-runtime-v2): add http2 support

---

README.md

We wanted to quickly provide an easy way to highlight some of the core concepts of AWS SDK v3 that are largely similar between clients. We're putting this at the top level readme. This is by no means an exhaustive list and we'd love comments on other topics people would like included here. 
---

docs(readme): highlight high level concepts

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsTraitsUtils.java
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/NotSame.smithy
packages/config-resolver/src/EndpointsConfig.ts

These changes are to support generating a non-AWS typescript client. There are changes in the code generation logic to skip pieces that apply only to AWS services. Some typescript dependencies (aws-sdk/config-resolver) also needed updates.
This is initial prototype work for smithy-typescript-ssdk-demo.
Using these changes I successfully generated a working non-AWS typescript client for the bootleg-service in smithy-typescript-ssdk-demo.
---

Support generating non-AWS client

---

clients/client-cognito-identity/karma.conf.js
clients/client-s3/karma.conf.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2265
Explicitly use ChromeHeadless with no-sandbox in e2e tests.
Verified that E2E tests are successfully run:
```console
$ node ./tests/e2e/index.js
```
---

fix(e2e): explicitly use ChromeHeadless with no-sandbox

---

scripts/generate-clients/README.md

Documentation to mention dependency on smithy-typescript.
Add link in documentation text for the dependency smithy-typescript
The link to external dependency install steps works, as has been noted by myself and @ajredniwja
The dependency on smithy-typescript crosses over from the usual node/javascript package ecosystem into java/maven/gradle used by smithy.  It's also for an internal/developer step in the codebase.  As such it is not an automated install of the dependency.
---

docs(upgrading): add generate-clients doc dependencies

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
packages/config-resolver/src/CustomEndpointsConfig.ts
packages/config-resolver/src/EndpointsConfig.ts
packages/config-resolver/src/index.ts

This is a refactoring of my earlier attempt at getting a non-AWS client working wrt endpoint resolution. This addresses the concern in https://github.com/aws/aws-sdk-js-v3/pull/2279#discussion_r617402875 by separating out the logic used by AWS client v/s non-AWS client. Also makes endpoint required for non-AWS client, addressing https://github.com/adamthom-amzn/aws-sdk-js-v3/pull/1#issuecomment-804665638.
This approach adds some duplication. But seems to fit within the current plugin model in the codegen. Trying to use the same EndpointsConfig.ts but different methods/types would not fit easily into the ServiceGenerator logic. I thought it is better to have some minimal duplication in config-resolver than bigger restructing in codegen.
I generated the client used in our …

chore(codegen,config-resolver): refactor how endpoint is resolved for non-AWS client

---

packages/client-documentation-generator/src/sdk-client-toc-plugin.ts

The current client reference contains unwanted commands from STS & SSO because they are pulled from the dependencies: like `AssumeRoleCommand` and `AssumeRoleWithSAMLCommand` in the screen shot bellow:
<details><summary>Current ToC screenshot</summary>
<p>
</p>
</details>
This change moves these unwanted commands to the bottom:
<details><summary>New ToC screenshot</summary>
<p>
</p>
</details>
This change also provide aggregation of the waiters.
<details><summary>Aggregation of Waiters</summary>
<p>
</p>
</details>
---

docs(clients): remove unexpected STS commands

---

packages/config-resolver/src/CustomEndpointsConfig.spec.ts
packages/config-resolver/src/CustomEndpointsConfig.ts

Adding tests for new CustomEndpointsConfig
```
yarn build
yarn test
```
---

test(config-resolver): add test for CustomEndpointsConfig

---

packages/xml-builder/src/XmlText.spec.ts
packages/xml-builder/src/escape-element.spec.ts
packages/xml-builder/src/escape-element.ts

XML entity encoding for carriage return, line feed, next line, line separator characters,
quote and single quote
JS-2318
**Open question**
This can bring potential, but unlikely, breaking change because the `"` and `'` which previously unencoded, is now encoded to `&quot;` `&apos;` to match the behavior of other SDKs, like [Java v2](https://github.com/aws/aws-sdk-java-v2/pull/2399/files). But I've confirmed that the same content after deserialized is not changed.
---

fix(xml-builder): xml entity encoding for more characters

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsTraitsUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/NotSame.smithy
packages/config-resolver/src/CustomEndpointsConfig.spec.ts
packages/config-resolver/src/CustomEndpointsConfig.ts
packages/config-resolver/src/EndpointsConfig.ts
packages/config-resolver/src/index.ts

This rebases the ssdk branch so that it can be merged into main. Keeping the ssdk branch as a separate feature branch has become cumbersome and will only become more problematic over time.
Note: this build won't pass until this is merged in: https://github.com/awslabs/smithy-typescript/pull/315/
---

chore: merge ssdk branch into main

---

packages/middleware-user-agent/src/user-agent-middleware.spec.ts
packages/middleware-user-agent/src/user-agent-middleware.ts

Internal JS-2583: Some services do not output custom headers in the query logs, so the UA string is missing for those services in metrics database.
* Swaps user agent headers for non-browser environments.
* Retains `x-amz-user-agent` for browser as it's similar to v2 behavior https://github.com/aws/aws-sdk-js/blob/bfb22c7b474e72791f16ef0fcb5db7794a0207a3/lib/http.js#L114-L117
Unit tests
---

fix(middleware-user-agent-header): swap user agent headers for non-browser environments

---

README.md

Line 388 contains invalid language mark, it causes panic for reference generator.
---

docs(readme): fix code examples format in readme

---

packages/client-documentation-generator/src/sdk-client-rename-project.ts
packages/client-documentation-generator/src/sdk-client-toc-plugin.ts
packages/client-documentation-generator/src/utils.ts

Currently the google search doesn't show link
with this change, each client will have a more descriptive title:
---

docs(clients): descriptive client title

---

package.json
packages/credential-provider-node/README.md
packages/credential-provider-node/package.json
packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts
packages/credential-provider-web-identity/package.json
packages/credential-provider-web-identity/src/fromTokenFile.spec.ts
packages/credential-provider-web-identity/src/fromTokenFile.ts

Fixes #2148 
Adds default support for web identity credentials. This is useful when using this SDK with [IAM Roles for Service accounts in EKS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) which set `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` behind the scenes. Without this the default behavior of the SDK is to use credentials from IMDS.
Tests have been updated.
Additional updates include:
- Update `README.md` to include web identity params and default load order information (fixes typo)
- Set `init` param of `fromTokenFile` to optional. Default to the default web identity assume role function from `client-sts` if not provided
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

feat(credential-provider-node): add support for web identity provider

---

packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts

#1525 
detect errors on the NodeHttp2Handler, immediately destroy
connections on unexpected error mode, and reconnect.
Prior to this PR, if the server sent the client a GOAWAY frame,
the session would not be removed from the connection pool and requests
would fail indefinitely. This fixes that.
This tries to avoid keeping streams(requests) on the Http2Session
(tcp connection) from being stuck in an open state waiting for a gentle
close even if there were unexpected protocol or connection errors
during the request, assuming http2 errors are rare.
(if a server or load balancer or network is misbehaving,
close() might get stuck waiting for requests to finish,
especially if requests and sessions don't have timeouts?)
I'm only slightly familiar with http/2 client implementations from
working …

fix(node-http-handler): handle NodeHttp2Handler session failure

---

packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/smithy-client/src/sdk-error.ts
protocol_tests/aws-ec2/tests/functional/ec2query.spec.ts
protocol_tests/aws-json/tests/functional/awsjson1_1.spec.ts
protocol_tests/aws-query/tests/functional/awsquery.spec.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Resolves https://github.com/aws/aws-sdk-js-v3/issues/2292
The lower level stacks than throw anything to retry strategy in
practice, so casting them to SdkError type is unsafe. With this
change the retryStrategy will do best effort to convert the
thrown any object to SdkError and then supply to retryDecider
and so on.
Another change is making SdkError type more general. It previously
requires $fault, $metadata, which is obviously incorrect. Error
thrown by SDK itself never contains these keys. So I mark them
optional. Granted this is a breaking change to function interface
like RetryDecider, but anyone depending it being required should
already fail anyway.
/cc @just-boris
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

fix(middleware-retry): defaultStrategy handles any error

---

clients/client-sts/defaultRoleAssumers.spec.ts
clients/client-sts/defaultStsRoleAssumers.ts
packages/credential-provider-node/src/index.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2275
The default role assumer will now call the `sts:assumeRole` API with the supplied source credentials. Previously, the STS client internal only use the source credential from the first invocation.
---

fix(client-sts): make role assumer source creds refreshable

---

packages/endpoint-cache/LICENSE
packages/endpoint-cache/README.md
packages/endpoint-cache/jest.config.js
packages/endpoint-cache/package.json
packages/endpoint-cache/src/Endpoint.ts
packages/endpoint-cache/src/EndpointCache.spec.ts
packages/endpoint-cache/src/EndpointCache.ts
packages/endpoint-cache/src/index.ts
packages/endpoint-cache/tsconfig.cjs.json
packages/endpoint-cache/tsconfig.es.json
yarn.lock

Refs: https://github.com/aws/aws-sdk-js-v3/issues/2211
adds EndpointCache for Endpoint Discovery:
* uses `mnemonist/lru-cache` for storing the cache.
* the `set` operation stores milliseconds elapsed since the UNIX epoch in Expires param based on CachePeriodInMinutes provided in Endpoint.
* the `get` operation returns a random un-expired endpoint. 
Unit tests
---

feat(endpoint-cache): add EndpointCache for Endpoint Discovery

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

This adds differentation for empty body behavior in restJson1. For
responses this protocol requires always sending an empty json object
if there is some shape defined as output but nothing bound to the
body or payload.
depends on: https://github.com/awslabs/smithy-typescript/pull/305
---

Differentiate server serde

---

clients/client-api-gateway/protocols/Aws_restJson1.ts
clients/client-auditmanager/protocols/Aws_restJson1.ts
clients/client-backup/protocols/Aws_restJson1.ts
clients/client-chime/protocols/Aws_restJson1.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-devops-guru/protocols/Aws_restJson1.ts
clients/client-elastic-inference/protocols/Aws_restJson1.ts
clients/client-elasticsearch-service/protocols/Aws_restJson1.ts
clients/client-greengrass/protocols/Aws_restJson1.ts
clients/client-guardduty/protocols/Aws_restJson1.ts
clients/client-iot-events/protocols/Aws_restJson1.ts
clients/client-iot/protocols/Aws_restJson1.ts
clients/client-iotanalytics/protocols/Aws_restJson1.ts
clients/client-iotsitewise/protocols/Aws_restJson1.ts
clients/client-lambda/protocols/Aws_restJson1.ts
clients/client-lex-runtime-v2/protocols/Aws_restJson1.ts
clients/client-macie2/protocols/Aws_restJson1.ts
clients/client-mgn/protocols/Aws_restJson1.ts
clients/client-pinpoint-email/protocols/Aws_restJson1.ts
clients/client-ram/protocols/Aws_restJson1.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-securityhub/protocols/Aws_restJson1.ts
clients/client-sesv2/protocols/Aws_restJson1.ts
clients/client-transcribe-streaming/protocols/Aws_restJson1.ts
clients/client-xray/protocols/Aws_restJson1.ts
protocol_tests/aws-restjson/protocols/Aws_restJson1.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/305
Write content-type header for missing operations
CI
---

chore(clients): write content-type header for missing operations

---

packages/middleware-bucket-endpoint/src/bucketHostname.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostname.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/plugin.spec.ts

3 formats of ARN s3 accepts is touched in this change: Outposts ARN, AccessPoint ARN,
and ObjectLambda ARN. Here are the changes:
* All of the 3 ARN formats no longer accept s3 global region: s3-global("s3.amazonaws.com"),
s3-external-1("s3-external-1.amazonaws.com").
* Outposts ARN no longer support FIPS region, e.g. fips-us-gov-east-1
* AccessPoint ARN accepts FIPS regions with a special endpoint format, e.g. `{accesspoint-name}-{account-id}.s3-accesspoint[-fips][.dualstack].{region}.{partition}`
* ObjectLambda ARN accepts FIPS regions with a special endpoint format, e.g. `{accesspointName}-{accountId}.s3-object-lambda[-fips].{region}.{dnsSuffix}`
#JS-2608
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

feat(middleware-bucket-endpoint): arn supports fips & handles global regions

---

packages/endpoint-cache/src/EndpointCache.spec.ts
packages/endpoint-cache/src/EndpointCache.ts

`mnemonist` is a pretty big (well, for web-bundles anyway) commonjs package, which is currently included IN FULL from the endpoint-cache package. This is less than ideal when using the sdk on the frontend side, since it adds about 270kb to the bundle (before minification).
Since only the LRU-Cache is needed, changing the import to directly target the lru-cache module helps bundlers tree shake correctly, reducing the included code to about 15kb.
I ran compilation on the `endpoint-cache` package and executed the commonjs build via `node dist/cjs/EndpointCache.js` just to check if the import would throw. I tested the es build integrated in my webpack project to check the reduced bundle size.
Also ran `yarn test:all`
Before:
After:
---
By submitting this pull request, I confirm that you can …

fix(endpoint-cache): reduce bundle size

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

This updates the java group name to `software.amazon.smithy.typescript` so that publishing can be isolated from base smithy.
related: https://github.com/awslabs/smithy-typescript/pull/341
---

chore: update java group name

---

codegen/build.gradle.kts

AWS has their own instance of the sonatype repo which we are obligated to use.
---

chore: update sonatype repo url to AWS specific url

---

packages/middleware-retry/src/defaultRetryQuota.ts
packages/middleware-retry/src/defaultStrategy.spec.ts
packages/middleware-retry/src/defaultStrategy.ts
packages/middleware-retry/src/index.ts
packages/middleware-retry/src/types.ts

Refs: internal JS-2633
move non-config interfaces to types.ts in middleware-retry.
This is similar to `types.ts` file in:
* lib-storage https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/types.ts
* middleware-stack https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-stack/src/types.ts
CI
---

chore(middleware-retry): move non-config interfaces to types.ts

---

protocol_tests/aws-ec2/package.json
protocol_tests/aws-json/package.json
protocol_tests/aws-query/package.json
protocol_tests/aws-restjson/package.json
protocol_tests/aws-restxml/package.json

* Refs: https://github.com/aws/aws-sdk-js-v3/pull/2440#issuecomment-850410316
* `@aws-sdk/types` were moved to deps in https://github.com/aws/aws-sdk-js-v3/pull/1902 for clients, but weren't removed from protocol_tests.
Removes @aws-sdk/types from devDeps, as it's present in deps.
* CI
* Verified that running `yarn generate-clients` does not add `@aws-sdk/types` in devDeps.
---

chore(protocol_tests): remove @aws-sdk/types from devDeps

---

packages/node-config-provider/README.md

This PR fixes the package name. As of now, it is `@aws-sdk/node-http-handler` but should be `@aws-sdk/node-config-provider`.
---

docs(node-config-provider): fix package name in README

---

lib/lib-storage/README.md
lib/lib-storage/example-code/upload-string.ts

Fix the typo in the readme and example code
"paralell -> parallel"
Example code was tested locally
---

docs(lib-storage): fix typo paralell -> parallel

---

clients/client-sts/defaultRoleAssumers.spec.ts
clients/client-sts/defaultRoleAssumers.ts
clients/client-sts/defaultStsRoleAssumers.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts

Resolves #2356 
This change allows users to overwrite the `requestHandler` of the STS client used in the default role assumers from
`getDefaultRoleAssumer` and `getDefaultRoleAssumerWithWebIdentity`. As a result, you can specify the http options
of the under lying STS client like `socketTimeout`, `connectionTimeout` and the `httpsAgent` etc.
unit test
---

fix(client-sts): allow overwriting default role assumer http handler

---

UPGRADING.md

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2405
add waiters and credentials(with all the v2 credentials the their equivalents in v3) to upgrading guide
---

docs(upgrading): add waiters and credentials upgrading guide

---

README.md

N/A
The current link to `package-lock.json` is `404`.
This PR is update it and add link of `yarn.lock`.
N/A
This PR just update README. No need testing.

docs(README): update lock file's link

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependency.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependencyTest.java
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/NonAwsService.smithy

I had disabled user agent plugin for non AWS clients earlier as it depended on serviceId which is not present for non AWS services. This enables it back. serviceId is [optional](https://github.com/aws/aws-sdk-js-v3/blob/10db5ac2aa34d11ecf039ab51071f55985d76cf0/packages/util-user-agent-node/src/index.ts#L10), so omitting it for non AWS services.
Added unit tests.
Generated client for non AWS service in demo package and looked at headers sent to the service by this client and compared with AWS service's client.
Demo service client:
```
user-agent: aws-sdk-js/1.0.0-rc.1 os/darwin/19.6.0 lang/js md/nodejs/15.10.0
x-amz-user-agent: aws-sdk-js/1.0.0-rc.1
```
where 1.0.0-rc.1 is the version of generated client in its package.json.
AWS service client (used AccessAnalyzerClient):
```
user-agent: …
```

feat(codegen): add user agent for non AWS clients

---

packages/middleware-retry/src/configurations.spec.ts
packages/middleware-retry/src/configurations.ts
packages/middleware-retry/src/retryMiddleware.spec.ts
packages/middleware-retry/src/retryMiddleware.ts

Internal JS-2636
Call retry strategy based on value in retryMode.
Verified that adaptive retry strategy is called when retryMode is passed:
```js
const { DynamoDB } = require("../aws-sdk-js-v3/clients/client-dynamodb");
(async () => {
const client = new DynamoDB({ retryMode: "adaptive" });
await client.listTables({ Limit: 1 });
})();
```
Verified that retryStrategy.mode was `"adaptive"` in retryMiddleware using console.log
---

feat(middleware-retry): call retry strategy based on value in retryMode

---

packages/middleware-retry/src/index.ts

Follow-up to:
* https://github.com/aws/aws-sdk-js-v3/pull/2439
* https://github.com/aws/aws-sdk-js-v3/pull/2454
Export DefaultRateLimiter, so that customer can use it for creating a custom AdaptiveRetryStrategy as follows:
```js
import { AdaptiveRetryStrategy, DefaultRateLimiter } from "@aws-sdk/middleware-retry";
...
const client = new DynamoDB({
region,
retryStrategy: new AdaptiveRetryStrategy({
rateLimiter: new DefaultRateLimiter({ beta: 0.5 })
}),
});
...
```
CI
---

chore(middleware-retry): export DefaultRateLimiter

---

packages/middleware-retry/src/defaultRetryQuota.ts

N/A
Add options to StandardRetryStrategy to allows granular customization.
It now accepts noRetryIncrement, retryCost and timeoutRetryCost.
CI
---

chore(middleware-retry): add options to StandardRetryStrategy

---

protocol_tests/aws-ec2/tests/functional/ec2query.spec.ts
protocol_tests/aws-query/tests/functional/awsquery.spec.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2464
The protocol_tests were mistakenly formatted using prettier v2.2.1 in the workspace for PR https://github.com/aws/aws-sdk-js-v3/pull/2464
The prettier version was bumped to v2.3.0 in https://github.com/aws/aws-sdk-js-v3/pull/2444
Verified the prettier v2.3.0 was installed before running `yarn generate-clients` as follows:
```console
$ ./node_modules/.bin/prettier --version
2.3.0
```
Verified that prettier formatting for protocol_tests is same as that in https://github.com/aws/aws-sdk-js-v3/pull/2444
---

fix(protocol_tests): format files using prettier v2.3.0

---

clients/client-applicationcostprofiler/ApplicationCostProfilerClient.ts
clients/client-apprunner/AppRunnerClient.ts
clients/client-ssm-contacts/SSMContactsClient.ts
clients/client-ssm-incidents/SSMIncidentsClient.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2464
The documentation for config.region for new clients is different.
For example, for new client `client-applicationcostprofiler` it has suffix ` or use as signingRegion` https://github.com/aws/aws-sdk-js-v3/blob/72cc2dc89f89b6f3290bed623ebb43e5725bed0d/clients/client-applicationcostprofiler/ApplicationCostProfilerClient.ts#L165-L168
The suffix is missing in old clients: https://github.com/aws/aws-sdk-js-v3/blob/72cc2dc89f89b6f3290bed623ebb43e5725bed0d/clients/client-dynamodb/DynamoDBClient.ts#L339-L342
It's likely that this suffix was mistakenly added when clients were updated in https://github.com/aws/aws-sdk-js-v3/pull/2464
Verified that the documentation for region is for new clients is same as that in previous clients.
---
By …

fix(clients): documentation for config.region for new clients

---

lib/lib-dynamodb/package.json

I've noticed that from `npm` website the link to the homepage was broken. This PR is to update the link with the correct one.
---

fix(@aws-sdk/lib-dynamodb): correct homepage URL in package.json

---

clients/client-glacier/protocols/Aws_restJson1.ts
clients/client-lambda/protocols/Aws_restJson1.ts
clients/client-mediastore-data/protocols/Aws_restJson1.ts

Resolves https://github.com/aws/aws-sdk-js-v3/issues/2021
Related to https://github.com/awslabs/smithy-typescript/pull/354
parse the status code traits for rest protocols.
---

fix(clients): parse status code bindings in rest protocols

---

packages/credential-provider-cognito-identity/src/fromCognitoIdentity.spec.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.spec.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.ts
packages/credential-provider-env/src/index.spec.ts
packages/credential-provider-env/src/index.ts
packages/credential-provider-imds/src/fromContainerMetadata.ts
packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts
packages/credential-provider-imds/src/fromInstanceMetadata.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.spec.ts
packages/credential-provider-imds/src/remoteProvider/httpRequest.ts
packages/credential-provider-ini/src/index.ts
packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts
packages/credential-provider-process/src/index.ts
packages/credential-provider-sso/src/index.ts
packages/credential-provider-web-identity/src/fromTokenFile.spec.ts
packages/credential-provider-web-identity/src/fromTokenFile.ts
packages/credential-provider-web-identity/src/fromWebToken.spec.ts
packages/credential-provider-web-identity/src/fromWebToken.ts
packages/node-config-provider/src/fromEnv.spec.ts
packages/node-config-provider/src/fromEnv.ts
packages/node-config-provider/src/fromSharedConfigFiles.spec.ts
packages/node-config-provider/src/fromSharedConfigFiles.ts
packages/property-provider/src/ProviderError.spec.ts
packages/property-provider/src/ProviderError.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2137
Previously when credential resolve chain fails to resolve the credentials, it throws the error message from the last credential provider. As a result, the error message from the credential provider chain is not helpful, when no credentials can be resolved. For example, users see `Error: TimeoutError` when no credentials can be resolved. This is because the last provider in the credential chain is the Instance Metadata Service, and it will timeout when running on local machine. Instead, we should indicate credential error in the message. 
With this change, if none of the provider can resolve to a valid credential, the Node.js credential provider chain will throw `CredentialsError: Could not load credentials from any providers` just …

feat(credential-provider-node): throw cannot load credential error from credentail chain

---

packages/s3-request-presigner/src/getSignedUrl.spec.ts
packages/s3-request-presigner/src/getSignedUrl.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2383
Remove `x-amz-user-agent` header when presign the request.
Unit test & manual test with S3 GET and PUT request
---

fix(s3-request-presigner): remove x-amz-user-agent header

---

packages/credential-provider-sso/README.md

N/A
Clarifies the SSO provider documentation, removes ambiguity, fixes typos and aligns tenses.
N/A, documentation change only

docs(credential-provider-sso): readme fixes, clarification

---

packages/smithy-client/src/extended-encode-uri-component.spec.ts
packages/smithy-client/src/extended-encode-uri-component.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2499#issuecomment-864117029
Use uppercase for percent encodings
As per [rfc3986 section 2.1](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1), it should be `"%2A"`
> The uppercase hexadecimal digits 'A' through 'F' are equivalent to
the lowercase digits 'a' through 'f', respectively.  If two URIs
differ only in the case of hexadecimal digits used in percent-encoded
octets, they are equivalent.  For consistency, URI producers and
normalizers should use uppercase hexadecimal digits for all percent-
encodings.
CI
---

fix(smithy-client): use uppercase for percent encodings

---

codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
protocol_tests/aws-query/models/models_0.ts
protocol_tests/aws-query/protocols/Aws_query.ts
protocol_tests/aws-query/tests/functional/awsquery.spec.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2153
Pins smithy to minor version 1.8.x
CI
---

chore(codegen): pin smithy to 1.8.x

---

lib/lib-storage/README.md

N/A
Add JavaScript syntax highlighting to code block
README now has JavaScript syntax highlighting on GitHub
N/A
---

docs(lib-storage): add "js" syntax highlighting to code block

---

codegen/protocol-test-codegen/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
protocol_tests/aws-query/tests/functional/awsquery.spec.ts

n/a
This updates the protocol support to use the new `generateProtocolTests` interface method. This allows making use of the `skip` functionality in https://github.com/awslabs/smithy-typescript/pull/360 to temporarily skip known test failures.
Clients were regenerated, see the final commit for the diff
https://github.com/awslabs/smithy-typescript/pull/360
---

chore: support programmatically generating and skipping protocol tests

---

lib/lib-dynamodb/package.json
lib/lib-storage/package.json

- Going forward: All higher order libs that allow users to "bring their own client" should declare that client as a peer dep.
Changes lib/storage and lib/dynamodb to use peer dependencies instead of pinned dependencies over their clients.
This fixes a bunch of type errors where the libs would expect the latest types without actually needing them. This caused customer pain when attempting to use packages modularly because the version of the lib would always have to be the same version as the client passed into the lib. 
CC: @AllanZhengYP and I worked on this yesterday. This probably solves several issues in the backlog too.
- Published to local verdaccio. Verified that the libs are using the version of s3 that I …

feat(lib): change higher level libs use peer deps on clients

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointDiscoveryPlugin.java

Refs: https://github.com/awslabs/smithy-typescript/pull/353
uses function supplier in RuntimeClientPlugin instead of static function parameters.
Verified that `yarn generate-clients` did not update the RuntimeClientPlugin functions in clients.
Refs: https://github.com/awslabs/smithy-typescript/issues/352
---

chore(codegen): use function supplier in RuntimeClientPlugin

---

clients/client-dynamodb/DynamoDBClient.ts
clients/client-sts/STSClient.ts
clients/client-timestream-query/TimestreamQueryClient.ts
clients/client-timestream-write/TimestreamWriteClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointDiscoveryPlugin.java
packages/middleware-endpoint-discovery/src/resolveEndpointDiscoveryConfig.spec.ts
packages/middleware-endpoint-discovery/src/resolveEndpointDiscoveryConfig.ts
packages/middleware-sdk-sts/src/index.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/372
Convert second argument of resolve to options
CI
---

chore(clients): convert second argument of resolve to options

---

clients/client-timestream-query/commands/CancelQueryCommand.ts
clients/client-timestream-query/commands/QueryCommand.ts
clients/client-timestream-write/commands/CreateDatabaseCommand.ts
clients/client-timestream-write/commands/CreateTableCommand.ts
clients/client-timestream-write/commands/DeleteDatabaseCommand.ts
clients/client-timestream-write/commands/DeleteTableCommand.ts
clients/client-timestream-write/commands/DescribeDatabaseCommand.ts
clients/client-timestream-write/commands/DescribeTableCommand.ts
clients/client-timestream-write/commands/ListDatabasesCommand.ts
clients/client-timestream-write/commands/ListTablesCommand.ts
clients/client-timestream-write/commands/ListTagsForResourceCommand.ts
clients/client-timestream-write/commands/TagResourceCommand.ts
clients/client-timestream-write/commands/UntagResourceCommand.ts
clients/client-timestream-write/commands/UpdateDatabaseCommand.ts
clients/client-timestream-write/commands/UpdateTableCommand.ts
clients/client-timestream-write/commands/WriteRecordsCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointDiscoveryPlugin.java
packages/middleware-endpoint-discovery/src/getEndpointDiscoveryPlugin.ts

Internal JS-2654
Calls EndpointDiscoveryPlugin from client, and passes boolean value `isDiscoveredEndpointRequired` to it.
Tested with the following code:
```js
import { TimestreamQuery } from "../aws-sdk-js-v3/clients/client-timestream-query/dist/cjs/index.js";
const client = new TimestreamQuery({ region, logger: console });
const DatabaseName = `Database1619998684282`;
const TableName = `Table1619998684282`;
const QueryString = `SELECT * FROM ${DatabaseName}.${TableName} ORDER BY time LIMIT 2`;
await client.query({ QueryString });
```
Output: DescribeEndpointsCommand is called before QueryCommand
```console
{{
clientName: 'TimestreamQueryClient',
commandName: 'DescribeEndpointsCommand',
input: { Operation: 'Query', Identifiers: undefined },
output: { …
```

chore(clients): call EndpointDiscoveryPlugin with isDiscoveredEndpointRequired

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointDiscoveryPlugin.java

* Refs: https://github.com/awslabs/smithy-typescript/pull/353
* Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2395
While introducing Endpoint Discovery support, we had hardcoded the Endpoint Discovery Command.
This code change replaces it with Command name described in ClientDiscoveredEndpointTrait. 
Verified that `yarn generate-clients` did not override the clients.
---

chore(codegen): read Endpoint Discovery Command from trait

---

protocol_tests/aws-json-10/package.json

The scripts were updated in https://github.com/aws/aws-sdk-js-v3/pull/2537
They were missed in aws-json-10 package, as it was created in parallel https://github.com/aws/aws-sdk-js-v3/pull/2529
add downlevel-dts script and removes prepublishOnly script from aws-json-10
CI
---

fix(protocol_tests): add downlevel-dts script to aws-json-10

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

n/a
This bumps the version of the java code generator to 0.4.0 so a new release can be cut.
Built with the version bump, no changes
n/a
---

chore: bump java version to 0.4.0

---

codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPluginTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfigTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPluginsTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependencyTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegrationTest.java
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/SsdkExample.smithy
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/SsdkExampleSigV4.smithy

I had touched test TypescriptIntegrations for adding support for
generic non-AWS clients. Adding unit tests for them.
`gradle build`
---

test(codegen): add unit tests for recent changes to integrations

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointDiscoveryPlugin.java

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2395
Populates identifiers for endpoint discovery by reading ClientEndpointDiscoveryIdTrait
N/A as ClientEndpointDiscoveryIdTrait is not populated in any models.
Verified that generated clients are not updated.
---

chore(codegen): populate identifiers for endpoint discovery

---

packages/smithy-client/src/client.ts

Currently the built `.d.ts` to the smithy client looks like
```typescript
export declare class Client<HandlerOptions, ClientInput extends object, ClientOutput extends MetadataBearer, ResolvedClientConfiguration extends SmithyResolvedConfiguration<HandlerOptions>> implements IClient<ClientInput, ClientOutput, ResolvedClientConfiguration> {
middlewareStack: import("@aws-sdk/types").MiddlewareStack<ClientInput, ClientOutput>; // <== incorrect!
```
This annoys the API-Extractor.
---

chore(smithy-client): remove in-line import in types

---

packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/node-http-handler/src/server.mock.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2550
Adds an option to disableConcurrentStreams in NodeHttp2Handler
Example:
```js
const client = new H2HandlerClient({
requestHandler: new NodeHttp2Handler({
disableConcurrentStreams: true
}),
});
```
CI is successful
Verified that TranscribeStreaming works in parallel in demo code https://github.com/trivikr/aws-parallel-transcribe-repro/pull/1
---

feat(node-http-handler): configure disableConcurrentStreams in NodeHttp2Handler

---

clients/client-transcribe-streaming/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTranscribeStreamingDependency.java

Resolves: #2555
Sets Transcribe Streaming client H/2 handler to create new session for every new request. Previously it doesn't work for concurrent stream on 1 session, possibly due to server-side limitation.
---

fix(client-transcribe-streaming): disable concurrent streams in handler

---

codegen/sdk-codegen/build.gradle.kts
scripts/generate-clients/index.js

Right now all SDK clients are generated with name specified in `aws-models` folder. Even though model file names are generated from the model's `sdkId`, mistakenly renaming these model files could result in generating new clients. 
Instead clients shuold be generated irrelavant of the file name. This change generates the package name from the model directly. It has also been fixed in [Go v2 SDK](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/build.gradle.kts#L64-L86).
This change also:
* Add a `-n` option to `generate-clients` script to disable generating protocol tests. It eliminating protocol test clients generation when developer wants to generate a single model.
* New clients are now generated with version `3.0.0`, previously it was `1.0.0-rc.1`
What does this …

chore: generate client name according to sdkId

---

scripts/generate-clients/index.js

-s/--server-artifacts having a default value makes it see conflicts with
-m/-n/-g even if the caller did not specify them. Removing the default
fixes this.
ran both `yarn generate-clients -g codegen/sdk-codegen/aws-models/dynamodb.2012-08-10.json` and `yarn generate-clients -s` locally.
---

fix(codegen): fix detection of -s for generate-clients

---

packages/middleware-apply-body-checksum/src/applyMd5BodyChecksumMiddleware.ts
packages/middleware-apply-body-checksum/src/md5Configuration.ts

N/A
Use arrow functions in middleware-apply-body-checksum
CI
---

chore(middleware-apply-body-checksum): use arrow functions

---

packages/postinstall-node-version-check/.gitignore
packages/postinstall-node-version-check/.npmignore
packages/postinstall-node-version-check/CHANGELOG.md
packages/postinstall-node-version-check/LICENSE
packages/postinstall-node-version-check/README.md
packages/postinstall-node-version-check/jest.config.js
packages/postinstall-node-version-check/package.json
packages/postinstall-node-version-check/src/emitWarningIfUnsupportedVersion.spec.ts
packages/postinstall-node-version-check/src/emitWarningIfUnsupportedVersion.ts
packages/postinstall-node-version-check/src/index.spec.ts
packages/postinstall-node-version-check/src/index.ts
packages/postinstall-node-version-check/tsconfig.cjs.json

Internal JS-2727
Creates a script which can be run on postinstall
The script displays the following message if Node.js version is <12.0.0
```console
(node:11997) NodeDeprecationWarning: The AWS SDK for JavaScript (v3) will
no longer support Node.js v10.24.1 as of January 1, 2022.
To continue receiving updates to AWS services, bug fixes, and security
updates please upgrade to Node.js 12.x or later.
More information can be found at: {LINK TO BLOG}
```
* Unit testing
* Tested in [postinstall-node-version-check@0.2.4](https://www.npmjs.com/package/postinstall-node-version-check) with [test-postinstall-node-version-check@0.1.4](https://www.npmjs.com/package/test-postinstall-node-version-check)
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

feat(postinstall-node-version-check): util to show NodeDeprecationWarning

---

packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2556
Request's `goaway` event is not defined in the [Node.js spec](https://nodejs.org/api/http2.html#http2_class_http2stream), so remove it.
---

fix(node-http-handler): throw meaningful errors in H2 events

---

packages/credential-provider-ini/README.md
packages/credential-provider-ini/package.json
packages/credential-provider-ini/src/index.spec.ts
packages/credential-provider-ini/src/index.ts
packages/credential-provider-node/src/index.spec.ts
packages/credential-provider-node/src/index.ts
packages/credential-provider-process/package.json
packages/credential-provider-process/src/index.ts
packages/credential-provider-sso/README.md
packages/credential-provider-sso/package.json
packages/credential-provider-sso/src/index.spec.ts
packages/credential-provider-sso/src/index.ts
packages/util-credentials/LICENSE
packages/util-credentials/README.md
packages/util-credentials/jest.config.js
packages/util-credentials/package.json
packages/util-credentials/src/index.ts
packages/util-credentials/tsconfig.cjs.json
packages/util-credentials/tsconfig.es.json

Resolves #2504
* Add SSO credential support to INI credential provider. As a result, the SDK can follow the assume role chain specified in the shared `~/.aws/credentials` file, and assume the role derived from the SSO credential.
* The SSO credential provider supports specifying SSO parameters(e.g. start URL, account id, assume role name, region) in-line from the constructor parameters. If none of them is supplied, the provider will fall back to resolve the specified profile in the shared `~/.aws/credentials` file. **NOTE**: The SSO credential provider itself doesn't support assume role chain. It will fail if specified profile doesn't use a SSO credential
* Create an internal package `@aws-sdk/util-credentials` to host all the shared credential utilities. This is to optimize the …

feat(credential-provider-sso): support sso credential when resolving shared credential file

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

This bumps the version of the code generators. This should be merged after the next SDK release.
This depends on: https://github.com/awslabs/smithy-typescript/pull/385
(The java ci will fail due to the version bump, until the above is released)
---

chore: bump code generators to 0.4.1

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

n/a
This re-enables an SSDK protocol test  since the feature is being fixed in https://github.com/awslabs/smithy-typescript/pull/386
CI won't pass until that is merged.
Built the smithy-typescript change locally, and then ran the protocol tests.
n/a
---

chore: re-enable ssdk content-length test

---

clients/client-sts/tsconfig.json

No issue
This caused a warning for me when bundling with esbuild
```
> node_modules/@aws-sdk/client-ecs/node_modules/@aws-sdk/client-sts/tsconfig.json:26:4: warning: Duplicate key "stripInternal" in object literal
26 │     "stripInternal": true,
╵     ~~~~~~~~~~~~~~~
```
Not tested, change made through github web ui
---

fix(client-sts): duplicate stripInternal entry in tsconfig

---

packages/smithy-client/src/index.ts

fixes #2597
Explicitly re-export types using `export type ...`
Successfully built it locally with both `yarn build:all` and deno.
---

fix(smithy-client): export type explicitly

---

scripts/generate-clients/copy-to-clients.js
scripts/generate-clients/index.js

Changes to `scripts/` was mistakenly included in last PR #2574. This change reverts the unintended diffs.
---

chore: revert script change

---

protocol_tests/aws-json-10/JSONRPC10Client.ts
protocol_tests/aws-json-10/runtimeConfig.browser.ts
protocol_tests/aws-json-10/runtimeConfig.native.ts
protocol_tests/aws-json-10/runtimeConfig.shared.ts
protocol_tests/aws-json-10/runtimeConfig.ts
scripts/generate-clients/copy-to-clients.js
scripts/generate-clients/index.js

The [JSONRPC10Client.ts](https://github.com/aws/aws-sdk-js-v3/blob/5e3db0064c8916b51778a80e7c0c6ac307f69fd4/protocol_tests/aws-json-10/JSONRPC10Client.ts#L208) and JSONRPC10.ts cannot be updated with the generate-client script because they are in aws-json-10 folder, the script cannot infer the class name from the folder correctly(should have been `JSON10Client` instead). 
We need to update the script to not rely on the generated client folder name to infer the client class name.
---

chore(protocol-test): update json 1.0 test

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

n/a
bumps the code generator version to `0.5.0` and picks up the `0.5.0` update of `smithy-typescript-codegen`: https://github.com/awslabs/smithy-typescript/pull/390
build and tested locally.
The java ci will fail until upstream is merged.
---

chore: bump code generators to 0.5.0

---

packages/smithy-client/src/emitWarningIfUnsupportedVersion.spec.ts
packages/smithy-client/src/emitWarningIfUnsupportedVersion.ts
packages/smithy-client/src/index.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2594#issuecomment-883696975
Create emitWarningIfUnsupportedVersion in smithy-client.
This file would be called from runtimeConfig in clients.
CI
---

chore(smithy-client): emitWarningIfUnsupportedVersion

---

packages/credential-provider-node/package.json

This being missing broke something for me. I can give some more context if needed. The package is imported in https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-node/src/index.ts#L16 
---

fix(credential-provider-node): add missing dependency

---

codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
protocol_tests/aws-restjson/models/models_0.ts
protocol_tests/aws-restjson/protocols/Aws_restJson1.ts
protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts

Just an update to smithy-1.10.0 in code generation. It doesn't change anything outside of a protocol test, and makes it easier to test against new Smithy changes locally.
Ran `yarn generate-clients` and `yarn test:protocols`. There were unrelated changes from client generation due to https://github.com/awslabs/smithy-typescript/pull/392 not being in smithy-typescript 0.5.0 in Maven, so I manually reverted the changes that would have rolled back the new generated code.
---

Update code generation to Smithy 1.10

---

packages/middleware-apply-body-checksum/src/md5Configuration.ts
packages/middleware-sdk-sqs/src/configurations.ts
packages/middleware-ssec/src/index.ts
packages/types/src/crypto.ts

N/A
Uses existing HashConstructor interface instead of `{ new (): Hash }`
CI
---

fix(packages): use HashConstructor instead of { new: Hash }

---

clients/client-sqs/SQSClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddSqsDependency.java

Similar to https://github.com/aws/aws-sdk-js-v3/pull/2573
Fixes link to Hash interface in the SQS documentation.
<details>
<summary>Before: Link is not clickable.</summary>
</details>
<details>
<summary>After: Link points to Hash interface in @aws-sdk/types</summary>
</details>
---

chore(codegen): fix link to Hash interface in SQS

---

codegen/protocol-test-codegen/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2626
Bumps smithy to 1.11.x
Packages were generated without any errors.
---

chore(codegen): bump to smithy 1.11.x

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2644#issuecomment-893606585
Skips the following failing test:
```console
324 | FAIL protocol_tests/aws-restxml/tests/functional/restxml.spec.ts (24.898 s)
325 | ● SimpleScalarPropertiesPureWhiteSpace:Response
326 |  
327 | expect(received).toBe(expected) // Object.is equality
328 |  
329 | Expected: true
330 | Received: false
331 |  
332 | 4242 \|   Object.keys(paramsToValidate).forEach((param) => {
333 | 4243 \|     expect(r[param]).toBeDefined();
334 | > 4244 \|     expect(equivalentContents(r[param], paramsToValidate[param])).toBe(true);
335 | \|                                                                   ^
336 | 4245 \|   });
337 | 4246 \| });
338 | 4247 \|
339 |  
340 | at Object.keys.forEach …
```

chore(codegen): skip scalar pure whitespace protocol test

---

packages/md5-js/package.json
packages/md5-js/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2640
Calls fromUtf8 from correct environment in md5-js
Added console.log as follows:
<details>
<summary>packages/util-utf8-browser/src/index.ts</summary>
```diff
declare const TextDecoder: Function | undefined;
declare const TextEncoder: Function | undefined;
-export const fromUtf8 = (input: string): Uint8Array =>
-  typeof TextEncoder === "function" ? textEncoderFromUtf8(input) : jsFromUtf8(input);
+export const fromUtf8 = (input: string): Uint8Array => {
+  console.log("util-utf8-browser");
+  return typeof TextEncoder === "function" ? textEncoderFromUtf8(input) : jsFromUtf8(input);
+};
export const toUtf8 = (input: Uint8Array): string =>
typeof TextDecoder === "function" ? textEncoderToUtf8(input) : jsToUtf8(input);
```
</details> …

fix(md5-js): call fromUtf8 from correct environment

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts
lib/lib-storage/src/chunks/getChunkBuffer.spec.ts
lib/lib-storage/src/chunks/getChunkBuffer.ts
lib/lib-storage/src/chunks/getChunkStream.ts
lib/lib-storage/src/chunks/getDataReadable.spec.ts
lib/lib-storage/src/chunks/getDataReadableStream.spec.ts

Use Put for uploads smaller than part size in lib-storage
When upgrading from `s3.upload` to `lib-storage` upload, the performance for small files has degraded and the number of API calls has tripled. This was caused by `v2` implementing an optimization for `s3.upload` that uses PUT for uploads that are one part only (which is one API call), while `lib-storage` always uses multi-part uploads (which is at least 3 api calls).
fixes #2593
This PR implements PUT for small uploads, instead of using multi-part uploads for smaller files. 
Added multiple tests to Upload.spec.js, that test both "large" multi-part uploads and smaller uploads.
The most complex part of this PR (IMO) is delaying the multi-part start command, which needs to happen only after we're certain that we need it. So now it …

feat(lib-storage): use PUT for small uploads

---

.github/workflows/server-protocol-tests.yml

Fixes CI failures in server-protocol-tests.
Example https://github.com/aws/aws-sdk-js-v3/pull/2654/checks?check_run_id=3291926075
This links the ssdk common library before running the ssdk protocol tests.
Ran the steps myself, and also the CI here.
---

fix(ci): link in development ssdk common lib

---

tests/e2e/index.js
tests/e2e/run-e2e-tests.js

Follow up to #2666
Previously the `changedPackages` contains empty array like `[[""]]` when no e2e-applicable package exists. This change removes it.
Verified locally.
---

test(e2e): fix test fail when no package changes

---

clients/client-auto-scaling/protocols/Aws_query.ts
clients/client-cloudformation/protocols/Aws_query.ts
clients/client-cloudfront/protocols/Aws_restXml.ts
clients/client-cloudsearch/protocols/Aws_query.ts
clients/client-cloudwatch/protocols/Aws_query.ts
clients/client-docdb/protocols/Aws_query.ts
clients/client-ec2/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts
clients/client-elastic-load-balancing/protocols/Aws_query.ts
clients/client-elasticache/protocols/Aws_query.ts
clients/client-iam/protocols/Aws_query.ts
clients/client-neptune/protocols/Aws_query.ts
clients/client-rds/protocols/Aws_query.ts
clients/client-redshift/protocols/Aws_query.ts
clients/client-route-53/protocols/Aws_restXml.ts
clients/client-s3-control/protocols/Aws_restXml.ts
clients/client-s3/protocols/Aws_restXml.ts
clients/client-ses/protocols/Aws_query.ts
clients/client-sns/protocols/Aws_query.ts
clients/client-sqs/protocols/Aws_query.ts
clients/client-sts/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
protocol_tests/aws-ec2/protocols/Aws_ec2.ts
protocol_tests/aws-query/protocols/Aws_query.ts
protocol_tests/aws-restxml/protocols/Aws_restXml.ts
protocol_tests/aws-restxml/tests/functional/restxml.spec.ts

Internal JS-2756
Do not trim values while parsing XML
Protocol tests
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2646
---

fix(clients): only trim xml tag values which contain newline

---

clients/client-auditmanager/AuditManagerClient.ts
clients/client-connect-contact-lens/ConnectContactLensClient.ts
clients/client-customer-profiles/CustomerProfilesClient.ts
clients/client-devops-guru/DevOpsGuruClient.ts
clients/client-iot-data-plane/IoTDataPlaneClient.ts
clients/client-service-catalog-appregistry/ServiceCatalogAppRegistryClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2041
Re-introduces CORS retry headers for supported services
Verified in internal tickets that headers are supported for services in this PR.
---

chore(clients): re-introduce CORS retry headers for supported services

---

packages/property-provider/src/memoize.spec.ts
packages/property-provider/src/memoize.ts

Previously `memoize()` cached the provider promise no matter whether the promise is rejected. When the credential provider throws, the client will keep throwing the credential error even after the underlying credential provider resumes. 
With this change the `memoize()` only caches the successfully resolved credentials. If the credential provider errors out, it will retry the provider in next API call as no credential is available still.
Unit test, integration test
JS-2740
---

fix(property-provider): stop memoizing rejected provider

---

packages/middleware-sdk-transcribe-streaming/src/configuration.ts

This fixes a bug in minified production code described here in #2002 by removing a faulty validator.

fix(middleware-sdk-transcribe-streaming): validate signer

---

packages/middleware-signing/src/middleware.spec.ts
packages/middleware-signing/src/middleware.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2208
Updates systemClockOffset on error in middleware-signing
* CI
* Updated system time offset to more than 15 minutes and verified that request is successful in the second retry
<details>
```js
import { S3 } from "../aws-sdk-js-v3/clients/client-s3/dist/cjs/index.js";
const region = "us-east-1";
const client = new S3({ region, logger: console });
await client.listBuckets({});
```
</details>
<details>
<summary>Output</summary>
```console
{
clientName: 'S3Client',
commandName: 'ListBucketsCommand',
input: {},
output: {
Buckets: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
Owner: {
DisplayName: 'trivikr',
ID: 'f36465be55e5435ccc8357d4857b23522cbf71100368115f086c017f5092617a'
}
},
metadata: { …
```

fix(middleware-signing): update systemClockOffset on error

---

packages/util-dynamodb/README.md

Refs: https://github.com/aws/aws-sdk-js-v3/issues/2652
Adds information about DyamoDB DocumentClient in README of `@aws-sdk/util-dynamodb`
N/A
---

docs(util-dynamodb): add info about Document client

---

packages/smithy-client/src/parse-utils.spec.ts
packages/smithy-client/src/parse-utils.ts

n/a
This adds assertion and parse utilities for differently sized numbers.
So many tests.
This depends on: https://github.com/awslabs/smithy-typescript/pull/404
---

feat(smithy-client): add parse utils for sized numbers

---

clients/client-docdb/commands/CreateDBClusterCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddCrossRegionCopyingPlugin.java
packages/middleware-sdk-rds/package.json
packages/middleware-sdk-rds/src/index.spec.ts
packages/middleware-sdk-rds/src/index.ts

ref JS-2709
Previously users will see `PreSignedurl could not be authenticated` error for cross regional copy of snapshots. This is because the presigned url populated automatically be SDK was URIEncoded twice in the body. This change remove the extra uri encoding. 
This change basically is revert of https://github.com/aws/aws-sdk-js-v3/pull/773
**[UPDATE]** Unit test, Manual test API:
* `RDS: :CopyDBClusterSnapshot`
* `RDS::CreateDBCluster`
* `RDS::CopyDBSnapshot`
* `RDS::CreateDBInstanceReadReplica`
* `RDS::StartDBInstanceAutomatedBackupsReplication`
* `DocDB::CopyDBClusterSnapshot`
* `Neptune::CopyDBClusterSnapshot`
* `Neptune::CreateDBCluster`.
I remove the support of presigned URL on `DocDB::CreateDBCluster`, because the source identifier parameter does not exist, so a URL cannot be …

fix(middleware-sdk-rds): double encoding the presigned url

---

packages/smithy-client/src/parse-utils.spec.ts
packages/smithy-client/src/parse-utils.ts

N/A
This updates the number parsing utilities to reject strings like "1A", which `parseFloat` would ordinarily happily accept as the value `1`. It also updates it to reject the wide swath of alternative number formats that JS numbers can have.
Additional unit tests were added.
---

fix(parse): reject numeric strings with non-numbers

---

packages/signature-v4-crt/package.json

ref: JS-2789
new crt package misses the downlevel-dts script, introduced in #2537.
---

chore(signature-v3-crt): add downlevel script

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

n/a
bumps the code generator version to 0.6.0 and picks up the 0.6.0 update of smithy-typescript-codegen: https://github.com/awslabs/smithy-typescript/pull/410
```
cd codegen
gradle build publishToMavenLocal
cd ../
yarn generate-clients
```
The java ci will fail until https://github.com/awslabs/smithy-typescript/pull/410 is merged.
---

chore(codegen): bump code generators to 0.6.0

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java

n/a
This enables the ssdk protocol tests that ensure that hex numbers (`0xFF` for example) and strings with non-number characters (e.g. `123ABC`). They pass as of https://github.com/aws/aws-sdk-js-v3/pull/2729
Built the `main` branch of Smithy, which has the relevant tests, and ran them to ensure they pass.
n/a
---

chore: enable excess character tests

---

packages/smithy-client/src/date-utils.spec.ts
packages/smithy-client/src/date-utils.ts

From context, we know what the format of a timestamp should be, and we can
restrict the input to match that format rather than relying on the unspecified
behavior of new Date(string).
Unit tests, plus regeneration of clients, client protocol tests, server protocol tests. (those PRs to follow)
- We generally try to avoid adding dependencies, which is why I wrote these functions here, but there's potential for even more verification (like day of week) that I'm avoiding altogether that we might not have to with a real date/time library.
- We could write a more performant parser without using regex, but getting the behavior and abstraction right first is more important to me.
- I was split between putting these in date-utils or parse-utils, I'm open to suggestions.
--- …

feat(smithy-client): support strict timestamp parsing

---

packages/smithy-client/src/parse-utils.spec.ts
packages/smithy-client/src/parse-utils.ts

Unions must be JSON objects that only have one key set.
Unit tests, and protocol tests against regenerated clients.
---

feat(smithy-client): support strict union parsing

---

clients/client-app-mesh/protocols/Aws_restJson1.ts
clients/client-codeguruprofiler/protocols/Aws_restJson1.ts
clients/client-ssm-incidents/protocols/Aws_restJson1.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
protocol_tests/aws-json/protocols/Aws_json1_1.ts
protocol_tests/aws-restjson/protocols/Aws_restJson1.ts

n/a
This asserts that sets do not contain duplicate entries.
The tests on `main` of smithy were generated and ran.
n/a
---

feat(codegen): assert sets have no duplicates

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java

n/a
This updates list parsing for SSDKs to throw an error whenever a
null value shows up in a list or set that isn't meant to be sparse.
Clients remain tolerant of these nulls to preserve compatibility with
services that are not so strict.
Tests from `main` on smithy were run.
n/a
---

feat(codegen): reject null in non-sparse collections

---

lib/lib-dynamodb/package.json

Resolves: #2758
Follow up: #2516 
Move `@aws-sdk/util-dynamodb` to `@aws-sdk/lib-dynamobd`'s production dependency.
* Unit test; 
* Local publish, install and validate:
```typescript
import { DynamoDBClient } from "@aws-sdk/client-dynamodb"; // ES6 import
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb"; // ES6 import
// Bare-bones DynamoDB Client
const client = new DynamoDBClient({});
const ddbDocClient = DynamoDBDocumentClient.from(client);
(async (): Promise<void> => {
await ddbDocClient.send(
new PutCommand({
TableName: "table",
Item: {
id: "1",
content: "content from DynamoDBDocumentClient",
},
})
);
})();
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(lib-dynamodb): add util-dynamodb to dependencies

---

clients/client-s3/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ObjectSizeMemberShapeType.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

Resolves: #2751 
Reference: https://github.com/aws/aws-sdk-go-v2/pull/767
Add customization to S3 model to change `Size` shape from integer to long. This will unblock the object size longer than the integer range.
---

fix(client-s3): remove int validation of object size type

---

packages/s3-request-presigner/src/presigner.spec.ts
packages/s3-request-presigner/src/presigner.ts

Resolves: #2726
When presigning requests, the presigner will put the request's hostanme into the `host` header. However, when presigning a request with custom port (not `443`, `80`), the port is missed from the `host` header. Thus the signature will mismatch. This change fixes the issue.
Unit test
---

fix(s3-request-presigner): inject hostname with custom port

---

packages/util-base64-browser/src/index.spec.ts
packages/util-base64-browser/src/index.ts
packages/util-base64-node/src/index.spec.ts
packages/util-base64-node/src/index.ts

n/a
This updates the node and browser base64 parsers to validate the input string before parsing.
Node previously would just ignore invalid characters and treat padding as optional. The browser implementation required padding, but had a bug where invalid characters were treated as 0.
Additional unit tests were added.
n/a
---

fix(base64): validate base64 strings

---

lib/lib-dynamodb/README.md

N/A
There was a syntax error in the documentation of the `lib-dynamodb` module.
Using eslint
---

docs(lib-dynamodb): fix syntax errors inside objects

---

clients/client-lex-runtime-service/protocols/Aws_restJson1.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
protocol_tests/aws-restjson/protocols/Aws_restJson1.ts

n/a
Updates codegen resulting from: https://github.com/awslabs/smithy-typescript/pull/419
Additionally, removes suppressions for remaining base64 malformed request tests, as after this they're all resolved.
Generators were run off of smithy main and protocol tests / malformed request tests all passed.
n/a
---

chore: update base64 codegen

---

lib/lib-dynamodb/tsconfig.es.json
lib/lib-storage/tsconfig.cjs.json
lib/lib-storage/tsconfig.es.json

Noticed while working on https://github.com/aws/aws-sdk-js-v3/issues/2799
Define workspace specific compilerOptions in lib-*
Verified that following values are present in root `tsconfig.cjs.json`
```
"strict": true,
"sourceMap": false,
"declaration": true,
"importHelpers": true,
"noEmitHelpers": true,
"inlineSourceMap": true,
"inlineSources": true,
```
We're using default for `stringInternal`
Verified that following values are present in root `tsconfig.es.json`
```
"strict": true,
"sourceMap": false,
"declaration": true,
"importHelpers": true,
"noEmitHelpers": true,
"inlineSourceMap": true,
"inlineSources": true,
```
---

chore(tsconfig): define workspace specific compilerOptions

---

packages/middleware-sdk-s3/src/S3SignatureV4.ts

Resolves #2806
esbuild will try to bundle the optional dependency `@aws-sdk/signature-v4-crt` and will throw if the dependency is not installed. Unlike Webpack, there's no good way to suppress it with magical comments. 
One way to solve this is to wrap the `await import()` with `try...catch`, because esBuild [supresses this error explicitly](https://github.com/evanw/esbuild/commit/6be8e44beba8e765c2b99683608540ce40d6a58f). However, in generated code the import is wrapped by tslib import helper. I didn't remove the import helper because it may break the ES6 class polyfill provided by import helper. Instead, we use the Node.js `require()` here because:
1. Crt package doesn't work for any bundlers now anyway
2. `require()` won't be analyzed by bundler, so `@aws-sdk/signature-v4-crt` is not …

fix(middleware-sdk-s3): missing dependency with esbuild

---

lib/lib-storage/package.json

Webpack5 fails when bundler lib-storage because it requires 'fs' module. This change explicitly disable bundling fs module in browsers.
When bundling code bellow with Webpack 5:
```javascript
import { S3Client } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";
const Bucket = "xxx";
const Body = "xxx"
const s3 = new S3Client({
credentials: {
accessKeyId: "key",
secretAccessKey: "secret"
},
region: "us-west-2"
});
const upload = new Upload({
client: s3,
params: {
Bucket,
Key: "xxx",
Body
}
})
upload.done().then(console.log).catch(console.error)
```
Webpack fail to bundle it out-of-box:
```console
Module not found: Error: Can't resolve 'fs' in '/xxx/workspace/tmp/sdk-test/lib-dynamodb'
```
This change fix the issue.
---
By …

chore(lib-storage): stop bundling fs in browsers

---

packages/client-documentation-generator/tsconfig.types.json
packages/core-packages-documentation-generator/tsconfig.types.json
packages/credential-provider-cognito-identity/tsconfig.es.json
packages/middleware-sdk-transcribe-streaming/tsconfig.es.json
packages/signature-v4-crt/tsconfig.es.json
packages/signature-v4/tsconfig.es.json
tsconfig.cjs.json
tsconfig.es.json
tsconfig.json
tsconfig.types.json

Internal JS-2845
Cleans up tsconfig by removing default and redundant options
Integration tests are successful:
```console
$ yarn test:integration
yarn run v1.22.11
$ jest --config jest.config.integ.js --passWithNoTests
PASS  clients/client-transcribe-streaming/test/index.integ.spec.ts (31.608 s)
TranscribeStream client
✓ should stream the transcript (28774 ms)
Tests:       1 passed, 1 total
Time:        32.093 s
Done in 32.76s.
$ yarn test:integration-legacy
yarn run v1.22.11
$ cucumber-js --fail-fast
........................................................................................................................................................................................................................... …
```

chore(tsconfig): remove default and redundant options

---

package.json
scripts/downlevel-dts/README.md
scripts/downlevel-dts/index.js
yarn.lock

* Internal JS-2834
* https://github.com/aws/aws-sdk-js-v3/issues/2797
* https://github.com/aws/aws-sdk-js-v3/issues/2799
Runs downlevel-dts npm script (if present) in each workspace of monorepo, and strips comments from `*.d.ts` files. The npm install size is reduced by `~6%`.
<details>
<summary>Script</summary>
Rename `.txt` to `.js` before running
[npmInstallSizes.txt](https://github.com/aws/aws-sdk-js-v3/files/7237016/npmInstallSizes.txt)
</details>
<details>
Total size: 834.16 MB
[before.md](https://github.com/aws/aws-sdk-js-v3/files/7237033/before.md)
</details>
<details>
Total size: 789.60 MB
[after.md](https://github.com/aws/aws-sdk-js-v3/files/7237090/after.md)
</details>
Verified that comments are removed from `*.d.ts` files. …

chore(scripts): add script to downlevel-dts and strip comments

---

clients/client-s3/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
protocol_tests/aws-restxml/protocols/Aws_restXml.ts

Resolves #1814 
Resolves #2445 
When the payload member has xmlname trait, we need to use the xmlname value for the member rather than the target shape's name.
Cross validate the diffs with the V2 SDK.
Smithy doc: https://awslabs.github.io/smithy/1.0/spec/core/xml-traits.html#xmlname-trait
---

fix(client-s3): use member xmlname if applicable

---

package.json
scripts/downlevel-dts/README.md
scripts/downlevel-dts/downlevelWorkspace.js
scripts/downlevel-dts/downlevelWorkspace.mjs
scripts/downlevel-dts/getAllFiles.mjs
scripts/downlevel-dts/getDeclarationDirname.mjs
scripts/downlevel-dts/getDownlevelDirname.mjs
scripts/downlevel-dts/getWorkspaces.mjs
scripts/downlevel-dts/index.js
scripts/downlevel-dts/index.mjs
yarn.lock

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2834#issuecomment-928178784
Runs downlevel-dts scripts in parallel to improve performance.
<details>
```console
$ foreach dir ("lib" "packages" "clients" "protocol_tests")
for d in $dir/* ;do (cd "$d" && rm -rf dist/types/ts3.4); done
end
$ time yarn downlevel-dts
yarn run v1.22.11
$ node ./scripts/downlevel-dts
Done in 699.06s.
yarn downlevel-dts  1165.78s user 64.57s system 175% cpu 11:39.19 total
```
</details>
<details>
```console
$ foreach dir ("lib" "packages" "clients" "protocol_tests")
for d in $dir/* ;do (cd "$d" && rm -rf dist/types/ts3.4); done
end
$ time yarn downlevel-dts
yarn run v1.22.11
$ node --es-module-specifier-resolution=node ./scripts/downlevel-dts
Done in 58.73s.
yarn …
```

fix(scripts): run downlevel-dts script in parallel

---

.gitignore

Refs: https://github.com/awslabs/smithy-typescript/issues/425
gitignore files auto-created by VSCode in codegen
N/A
---

chore(codegen): gitignore files auto-created by VSCode

---

.gitignore
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/gitignore
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPluginTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfigTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPluginsTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddClientRuntimeConfigTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependencyTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegrationTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegrationTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegrationTest.java
scripts/generate-clients/copy-to-clients.js

Refs: aws/aws-sdk-js-v3#1306
The changes in scripts and codegen to move source files to 'src' folder.
* smithy-ts PR posted at https://github.com/awslabs/smithy-typescript/pull/434
* clients are updated in https://github.com/aws/aws-sdk-js-v3/pull/2845
Check testing section of https://github.com/aws/aws-sdk-js-v3/pull/2845
---

feat(codegen): move source files to 'src' folder

---

.esprintrc
package.json
scripts/generate-clients/code-eslint-fix.js
scripts/generate-clients/index.js
yarn.lock

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2838 which ran eslint in series.
~This PR will be made ready for review after source code is moved to src folder in https://github.com/aws/aws-sdk-js-v3/pull/2845~ PR is ready
Adds script to `eslint --fix` clients source code in parallel 
<details>
```console
$ time yarn generate-clients
...
Done in 68.60s.
yarn generate-clients  10.74s user 2.37s system 19% cpu 1:08.73 total
```
</details>
<details>
```console
$ time yarn generate-clients
...
Done in 111.67s.
yarn generate-clients  15.69s user 2.66s system 16% cpu 1:51.80 total
```
</details>
Verified that source code is linted in https://github.com/aws/aws-sdk-js-v3/pull/2849
---
By submitting this pull request, I confirm that you …

feat(scripts): use esprint to eslint --fix clients source code

---

protocol_tests/aws-ec2/test/functional/ec2query.spec.ts
protocol_tests/aws-json-10/test/functional/awsjson1_0.spec.ts
protocol_tests/aws-json/test/functional/awsjson1_1.spec.ts
protocol_tests/aws-query/test/functional/awsquery.spec.ts
protocol_tests/aws-restjson/test/functional/restjson1.spec.ts
protocol_tests/aws-restxml/test/functional/restxml.spec.ts
scripts/generate-clients/copy-to-clients.js

In the [codegen PR](https://github.com/aws/aws-sdk-js-v3/pull/2844) to move source code from source folder to "src", there was an incorrect check for folder name for protocol_tests for overwriting `"test"` folder. It checked for folder name `aws-` instead of package name `@aws-sdk/aws-`.
This issue was noticed in https://github.com/aws/aws-sdk-js-v3/pull/2840
Check for full package name before overwriting the "test" folder.
Verified that:
* `yarn test:protocols` is successful.
* Generating s3 client does not overwrite "test" folder in client-s3.
---

fix(scripts): overwrite test folder for protocol_tests

---

.esprintrc
scripts/generate-clients/index.js

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2846
The script was not linting SSDK protocol tests. This issue was noticed while moving source code to src folder in SSDK protocol tests in https://github.com/awslabs/smithy-typescript/pull/437
eslint SSDK protocol tests
Verified that source code is linted in `protocol_tests/aws-restjson-server` after running `yarn generate-clients --server-artifacts`
---

fix: eslint SSDK protocol tests

---

protocol_tests/aws-restxml/test/functional/restxml.spec.ts

Followup to #2835
Related to https://github.com/awslabs/smithy-typescript/pull/433
Previously the protocol test won't throw if the xml payload's outmost node name is different. For example, it succeeded if payload is `<Hola><name>Phreddy</name></Hola>` but expected `<Hello><name>Phreddy</name></Hello>`. This change fixes it.
---

test(protocol): compare xml payload correctly

---

README.md

docs: add known issues link to MRAP

---

clients/client-cognito-identity/test/e2e/CognitoIdentity.ispec.ts

Internal JS-2860
imports client from src location for client-cognito-identity tests.
Commit which fixed e2e tests in PR: [`928ce1c` (#2845)](https://github.com/aws/aws-sdk-js-v3/pull/2845/commits/928ce1c69e2f4d6ed3e8dc4a6ff06cdb663c7cb8)
Updating import for `test/e2e/CognitoIdentity.ispec.ts` was missed.
The e2e tests for client-cognito-identity were successful!
```console
$ pwd
/home/trivikr/workspace/aws-sdk-js-v3/clients/client-cognito-identity
$ AWS_SMOKE_TEST_REGION=[Region] AWS_SMOKE_TEST_IDENTITY_POOL_ID=[IdentityPoolId] yarn test:e2e
...
Chrome Headless 94.0.4606.61 (Linux x86_64): Executed 1 of 1 SUCCESS (0.216 secs / 0.214 secs)
```
---

fix(client-cognito-identity): import client from new location in src

---

packages/client-documentation-generator/src/sdk-client-rename-project.ts
packages/client-documentation-generator/src/sdk-client-toc-plugin.ts
packages/client-documentation-generator/src/utils.ts

Internal JS-2862
Fixes doc generation after source code for clients was moved to src folder in https://github.com/aws/aws-sdk-js-v3/pull/2845
Verified that `build:docs` command succeeds for all clients:
```
$ ./node_modules/.bin/lerna run --scope '@aws-sdk/client-*' build:docs
```
---

fix(client-documentation-generator): read files from src folder

---

features/opsworks/step_definitions/opsworks.js

Internal JS-2867
Refs: https://github.com/aws/aws-sdk-js/pull/3839
Explicitly setting region for OpsWorks integration tests, as they're failing intermittently.
Integration test for OpsWorks is successful
```console
$ yarn test:integration-legacy -t @opsworks
yarn run v1.22.11
$ cucumber-js --fail-fast -t @opsworks
..................
14 steps (14 passed)
0m01.326s
Done in 4.93s.
```
---

fix(client-opsworks): intermittent integ tests failures

---

packages/middleware-bucket-endpoint/package.json
packages/middleware-bucket-endpoint/src/NodeDisableMultiregionAccessPointConfigOptions.spec.ts
packages/middleware-bucket-endpoint/src/NodeDisableMultiregionAccessPointConfigOptions.ts
packages/middleware-bucket-endpoint/src/NodeUseArnRegionConfigOptions.spec.ts
packages/middleware-bucket-endpoint/src/NodeUseArnRegionConfigOptions.ts
packages/middleware-bucket-endpoint/src/configurations.ts
packages/middleware-bucket-endpoint/src/index.ts

Use booleanSelector introduced in https://github.com/aws/aws-sdk-js-v3/pull/2941
~~Note: This PR will be made ready once fix in https://github.com/aws/aws-sdk-js-v3/pull/2945 is merged.~~ PR is ready!
Uses booleanSelector from node-config-provider for:
* NODE_USE_ARN_REGION_CONFIG_OPTIONS
* NODE_DISABLE_MULTIREGION_ACCESS_POINT_CONFIG_OPTIONS
Unit tests
---

chore(middleware-bucket-endpoint): use booleanSelector from node-config-provider

---

packages/config-resolver/src/regionInfo/getRegionInfo.spec.ts
packages/config-resolver/src/regionInfo/getRegionInfo.ts
tests/functional/endpoints/fips/test_cases_supported.json
tests/functional/endpoints/fips/test_cases_unsupported.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2966
Resolves region from regionHash first before checking for endpoint in partitionHash
* Unit tests
* Functional tests
---

fix(config-resolver): resolve region first from regionHash

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Bumps the smithy-typescript-aws-codegen version to 0.7.0 and picks up the 0.7.0 update of smithy-typescript-codegen - https://github.com/awslabs/smithy-typescript/pull/461
```
cd codegen
gradle build publishToMavenLocal
cd ../
yarn install
yarn generate-clients
```
---

Bump code generators to 0.7.0

---

packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts
packages/config-resolver/src/endpointsConfig/utils/getEndpointFromRegion.spec.ts
packages/config-resolver/src/endpointsConfig/utils/getEndpointFromRegion.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.ts
packages/middleware-bucket-endpoint/src/configurations.ts
packages/middleware-sdk-s3-control/src/configurations.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/parse-outpost-arnables.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/plugin.spec.ts
packages/middleware-sdk-sts/src/index.ts
packages/middleware-signing/src/configuration.spec.ts
packages/middleware-signing/src/configurations.ts

PR for follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2980
Passes fips/dualstack configuration while resolving regionInfo from following packages:
* config-resolver
* middleware-bucket-endpoint
* middleware-sdk-s3-control
* middleware-signing
* CI
* Integration tests
---

chore: pass fips/dualstack config to regionInfoProvider

---

packages/middleware-sdk-s3-control/src/process-arnables-plugin/getOutpostEndpoint.spec.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/getOutpostEndpoint.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/index.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/parse-outpost-arnables.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/plugin.spec.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/update-arnables-request.ts
packages/middleware-sdk-s3-control/src/redirect-from-postid.spec.ts
packages/middleware-sdk-s3-control/src/redirect-from-postid.ts

Internal JS-2928
Adds support for FIPS in S3 Outposts Control Plane
Unit testing
---

feat(client-s3-control): support FIPS in S3 Outposts Control Plane

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

This fixes the broken smithy-aws-typescript-codegen-0.7.0 release.
I created smithy-aws-typescript-codegen-0.7.1  branch from the v3.39.0. And added the changelog updates for 0.7.1.
This PR is to merge this to smithy-aws-typescript-codegen-0.7.1 branch, it will not be merged to main.
Build of client generated in SSDK demo repo failed with 0.7.0. They work with these changes to 0.7.1 branch.
---

Smithy aws typescript codegen 0.7.1

---

packages/middleware-bucket-endpoint/src/bucketHostname.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostname.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/3001
Fixes https://github.com/aws/aws-sdk-js-v3/issues/3002
Removes dualstack from hostname before processing
* Unit testing
* Manual testing with repro code given in:
* #3001 
* #3002
---

fix(middleware-bucket-endpoint): remove dualstack from hostname before processing

---

codegen/build.gradle.kts
codegen/generic-client-test-codegen/build.gradle.kts
codegen/protocol-test-codegen/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

This centralizes the Smithy version in the root Gradle file for ease of use,
and locks the CLI to the same Smithy version as the Smithy dependencies.
Built locally in combination with https://github.com/awslabs/smithy-typescript/pull/465
---

fix(codegen): use specific Smithy version

---

packages/credential-provider-web-identity/package.json

Found as part of bundler test: https://github.com/AllanZhengYP/aws-sdk-js-v3/pull/195
The Web Identity Credential Provider contains both Node.js-specific module and browser-specific module. It causes the bundlers like Webpack to fail with `cannot resolve 'fs' module`. This change exclude the files that requires node.js specific module. 
Tested with bundler test.
---

fix(credential-provider-web-identity): exclude node.js files for web

---

packages/polly-request-presigner/package.json
packages/polly-request-presigner/src/getSynthesizeSpeechUrl.ts

Related: AllanZhengYP#195
`@aws-sdk/client-polly` was not included in in the production dependency. This will cause the failure with bundlers.
---

fix(polly-request-presigner): add missing polly dependency

---

packages/credential-providers/package.json
packages/credential-providers/src/index.web.ts

Follow up to https://github.com/aws/aws-sdk-js-v3/pull/3005. Correctly exclude node.js specific modules.
Related: https://github.com/AllanZhengYP/aws-sdk-js-v3/pull/195
---

fix(credential-providers): exclude node.js files for web

---

features/ses/ses.feature

Refs: https://github.com/aws/aws-sdk-js/pull/3956
Disables Rescue SES InvalidParameterValue test
Integration tests are successful.
---

test(integration): disable Rescue SES InvalidParameterValue test

---

packages/middleware-bucket-endpoint/src/bucketHostname.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3003
Adds check for fips/dualstack in s3 hostname pattern, so that additional modification is not required elsewhere.
* Unit testing
* Manual testing with repro code given in:
* #3001 
* #3002
---

chore(middleware-bucket-endpoint): include fips/dualstack checks in s3 hostname pattern

---

lib/lib-storage/package.json
yarn.lock

Related to https://github.com/AllanZhengYP/aws-sdk-js-v3/pull/195
This change reduce the need for specifying `events` polyfill in WebPack 5 when bundling `@aws-sdk/lib-storage` package. The dependency is required for `stream-browserify` dependency. 
---

fix(lib-storage): add events polyfill

---

packages/middleware-sdk-ec2/package.json
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-ec2/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3021
Similar to https://github.com/aws/aws-sdk-js-v3/pull/2711
Remove double encoding of presigned url
* CI
* Verified while debugging https://github.com/aws/aws-sdk-js-v3/issues/3021#issuecomment-967561714
---

fix(middleware-sdk-ec2): remove double encoding of presigned url

---

features/ses/ses.feature

Reverts https://github.com/aws/aws-sdk-js-v3/pull/3013
Enable Rescue SES InvalidParameterValue test, as the error message is corrected by the service.
<details>
<summary>Integration test run</summary>
```console
$ yarn test:integration:legacy -t @ses
$ cucumber-js --fail-fast -t @ses
.............
```
</details>
---

test(integration): enable Rescue SES InvalidParameterValue test

---

packages/middleware-sdk-s3-control/src/process-arnables-plugin/getOutpostEndpoint.spec.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/getOutpostEndpoint.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/parse-outpost-arnables.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/plugin.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3026
This was missed in https://github.com/aws/aws-sdk-js-v3/pull/2985
Remove validation for FIPS in S3 Outposts Control Plane
* Unit testing
* Verified with the code from bug report
<details>
```js
import { S3Control } from "../aws-sdk-js-v3/clients/client-s3-control/dist-cjs/index.js";
const logHostnameMiddleware = (next) => async (args) => {
console.log({ hostname: args.request.hostname });
return next(args);
};
const logHostnameMiddlewareOptions = { step: "deserialize" };
const region = "us-gov-west-1";
const useFipsEndpoint = true;
const AccountId = "123456789012";
const Bucket = `arn:aws-us-gov:s3-outposts:${region}:${AccountId}:outpost:outpostName:bucket:bucketName`;
const client = new S3Control({ region, …
```

fix(middleware-sdk-s3-control): do not validate for FIPS in S3 Outposts

---

clients/client-kendra/src/models/models_0.ts
clients/client-kendra/src/protocols/Aws_json1_1.ts

`DocumentAttributeValue` was incorrectly modeled as an enum instead of a structure.
This update changes `DocumentAttributeValue` to a structure shape. It means the associated
JavaScript object can contain more than 1 entry.
This PR is separate from #3039 to generate a standalone changelog entry
---

fix(client-kendra): change incorrectly modeled DocumentAttributeValue to structure

---

tests/functional/endpoints/index.spec.ts

Helps debug issues like CI failures in [`be5740f` (#3039)](https://github.com/aws/aws-sdk-js-v3/pull/3039/commits/be5740f0d5834bbcd5bb9c069cc36ccac23746ef)
Mention fips/dualstack config in test title
Before:
```console
...
✓ testing "client-s3-control" with region: us-gov-east-1
✓ testing "client-s3-control" with region: us-gov-east-1
✓ testing "client-s3-control" with region: us-gov-east-1
✓ testing "client-s3-control" with region: us-gov-east-1
...
```
After:
```console
...
✓ testing "client-s3-control" with {"region":"us-gov-east-1","useFipsEndpoint":false,"useDualstackEndpoint":false}
✓ testing "client-s3-control" with {"region":"us-gov-east-1","useFipsEndpoint":false,"useDualstackEndpoint":true}
✓ testing "client-s3-control" with …
```

test(endpoint): mention fips/dualstack config in title

---

clients/client-acm-pca/src/endpoints.ts
clients/client-batch/src/endpoints.ts
clients/client-cloudwatch/src/endpoints.ts
clients/client-config-service/src/endpoints.ts
clients/client-database-migration-service/src/endpoints.ts
clients/client-docdb/src/endpoints.ts
clients/client-dynamodb/src/endpoints.ts
clients/client-ecr/src/endpoints.ts
clients/client-eks/src/endpoints.ts
clients/client-elastic-load-balancing-v2/src/endpoints.ts
clients/client-elastic-load-balancing/src/endpoints.ts
clients/client-elasticache/src/endpoints.ts
clients/client-emr/src/endpoints.ts
clients/client-guardduty/src/endpoints.ts
clients/client-identitystore/src/endpoints.ts
clients/client-lex-model-building-service/src/endpoints.ts
clients/client-lex-runtime-service/src/endpoints.ts
clients/client-neptune/src/endpoints.ts
clients/client-rds/src/endpoints.ts
clients/client-resource-groups/src/endpoints.ts
clients/client-s3-control/src/endpoints.ts
clients/client-s3/src/endpoints.ts
clients/client-sagemaker-runtime/src/endpoints.ts
clients/client-sagemaker/src/endpoints.ts
clients/client-service-catalog-appregistry/src/endpoints.ts
clients/client-service-quotas/src/endpoints.ts
clients/client-ssm/src/endpoints.ts
clients/client-sts/src/endpoints.ts
clients/client-transcribe/src/endpoints.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java

Fixes https://github.com/aws/aws-sdk-js-v3/issues/3043
Merges variants from partition defaults and service defaults using tags as unique key
Verified that endpoint resolution returns `dynamodb.us-gov-east-1.api.aws` for DynamoDB with region=us-gov-east-1 and useDualstackEndpoint=true
<details>
```js
import { DynamoDB } from "../aws-sdk-js-v3/clients/client-dynamodb/dist-cjs/index.js";
const client = new DynamoDB({
region: "us-gov-east-1",
useDualstackEndpoint: true,
});
await client.listTables({});
```
</details>
<details>
<summary>Output</summary>
```console
node:internal/process/esm_loader:94
internalBinding('errors').triggerUncaughtException(
^
Error: getaddrinfo ENOTFOUND dynamodb.us-gov-east-1.api.aws
at GetAddrInfoReqWrap.onlookup [as oncomplete] …
```

fix(clients): merge default variants by comparing tags

---

features/cloudwatchevents/step_definitions/cloudwatchevents.js
features/cloudwatchlogs/step_definitions/cloudwatchlogs.js
features/cognitoidentity/step_definitions/cognitoidentity.js
features/cognitosync/step_definitions/cognitosync.js
features/configservice/step_definitions/configservice.js
features/datapipeline/step_definitions/datapipeline.js
features/devicefarm/step_definitions/devicefarm.js
features/directconnect/step_definitions/directconnect.js
features/directoryservice/step_definitions/directoryservice.js
features/dms/step_definitions/dms.js
features/dynamodbstreams/step_definitions/dynamodbstreams.js
features/elasticbeanstalk/step_definitions/elasticbeanstalk.js
features/elastictranscoder/step_definitions/elastictranscoder.js
features/elb/step_definitions/elb.js
features/elbv2/step_definitions/elbv2.js
features/es/step_definitions/es.js
features/route53/step_definitions/route53.js
features/route53domains/step_definitions/route53domains.js
features/storagegateway/step_definitions/storagegateway.js

followup: https://github.com/aws/aws-sdk-js-v3/pull/3033
Some import statement was missed in last PR. this change fixes it
```console
node node_modules/.bin/cucumber-js
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```

test(e2e-legacy): fix incorrect client imports

---

codegen/protocol-test-codegen/build.gradle.kts

Looks like a miss in earlier [PR](https://github.com/aws/aws-sdk-js-v3/pull/3011/files#diff-ecac4c366ecda2edce8ba9ad12c048529a09b34f458ade1ec42fd8f613d9e564) which locked the versions centrally.
---

fix(codegen): use specific smithy-cli version in protocol-test-codegen

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-restjson/src/RestJsonProtocol.ts
private/aws-protocoltests-restjson/src/RestJsonProtocolClient.ts
private/aws-protocoltests-restjson/src/commands/TestBodyStructureCommand.ts
private/aws-protocoltests-restjson/src/commands/TestNoPayloadCommand.ts
private/aws-protocoltests-restjson/src/commands/TestPayloadBlobCommand.ts
private/aws-protocoltests-restjson/src/commands/TestPayloadStructureCommand.ts
private/aws-protocoltests-restjson/src/commands/index.ts
private/aws-protocoltests-restjson/src/models/models_0.ts
private/aws-protocoltests-restjson/src/protocols/Aws_restJson1.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/468
Bump smithy to 1.14.x
Protocol tests are successful
---

chore(deps): bump smithy to 1.14.x

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Bumps the smithy-typescript-aws-codegen version to 0.8.0 and picks up the 0.8.0 update of smithy-typescript-codegen - https://github.com/awslabs/smithy-typescript/pull/469
```
cd codegen
gradle build publishToMavenLocal
cd ../
yarn install
yarn generate-clients
```
smithy-aws-typescript-codegen 0.7.1 was created in a branch https://github.com/aws/aws-sdk-js-v3/pull/2987. Manually copied the changelog entry for 0.7.1 into main here in one commit, and then updated to 0.8.0 in 2nd commit.
---

chore(codegen): bump code generators to 0.8.0

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts

This test was disabled when updating clients in [`d1746ce` (#2674)](https://github.com/aws/aws-sdk-js-v3/pull/2674/commits/d1746ce61ef19377f83bded44a6f89a99c5f7fe8)
The test was disabled as it was incorrect in smithy.
It was fixed by writing server only test `RestJsonNoInputAndOutputAllowsAccept` in https://github.com/awslabs/smithy/pull/935
Enables RestJsonNoInputAndOutput test in aws-protocoltests-restjson
Protocol tests are successful.
This PR will be rebased from main and made ready after smithy is bumped to 1.14.x in https://github.com/aws/aws-sdk-js-v3/pull/3053
---

chore(aws-protocoltests-restjson): enable RestJsonNoInputAndOutput

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddDocumentClientPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientPaginationGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientUtils.java
lib/lib-dynamodb/src/index.ts
lib/lib-dynamodb/src/pagination/Interfaces.ts
lib/lib-dynamodb/src/pagination/QueryPaginator.ts
lib/lib-dynamodb/src/pagination/ScanPaginator.ts
lib/lib-dynamodb/src/pagination/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2159
Adds pagination to DynamoDBDocumentClient
Verified with test code from [code examples from Developer Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.04.html)
<details>
```js
import { DynamoDBClient } from "@aws-sdk/client-dynamodb"; // v3.42.0
import {
DynamoDBDocumentClient,
paginateQuery,
} from "../aws-sdk-js-v3/lib/lib-dynamodb/dist-cjs/index.js";
const client = new DynamoDBClient({ region });
const docClient = DynamoDBDocumentClient.from(client);
const paginatorConfig = { client: docClient, pageSize: 5 };
const commandParams = {
TableName: "Movies",
KeyConditionExpression: "#yr = :yyyy",
ExpressionAttributeNames: {
"#yr": "year",
}, …
```

feat(lib-dynamodb): add pagination

---

clients/client-databrew/src/DataBrewClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2038
Omits retry headers in client-databrew
N/A
---

fix(client-databrew): omit retry headers

---

tests/e2e/run-e2e-tests.js

The e2e test fails when only 1 package is supplied. This is caused by a bug with the lerna command construction. Fix it according to https://github.com/lerna/lerna/issues/1846#issuecomment-855290857
---

test(e2e): fix lerna filter when only 1 package to test

---

codegen/build.gradle.kts

Codegen throws transient out-of-memory error when generating the biggest model-EC2. Bump up the JVM memory as an workaround. 
---

chore(codegen): set JVM memory size to 4gb

---

packages/hash-stream-node/README.md
packages/hash-stream-node/src/index.ts
packages/hash-stream-node/src/readableStreamHasher.spec.ts
packages/hash-stream-node/src/readableStreamHasher.ts

Internal JS-2965
Adds readableStreamHasher which pipes the provided stream to hashConstructor
Unit tests
* Mocking tricks with Jest: https://bensmithgall.com/blog/jest-mock-trick
* Testing streams https://dev.to/cdanielsen/testing-streams-a-primer-3n6e
---

feat(hash-stream-node): add readableStreamHasher

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/475
Bump smithy to 1.15.x
---

chore(codegen): bump smithy to 1.15.x

---

package.json
packages/s3-request-presigner/src/getSignedUrl.spec.ts
yarn.lock

Previous bump was done in https://github.com/aws/aws-sdk-js-v3/pull/2444
Bumps prettier to v2.5.1
* Prettier 2.4 release post https://prettier.io/blog/2021/09/09/2.4.0.html
* Prettier 2.5 release post https://prettier.io/blog/2021/11/25/2.5.0.html
---

chore(deps-dev): bump prettier to v2.5.1

---

lib/lib-dynamodb/src/commands/BatchGetCommand.ts
lib/lib-dynamodb/src/commands/ExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/QueryCommand.ts
lib/lib-dynamodb/src/commands/ScanCommand.ts

chore(lib-storage): reformat with prettier v2.5.1

---

packages/signature-v4/package.json
packages/signature-v4/src/SignatureV4.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2879#issuecomment-938222446
Mock Date in SigV4 tests
CI
---

fix(signature-v4): mock Date in SigV4 tests

---

packages/middleware-serde/src/deserializerMiddleware.spec.ts
packages/middleware-serde/src/deserializerMiddleware.ts
packages/middleware-signing/src/middleware.spec.ts
packages/middleware-signing/src/middleware.ts
packages/types/src/shapes.ts

Resolves: #3119 
Currently, SDK cannot correct the clock skew automatically from the error response. This change fixes the issue. Moreover, a new member `$response` is added to the `SmithyException` interface. As a result, users can access the lower level HTTP response from any server-side exceptions. 
Unit test
---

fix(middleware-signing): correct clock skew from error response

---

scripts/generate-clients/copy-to-clients.js

Related to using root tsconfig for all clients in aws-sdk-js-v3
Refs: #1307
Removes devDeps defined in monorepo root from clients.
Individual devDeps, if present, were removed in https://github.com/aws/aws-sdk-js-v3/pull/3139
Testing that the packages work without dependencies is done in https://github.com/aws/aws-sdk-js-v3/pull/3139
Verified that dependencies are not added during client generation with client-acm:
```console
$ sed -n 53,58p clients/client-acm/package.json 
},
"devDependencies": {
"@aws-sdk/service-client-documentation-generator": "3.38.0",
"@types/node": "^12.7.5"
},
"engines": {
$ yarn generate-clients -g codegen/sdk-codegen/aws-models/acm.json -n
...
copying @aws-sdk/client-acm from /local/home/trivikr/workspace/backup/backup-aws-sdk-js-v3/codegen/sdk-codegen/build/smit …
```

chore(scripts): remove devDeps defined in monorepo root

---

tsconfig.json
typedoc.json

Similar to https://github.com/aws/aws-sdk-js-v3/pull/3135, but for non-clients at root
Moved root typedocOptions to typedoc.json
Verified that `build-documentation` script is successful.
```console
$ yarn build-documentation --clientDocs docs/clients/{{CLIENT}} --theme
...
Rendering [========================================] 100%
Documentation generated at /local/home/trivikr/workspace/backup/backup-aws-sdk-js-v3/docs
Done in 11.11s.
$ ls docs
assets  classes  enums  globals.html  index.html  interfaces  modules
```
---

chore(typedoc): move root typedocOptions to typedoc.json

---

packages/md5-js/tsconfig.cjs.json

Noticed in build failures while using root TSConfig in clients at #3151
Removes unnecessary exclude from tsconfig in md5-js
Verified that build is successful
```console
$ md5-js> yarn build
$ yarn build:cjs && yarn build:es && yarn build:types
$ tsc -p tsconfig.cjs.json
$ tsc -p tsconfig.es.json
$ tsc -p tsconfig.types.json
Done in 4.24s.
```
---

fix(md5-js): remove unnecessary exclude from tsconfig

---

private/aws-protocoltests-json-10/jest.config.js

This issue was identified while attempting to use root TSConfig in clients in https://github.com/aws/aws-sdk-js-v3/pull/3149
Extend jest.config.js in aws-protocoltests-json-10 from jest.config.base.js
Verified that unit tests are successfully run in aws-protocoltests-json-10
```console
$ aws-protocoltests-json-10> yarn test
...
Tests:       47 passed, 47 total
Time:        6.934 s
Done in 7.98s.
```
---

test(aws-protocoltests-json-10): extend from jest.config.base.js

---

jest.config.integ.js
jest.config.js

Improvement noticed while working on root TSConfigs in https://github.com/aws/aws-sdk-js-v3/pull/3151
Removes unused configuration from `jest.config.js` and `jest.config.integ.js`
The `jest.config.js` uses [projects](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig) configuration to specify which packages should run jest, and doesn't run the test in `<rootDir>`. Rest of the configuration is not used.
CI
---

chore(jest): remove unused configuration

---

jest.config.base.js
package.json
packages/credential-providers/src/fromTemporaryCredentials.spec.ts
tsconfig.test.json
yarn.lock

This issue was identified while attempting to use root TSConfig in clients in #3149
Uses custom tsconfig while running tests
CI
PRs to merge before making this PR ready:
* https://github.com/aws/aws-sdk-js-v3/pull/3159
* https://github.com/aws/aws-sdk-js-v3/pull/3160
---

chore(jest): use custom tsconfig for running tests

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java

Internal JS-3014
Populate dnsSuffix in endpoint before populating hostname
Verified that there are no changes when running `yarn generate-clients`
---

fix(codegen): populate dnsSuffix just before consuming hostname

---

private/aws-protocoltests-ec2/test/functional/ec2query.spec.ts
private/aws-protocoltests-json-10/test/functional/awsjson1_0.spec.ts
private/aws-protocoltests-json/test/functional/awsjson1_1.spec.ts
private/aws-protocoltests-query/test/functional/awsquery.spec.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts
private/aws-protocoltests-restxml/test/functional/restxml.spec.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/490
Checks for ErrorName to be thrown, thus removing unused imports
Protocol tests
---

chore(protocoltests): remove unused imports

---

clients/client-auto-scaling/src/protocols/Aws_query.ts
clients/client-cloudformation/src/protocols/Aws_query.ts
clients/client-cloudfront/src/protocols/Aws_restXml.ts
clients/client-cloudsearch/src/protocols/Aws_query.ts
clients/client-cloudwatch/src/protocols/Aws_query.ts
clients/client-cognito-identity-provider/src/protocols/Aws_json1_1.ts
clients/client-docdb/src/protocols/Aws_query.ts
clients/client-elastic-beanstalk/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing/src/protocols/Aws_query.ts
clients/client-elasticache/src/protocols/Aws_query.ts
clients/client-iam/src/protocols/Aws_query.ts
clients/client-kms/src/protocols/Aws_json1_1.ts
clients/client-memorydb/src/protocols/Aws_json1_1.ts
clients/client-neptune/src/protocols/Aws_query.ts
clients/client-organizations/src/protocols/Aws_json1_1.ts
clients/client-rds/src/protocols/Aws_query.ts
clients/client-redshift/src/protocols/Aws_query.ts
clients/client-route-53/src/protocols/Aws_restXml.ts
clients/client-service-quotas/src/protocols/Aws_json1_1.ts
clients/client-ses/src/protocols/Aws_query.ts
clients/client-sns/src/protocols/Aws_query.ts
clients/client-sqs/src/protocols/Aws_query.ts
clients/client-sts/src/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
private/aws-protocoltests-query/src/protocols/Aws_query.ts

Internal JS-3027
This code change surfaced a bug in our error deserializer, where the error message is modeled to be in key `message` but the actual message is response payload with key `Message`.
This reverts commit 351bd3a40ad37be79d823d6a0e4e48304728ea6f added in https://github.com/aws/aws-sdk-js-v3/pull/3174.
Integration tests were successful.
```
$ yarn test:integration:legacy
$ cucumber-js --fail-fast
................................................................................................................................................................................................................................................................................................................................................................................... …
```

chore: revert support for awsQueryError trait

---

packages/util-defaults-mode-browser/src/resolveDefaultsModeConfig.ts

Resolves #3202 
Similar to https://github.com/aws/aws-sdk-js-v3/pull/1991, fix Vite build by importing `bowser` from default export
```console
./node_modules/.bin/snowpack build
[24:35:27] [snowpack] Hint: run "snowpack init" to create a project config file. Using defaults...
[24:35:27] [snowpack] ! building files...
[24:35:27] [snowpack] ✔ files built. [0.05s]
[24:35:27] [snowpack] ! building dependencies...
[24:35:31] [snowpack] ✔ dependencies built. [3.26s]
[24:35:31] [snowpack] ! writing to disk...
[24:35:31] [snowpack] ✔ write complete. [0.02s]
[24:35:31] [snowpack] ▶ Build Complete!
```
---

fix(util-defaults-mode-browser): import bowser by default export

---

private/aws-protocoltests-ec2/tsconfig.types.json
private/aws-protocoltests-json-10/tsconfig.types.json
private/aws-protocoltests-json/tsconfig.types.json
private/aws-protocoltests-query/tsconfig.types.json
private/aws-protocoltests-restjson/tsconfig.types.json
private/aws-protocoltests-restxml/tsconfig.types.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3212
Add emitDeclarationOnly for types
Verified that running `yarn build:protocols` does not emit tranpiled JS files in src folder.
---

fix(aws-protocoltests-*): add emitDeclarationOnly for types

---

scripts/generate-clients/copy-to-clients.js

This removes the prepack script from client package.json
Tested as a part of the Smithy-1.16 update PR: https://github.com/aws/aws-sdk-js-v3/pull/3215 - I removed the unnecessary if check
---

chore(codegen): remove prepack script from clients

---

codegen/build.gradle.kts
codegen/generic-client-test-codegen/build.gradle.kts
codegen/protocol-test-codegen/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java

Includes removal of @jsonName support from AWS JSON protocols, which is a
change made to the spec in 1.16.
Regenerated clients and ran client and server protocol tests locally
---

feat(codegen): update to Smithy-1.16.3

---

packages/eventstream-handler-node/src/EventStreamPayloadHandler.ts

This issue surfaced when attempting to bump yarn version to berry in https://github.com/aws/aws-sdk-js-v3/pull/3235
Explicitly define type of err in eventstream-handler-node
yarn build is successful.
---

fix(eventstream-handler-node): explicitly define type of err

---

packages/middleware-retry/package.json
packages/middleware-sdk-transcribe-streaming/package.json

The missing `@types/uuid` was noticed while trying to bump yarn to berry in https://github.com/aws/aws-sdk-js-v3/pull/3235
Adds missing @types/uuid as devDependencies in impacted packages.
<details>
<summary>Script used</summary>
```js
// @ts-check
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { getWorkspacePaths } from "./update-versions/getWorkspacePaths.mjs";
getWorkspacePaths().forEach((workspacePath) => {
const packageJsonPath = join(workspacePath, "package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath).toString());
if (packageJson.dependencies && packageJson.dependencies["uuid"]) {
if (packageJson.devDependencies && packageJson.devDependencies["@types/uuid"] === undefined) {
packageJson.devDependencies["@types/uuid"] = …
```

chore(deps-dev): add missing @types/uuid

---

scripts/generate-clients/copy-to-clients.js

Refs: https://github.com/aws/aws-sdk-js-v3/issues/3243
Update generate-clients script to use same version of devDeps across clients
Clients updated in https://github.com/aws/aws-sdk-js-v3/pull/3244
---

chore(scripts): use same version of devDeps across clients

---

packages/middleware-sdk-transcribe-streaming/package.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/3248
Removes unused yarn build before test, as it's no longer required.
We use ts-jest to run jest tests without compiling them to TypeScript.
Verified that `yarn test` succeeds without building `middleware-sdk-transcribe-streaming` package:
```console
$ yarn test
$ jest --passWithNoTests
PASS  src/middleware-endpoint.spec.ts
PASS  src/signer.spec.ts
PASS  src/websocket-handler.spec.ts
Test Suites: 3 passed, 3 total
Tests:       15 passed, 15 total
Time:        4.395 s
Done in 5.46s.
```
---

chore(middleware-sdk-transcribe-streaming): remove unused yarn build before test

---

codegen/build.gradle.kts
codegen/sdk-codegen/gradle.properties

JVM out of memory exception in the CI:
```console
Projection ec2.2016-11-15 failed: java.lang.OutOfMemoryError: Java heap space
java.base/java.util.Arrays.copyOf(Arrays.java:3745)
```
[Gradle build fails with Out of Memory: Java heap space error](https://stackoverflow.com/questions/63088123/gradle-build-fails-with-out-of-memory-java-heap-space-error)
---

chore(codegen): increase JVM memory size

---

package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3259
Adds packageManager value `yarn@1.22.17`
<details>
<summary>Node.js 14.x (v14.18.3) without corepack</summary>
```console
$ aws-sdk-js-v3> node -v
v14.18.3
$ aws-sdk-js-v3> corepack -v
zsh: command not found: corepack
$ aws-sdk-js-v3> yarn -v
zsh: command not found: yarn
```
</details>
<details>
<summary>Node.js 14.x (v14.18.3) with corepack</summary>
```console
$ aws-sdk-js-v3> node -v
v14.18.3
$ aws-sdk-js-v3> corepack -v                                                 
zsh: command not found: corepack
$ aws-sdk-js-v3> yarn -v
zsh: command not found: yarn
$ aws-sdk-js-v3> npm install -g corepack
...
+ corepack@0.10.0
updated 1 package in 0.118s
$ aws-sdk-js-v3> yarn -v
1.22.17
```
</details>
<details>
<summary>Node.js >= …

chore(package.json): add packageManager field with value `yarn@1.22.17`

---

clients/client-accessanalyzer/src/models/models_0.ts
packages/smithy-client/src/exceptions.spec.ts
packages/smithy-client/src/exceptions.ts
packages/smithy-client/src/index.ts
packages/types/src/shapes.ts

https://github.com/aws/aws-sdk-js-v3/issues/1506
https://github.com/aws/aws-sdk-js-v3/issues/2007
* Create a new `ServiceException` class as a base class for all the server-side exception classes. The refactor to the deserializer will come next. It implements the mostly the same interface as `SdkError`.
* `SdkError` interface is **deprecated** because it is not used/enforced in actual exceptions thrown from the deserializer. It cannot be changed to `ServiceException` class because it declares every member as optional. However, the `SdkException` contains required members(`message`, `name`), simply keeping the name will cause breaking change to anyone consuming the `SdkError` interface.
* `SmithyExceptoin` interface is deprecated for the same reason.
TBD
--- …

feat(smithy-client): implement SdkException class

---

UPGRADING.md
packages/middleware-bucket-endpoint/src/configurations.ts

Clear some confusions with `bucketEndpoint` configs
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3031
---

docs(middleware-bucket-endpoint): clarification for bucketEndpoint config

---

package.json

Discussed internally over Slack: The command `lerna:version` fails, and will block `v3.51.0` release.
```console
$ yarn lerna:version
$ lerna version --exact --conventional-commits --no-push --no-git-tag-version --no-commit-hooks --loglevel silent --no-private --yes
node:events:368
throw er; // Unhandled 'error' event
^
Error: warning: refname 'v3.50.0' is ambiguous.
at DestroyableTransform._transform (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/git-raw-commits/index.js:83:30)
at DestroyableTransform.Transform._read (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/readable-stream/lib/_stream_transform.js:184:10)
at DestroyableTransform.Transform._write (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/readable-stream/lib/_stream_transform.js: …
```

fix(package.json): update version to v3.50.0

---

scripts/downlevel-dts/downlevelWorkspace.mjs

Internal JS-3107
Follow-up in JS-3106
Los instead of throwing error in downlevel script.
Reason for the change: We only build the packages to be published in new release automation scripts. Making this change to ignore when types are not available for any package. We'll run downlevel only for the changed packages as a follow-up.
```console
$ cd private/aws-echo-service
$ rm -rf dist-types
$ cd ../../
$ yarn build:types:downlevel                                            
$ node --es-module-specifier-resolution=node ./scripts/downlevel-dts
The types for "aws-echo-service" do not exist.
Done in 5.22s.
```
---

fix(scripts): log when types not present in downlevel script

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-restjson/src/models/models_0.ts
private/aws-protocoltests-restxml/test/functional/restxml.spec.ts
scripts/generate-clients/copy-to-clients.js

This updates to Smithy 1.17.0 and temporarily disables type checking for ts-jest in the server protocol tests only. We have been unable to find any other way to get server protocol tests to type check correctly.
`yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols`
---

Smithy 1.17.0 update and server protocol test workaround

---

packages/smithy-client/src/exceptions.ts

Add an exception class constructor parameter type. It infers the exception class's contructor parameter from the exception interface and the base exception interface. It's used by client-side SDK and server-side SDK. 
Required by:
#3267 
#3310 
---

feat(smithy-client): add ExceptionOptionType type

---

codegen/sdk-codegen/gradle.properties

The OutOfMemory error appears even after we increased maximum size of memory allocation pool to `4g` in https://github.com/aws/aws-sdk-js-v3/pull/3253 
Temporarily disable manual increase of maximum memory size of memory allocation pool in Java, and generate heap dump on OutOfMemory.
The command `yarn generate-clients` is successful in the workspace hosted on `c5.9xlarge`
Java docs: https://docs.oracle.com/javase/7/docs/webnotes/tsg/TSG-VM/html/clopts.html
---

chore(codegen): generate heap dump on OutOfMemory error

---

scripts/generate-clients/.gitignore
scripts/generate-clients/code-gen-dir.js
scripts/generate-clients/code-gen.js

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3321
* Copies clients generated in a batch in a temporary directory `TEMP_CODE_GEN_SDK_OUTPUT_DIR`.
* Copies the clients back to `CODE_GEN_SDK_OUTPUT_DIR` after all batches are done running.
* Cleans up `TEMP_CODE_GEN_SDK_OUTPUT_DIR` after copying is complete
Followed steps to reproduce from https://github.com/aws/aws-sdk-js-v3/issues/3321 and verified that all `a*.json` clients are present in `sdk-codegen` folder although clients were generated in the batches of `5`
```console
$ ls /local/home/trivikr/workspace/aws-sdk-js-v3/codegen/sdk-codegen/build/smithyprojections/sdk-codegen
accessanalyzer.2019-11-01      apigatewaymanagementapi.2018-11-29        app-mesh.2019-01-25
account.2021-02-01             apigatewayv2.2018-11-29 …
```

fix(scripts): store clients generated in a batch in temp directory

---

package.json

Internal JS-3106
Allow private in lerna:version command
Verified that private packages are bumped in lerna:version
```console
$ yarn lerna:version
$ lerna version --exact --conventional-commits --no-push --no-git-tag-version --no-commit-hooks --loglevel silent --yes
...
- @aws-sdk/aws-echo-service: 3.51.0 => 3.52.0 (private)
- @aws-sdk/aws-protocoltests-ec2: 3.51.0 => 3.52.0 (private)
- @aws-sdk/aws-protocoltests-json-10: 3.51.0 => 3.52.0 (private)
- @aws-sdk/aws-protocoltests-json: 3.51.0 => 3.52.0 (private)
- @aws-sdk/aws-protocoltests-query: 3.51.0 => 3.52.0 (private)
- @aws-sdk/aws-protocoltests-restjson: 3.51.0 => 3.52.0 (private)
- @aws-sdk/aws-protocoltests-restxml: 3.51.0 => 3.52.0 (private)
Done in 60.95s.
```
---
By submitting this pull request, I confirm that …

chore(lerna): allow private in version command

---

packages/hash-stream-node/src/fileStreamHasher.ts
packages/hash-stream-node/src/fsCreateReadStream.spec.ts
packages/hash-stream-node/src/fsCreateReadStream.ts
packages/hash-stream-node/src/isFileStream.spec.ts
packages/hash-stream-node/src/isFileStream.ts
packages/hash-stream-node/src/readableStreamHasher.spec.ts
packages/hash-stream-node/src/readableStreamHasher.ts

Internal JS-2965
Adds support for file stream in readableStreamHasher
Done in [private-aws-sdk-js-v3/pull/75](https://github.com/aws/private-aws-sdk-js-v3/pull/75)
---

fix(hash-stream-node): support file stream in readableStreamHasher

---

packages/hash-stream-node/src/readableStreamHasher.spec.ts
packages/hash-stream-node/src/readableStreamHasher.ts

Internal JS-2965
Throws error if non-file readableStream is flowing
Unit testing
Will be made ready after https://github.com/aws/aws-sdk-js-v3/pull/3338 is merged.
---

fix(hash-stream-node): throw error if non-file readableStream is flowing

---

packages/types/src/index.ts
packages/types/src/stream.ts
packages/util-stream-browser/.gitignore
packages/util-stream-browser/CHANGELOG.md
packages/util-stream-browser/LICENSE
packages/util-stream-browser/README.md
packages/util-stream-browser/jest.config.js
packages/util-stream-browser/package.json
packages/util-stream-browser/src/getAwsChunkedEncodingStream.ts
packages/util-stream-browser/src/index.ts
packages/util-stream-browser/tsconfig.es.json
packages/util-stream-browser/tsconfig.types.json
packages/util-stream-node/.gitignore
packages/util-stream-node/CHANGELOG.md
packages/util-stream-node/LICENSE
packages/util-stream-node/README.md
packages/util-stream-node/jest.config.js
packages/util-stream-node/package.json
packages/util-stream-node/src/getAwsChunkedEncodingStream.ts
packages/util-stream-node/src/index.ts
packages/util-stream-node/tsconfig.cjs.json
packages/util-stream-node/tsconfig.es.json
packages/util-stream-node/tsconfig.types.json

Internal JS-2965
Adds getAwsChunkedEncodingStream functions in browser and Node.js
Integration testing done in https://github.com/aws/private-aws-sdk-js-v3/pull/75
Unit tests will be added in a separate PR.
---

feat(util-stream): add getAwsChunkedEncodingStream

---

clients/client-s3/src/commands/WriteGetObjectResponseCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java

Resolves #2476
We have a customization that will inspect the S3 request’s `Bucket` parameters. This customization should only be applied to operations with `Bucket` input parameter. However, it was incorrectly applied to the operation which doesn’t have such parameter
---

fix(client-s3): disable bucket endpoint plugin in WriteGetObjectResponseCommand

---

packages/util-stream-browser/package.json
packages/util-stream-node/package.json

Mistakenly added in https://github.com/aws/aws-sdk-js-v3/pull/3339
The jest dependencies were added during development in private.
We now have bumped Jest to v27 and declare jest dependency in root package.json
N/A
---

fix(util-stream): remove jest from devDeps

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java

Internal JS-3100
Adds getAwsChunkedEncodingStream to config
Tested with model updates in https://github.com/aws/private-aws-sdk-js-v3/pull/106
---

feat(codegen): add getAwsChunkedEncodingStream to config

---

packages/util-stream-browser/package.json
packages/util-stream-node/package.json

Internal JS-3127
The util-stream packages contains the original script `downlevel-dts` added in private, which was renamed to `build:types:downlevel` in public
Verified that running `build:types:downlevel` at top level was successful.
```console
$ yarn build:types:downlevel
$ node --es-module-specifier-resolution=node ./scripts/downlevel-dts
Done in 67.61s.
```
---

fix(util-stream): rename downlevel-dts to build:types:downlevel

---

lib/lib-storage/src/Upload.ts

Internal JS-3100
Adds available checksum values to CompletedPart array
Tested with model updates in https://github.com/aws/private-aws-sdk-js-v3/pull/106
---

chore(lib-storage): add available checksum values to CompletedPart array

---

packages/hash-stream-node/src/fsCreateReadStream.spec.ts
packages/hash-stream-node/src/fsCreateReadStream.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3368
Disables createReadStream with file descriptor
<details>
<summary>PutObject</summary>
```js
import { createReadStream } from "fs";
const client = new S3({ region });
// File created with command "(for i in {1..10000}; do echo $i "hello world"; done) > hello-world.txt"
const fileName = "hello-world.txt";
const readableStream = createReadStream(fileName);
const Bucket = "aws-sdk-js-trivikr-flexible-checksums-testing";
const Key = fileName;
const Body = readableStream;
const ChecksumAlgorithm = "CRC32";
await client.putObject({ Bucket, Key, Body, ChecksumAlgorithm });
```
</details>
<details>
<summary>GetObject</summary>
```js
import { …
```

fix(hash-stream-node): disable createReadStream with file descriptor

---

packages/util-stream-node/src/getAwsChunkedEncodingStream.spec.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3339
Adds tests for getAwsChunkedEncodingStream
Unit testing
---

test(util-stream-node): getAwsChunkedEncodingStream

---

clients/client-s3/test/flexibleChecksums.spec.ts

* Internal P60376090
* Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3360
Update client-s3 functional tests for verify trailing checksum
Functional testing
---

test(client-s3): update functional tests to verify trailing checksums

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Set for release on 2022-03-02.
This will not pass CI until https://github.com/awslabs/smithy-typescript/pull/521 is merged.
---

Bump code generators to 0.10.0

---

packages/util-body-length-node/src/calculateBodyLength.spec.ts
packages/util-body-length-node/src/calculateBodyLength.ts
packages/util-body-length-node/src/index.ts

Refactoring before fix for https://github.com/aws/aws-sdk-js-v3/issues/3377 is posted.
Moves calculateBodyLength to it's own file, and adds missing unit tests
Unit testing
This PR will be rebased after https://github.com/aws/aws-sdk-js-v3/pull/3380 is merged.
---

chore(util-body-length-node): move calculateBodyLength to it's own file

---

packages/util-body-length-node/src/calculateBodyLength.spec.ts
packages/util-body-length-node/src/calculateBodyLength.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3383
Supports computation of body length when fs.ReadStream is created with path of type Buffer.
Verified that object is successfully uploaded
<details>
<summary>PutObject without Checksum</summary>
```js
import { createReadStream } from "fs";
const client = new S3({ region });
// File created with command "(for i in {1..1000}; do echo $i "hello world"; done) > hello-world.txt"
const fileName = "hello-world.txt";
const readableStream = createReadStream(Buffer.from(fileName));
const Bucket = "aws-sdk-js-trivikr";
const Key = fileName;
const Body = readableStream;
try {
await client.putObject({ Bucket, Key, Body });
} catch (error) { …
```

fix(util-body-length-node): fs.ReadStream with path of Buffer type

---

packages/util-body-length-node/src/calculateBodyLength.spec.ts
packages/util-body-length-node/src/calculateBodyLength.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3377
Compute length when fs.ReadStream is created using fd.createReadStream
Verified that object is successfully put in the following cases:
<details>
<summary>PutObject without Checksum</summary>
```js
import { open } from "fs/promises";
const client = new S3({ region });
// File created with command "(for i in {1..1000}; do echo $i "hello world"; done) > hello-world.txt"
const fileName = "hello-world.txt";
const fd = await open(fileName);
const readableStream = fd.createReadStream();
const Bucket = "aws-sdk-js-trivikr";
const Key = fileName;
const Body = readableStream;
try {
await client.putObject({ Bucket, Key, Body });
} catch …
```

fix(util-body-length-node): support fd.createReadStream

---

packages/util-body-length-browser/src/calculateBodyLength.spec.ts
packages/util-body-length-browser/src/calculateBodyLength.ts
packages/util-body-length-node/src/calculateBodyLength.spec.ts
packages/util-body-length-node/src/calculateBodyLength.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/3400
Throw Error if body length can't be computed
* Unit testing
* Integration testing
---

chore(util-body-length): throw Error if body length can't be computed

---

packages/credential-provider-imds/src/fromContainerMetadata.spec.ts
packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts
packages/credential-provider-imds/src/fromInstanceMetadata.ts
packages/credential-provider-imds/src/index.ts
packages/credential-provider-imds/src/types.ts
packages/credential-provider-imds/src/utils/getExtendedInstanceMetadataCredentials.spec.ts
packages/credential-provider-imds/src/utils/getExtendedInstanceMetadataCredentials.ts
packages/credential-provider-imds/src/utils/staticStabilityProvider.spec.ts
packages/credential-provider-imds/src/utils/staticStabilityProvider.ts

Implement static stability strategy to support cases when IMDS is unable to refresh credentials.
---

feat(credential-provider-imds): support static stability

---

packages/middleware-content-length/src/index.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/3400
Sets transfer-encoding if content-length is not set.
Refs: https://github.com/aws/aws-sdk-js-v3/issues/3400#issuecomment-1062366026
* Integration testing
* Unit tests are not present for the middleware, and should be added in a separate PR.
Verified that `transfer-encoding` header is set to `chunked` in the following test case when we attempt to send ReadableStream to PutObject:
```js
import { Readable } from "stream";
const client = new S3({ region });
const readableStream = new Readable();
const mockDataChunks = ["Hello", "World"];
setTimeout(() => {
mockDataChunks.forEach((chunk) => readableStream.emit("data", chunk)); …
```

chore(middleware-content-length): set transfer-encoding if content-length is not set

---

packages/middleware-flexible-checksums/src/configuration.ts
packages/types/src/stream.ts

The packages equivalent of https://github.com/aws/aws-sdk-js-v3/pull/3405
Sets bodyLengthChecker type to BodyLengthCalculator in packages
CI
---

chore(packages): set bodyLengthChecker type to BodyLengthCalculator

---

packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts

P59814336
If customer make make `MediaStoreData::PutObject` API call with SDK, but mistakenly use the absolute path for `Path` parameter, they will get invalid signature error, for example:
```javascript
const client = new MediaStoreDataClient({
endpoint: "https://[store].data.mediastore.us-west-2.amazonaws.com",
});
client.send(
new PutObjectCommand({
Path: "/some/path", // <== should not lead by slash
Body: "hello",
}),
console.log
);
```
However the same call doesn't fail in AWS CLI. The route cause being the path in the request sent to the wire is `//some/path`, but the server side strips the redundant slashes. Since the signature is generated with double slashes, the invalid signature error raises.
This change adopts the same behavior as Botocore to strip reduntant slashes.
This …

fix(signature-v4): normalized the path before double encoding it

---

packages/credential-provider-imds/src/fromInstanceMetadata.ts
packages/credential-provider-imds/src/remoteProvider/RemoteProviderInit.ts
packages/credential-provider-imds/src/utils/getExtendedInstanceMetadataCredentials.spec.ts
packages/credential-provider-imds/src/utils/getExtendedInstanceMetadataCredentials.ts
packages/credential-provider-imds/src/utils/staticStabilityProvider.spec.ts
packages/credential-provider-imds/src/utils/staticStabilityProvider.ts
packages/middleware-logger/package.json
packages/middleware-logger/src/loggerMiddleware.ts
packages/middleware-signing/src/configurations.ts
packages/types/src/logger.ts

Followup to https://github.com/aws/aws-sdk-js-v3/pull/3402
Support printing credential extension warning message to a custom logger
Unit test; Manual integ test
---

feat(credential-provider-imds): accept custom logger

---

packages/shared-ini-file-loader/src/getProfileName.spec.ts
packages/shared-ini-file-loader/src/getProfileName.ts
packages/shared-ini-file-loader/src/index.ts
packages/shared-ini-file-loader/src/parseKnownFiles.spec.ts
packages/shared-ini-file-loader/src/parseKnownFiles.ts
packages/util-credentials/src/get-master-profile-name.ts
packages/util-credentials/src/index.ts
packages/util-credentials/src/parse-known-profiles.ts

Internal JS-3150
The code from util-credentials will be used outside credentials in future. Moving it to `shared-ini-file-loader` as it's most relevant there.
Move code from util-credentials to shared-ini-file-loader
CI
---

chore(shared-ini-file-loader): move code from util-credentials

---

packages/credential-provider-ini/package.json
packages/credential-provider-ini/src/fromIni.spec.ts
packages/credential-provider-ini/src/fromIni.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.spec.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.ts
packages/credential-provider-node/package.json
packages/credential-provider-node/src/defaultProvider.spec.ts
packages/credential-provider-node/src/defaultProvider.ts
packages/credential-provider-process/package.json
packages/credential-provider-process/src/fromProcess.spec.ts
packages/credential-provider-process/src/fromProcess.ts
packages/credential-provider-sso/package.json
packages/credential-provider-sso/src/fromSSO.spec.ts
packages/credential-provider-sso/src/fromSSO.ts
packages/credential-providers/package.json

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3420
Replace dependency on util-credentials files with new files in shared-ini-file-loader
CI
---

chore(credential-providers): remove dependency on util-credentials

---

packages/middleware-sdk-s3/package.json
packages/signature-v4-crt/package.json
yarn.lock

Bump up to latest aws-crt version to pick up the latest OpenSSL patch.
---

chore(signature-v4-crt): bump aws-crt to 1.11.3

---

packages/middleware-content-length/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3418
Switches back to previous experience where header 'content-length' was not set, and no other header was set.
The existing behavior was added after checking RFC 7230 in https://github.com/aws/aws-sdk-js-v3/issues/3400#issuecomment-1062257234, and AWS SDK for Python behavior in https://github.com/aws/aws-sdk-js-v3/issues/3400#issuecomment-1062366026. The issue happened in Transcribe Streaming as it uses HTTP/2, and the middleware doesn't check for version of HTTP protocol for setting 'transfer-encoding' header.
Unit tests are absent, and to be added separately to the module.
No additional testing needed, as it's basic reverting to the previous flow.
---
By submitting this pull request, I confirm that you can use, modify, copy, and …

fix(middleware-content-length): swallow error if content-length computation fails

---

packages/shared-ini-file-loader/src/getSSOTokenFilepath.spec.ts
packages/shared-ini-file-loader/src/getSSOTokenFilepath.ts
packages/shared-ini-file-loader/src/getSSOTokenFromFile.spec.ts
packages/shared-ini-file-loader/src/getSSOTokenFromFile.ts
packages/shared-ini-file-loader/src/index.ts

Internal JS-3150
The code to get SSO Token filepath will be used outside of shared-ini-file-loader in future. Creating a utility for that purpose.
Add utility getSSOTokenFilepath which returns the filepath where SSO Token is stored
Unit testing
Similar to https://github.com/aws/aws-sdk-js-v3/pull/3421
---

chore(shared-ini-file-loader): add utility getSSOTokenFilepath

---

packages/middleware-serde/src/deserializerMiddleware.spec.ts
packages/middleware-serde/src/deserializerMiddleware.ts

Ref: D38831498
The `$response` trait includes raw response for AWS service errors only. It's a low-risk that AWS service will include sensitive information in the error responses, but the possibility still exists.
This issue is scoped only with the logger, which means the logger should not print out the raw HTTP response for errors by default. This is because customer can access the raw HTTP response in variety of ways in the JavaScript SDK, we cannot prevent them from accessing potentially sensitive information.
This change makes the `$response` inenumerable makes sense here, so that the logger won't print the raw Http response by default. However, if customer need to access the raw Http response when handling the error, they can still access them specifically by `error.$response`.
Unit …

fix(middleware-serde): mark  error entry non-enumerable

---

packages/credential-provider-node/src/defaultProvider.spec.ts
packages/property-provider/src/CredentialsProviderError.spec.ts
packages/property-provider/src/CredentialsProviderError.ts
packages/property-provider/src/ProviderError.spec.ts
packages/property-provider/src/ProviderError.ts
packages/property-provider/src/index.ts

Internal JS-3150
We're going to introduce new ProviderErrors in future.
Un-deprecates ProviderError and extends CredentialsProviderError from it.
Unit testing
---

chore(property-provider): extend CredentialsProviderError from ProviderError

---

packages/credential-provider-node/src/defaultProvider.ts
packages/middleware-endpoint-discovery/src/resolveEndpointDiscoveryConfig.ts
packages/middleware-sdk-ec2/src/index.ts
packages/middleware-sdk-rds/src/index.ts
packages/middleware-signing/src/configurations.ts
packages/property-provider/src/memoize.spec.ts
packages/property-provider/src/memoize.ts
packages/types/src/util.ts

The dynamic credentials are memoized for certain expiration. V3 SDK doesn't offer a way to force a refresh for credentials, however V2 supports it: in V2, one can simply do `cred.get(callback)` to force a refresh. 
This change provides a hash option with key `forceRefresh: boolean` in the resolved credentials provider function. By setting the key, the underlying credential provider will be invoked again in regardless of the current credentials' expiration. For example:
```typescript
const client = new FooClient({});
//... needs a force refresh...
await client.config.credentials({ forceRefresh: true });
//... make more API calls...
```
Unit test
---

feat(property-provider): memoize() supports force refresh

---

packages/property-provider/src/CredentialsProviderError.spec.ts
packages/property-provider/src/ProviderError.spec.ts
packages/property-provider/src/ProviderError.ts

The issue was observed in https://github.com/aws/aws-sdk-js-v3/pull/3438
Copy error properties to ProviderError in from()
Unit testing
---

fix(property-provider): copy error properties to ProviderError in from()

---

packages/types/src/profile.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3437
Removes @internal jsdoc tag from profile types
```console
$ types> yarn clean && yarn build 
...
$ cat dist-types/profile.d.ts 
export interface Profile {
[key: string]: string | undefined;
}
export interface ParsedIniData {
[key: string]: Profile;
}
export interface SharedConfigFiles {
credentialsFile: ParsedIniData;
configFile: ParsedIniData;
}
```
---

fix(types): remove @internal jsdoc tag from profile types

---

packages/property-provider/src/CredentialsProviderError.ts
packages/property-provider/src/ProviderError.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3444
Manually adjust the prototype of *ProviderError
Verified that instanceof checks succeed for ES5 versions of *ProviderError
```js
const { __extends } = require("tslib");
var ProviderError = (function (_super) {
__extends(ProviderError, _super);
function ProviderError(message, tryNextLink) {
if (tryNextLink === void 0) {
tryNextLink = true;
}
var _this = _super.call(this, message) || this;
_this.tryNextLink = tryNextLink;
_this.name = "ProviderError";
Object.setPrototypeOf(_this, ProviderError.prototype);
return _this;
}
ProviderError.from = function (error, tryNextLink) {
if (tryNextLink === void 0) {
tryNextLink = true;
}
return Object.assign(new this(error.message, tryNextLink), error);
};
return ProviderError;
})(Error);
var …
```

fix(property-provider): manually adjust the prototype of *ProviderError

---

scripts/generate-clients/copy-to-clients.js

Fixes server-protocols test failures https://github.com/aws/aws-sdk-js-v3/runs/5631723369
The typescript version was updated in https://github.com/aws/aws-sdk-js-v3/pull/3448, but the override in generate-clients was not updated.
CI is successful (including server-protocol tests)
---

fix(scripts): update typescript version in generate-clients

---

packages/middleware-retry/package.json
packages/middleware-retry/src/configurations.spec.ts
packages/middleware-retry/src/configurations.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/3456
Use normalizeProvider from util-middleware
CI
---

chore(middleware-retry): use normalizeProvider from util-middleware

---

packages/middleware-sdk-s3/package.json

Use `peerDependenciesMeta` to suppress the peer dependency warning. https://github.com/aws/aws-sdk-js-v3/issues/2822#issuecomment-1022116272
---

chore(middleware-sdk-s3): set peerDependenciesMeta to fix installation warning

---

packages/credential-provider-node/src/defaultProvider.spec.ts
packages/credential-provider-node/src/defaultProvider.ts
packages/node-config-provider/src/fromSharedConfigFiles.spec.ts
packages/node-config-provider/src/fromSharedConfigFiles.ts
packages/shared-ini-file-loader/src/parseKnownFiles.spec.ts
packages/shared-ini-file-loader/src/parseKnownFiles.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/3285
Caching of configuration happens at slurpFile level in https://github.com/aws/aws-sdk-js-v3/pull/3285
The function loadSharedConfigFiles can be called multiple times, and doesn't have to be called at top level.
```js
// packages/shared-ini-file-loader/src/slurpFile.ts
let readFileCallTotal = 0;
export const slurpFile = (path: string) =>
new Promise<string>((resolve, reject) => {
if (!fileStatusHash[path]) {
// File not read yet, set file isReading to true and read file.
fileStatusHash[path] = { isReading: true, contents: "", requestQueue: [] };
fileStatusHash[path].requestQueue.push({ resolve, reject });
const readFileCallMsg = `readFile call #${++readFileCallTotal} for: ${path}`;
console.log(`start: ${readFileCallMsg}`);
readFile(path, …
```

chore(packages): remove loadedConfig option

---

packages/node-config-provider/src/fromSharedConfigFiles.spec.ts
packages/node-config-provider/src/fromSharedConfigFiles.ts

N/A
Get profile name from getProfileName
Unit testing
To be rebased after https://github.com/aws/aws-sdk-js-v3/pull/3478 is merged.
---

chore(node-config-provider): get profile name from getProfileName

---

clients/client-s3-control/test/S3Control.spec.ts
clients/client-s3/test/S3.spec.ts
packages/eventstream-marshaller/scripts/buildTestVectorsFixture.js
packages/middleware-endpoint-discovery/src/updateDiscoveredEndpointInCache.spec.ts
packages/middleware-endpoint-discovery/src/updateDiscoveredEndpointInCache.ts
packages/protocol-http/src/httpRequest.ts
packages/s3-presigned-post/src/createPresignedPost.ts
packages/service-client-documentation-generator/src/sdk-client-comment-update.ts
packages/signature-v4/src/SignatureV4.ts
packages/signature-v4/src/moveHeadersToQuery.ts
packages/util-base64-browser/src/index.ts
packages/util-format-url/src/index.ts
packages/util-hex-encoding/src/index.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
I have checked the return of each statement to make sure it's still the same as before

chore: replace deprecated String.prototype.substr()

---

packages/credential-provider-node/src/defaultProvider.spec.ts
packages/credential-provider-node/src/defaultProvider.ts

Noticed while working on https://github.com/aws/aws-sdk-js-v3/pull/3479
All upstream packages get profile name from `getProfileName` call which checks for env[AWS_PROFILE]
The value is not required to be set in defaultProvider.
Unit testing
~~To be rebased after https://github.com/aws/aws-sdk-js-v3/pull/3478 is merged.~~ Ready!
---

chore(credential-provider-node): do not set profile from env

---

packages/node-config-provider/src/fromSharedConfigFiles.ts

N/A
The `profile?: string;` is added in existing interface `SourceProfileInit`, and `SharedConfigInit` in fromSharedConfigFiles can extend from it.
CI
---

chore(node-config-provider): extend SharedConfigInit from SourceProfileInit

---

scripts/benchmark-size/limit.json

Remove the test preventing 10% size increase. This is to unblock the service launching a bigger release. We still have test to prevent the package size grow beyond 5 mb. 
In the future, we will change the size increase test to only monitoring a service client's dependency, instead of it's own size, because it depends on the model change.
---

test(size): remove the test preventing 10% size increase

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

This will not pass CI until https://github.com/awslabs/smithy-typescript/pull/532 is merged.

chore(codegen): bump code generators to 0.11.0

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-restjson/src/commands/StreamingTraitsRequireLengthCommand.ts
private/aws-protocoltests-restjson/src/models/models_0.ts
private/aws-protocoltests-restjson/src/protocols/Aws_restJson1.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts

Also bumping smithy version for smithy-typescript-codegen in https://github.com/awslabs/smithy-typescript/pull/531
Using locally published smithy-typescript-codegen and smithy-aws-typescript-codegen, ran
`yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols`
---

chore(codegen): update to Smithy 1.19.x

---

packages/middleware-sdk-s3/package.json
packages/signature-v4-crt/package.json
yarn.lock

Replace https://github.com/aws/aws-sdk-js-v3/pull/3514 because it was mistakenly merged during the release.
---

chore(signature-v4-crt): bump aws-crt version to 1.12.1

---

CONTRIBUTING.md

docs(contributing): update codegen guidance

---

packages/eventstream-handler-node/package.json
packages/eventstream-serde-node/package.json
packages/eventstream-serde-universal/package.json
packages/smithy-client/package.json

Issue uncovered in #3536 
I will bulk update the nodejs types in a separate PR.
Add missing dependency of `@types/node` in some of the dependency packages
---

chore(packages): add missing @types/node dep

---

packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts

Follow-up to:
* https://github.com/aws/aws-sdk-js-v3/pull/3340
* https://github.com/aws/aws-sdk-js-v3/pull/3347
The flexibleChecksumsMiddleware can compute the checksum directly from stringHasher, and doesn't need to call getChecksum which requires both stringHasher/streamHasher.
Unit testing
---

chore(middleware-flexible-checksums): call stringHasher from flexibleChecksumsMiddleware

---

packages/shared-ini-file-loader/src/slurpFile.spec.ts
packages/shared-ini-file-loader/src/slurpFile.ts

Noticed that Promises can be resolved/rejected only once while reviewing https://github.com/aws/aws-sdk-js-v3/pull/3545
Uses Promises in slurpFile hash
Unit testing
StackOverflow discussion https://codereview.stackexchange.com/a/51658
---

chore(shared-ini-file-loader): use Promises in slurpFile hash

---

packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts

Http2Session keeps node alive even with no requests running, presumably for server pushed streams. This is a behavior change from node's http 1 Agent, which does not keep node alive when there is no request running.
Emulate that behavior for Node2HttpHandler by `unref()`ing new sessions, and wrapping requests in a `ref()` / `unref()` pair.
This issue is mentioned by #1206, but it incorrectly assumes it's strictly related to connection timeouts. The interaction there is a bit strange to describe, since the actual network connection and request establishment overlap, but the behavior you should see is that if for example, you immediately create and abort a request, the session connection continues, but node will exit as the session is no longer `ref()`ed. Would be good to explicitly test …

fix(node-http-handler): http2 lets node exit

---

.gitignore
lib/lib-dynamodb/src/commands/marshallInput.spec.ts
lib/lib-dynamodb/src/commands/utils.ts
packages/util-dynamodb/src/marshall.spec.ts
packages/util-dynamodb/src/marshall.ts
packages/util-dynamodb/src/marshallTypes.spec.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/2807 
> @aws-sdk/lib-dynamodb incorrectly marshalls non-object types
- modify the `marshall` method in util-dynamodb and used by lib-dynamodb
- currently this only returns the `M` property assuming a map is the input
- I modified this function to return the M or L properties for maps and lists, but otherwise return the converted attributeValue. 
- separately, I believe the function `processObj` in lib-dynamodb needs to accept falsy values other than undef.
added unit/integration specs to cover the cases described in the issue and my other change to lib-dynamodb
`util-dynamodb` is an internal package providing the marshaling functionality.
`lib-dynamodb` is a wrapper for `client-dynamodb` that aims to simplify the object structure to one …

fix(util-dynamodb): allow marshall function to handle more input types

---

packages/node-http-handler/src/node-http2-handler.spec.ts

Follow up to #3541 
Clean up the unit test.
/cc @simonbuchan 
---

test(node-http-handler): clean up ref() & unref() tests

---

packages/shared-ini-file-loader/src/getProfileData.spec.ts
packages/shared-ini-file-loader/src/getProfileData.ts
packages/shared-ini-file-loader/src/loadSharedConfigFiles.spec.ts
packages/shared-ini-file-loader/src/loadSharedConfigFiles.ts

Internal JS-3252
Renames normalizeConfigFile to getProfileData
CI
---

chore(shared-ini-file-loader): rename normalizeConfigFile to getProfileData

---

packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/smithy-client/src/defaults-mode.ts

Similar to #3545 
Support provider functions in the contructor of H2 handler.
Unit test
---

chore(node-http-handler): h2 handler accept options in provider

---

clients/client-kinesis/jest.integ.config.js
clients/client-kinesis/src/runtimeConfig.ts
clients/client-kinesis/test/Kinesis.integ.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttp2Dependency.java

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/1206
Thanks to #3541, using HTTP/2 handler in service client is no longer blocked by weird socket timeout. This change removes hard-coding HTTP/2 clients but rely on the Smithy model. 
This change enable us to use HTTP/2 in Kinesis client without breaking customer. Added integration test for it.
This change doesn't include `defaultConfigProvider` to the handler constructor because none of the default config is applicable to HTTP/2 handler for now.
Integration test
---

chore(client-kinesis): switch to H2 handler

---

features/kinesis/kinesis.feature

Internal slack
This commit disables kinesis integration test, as it's failing in our internal preview builds.
It would be enabled after the v3.81.0 release, after a deep-dive and fixing the issue.
We suspected the issue was caused by https://github.com/aws/aws-sdk-js-v3/pull/3577, but it's not reproducible in workspace. Disable the legacy integration test, as the code change was tested with new integration test.
Verified that Kinesis legacy test is skipped
```console
$ yarn test:integration:legacy --fail-fast -t @kinesis
yarn run v1.22.18
$ cucumber-js --fail-fast --fail-fast -t @kinesis
0 scenarios
0 steps
0m00.000s
Done in 0.61s.
```
Verified that manually written test is successful:
```js
// kinesis.mjs
import { Kinesis } from …
```

fix(client-kinesis): disable Kinesis ResourceNotFoundException test

---

codegen/build.gradle.kts

Also bumping smithy version for smithy-typescript-codegen in https://github.com/awslabs/smithy-typescript/pull/540
Using locally published smithy-typescript-codegen and smithy-aws-typescript-codegen, ran
`yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols`
---

chore(codegen): update to Smithy 1.21.x

---

lib/lib-storage/README.md
lib/lib-storage/src/Upload.ts
lib/lib-storage/src/types.ts

Followup to https://github.com/aws/aws-sdk-js-v3/issues/2694
and its PR: https://github.com/aws/aws-sdk-js-v3/pull/2700
Clean up some type declarations in Upload.ts
- narrower input and output types
- add access modifiers to methods
- add explicit return types
Ran existing unit tests.

chore(lib-storage): narrow types in Upload

---

tests/functional/endpoints/test_cases_supported.json

Fixes [main branch functional test failure](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiYkthUUxndUkzQ2FreVlQVlFaUmM2RWU4SXFrd3VwbStjcGZ5NXhORjFlQ1BnTlU5RmFJcmdwU2FnSGRhdmo0dVhudlM2Tm1rTG02U1NMaGkydU5LZUFiQlNPSTh6cXVxN1Zta2pMdkhINTduIiwiaXZQYXJhbWV0ZXJTcGVjIjoiblFJTmhOdFkzZ2FEZXZSaCIsIm1hdGVyaWFsU2V0U2VyaWFsIjoxfQ%3D%3D/build/8aafafed-3377-4e55-8d3e-063ba2784ad2?tab=buildLogs).
The recent endpoints update to EC2 (https://github.com/aws/aws-sdk-js-v3/commit/79ad41b313273283c91f9c1358b0d1dd7b8686c1) breaks the endpoint test. This fix unblocks the main branch
---

test(endpoints): update ec2 ap-south-1 dualstack endpoint

---

packages/signature-v4-crt/package.json
packages/signature-v4-multi-region/package.json

The aws-crt dependency starts to support [Apple M1](https://github.com/awslabs/aws-crt-nodejs/commit/05389e312a95b5d4377b4b9a745353f390dde45a) since latest 1.22.2. 
This change bumps the peer dependency requirement of aws-crt to the latest version
/cc @graebm
---

chore(signature-v4-crt): bump aws-crt to 1.22.2

---

clients/client-kinesis/src/runtimeConfig.ts
clients/client-lex-runtime-v2/src/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttp2Dependency.java

The default config provider may specify the request timeout, which is applicable to the H2 handler.
---

feat(clients): http2 handler accept parameters from default config provider

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddNimbleCustomizations.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ObjectSizeMemberShapeType.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/StripNewEnumNames.java

Based on https://github.com/awslabs/smithy-typescript/pull/542. CI will fail till that's merged. Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` locally with both PRs and no change to generated clients.
---

Change `preprocessModel` to take `Model` instead of `PluginContext`

---

packages/node-http-handler/package.json
packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts

May fixes https://github.com/aws/aws-sdk-js-v3/pull/3577#issuecomment-1118870752. 
I found the H2 handler's session cache **cannot** evict the session if the session is closed from the server side. Hence when making the new request, the users will see error that the request made on destroyed session.
This change handles this event. I also re-evaluated the [current session events](https://nodejs.org/api/http2.html#class-http2session), and made sure the necessary events are handled.
Unit test
Whether this will fix the mentioned issue cannot be fully confirmed without server-side logs. But I could reproduce the same mentioned issue by server-side closing the session.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

fix(node-http-handler): handle close event in H2 from server side

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegration.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegrationTest.java

Based on https://github.com/awslabs/smithy-typescript/pull/544. CI will fail till that's merged. Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` locally with both PRs and no change to generated clients.
---

chore(codegen): refactor decorateSymbolProvider to match SmithyIntegration

---

packages/smithy-client/src/emitWarningIfUnsupportedVersion.spec.ts
packages/smithy-client/src/emitWarningIfUnsupportedVersion.ts

Internal JS-3236
Emits unsupported version warning for Node.js <14.x
Unit testing
---

chore(smithy-client): emit unsupported version warning for Node.js <14.x

---

private/aws-protocoltests-json-10/src/models/models_0.ts
private/aws-protocoltests-json/src/models/models_0.ts
private/aws-protocoltests-query/src/models/models_0.ts
private/aws-protocoltests-restjson/src/models/models_0.ts
private/aws-protocoltests-restxml/src/models/models_0.ts

Based on https://github.com/awslabs/smithy-typescript/pull/547
Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` and the only diffs are some rearranging of code within a file in protocoltests.
---

chore(clients): regenerate based on smithy-typescript#547

---

.gitignore
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientCommandGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/propertyaccess/PropertyAccessor.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/propertyaccess/PropertyAccessorTest.java

Internal P64934837
- add function helper for property access to decide between `.prop` and `['prop']` access modes. 
- it's not exhaustively applied, but covers the issue that was exposed by the unreleased model.
- no changes needed in smithy-typescript.
- ran `yarn generate-clients` using the unreleased smithy model (not shown here) 
- confirmed unreleased model builds valid TS and compiles to dist.
- confirmed this doesn't cause any existing client code changes. 
- added unit tests for new function

fix(codegen): check javascript property validity for property access

---

clients/client-lex-runtime-v2/src/protocols/Aws_restJson1.ts
clients/client-s3/src/protocols/Aws_restXml.ts
clients/client-transcribe-streaming/src/protocols/Aws_restJson1.ts

Internal JS-3299
Use Record<string, any> in event stream deserializer
[TypeScript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgDwIYFsAOAbOB5ARgKxgF4YBvAKBhgCJw5qAuGARgBpKaoB3ERmAJnZVqUABYAnOPSYBmcgF9y5UJFiTQ4gCZMASnA2aAPNHEBLMAHNWMMAFcUuOOIB8xeMnRY8+ANzLw0DAA1nAAngDKUGaW3kykANohoQwm5hYAukx2Dk7yboiomDgEPkA):
```ts
const exampleObj = { "one": 1, "two": 2, "three": 3}
const record: Record<string, number> = exampleObj;
const keyStringObj: {[key:string]: number} = exampleObj;
```
smithy-ts PR: https://github.com/awslabs/smithy-typescript/pull/556
---

chore(clients): use Record type in event stream deserializer

---

clients/client-s3/test/e2e/S3.ispec.ts

Make sure the event stream handling in HTTP/1.1 works in browsers
```console
lerna info run Ran npm script 'test:e2e' in '@aws-sdk/client-s3' in 30.8s:
$ ts-mocha test/**/*.ispec.ts && karma start karma.conf.js
@aws-sdk/client-s3
PutObject
✓ should succeed with Node.js readable stream body (562ms)
GetObject
✓ should succeed with valid body payload (2759ms)
ListObjects
✓ should succeed with valid bucket (154ms)
✓ should throw with invalid bucket (269ms)
MultipartUpload
✓ should successfully create, upload list and complete (607ms)
✓ should successfully create, abort, and list upload (230ms)
selectObjectContent
✓ should succeed (169ms)
7 passing (6s)
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Failed to compile.
WARN: 'Are you using a Stream of unknown length as the Body …
```

test(s3): e2e test for s3 selectObjectContent

---

.github/workflows/commit-message-lint.yml

The PR validation App [stops working recently](https://github.com/zeke/semantic-pull-requests/issues/187).
This change introduce a new GitHub action to validate the commit message according to the `commitlint.config.js`.
---

chore: add commit lint action

---

clients/client-auto-scaling/src/protocols/Aws_query.ts
clients/client-cloudformation/src/protocols/Aws_query.ts
clients/client-cloudfront/src/protocols/Aws_restXml.ts
clients/client-cloudsearch/src/protocols/Aws_query.ts
clients/client-cloudwatch/src/protocols/Aws_query.ts
clients/client-docdb/src/protocols/Aws_query.ts
clients/client-ec2/src/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing/src/protocols/Aws_query.ts
clients/client-elasticache/src/protocols/Aws_query.ts
clients/client-iam/src/protocols/Aws_query.ts
clients/client-neptune/src/protocols/Aws_query.ts
clients/client-rds/src/protocols/Aws_query.ts
clients/client-redshift/src/protocols/Aws_query.ts
clients/client-route-53/src/protocols/Aws_restXml.ts
clients/client-s3-control/src/protocols/Aws_restXml.ts
clients/client-s3/src/protocols/Aws_restXml.ts
clients/client-ses/src/protocols/Aws_query.ts
clients/client-sns/src/protocols/Aws_query.ts
clients/client-sqs/src/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
private/aws-protocoltests-ec2/src/protocols/Aws_ec2.ts
private/aws-protocoltests-query/src/protocols/Aws_query.ts
private/aws-protocoltests-restxml/src/protocols/Aws_restXml.ts

Resolves: #3585 
Follow up to: #885 #914 #919 #955
The underlying xml parser used by the SDK(fast-xml-parser) parses the self-closing tags(e.g. `<Filter/>`) to empty string(e.g. `{ "Filter": "" }`). The mentioned PRs(#914 #919 #955) adds early return to the parser. If the parsed value of the member is empty string, it will return default empty value. If the member is a `Map`, then the empty value is `{}`; If the member is a `Collection(List)`, then the empty value is `[]`.
However the generated code has 2 issues:
1. The early if statement was not effective as the later if statement will still attempt to parse the subordinary shape out of `""`. For example
```js
if (output.Tag === "") {
contents.Tags = []; // <== this is overwritten
}
if (output["Tag"] !== undefined) { 
contents.Tags = …
```

fix(clients): handle empty xml tags

---

packages/middleware-sdk-ec2/package.json
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-ec2/src/index.ts

Internal V599567416
- Use the regionInfoProvider to get the hostname for a specific EC2 command, copySnapshot
- the previous value was partially hardcoded
- added unit tests

fix(middleware-sdk-ec2): use hostname from regionInfoProvider

---

clients/client-s3/src/commands/WriteGetObjectResponseCommand.ts
clients/client-s3/test/S3.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
packages/middleware-sdk-s3/package.json
packages/middleware-sdk-s3/src/index.ts
packages/middleware-sdk-s3/src/write-get-object-response-endpoint.spec.ts
packages/middleware-sdk-s3/src/write-get-object-response-endpoint.ts

Ref JS-3346
Resolves: #3528
Add customization to S3::WriteGetObjectResponse API's endpiont. It was missed in https://github.com/aws/aws-sdk-js-v3/pull/2143
Unit test, Functional test
Follow-up PRs:
* Throw error when S3 Lambda object ARN exists for S3 managed uploader
---

fix(s3): update endpoints for writeGetObjectResponse for object lambda

---

packages/types/src/profile.ts

Internal JS-3252
Deprecates type Profile in favor of ParsedIniSection, as new sections would be introduced in parsed ini in future.
Unit testing
---

chore(types): deprecate Profile in favor of ParsedIniSection

---

packages/credential-provider-cognito-identity/src/Logins.ts
packages/eventstream-marshaller/src/Message.ts
packages/eventstream-marshaller/src/vectorTypes.fixture.ts
packages/middleware-header-default/src/index.ts
packages/types/src/eventStream.ts
packages/types/src/http.ts
packages/types/src/profile.ts

Internal JS-3299
Replaces Object interface with Record type
Used regular expression `interface ([\w]*) \{\n. \[[^:]*: string\]: ([^;]*);\n\}` for searching, and replaced it with value `type $1 = Record<string, $2>;`
Verified that usage of imports won't break when interface is replaced with types in [TypeScript playground](https://www.typescriptlang.org/play?ssl=17&ssc=53&pln=13&pc=1#code/MYewdgzgLgBApgDwIYFsAOAbOB5ARgKxgF4YBvAKBhgCJw5qAuGARgBpKaoB3ERmAJnZVqUABYAnOPSYBmcgF9y5AJZgoccQDMkwODACySNAEk1G7brIcA2gGs4ATwbRxqgOYBdJmACuKXBoA3ApKUA5oeoZoACrheiQASnCg4gAmADwu7qwwvv4aAHzB5KCQsCAEpupaOnBMUVXmtcTwyOhYePjBpdAwFfixEfVGg-GtqJg4BMU95ZVmNboAwiBoDtEgUcMxcS39jYtw3eC9-aMraxuNFnUGRgc3ewSjxUA):
```ts
const exampleObj = {
"one": 1,
"two": 2,
"three": 3
}
interface MapInterface {
[key:string]: …
```

chore(packages): replace Object interface with Record type

---

package.json
yarn.lock

Internal JS-3363
Bumps prettier to 2.7.1
Verified that there are no new formatting introduced:
```console
$ ./node_modules/.bin/prettier --write packages/**/src/**/*.ts
...
$ ./node_modules/.bin/prettier --write lib/**/src/**/*.ts
...
$ ./node_modules/.bin/pprettier --write clients/**/src/**/*.ts
...
$ ./node_modules/.bin/pprettier --write private/**/src/**/*.ts
...
```
---

chore(deps-dev): bump prettier to 2.7.1

---

packages/middleware-sdk-transcribe-streaming/package.json
yarn.lock

Internal JS-3363
Bumps mock-socket to 9.1.5
Test is successful in `middleware-sdk-transcribe-streaming`
```console
$ middleware-sdk-transcribe-streaming> yarn test
$ jest --passWithNoTests
PASS  src/middleware-endpoint.spec.ts
PASS  src/signer.spec.ts
PASS  src/websocket-handler.spec.ts
Test Suites: 3 passed, 3 total
Tests:       15 passed, 15 total
Time:        4.848 s
Done in 6.02s.
```
* url-parse bump in https://github.com/aws/aws-sdk-js-v3/pull/3372
* https://github.com/thoov/mock-socket/issues/319#issuecomment-931310192
---

chore(deps-dev): bump mock-socket to 9.1.5

---

package.json
yarn.lock

Internal JS-3363
Bumps verdaccio to 5.13.0
Verified that local publish works with v5.13.0:
```console
$ yarn local-publish
...
- @aws-sdk/xml-builder@3.112.1-ci.0
lerna success published 413 packages
lerna http fetch PUT 201 http://localhost:4873/@aws-sdk%2frds-signer 132ms
Done in 42.43s.
```
Post-merge, this change will be verified with release automation tests.
---

chore(deps-dev): bump verdaccio to 5.13.0

---

package.json
yarn.lock

Internal JS-3396
Reverts https://github.com/aws/aws-sdk-js-v3/pull/3711
Downgrades verdaccio to v4.13.2 as tests were timing out in release pipeline
Verified that local publish works with v5.13.0:
```console
$ yarn local-publish
...
- @aws-sdk/xml-builder@3.114.1-ci.0
lerna success published 414 packages
lerna http fetch PUT 201 http://localhost:4873/@aws-sdk%2frds-signer 250ms
Done in 56.27s.
```
---

chore(deps-dev): downgrade verdaccio to 4.13.2

---

codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegrationTest.java

[`TypeScriptCodegenPlugin.createSymbolProvider`](https://github.com/awslabs/smithy-typescript/blob/584f7ed6577554b7bf4297cfc261a924a022f55e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java#L41) is `@Deprecated`. Removing here will allow deleting the method in smithy-typescript repo.
The current method is basically `return new SymbolVisitor(model, settings);`. `SymbolVisitor()` is not public, so instead using [`TypeScriptSettings.ArtifactType.CLIENT.createSymbolProvider`](https://github.com/awslabs/smithy-typescript/blob/584f7ed6577554b7bf4297cfc261a924a022f55e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java#L391) which is effectively the same.
--- …

chore(codegen): do not use deprecated TypeScriptCodegenPlugin.createSymbolProvider

---

packages/signature-v4-crt/package.json
packages/signature-v4-multi-region/package.json
packages/util-user-agent-node/package.json

Resolves: #3715  
Resolves: #3640 
The latest [AWS-CRT 1.12.5](https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.12.5) fix the issue of its huge runtime dependency. This change adopts the fix. This fix also specifies in the `util-user-agent-node` package that the aws-crt is an optional dependency. 
---

fix(signature-v4-crt): bump aws-crt to 1.12.5
