aws/aws-sdk-js-v3

packages/package-generator/src/ClientModuleGenerator.ts, packages/service-types-generator/src/Components/Model/MemberRef.spec.ts, packages/service-types-generator/src/Components/Model/MemberRef.ts, packages/service-types-generator/src/internalImports.ts, packages/xml-body-parser/src/index.spec.ts, packages/xml-body-parser/src/index.ts
This PR unblocks generating service clients using query and xml protocols(SQS, S3)
=> Fix flattened list and Fix issue of parsing result wrapper

packages/client-codecommit-node/README.md, packages/client-codecommit-node/test/smoke/index.spec.ts, packages/client-cognito-identity-browser/README.md, packages/client-dynamodb-v2-browser/README.md, packages/client-dynamodb-v2-browser/model/_ListAttributeValue.ts, packages/client-dynamodb-v2-browser/model/_MapAttributeValue.ts, packages/client-dynamodb-v2-node/README.md, packages/client-dynamodb-v2-node/model/_ListAttributeValue.ts, packages/client-dynamodb-v2-node/test/smoke/index.spec.ts, packages/client-kinesis-browser/README.md, packages/client-lambda-node/README.md, packages/client-lambda-node/test/smoke/index.spec.ts
update service clients: 
* client-codecommit-node,
* client-cognito-identity-browser,
* client-dynamodb-v2-browser, 
* client-dynamodb-v2-node,
* client-lambda-node,
* client-kinesis-browser
Mostly adding the READMEs and smoke tests
=> update service clients

packages/response-metadata-extractor/src/index.spec.ts, packages/response-metadata-extractor/src/index.ts
fix for https://github.com/aws/aws-sdk-js-v3/issues/181
=> fix missing request id on response

packages/util-body-length-node/src/index.spec.ts, packages/util-body-length-node/src/index.ts
Fix for https://github.com/aws/aws-sdk-js-v3/issues/177.
Added tests to cover a few additional cases.
=> fix multi-byte body lengths

.github/no-response.yml
Adds configuration for no-response bot
=> add no-response bot

.travis.yml
Add a test in CI to make sure every PR opened contains all the required code change. Before opening a PR you should run `scripts/rebuildClients.js` to make sure all necessary code change is contained.
The PR will fail until #204 is merged.
=> test: add commit completity test in ci

package.json
Add a new dev dependency to generate structured release note
=> chore: add generate-changelog to generate overall release notes

.travis.yml
Temporary remove the PR completion test in the CI as newly generated clients doesn't comply to the formattings introduced by prettier
=> chores: remove completion test

lerna.json, package.json
N/A
update lerna from `3.11.0` > `3.13.4`
=> chore: update lerna

commitlint.config.js, package.json
Add a commit lint to enforce conventional commit message.
=> chore: add commit lint

package.json
N/A
* Add "Amazon Web Services" as author name
* This also removes email ID as it's not listed in other AWS projects
=> chore: Add Amazon Web Services as author name

.travis.yml, package.json
=> chore: add support for codecov

README.md
=> docs: add code style prettier badge

CONTRIBUTING.md
=> doc: adding --version argument in example

.github/lock.yml
N/A
add link to create new issue in lockComment
=> doc: add link to create new issue in lockComment

packages/client-s3-browser/S3Client.ts, packages/client-s3-browser/S3Configuration.ts, packages/client-s3-browser/package.json, packages/client-s3-node/S3Client.ts, packages/client-s3-node/S3Configuration.ts, packages/client-s3-node/package.json, packages/s3-error-unmarshaller/.gitignore, packages/s3-error-unmarshaller/.npmignore, packages/s3-error-unmarshaller/LICENSE, packages/s3-error-unmarshaller/README.md, packages/s3-error-unmarshaller/package.json, packages/s3-error-unmarshaller/src/constants.ts, packages/s3-error-unmarshaller/src/index.spec.ts, packages/s3-error-unmarshaller/src/index.ts, packages/s3-error-unmarshaller/tsconfig.json, packages/s3-error-unmarshaller/tsconfig.test.json, packages/service-types-generator/src/ServiceCustomizations/s3/index.ts, packages/service-types-generator/src/ServiceCustomizations/s3/parser.ts, packages/service-types-generator/src/internalImports.ts
Add a customization to S3 to handle parsing S3's special exceptions shape.
=> S3 error unmarshaller

package.json, packages/client-pinpoint-browser/types/_SendUsersMessageResponse.ts, packages/credential-provider-process/src/index.ts, packages/package-generator/package.json, packages/service-types-generator/package.json, packages/service-types-generator/src/ServiceCustomizations/customizationsFromModel/signatureCustomizations.ts
=> chore: update prettier to 1.18.2

package.json
Fixes https://github.com/aws/aws-sdk-js-v3/issues/289
* lint-staged config was simplified as per documentation https://github.com/okonet/lint-staged#configuration
* verified that prettier now runs on precommit
=> chore: simplify lint-staged config

package.json
N/A
Fixes security vulnerability in lodash:
```
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @commitlint/cli [dev]                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @commitlint/cli > lodash …
```
=> chore(package): update @commitlint/* to version 8.1.0

packages/credential-provider-node/package.json, packages/package-generator/package.json
N/A
update node engines in package.json ([documentation](https://docs.npmjs.com/files/package.json#engines))
=> chore: update node engines in package.json

packages/service-types-generator/src/clientReadme.ts
N/A
This was missed in https://github.com/aws/aws-sdk-js-v3/pull/271
=> fix: add preview badge in clientReadme

README.md
* Add instruction for installing clients from source code
* Format the README
=> feat: add install from source to README

packages/signature-v4-node/README.md
Updated to match SignatureV4.d.ts
- Resolves https://github.com/aws/aws-sdk-js-v3/issues/320
- Updates the README.md according to the TypeScript definitions
=> Update signature-v4-node README.md

.github/lock.yml
=> chore: lock inactive issues from 2019-02-01

README.md
=> docs: update README import statement

clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts
=> fix: pass body to error deserializer

packages/node-http-handler/src/get-transformed-headers.ts, packages/node-http-handler/src/index.ts, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-handler.spec.ts, packages/node-http-handler/src/node-http2-handler.ts, packages/node-http-handler/src/server.mock.ts, packages/node-http-handler/src/write-request-body.ts, packages/types/src/http.ts
Follow up to https://github.com/aws/aws-sdk-js-v3/pull/317 in `smithy-codegen` branch
Node.js HTTP/2 Handler
=> feat: [WIP] Node.js HTTP/2 Handler in smithy-codegen

_config.yml
N/A
* Looks like this was added by mistake in commit https://github.com/aws/aws-sdk-js-v3/commit/c27a9855cf059c3dd863500a78d204ba37819221
* I couldn't find history on how it got added. We've enabled [branch protection](https://help.github.com/en/github/administering-a-repository/about-protected-branches) on master to avoid such commits
=> chore: remove _config.yml

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
=> chore: update codegen plugins to new format

.github/ISSUE_TEMPLATE/--documentation.md
N/A
add documentation issue template
=> doc: add documentation issue template

README.md
N/A
add dependabot badge in README
=> chore: add dependabot badge in README

package.json
N/A
* The options --include-filtered-* were renamed in v3.18.0
* [CHANGELOG](https://github.com/lerna/lerna/blob/master/CHANGELOG.md#3180-2019-10-15)
* [Commit](https://github.com/lerna/lerna/commit/f2c3a92)
* PR which bumped lerna dependency from v3.18.3 in aws-sdk-js-v3 https://github.com/aws/aws-sdk-js-v3/pull/417
=> chore: rename --include-filtered-* options

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
=> fix: update error deserialization to return Error types

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java, packages/middleware-sdk-s3/src/validate-bucket-name.ts
Fixes plugin and tag settings for validate bucket name middleware
=> fix: middleware name and tags

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddProtocols.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestJson1_1.java
=> Enforce rest-json as version 1.1

features/cognitosync/step_definitions/cognitosync.js, features/extra/hooks.js
N/A
* integ tests for cognitosync from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cognitosync
```
=> feat: integ tests for cognitosync from minimal changes from v2

features/extra/hooks.js, features/ses/ses.feature, features/ses/step_definitions/ses.js
N/A
* integ tests for ses from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @ses
```
=> feat: integ tests for ses from minimal changes from v2

features/lambda/step_definitions/lambda.js
N/A
* integ tests for lambda from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @lambda
```
=> feat: integ tests for lambda from minimal changes from v2

features/iot/step_definitions/iot.js
N/A
* integ tests for iot from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @iot
```
=> feat: integ tests for iot from minimal changes from v2

features/es/step_definitions/es.js
N/A
* integ tests for elasticsearch-service from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @es
```
=> feat: integ tests for elasticsearch-service from minimal changes from v2

features/efs/step_definitions/efs.js
N/A
* integ tests for efs from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @efs
```
=> feat: integ tests for efs from minimal changes from v2

features/datapipeline/step_definitions/datapipeline.js
N/A
* integ tests for datapipeline from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @datapipeline
```
=> feat: integ tests for datapipeline from minimal changes from v2

features/ec2/ec2.feature, features/ec2/step_definitions/ec2.js
N/A
* integ tests for ec2 from minimal changes from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @ec2
```
=> feat: integ tests for ec2 from v2

features/autoscaling/autoscaling.feature, features/autoscaling/step_definitions/autoscaling.js
N/A
* integ tests for autoscaling from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @autoscaling
```
=> feat: integ tests for autoscaling from v2

features/cloudformation/cloudformation.feature, features/cloudformation/step_definitions/cloudformation.js
N/A
* integ tests for cloudformation from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cloudformation
```
=> feat: integ tests for cloudformation from v2

features/cloudsearch/step_definitions/cloudsearch.js
N/A
* integ tests for cloudsearch from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cloudsearch
```
=> feat: integ tests for cloudsearch from v2

features/cloudwatch/step_definitions/cloudwatch.js
N/A
* integ tests for cloudwatch from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cloudwatch
```
=> feat: integ tests for cloudwatch from v2

features/elasticbeanstalk/step_definitions/elasticbeanstalk.js
N/A
* integ tests for elastic-beanstalk from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @elasticbeanstalk
```
=> feat: integ tests for elastic-beanstalk from v2

features/elb/step_definitions/elb.js, features/elbv2/step_definitions/elbv2.js
N/A
* integ tests for elastic-load-balancing from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @elb
AWS_PROFILE=<profileName> yarn integ-test --tags @elbv2
```
=> feat: integ tests for elastic-load-balancing from v2

features/elasticache/step_definitions/elasticache.js
N/A
* integ tests for elasticache from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @elasticache
```
=> feat: integ tests for elasticache from v2

features/rds/rds.feature, features/rds/step_definitions/rds.js
N/A
* integ tests for rds from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @rds
```
=> feat: integ tests for rds from v2

features/redshift/step_definitions/redshift.js
N/A
* integ tests for redshift from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @redshift
```
=> feat: integ tests for redshift from v2

features/extra/helpers.js, features/sns/step_definitions/sns.js
N/A
* integ tests for sns from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @sns
```
=> feat: integ tests for sns from v2

features/extra/helpers.js
* Refs: https://github.com/aws/aws-sdk-js-v3/pull/516
* Noticed this update was required while writing integ tests for sns
update unexpectedError based on data returned from v3 call
=> fix: update unexpectedError based on data returned from v3 call

features/sts/step_definitions/sts.js
N/A
* integ tests for sts from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @sts
```
=> feat: integ tests for sts from v2

features/acm/step_definitions/acm.js
N/A
* integ tests for acm from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @acm
```
=> feat: integ tests for acm from v2

features/cloudtrail/step_definitions/cloudtrail.js
N/A
* integ tests for cloudtrail from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cloudtrail
```
=> feat: integ tests for cloudtrail from v2

features/cloudwatchevents/step_definitions/cloudwatchevents.js
N/A
* integ tests for cloudwatch-events from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cloudwatchevents
```
=> feat: integ tests for cloudwatch-events from v2

features/codecommit/step_definitions/codecommit.js
N/A
* integ tests for codecommit from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @codecommit
```
=> feat: integ tests for codecommit from v2

features/codedeploy/step_definitions/codedeploy.js
N/A
* integ tests for codedeploy from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @codedeploy
```
=> feat: integ tests for codedeploy from v2

features/codepipeline/step_definitions/codepipeline.js
N/A
* integ tests for codepipeline from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @codepipeline
```
=> feat: integ tests for codepipeline from v2

features/configservice/step_definitions/configservice.js
N/A
* integ tests for config-service from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @configservice
```
=> feat: integ tests for config-service from v2

features/directconnect/step_definitions/directconnect.js
N/A
* integ tests for direct-connect from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @directconnect
```
=> feat: integ tests for direct-connect from v2

features/directoryservice/step_definitions/directoryservice.js
N/A
* integ tests for directory-service from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @directoryservice
```
=> feat: integ tests for directory-service from v2

features/dynamodbstreams/step_definitions/dynamodbstreams.js
N/A
* integ tests for dynamodb-streams from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @dynamodbstreams
```
=> feat: integ tests for dynamodb-streams from v2

features/ecr/step_definitions/ecr.js
N/A
* integ tests for ecr from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @ecr
```
=> feat: integ tests for ecr from v2

features/ecs/ecs.feature, features/ecs/step_definitions/ecs.js
N/A
* integ tests for ecs from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @ecs
```
=> feat: integ tests for ecs from v2

features/emr/step_definitions/emr.js
N/A
* integ tests for emr from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @emr
```
=> feat: integ tests for emr from v2

features/gamelift/step_definitions/gamelift.js
N/A
* integ tests for gamelift from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @gamelift
```
=> feat: integ tests for gamelift from v2

features/inspector/step_definitions/inspector.js
N/A
* integ tests for inspector from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @inspector
```
=> feat: integ tests for inspector from v2

features/kinesis/step_definitions/kinesis.js
N/A
* integ tests for kinesis from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @kinesis
```
=> feat: integ tests for kinesis from v2

features/kms/step_definitions/kms.js
N/A
* integ tests for kms from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @kms
```
=> feat: integ tests for kms from v2

features/ssm/step_definitions/ssm.js
N/A
* integ tests for ssm from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @ssm
```
=> feat: integ tests for ssm from v2

features/storagegateway/step_definitions/storagegateway.js
N/A
* integ tests for storagegateway from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @storagegateway
```
=> feat: integ tests for storagegateway from v2

features/support/step_definitions/support.js
N/A
* integ tests for support from v2
```console
AWS_PROFILE=<profileName-with-premium-support> yarn integ-test --tags @support
```
=> feat: integ tests for support from v2

features/swf/step_definitions/swf.js
N/A
* integ tests for swf from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @swf
```
=> feat: integ tests for swf from v2

features/workspaces/step_definitions/workspaces.js
N/A
* integ tests for workspaces from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @workspaces
```
=> feat: integ tests for workspaces from v2

features/route53domains/step_definitions/route53domains.js
N/A
* integ tests for route53domains from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @route53domains
```
=> feat: integ tests for route53domains from v2

features/devicefarm/step_definitions/devicefarm.js
N/A
* integ tests for device-farm from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @devicefarm
```
=> feat: integ tests for device-farm from v2

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddStreamHasherDependency.java
fixes generated streamHasher type in ClientDefaults
=> fix: streamHasher type

features/cognitoidentity/step_definitions/cognitoidentity.js, packages/protocol-json-rpc/src/JsonRpcParser.ts
N/A
* integ tests for cognitoidentity from v2
```console
AWS_PROFILE=<profileName> yarn integ-test --tags @cognitoidentity
```
=> feat: integ tests for cognitoidentity from v2

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java
=> fix: fix build error when recursively call regionInfoProvider

buildspec.yml, codecov.yml
* Fixes: https://github.com/aws/aws-sdk-js-v3/issues/589
* Refs: https://github.com/aws/aws-sdk-js-v3/issues/585
* add `yarn test:all` in buildspec.yml
* add CodeCov token to codecov.yml
* CodeCov FAQ https://docs.codecov.io/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found
=> chore: add `yarn test:all` in buildspec.yml

packages/middleware-operation-logging/src/index.spec.ts, packages/middleware-operation-logging/src/index.ts
REfs: https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-569869880
fix: issues with middleware-operation-logging
=> fix: issues with middleware-operation-logging

packages/middleware-apply-body-checksum/src/index.ts
Refs: https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-570064686
fix: Cannot find module './md5configuration'
=> fix: Cannot find module './md5configuration'

codegen/smithy-aws-typescript-codegen/build.gradle.kts
=> chore: update smithy-codegen-core dep to 0.9.6

clients/client-api-gateway/package.json
Refs: https://github.com/aws/aws-sdk-js-v3/issues/617
manually update version number for client-api-gateway
=> chore: update version number for client-api-gateway

.github/ISSUE_TEMPLATE/---bug-report.md
Updates the issue template for bug report : adds a bug report label automatically 
=> chore: update ---bug-report.md

.github/ISSUE_TEMPLATE/---feature-request.md
Updates the issue template for feature-request : adds a feature-request label automatically
=> chore: update ---feature-request.md

package.json
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/630
add clients/* for lint-staged
=> chore: add clients/* for lint-staged

packages/middleware-sdk-api-gateway/package.json
=> fix: add protocol-http dependency to APIG middleware

packages/s3-request-presigner/.gitignore, packages/s3-request-presigner/.npmignore, packages/s3-request-presigner/CHANGELOG.md, packages/s3-request-presigner/LICENSE, packages/s3-request-presigner/README.md, packages/s3-request-presigner/jest.config.js, packages/s3-request-presigner/package.json, packages/s3-request-presigner/src/constants.ts, packages/s3-request-presigner/src/index.spec.ts, packages/s3-request-presigner/src/index.ts, packages/s3-request-presigner/tsconfig.json, packages/s3-request-presigner/tsconfig.test.json, packages/util-create-request/jest.config.js, packages/util-create-request/package.json, packages/util-create-request/src/foo.fixture.ts, packages/util-create-request/src/index.spec.ts, packages/util-create-request/src/index.ts, yarn.lock
Update 2 packages according to new interface, 2 packages needs to be updated to support s3 presigner:
* s3-request-presigner
* util-create-request
=> feat: update s3 presigner

packages/config-resolver/package.json, packages/middleware-bucket-endpoint/package.json, packages/middleware-sdk-machinelearning/package.json, packages/node-http-handler/package.json
N/A
add/remove protocol-http as a dependency in packages
=> chore: add/remove protocol-http as a dependency

clients/client-api-gateway/models/index.ts
fixes awslabs/smithy-typescript#82
=> fix: api-gateway client model comment

buildspec.yml
=> chore: update CI to test all packages

packages/response-metadata-extractor/package.json, packages/response-metadata-extractor/src/index.spec.ts, packages/response-metadata-extractor/src/index.ts
=> fix(response-metadata-extractor): update HttpResponse

package.json
=> chore: test dependency packages in CI

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
=> fix: dataSource for JSON RPC document deser

scripts/generate-clients/code-gen-dir.js, scripts/generate-clients/code-gen.js, scripts/generate-clients/code-prettify.js, scripts/generate-clients/copy-to-clients.js, scripts/generate-clients/index.js, scripts/generate-clients/spawn-process.js
Refs: https://github.com/aws/aws-sdk-js-v3/issues/698
* prettifying code in generate-clients
* this will reduce the number of files passed in lint-staged after CodeGen is run
=> feat: prettify code in generate-clients

packages/credential-provider-cognito-identity/.gitignore, packages/credential-provider-cognito-identity/.npmignore, packages/credential-provider-cognito-identity/CHANGELOG.md, packages/credential-provider-cognito-identity/LICENSE, packages/credential-provider-cognito-identity/README.md, packages/credential-provider-cognito-identity/jest.config.js, packages/credential-provider-cognito-identity/package.json, packages/credential-provider-cognito-identity/src/CognitoProviderParameters.ts, packages/credential-provider-cognito-identity/src/InMemoryStorage.spec.ts, packages/credential-provider-cognito-identity/src/InMemoryStorage.ts, packages/credential-provider-cognito-identity/src/IndexedDbStorage.spec.ts, packages/credential-provider-cognito-identity/src/IndexedDbStorage.ts, packages/credential-provider-cognito-identity/src/Logins.ts, packages/credential-provider-cognito-identity/src/Storage.ts, packages/credential-provider-cognito-identity/src/fromCognitoIdentity.spec.ts, packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts, packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.spec.ts, packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.ts, packages/credential-provider-cognito-identity/src/index.ts, packages/credential-provider-cognito-identity/src/localStorage-inmemoryStorage.spec.ts, packages/credential-provider-cognito-identity/src/localStorage.spec.ts, packages/credential-provider-cognito-identity/src/localStorage.ts, packages/credential-provider-cognito-identity/src/resolveLogins.spec.ts, packages/credential-provider-cognito-identity/src/resolveLogins.ts, packages/credential-provider-cognito-identity/tsconfig.json, packages/credential-provider-cognito-identity/tsconfig.test.json, yarn.lock
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/593
re-add credential-provider-cognito-identity, as `@aws-sdk/client-cognito-identity@alpha` is now released
=> chore: re-add credential-provider-cognito-identity

clients/client-api-gateway/APIGatewayClient.ts, packages/middleware-sdk-api-gateway/src/index.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/685
codegen with accept header changes
=> chore: codegen with accept header changes

buildspec.yml
Refs: https://github.com/aws/aws-sdk-js-v3/pull/590
* pass token while calling CodeCov
* CodeCov FAQ: https://docs.codecov.io/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found
=> chore: pass token while calling CodeCov

packages/middleware-sdk-machinelearning/src/predict-endpoint.spec.ts, packages/middleware-sdk-machinelearning/src/predict-endpoint.ts
Fixes test to cover using correct PredictEndpoint input
=> fix: test to cover correct input

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java, packages/middleware-sdk-sqs/.gitignore, packages/middleware-sdk-sqs/.npmignore, packages/middleware-sdk-sqs/CHANGELOG.md, packages/middleware-sdk-sqs/LICENSE, packages/middleware-sdk-sqs/README.md, packages/middleware-sdk-sqs/jest.config.js, packages/middleware-sdk-sqs/package.json, packages/middleware-sdk-sqs/src/configurations.ts, packages/middleware-sdk-sqs/src/index.ts, packages/middleware-sdk-sqs/src/receive-message.ts, packages/middleware-sdk-sqs/src/receive-messages.spec.ts, packages/middleware-sdk-sqs/src/send-message-batch.spec.ts, packages/middleware-sdk-sqs/src/send-message-batch.ts, packages/middleware-sdk-sqs/src/send-message.spec.ts, packages/middleware-sdk-sqs/src/send-message.ts, packages/middleware-sdk-sqs/tsconfig.json, packages/middleware-sdk-sqs/tsconfig.test.json
Migrates and applies message validation middleware for SQS clients
=> feat: sqs md5 validation middleware

clients/client-sqs/commands/ReceiveMessageCommand.ts, clients/client-sqs/commands/SendMessageBatchCommand.ts, clients/client-sqs/commands/SendMessageCommand.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/719
codegen with middleware-sdk-sqs
=> chore: codegen with middleware-sdk-sqs

packages/sha256-tree-hash/.gitignore, packages/sha256-tree-hash/.npmignore, packages/sha256-tree-hash/CHANGELOG.md, packages/sha256-tree-hash/LICENSE, packages/sha256-tree-hash/README.md, packages/sha256-tree-hash/jest.config.js, packages/sha256-tree-hash/package.json, packages/sha256-tree-hash/src/index.spec.ts, packages/sha256-tree-hash/src/index.ts, packages/sha256-tree-hash/tsconfig.json, packages/sha256-tree-hash/tsconfig.test.json
Adds sha256-tree-hash package to smithy-codegen branch
=> feat: add sha256-tree-hash pkg

scripts/generate-clients/copy-to-clients.js
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/778
* codegen for clients with long names (ones which have more than two words)
* Verified fix in commit https://github.com/aws/aws-sdk-js-v3/pull/777/commits/893ea1953126aef78575d450e261ae184930e5bc
=> fix: codegen for clients with long names

clients/client-auto-scaling/protocols/Aws_query.ts, clients/client-cloudformation/protocols/Aws_query.ts, clients/client-cloudsearch/protocols/Aws_query.ts, clients/client-cloudwatch/protocols/Aws_query.ts, clients/client-docdb/protocols/Aws_query.ts, clients/client-elastic-beanstalk/protocols/Aws_query.ts, clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts, clients/client-elastic-load-balancing/protocols/Aws_query.ts, clients/client-elasticache/protocols/Aws_query.ts, clients/client-iam/protocols/Aws_query.ts, clients/client-neptune/protocols/Aws_query.ts, clients/client-rds/protocols/Aws_query.ts, clients/client-redshift/protocols/Aws_query.ts, clients/client-route-53/protocols/Aws_restXml.ts, clients/client-s3-control/protocols/Aws_restXml.ts, clients/client-s3/protocols/Aws_restXml.ts, clients/client-ses/protocols/Aws_query.ts, clients/client-sns/protocols/Aws_query.ts, clients/client-sqs/protocols/Aws_query.ts, clients/client-sts/protocols/Aws_query.ts
refs: https://github.com/aws/aws-sdk-js-v3/pull/791
codegen for fixes in query clients
=> chore: codegen for fixes in query clients

clients/client-sqs/package.json
Adds missing middleware-depdendency
Fixes: #798
=> fix: add missing middleware dep

models/accessanalyzer.2019-11-01.json, models/codeguruprofiler.2019-07-18.json, models/iot-1click-devices-service.2018-05-14.json, models/iot-data-plane.2015-05-28.json, models/workmail.2017-10-01.json
This adds in a handful of previously missing services.
=> chore: Update models

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
=> fix: JSON RPC operation path generation

clients/client-api-gateway/protocols/Aws_restJson1_1.ts, clients/client-appconfig/protocols/Aws_restJson1_1.ts, clients/client-cloudfront/protocols/Aws_restXml.ts, clients/client-ebs/protocols/Aws_restJson1_1.ts, clients/client-glacier/protocols/Aws_restJson1_1.ts, clients/client-kinesis-video-archived-media/protocols/Aws_restJson1_1.ts, clients/client-kinesis-video-media/protocols/Aws_restJson1_1.ts, clients/client-lambda/protocols/Aws_restJson1_1.ts, clients/client-lex-model-building-service/protocols/Aws_restJson1_1.ts, clients/client-lex-runtime-service/protocols/Aws_restJson1_1.ts, clients/client-mediastore-data/protocols/Aws_restJson1_1.ts, clients/client-mobile/protocols/Aws_restJson1_1.ts, clients/client-networkmanager/protocols/Aws_restJson1_1.ts, clients/client-polly/protocols/Aws_restJson1_1.ts, clients/client-route-53/protocols/Aws_restXml.ts, clients/client-s3/protocols/Aws_restXml.ts, clients/client-sagemaker-runtime/protocols/Aws_restJson1_1.ts
Refs: https://github.com/awslabs/smithy-typescript/pull/114
codegen for use lowercased header name
=> chore: codegen for use lowercased header name

packages/body-checksum-browser/package.json, packages/body-checksum-node/package.json
=> fix: add missing dependencies for body checksum packages

codegen/README.md
Refs: https://github.com/aws/aws-sdk-js-v3/issues/832#issuecomment-581615735
add troubleshooting section for codegen
=> docs: add troubleshooting section for codegen

clients/client-glacier/package.json
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/849
add missing dependencies in client-glacier
=> fix: add missing dependencies in client-glacier

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java, packages/middleware-sdk-cognito-identity/.gitignore, packages/middleware-sdk-cognito-identity/.npmignore, packages/middleware-sdk-cognito-identity/LICENSE, packages/middleware-sdk-cognito-identity/README.md, packages/middleware-sdk-cognito-identity/jest.config.js, packages/middleware-sdk-cognito-identity/package.json, packages/middleware-sdk-cognito-identity/src/index.ts, packages/middleware-sdk-cognito-identity/src/removeAuthPlugin.spec.ts, packages/middleware-sdk-cognito-identity/src/removeAuthPlugin.ts, packages/middleware-sdk-cognito-identity/tsconfig.json
=> feat: allow making cognito identity request without credentials

clients/client-cognito-identity/commands/GetCredentialsForIdentityCommand.ts, clients/client-cognito-identity/commands/GetIdCommand.ts, clients/client-cognito-identity/commands/GetOpenIdTokenCommand.ts, clients/client-cognito-identity/package.json, clients/client-cognito-identity/runtimeConfig.browser.ts, clients/client-cognito-identity/runtimeConfig.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/853
codegen for cognito identity request without credentials
=> chore: codegen for cognito identity request without credentials

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
=> fix: exclude other clients from cognito identity customization

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
=> fix: JSON stringify structure/union payloads

scripts/generate-clients/copy-to-clients.js
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/904
fixes typo in CodeGen
=> fix: typo in CodeGen

scripts/generate-clients/copy-to-clients.js
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/908
* append newline at package.json EoF
* verified that package.json output is same as that formatted by prettier
=> fix: append newline at package.json EoF

clients/client-auto-scaling/protocols/Aws_query.ts, clients/client-cloudformation/protocols/Aws_query.ts, clients/client-cloudfront/protocols/Aws_restXml.ts, clients/client-cloudsearch/protocols/Aws_query.ts, clients/client-cloudwatch/protocols/Aws_query.ts, clients/client-docdb/protocols/Aws_query.ts, clients/client-ec2/protocols/Aws_ec2.ts, clients/client-elastic-beanstalk/protocols/Aws_query.ts, clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts, clients/client-elastic-load-balancing/protocols/Aws_query.ts, clients/client-elasticache/protocols/Aws_query.ts, clients/client-iam/protocols/Aws_query.ts, clients/client-neptune/protocols/Aws_query.ts, clients/client-rds/protocols/Aws_query.ts, clients/client-redshift/protocols/Aws_query.ts, clients/client-route-53/protocols/Aws_restXml.ts, clients/client-s3-control/protocols/Aws_restXml.ts, clients/client-s3/protocols/Aws_restXml.ts, clients/client-ses/protocols/Aws_query.ts, clients/client-sns/protocols/Aws_query.ts, clients/client-sqs/protocols/Aws_query.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/885
codegen for return empty instead of undefined
=> chore: codegen for return empty instead of undefined

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
=> fix: early return on empty xml tag

clients/client-cloudfront/protocols/Aws_restXml.ts, clients/client-route-53/protocols/Aws_restXml.ts, clients/client-s3-control/protocols/Aws_restXml.ts
Codegen for https://github.com/awslabs/smithy-typescript/pull/139
Fixes Rest XML error responses being returned without messages
=> chore: codegen to apply error members

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
=> fix: empty xml tag handling for Set shapes

clients/client-cloudsearch/protocols/Aws_query.ts, clients/client-cloudwatch/protocols/Aws_query.ts, clients/client-elastic-load-balancing-v2/protocols/Aws_query.ts, clients/client-iam/protocols/Aws_query.ts, clients/client-s3-control/protocols/Aws_restXml.ts, clients/client-ses/protocols/Aws_query.ts, clients/client-sns/protocols/Aws_query.ts, clients/client-sqs/protocols/Aws_query.ts
Codegen that corresponds to change in https://github.com/aws/aws-sdk-js-v3/pull/965
=> chore: xml map deser codegen

clients/client-kinesis/runtimeConfig.rn.ts, clients/client-s3/runtimeConfig.rn.ts, clients/client-transcribe-streaming/runtimeConfig.rn.ts
Codegen for https://github.com/awslabs/smithy-typescript/pull/143
Fixes #994 
=> fix: eventstream config throws in RN

packages/signature-v4/src/SignatureV4.spec.ts, packages/signature-v4/src/SignatureV4.ts, packages/types/src/signature.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1011
Update EventSigner signature API from signEvent to sign
=> feat(signature-v4): update EventSigner signature API to sign

packages/middleware-sdk-machinelearning/.npmignore, packages/middleware-sdk-s3-control/.npmignore, packages/middleware-sdk-s3/.npmignore
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/762
add *.tsbuildinfo to .npmignore
=> chore: add *.tsbuildinfo to .npmignore

features/s3/step_definitions/objects.js, packages/middleware-sdk-ec2/src/index.ts, packages/middleware-sdk-rds/src/index.ts, packages/s3-request-presigner/README.md, packages/s3-request-presigner/src/index.spec.ts, packages/s3-request-presigner/src/index.ts, packages/signature-v4/src/SignatureV4.spec.ts, packages/signature-v4/src/SignatureV4.ts, packages/types/src/signature.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1012
Rename presignRequest API to presign
=> feat(signature-v4): rename presignRequest API to presign

README.md
Refs: https://github.com/aws/aws-sdk-js-v3/issues/677
Update README with info about beta
=> chore: update README with info about beta

clients/client-s3-control/protocols/Aws_restXml.ts
refs: https://github.com/aws/aws-sdk-js-v3/pull/1052
CodeGen for https://github.com/aws/aws-sdk-js-v3/pull/1052
=> chore: codegen for protocol test fixes

packages/smithy-client/src/extended-encode-uri-component.ts
=> fix: Do not use + for spaces in encoding

features/extra/cleanup.js
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1068
clean s3 buckets after integration test is run
=> fix: clean s3 buckets after integration test is run

clients/client-kinesis/KinesisClient.ts, clients/client-s3/S3Client.ts, clients/client-transcribe-streaming/TranscribeStreamingClient.ts
Ref: https://github.com/awslabs/smithy-typescript/pull/157
=> docs: fix doc for event stream serde provider

features/dynamodb/step_definitions/dynamodb.js
N/A
* creates table with AutoScaling in integ tests, as required by internal policy
* Verified that dynamodb integration tests are successful
```console
$ yarn test:integration --tags @dynamodb
$ cucumber-js --tags @dynamodb
...............................
6 scenarios (6 passed)
19 steps (19 passed)
0m15.203s
Done in 17.18s.
```
=> chore: create table with AutoScaling in integ tests

package.json
N/A
This was missed in https://github.com/aws/aws-sdk-js-v3/pull/1110
=> chore: update version to 1.0.0-beta.4

codegen/protocol-test-codegen/build.gradle.kts, codegen/protocol-test-codegen/smithy-build.json, scripts/generate-clients/code-gen-dir.js, scripts/generate-clients/code-gen.js, scripts/generate-clients/code-prettify.js, scripts/generate-clients/copy-to-clients.js, scripts/generate-clients/index.js
N/A
* This PR adds support to update protocol_tests when generate-clients is run
* This PR also updates protocol_tests package names to match that of folders
* The existing update to protocol_tests was done in PR https://github.com/aws/aws-sdk-js-v3/pull/1143
=> feat: update protocol_tests when generate-clients is run

clients/client-app-mesh/models/index.ts, clients/client-groundstation/models/index.ts, clients/client-kinesis/models/index.ts, clients/client-rds-data/models/index.ts, clients/client-s3/models/index.ts, clients/client-transcribe-streaming/models/index.ts
Refs: https://github.com/awslabs/smithy-typescript/pull/173
CodeGen to convert visit method to an arrow function
=> chore: convert visit method to an arrow function

README.md
*Issue #, if available:* N/A
A single ampersand runs the first script in the background rather than chaining them together.
=> docs: fix yarn install command in README

protocol_tests/aws-restjson/tests/functional/aws_rest_json_1_1.spec.ts, protocol_tests/aws-restxml/tests/functional/aws_rest_xml.spec.ts
* Missed in https://github.com/aws/aws-sdk-js-v3/pull/1144
* Caught in https://github.com/aws/aws-sdk-js-v3/pull/1169
Update array to SetShape in protocol_tests
=> fix: update array to SetShape in protocol_tests

clients/client-codecommit/protocols/Aws_json1_1.ts, clients/client-ec2/protocols/Aws_ec2.ts, clients/client-service-catalog/protocols/Aws_json1_1.ts
Was added by mistake in #1161
fix formatting missed by prettier
=> chore: fix formatting missed by prettier

clients/client-cloudfront/protocols/Aws_restXml.ts, clients/client-route-53/protocols/Aws_restXml.ts, clients/client-s3-control/protocols/Aws_restXml.ts, clients/client-s3/protocols/Aws_restXml.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java, protocol_tests/aws-restxml/protocols/Aws_restXml.ts
Similar to https://github.com/aws/aws-sdk-js-v3/pull/1153
remove variables from xml serializeCollection
* Simple list:
* Before:
```typescript
const serializeAws_restXmlAliasList = (
input: string[],
): any => {
const collectedNodes: any = [];
for (let entry of input) {
const node = new __XmlNode("string").addChildNode(new __XmlText(entry));
collectedNodes.push(node.withName("CNAME"));
}
return collectedNodes;
};
```
* After:
```typescript
const serializeAws_restXmlAliasList = (
input: string[],
): any => {
return input.map(entry => {
const node = new __XmlNode("string").addChildNode(new __XmlText(entry));
return node.withName("CNAME");
});
};
```
* nested lists:
* Before
```typescript
const …
```
=> chore: remove variables from xml serializeCollection

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java, protocol_tests/aws-restxml/protocols/Aws_restXml.ts
N/A
remove redundant return from xml serialize
=> chore: remove redundant return from xml serialize

README.md
=> docs: update readme for using a lock file

packages/eventstream-handler-node/src/EventStreamPayloadHandler.spec.ts
=> test(eventstream-handler-node): fix test broken in Node14

.gitignore, clients/client-app-mesh/protocols/Aws_restJson1_1.ts, clients/client-groundstation/protocols/Aws_restJson1_1.ts, clients/client-rds-data/protocols/Aws_restJson1_1.ts, clients/client-transcribe-streaming/protocols/Aws_restJson1_1.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
=> fix: JSON Union serialization issue

yarn.lock
Clean up yarn lock, originated from https://github.com/aws/aws-sdk-js-v3/pull/1230
=> fix(yarn lock): clean up yarn lock file

clients/client-kinesis/runtimeConfig.native.ts, clients/client-s3/runtimeConfig.native.ts
https://github.com/awslabs/smithy-typescript/pull/182
=> feat: codegen enabling eventstream serde in RN

packages/middleware-retry/src/delayDecider.spec.ts, packages/middleware-retry/src/delayDecider.ts
N/A
updated tests for delayDecider while working on new retry behavior
=> test: update tests for delayDecider

clients/client-dynamodb/DynamoDB.ts, clients/client-dynamodb/models/index.ts, clients/client-dynamodb/protocols/Aws_json1_0.ts, clients/client-rds/RDS.ts, clients/client-rds/models/index.ts, clients/client-rds/protocols/Aws_query.ts, codegen/sdk-codegen/aws-models/dynamodb.2012-08-10.json, codegen/sdk-codegen/aws-models/rds.2014-10-31.json
This PR also includes a commit for codegen based on these models.
Fixes #1260
=> chore: update service models

packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.ts
Done as part of IMDS v2 in JS-1802
adds arrow functions in ImdsCredentials.ts
=> chore(credential-provider-imds): arrow fn in ImdsCredentials

packages/credential-provider-imds/src/remoteProvider/retry.spec.ts, packages/credential-provider-imds/src/remoteProvider/retry.ts
Done as part of IMDS v2 in JS-1802
update tests for retry
=> test(credential-provider-imds): update tests for retry

.github/workflows/stale_issues.yml
Adding workflow for stale action
=> feat: add stale action workflow

clients/client-transcribe-streaming/README.md
@trivikr @alexforsyth This is the README draft. Thank you guys for proofreading it. ❤️
=> docs(client-transcribe-streaming): add readme

packages/config-resolver/src/EndpointsConfig.spec.ts, packages/config-resolver/src/EndpointsConfig.ts, packages/config-resolver/src/RegionConfig.spec.ts, packages/config-resolver/src/RegionConfig.ts
Internal issue JS-1834
simplifies and add tests for config-resolver
=> feat: simplify and add extensive tests got config-resolver

features/elbv2/step_definitions/elbv2.js
=> test: fix import for elbv2 integ test

packages/util-arn-parser/.gitignore, packages/util-arn-parser/.npmignore, packages/util-arn-parser/LICENSE, packages/util-arn-parser/README.md, packages/util-arn-parser/jest.config.js, packages/util-arn-parser/package.json, packages/util-arn-parser/src/index.spec.ts, packages/util-arn-parser/src/index.ts, packages/util-arn-parser/tsconfig.cjs.json, packages/util-arn-parser/tsconfig.es.json
Migrate the [ARN parser](https://github.com/aws/aws-sdk-js/blob/c2ad3ef8fd486bb58edc225f74152dda51f9f2fe/lib/util.js#L981-L982) from V2 to V3
=> feat(util-arn-parser): add a general purpose ARN parser

clients/client-app-mesh/models/index.ts, clients/client-groundstation/models/index.ts, clients/client-kinesis/models/index.ts, clients/client-rds-data/models/index.ts, clients/client-s3/models/index.ts, clients/client-transcribe-streaming/models/index.ts
Refs: awslabs/smithy-typescript#190
adds filterSensitiveLog for Union types
=> feat: add filterSensitiveLog for Union types

codegen/sdk-codegen/aws-models/accessanalyzer.2019-11-01.json, codegen/sdk-codegen/aws-models/app-mesh.2019-01-25.json, codegen/sdk-codegen/aws-models/braket.2019.09.01.json
Cleanup on select deployed models.
=> feat: update select smithy models

scripts/generate-clients/copy-to-clients.js
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1483
Verified that new pagination files were generated in [`3060cb4` (#1481)](https://github.com/aws/aws-sdk-js-v3/pull/1481/commits/3060cb463c16330209778a1a31dc8436f49a5992)
=> fix(codegen): add pagination folder in overwritablePathnames

packages/client-documentation-generator/src/sdk-client-source-update.ts, packages/credential-provider-imds/src/remoteProvider/httpRequest.spec.ts, packages/credential-provider-ini/src/index.spec.ts, packages/credential-provider-process/src/index.spec.ts, packages/fetch-http-handler/src/fetch-http-handler.spec.ts, packages/fetch-http-handler/src/index.spec.ts, packages/node-http-handler/src/index.spec.ts, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts, packages/shared-ini-file-loader/src/index.spec.ts, packages/util-user-agent-node/src/index.spec.ts, packages/util-user-agent-node/src/index.ts, packages/xml-builder/src/index.spec.ts, tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1512
sets esModuleInterop to true in packages
=> chore: set esModuleInterop to true in packages

packages/middleware-logger/src/loggerMiddleware.spec.ts
Tests weren't added to meet deadline for gamma.8 release in https://github.com/aws/aws-sdk-js-v3/pull/1478
add tests for loggerMiddleware
=> test: add tests for loggerMiddleware

codegen/sdk-codegen/aws-models/codeguruprofiler.2019-07-18.json
=> fix: update CodeGuruProfiler event source

packages/util-dynamodb/.npmignore
follow up to https://github.com/aws/aws-sdk-js-v3/pull/1462
=> chore(util-dynamodb): publish src to npm

packages/is-array-buffer/src/index.ts
The package was examined while fixing unit tests in: https://github.com/aws/aws-sdk-js-v3/pull/1562
chore(is-array-buffer): convert to arrow functions
=> chore(is-array-buffer): convert to arrow functions

packages/util-utf8-browser/src/index.ts, packages/util-utf8-browser/src/pureJs.ts, packages/util-utf8-node/src/index.ts
The package was examined while fixing unit tests in: #1562
chore(util-utf8-*): convert to arrow functions
=> chore(util-utf8-*): convert to arrow functions

lib/storage/README.md
N/A
fix(storage): add version and downloads badges
=> fix(storage): add version and downloads badges

CODE_OF_CONDUCT.md
N/A
Adds Code of Conduct from workshop repo: https://github.com/aws-samples/aws-sdk-js-v3-workshop/blob/master/CODE_OF_CONDUCT.md
=> chore(docs): add Code Of Conduct

clients/client-s3/S3.spec.ts
Because the issue with our CI/CD script, the unit doesn't fail even the unit test fails. We will fix it shortly later. 
This change fixes a failed unit test.
=> test(client-s3): fix unit test

packages/middleware-logger/package.json, packages/middleware-logger/src/loggerMiddleware.spec.ts, packages/middleware-logger/src/loggerMiddleware.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1521
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1522
fix: log requestId, extendedRequestId, cfId in metadata
=> fix: log requestId, extendedRequestId, cfId in metadata

clients/client-transcribe-streaming/README.md
=> docs(client-transcribe-streaming): update readme

README.md
Fix a syntactical typo in a code snippet in the readme
=> fix(readme): close comment in a code snippet

packages/service-error-classification/src/constants.ts
Noticed while debugging https://github.com/aws/aws-sdk-js-v3/issues/1196
chore(service-error-classification): alphabetically order THROTTLING_ERROR_CODES
=> chore(service-error-classification): alphabetically order THROTTLING_ERROR_CODES

packages/fetch-http-handler/src/fetch-http-handler.ts, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-handler.ts
Noticed while working on https://github.com/aws/aws-sdk-js-v3/issues/1695
* Updates Options name to match that of class.
* Creates new private variables in class to store options values instead of entire object.
=> chore(handler): update Options name to match that of class

packages/s3-request-presigner/README.md
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1063
=> docs(s3-request-presigner): update readme

clients/client-s3/protocols/Aws_restXml.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java
=> fix(client-s3): fix union serialization

packages/shared-ini-file-loader/src/index.spec.ts, packages/shared-ini-file-loader/src/index.ts
=> fix(shared-ini-file-loader): ignore prohibited profile name

codegen/sdk-codegen/aws-models/s3.2006-03-01.json, codegen/smithy-aws-typescript-codegen/build.gradle.kts
=> fix: remove some s3 waiters

.github/ISSUE_TEMPLATE/---bug-report.md
Refs: https://github.com/aws/aws-sdk-js/blob/master/.github/ISSUE_TEMPLATE/---bug-report.md
Use bug and needs-triage labels for GitHub issue bug report template
=> chore(docs): use bug and needs-triage labels

lib/storage/src/data-chunk/readable-helper.ts
**Issue**
Fixes #1728 (#1828)
In `lib-storage`'s helper for chunking a `stream.Readable`, remove event listeners at the end of `_chunkFromStream()`. This prevents memory leaks caused by streaming the data to a growing number of variables as the function runs on longer files.
To verify, I used the example file upload script and uploaded a ~75MB file to S3 while debugging free memory. Before this patch, Node crashed with ~500MB left; afterwards, it finished and never dipped below 2GB free.
=> fix(lib-storage): cleanup stream listeners to prevent memory leak

packages/middleware-user-agent/src/user-agent-middleware.ts
previously the middleware was added relative(before) signing middleware.
It will throw for the requests not requiring singing. So change it
to absolute position.
=> fix(middleware-user-agent): add middleware to final step of build

README.md
=> chore(readme): add useful links from GA blog post

packages/eventstream-handler-node/README.md, packages/eventstream-serde-browser/README.md, packages/eventstream-serde-config-resolver/README.md, packages/eventstream-serde-node/README.md, packages/eventstream-serde-universal/README.md, packages/invalid-dependency/README.md, packages/middleware-host-header/README.md, packages/middleware-sdk-machinelearning/README.md, packages/middleware-sdk-s3-control/README.md, packages/middleware-sdk-s3/README.md, packages/middleware-sdk-sqs/README.md, packages/middleware-sdk-transcribe-streaming/README.md, packages/middleware-serde/README.md, packages/middleware-user-agent/README.md, packages/protocol-http/README.md, packages/smithy-client/README.md
N/A
fix(readme): remove duplicate @aws-sdk
<details>
</details>
<details>
</details>
=> fix(readme): remove duplicate @aws-sdk

packages/eventstream-handler-node/README.md, packages/eventstream-serde-browser/README.md, packages/eventstream-serde-config-resolver/README.md, packages/eventstream-serde-node/README.md, packages/eventstream-serde-universal/README.md, packages/invalid-dependency/README.md, packages/karma-credential-loader/README.md, packages/middleware-eventstream/README.md, packages/middleware-host-header/README.md, packages/middleware-sdk-machinelearning/README.md, packages/middleware-sdk-s3-control/README.md, packages/middleware-sdk-s3/README.md, packages/middleware-sdk-sqs/README.md, packages/middleware-sdk-transcribe-streaming/README.md, packages/middleware-serde/README.md, packages/middleware-user-agent/README.md, packages/polly-request-presigner/README.md, packages/protocol-http/README.md, packages/smithy-client/README.md
N/A
use latest in npm version tag
<details>
</details>
<details>
</details>
=> fix(readme): use latest in npm version tag

features/glacier/step_definitions/glacier.js
=> test(glacier): fix broken cucumber test

.github/pull_request_template.md
N/A
Adds a new PR template for the repository requesting testing and additional context section.
<details>
<summary>Existing template</summary>
</details>
<details>
<summary>New template</summary>
</details>
=> chore: add testing and context in PR template

packages/util-dynamodb/src/convertToAttr.spec.ts, packages/util-dynamodb/src/convertToAttr.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1861
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1980
This PR supports marshalling for objects created through [Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create)
Unit tests for Object.create, and class with inheritance.
---
=> feat(util-dynamodb): support marshalling for Object.create

.github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/--documentation.md, .github/pull_request_template.md
N/A
fixes typos in issues/PR templates;
* Adds missing newlines.
* Removes # from title
Files were viewed on Markdown on GitHub.
---
=> chore(docs): fix typos in issues/PR templates

packages/credential-provider-node/src/index.ts
Fixes typo in JSDoc : functino -> function
N/A
---
=> docs(credentials-provider-node): fix param JSDoc typo

README.md
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2046
adds link to notes-app in README
---
=> docs(readme): add link to notes-app

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBodyChecksumGeneratorDependency.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java
N/A
Removes unused logger from files, ensuring that following warning is not shown.
<details>
<summary>Warning</summary>
</details>
---
=> chore(codegen): remove unused logger from files

packages/credential-provider-node/package.json
Remove duplicated and out-of-date dependency
---
=> chore(credential-provider-node): remove ini loader dev dep

packages/util-user-agent-browser/src/index.ts
=> chore(util-user-agent-browser): fix typo

.vscode/extensions.json
it is helpful to have VSCode installing these extensions when start a new workspace.
---
=> chore: add eslint vscode extension recommandation

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
=> Serialize rest json error code header

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegration.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegration.java
These integrations do not generate useful output when client generation is disabled.
Local generation of SSDK and client.
---
=> chore: short-circuit ssdk-incompatible integrations

packages/s3-presigned-post/src/createPresignedPost.ts
*Issue #, if available:* N/A
*Description of changes:* Change empty object type to `Fields` in the `PresignedPost` interface.
=> fix(s3-presigned-post): type PresignedPost.fields

CONTRIBUTING.md
=> docs(contributing): guidance building single package

clients/client-amp/AmpClient.ts, clients/client-fis/FisClient.ts, clients/client-greengrassv2/GreengrassV2Client.ts, clients/client-iot-wireless/IoTWirelessClient.ts, clients/client-iotdeviceadvisor/IotDeviceAdvisorClient.ts, clients/client-iotfleethub/IoTFleetHubClient.ts, clients/client-lex-models-v2/LexModelsV2Client.ts, clients/client-lex-runtime-v2/LexRuntimeV2Client.ts, clients/client-location/LocationClient.ts, clients/client-lookoutequipment/LookoutEquipmentClient.ts, clients/client-lookoutmetrics/LookoutMetricsClient.ts, clients/client-mgn/MgnClient.ts, clients/client-mwaa/MWAAClient.ts, clients/client-wellarchitected/WellArchitectedClient.ts
This is a follow up to #2270 for the newly generated clients
---
=> docs(clients): update clients input and resolved config to interface

packages/middleware-apply-body-checksum/src/applyMd5BodyChecksumMiddleware.spec.ts, packages/middleware-apply-body-checksum/src/applyMd5BodyChecksumMiddleware.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2644#issuecomment-893606585
Uses lowercase name for content-md5 header to fix the following protocol test failure:
```console
344 | FAIL protocol_tests/aws-restjson/tests/functional/restjson1.spec.ts (26.65 s)
345 | ● RestJsonHttpChecksumRequired:Request
346 |  
347 | expect(received).toBeDefined()
348 |  
349 | Received: undefined
350 |  
351 | 1918 \|     expect(r.path).toBe("/HttpChecksumRequired");
352 | 1919 \|
353 | > 1920 \|     expect(r.headers["content-md5"]).toBeDefined();
354 | \|                                      ^
355 | 1921 \|     expect(r.headers["content-md5"]).toBe("iB0/3YSo7maijL0IGOgA9g==");
356 | 1922 \|     expect(r.headers["content-type"]).toBeDefined();
357 | 1923 \| …
```
=> fix(middleware-apply-body-checksum): use lowercase content-md5 header

tests/e2e/run-e2e-tests.js
Fix e2e test failure when no package changed since last release
---
=> test(e2e): fix test fail when no package changes

packages/middleware-signing/src/middleware.spec.ts, packages/middleware-signing/src/middleware.ts, packages/middleware-signing/src/utils/getSkewCorrectedDate.spec.ts, packages/middleware-signing/src/utils/getSkewCorrectedDate.ts, packages/middleware-signing/src/utils/getUpdatedSystemClockOffset.spec.ts, packages/middleware-signing/src/utils/getUpdatedSystemClockOffset.ts, packages/middleware-signing/src/utils/isClockSkewed.spec.ts, packages/middleware-signing/src/utils/isClockSkewed.ts
Refs: https://github.com/aws/aws-sdk-js-v3/issues/2208
Refactors middleware-signing to modular functions.
CI
---
=> chore(middleware-signing): refactor middleware to modular functions

clients/client-iot-data-plane/endpoints.ts, clients/client-iot/endpoints.ts, codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/endpoints.json
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2398
Endpoints were updated in https://github.com/aws/aws-sdk-js-v3/pull/2674 too
Update endpoint resolution as of 08/16/2021
---
=> feat(clients): update endpoint resolution as of 08/16/2021

packages/smithy-client/src/date-utils.ts
https://github.com/aws/aws-sdk-js-v3/issues/2977
https://github.com/aws/aws-sdk-js-v3/issues/2866
A babel plugin is altering regexes with named capturing groups in such a way that renders them invalid.
Locally in an amplify app, and with unit tests.
---
=> fix(smithy-client): remove capturing groups from date regex

packages/signature-v4-crt/README.md
=> doc(signature-v4-crt): notify this package is node.js only

packages/karma-credential-loader/package.json
Fixes https://github.com/aws/aws-sdk-js-v3/pull/2959
Mark internal test utility package as private.
---
=> feat(karma-credential-loader): mark package as private

clients/client-dynamodb-streams/src/endpoints.ts, clients/client-kms/src/endpoints.ts, codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/endpoints.json, tests/functional/endpoints/test_cases_supported.json
Subset of PR https://github.com/aws/aws-sdk-js-v3/pull/3039
This PR will be made ready after https://github.com/aws/aws-sdk-js-v3/pull/3044 is merged.
Updates endpoints as of 11/18/2021
Functional testing
---
=> chore(clients): update endpoints as of 11/18/2021

typedoc.client.json
Removes exclusion of explicit test files
The client tests are now in test folder, and it is excluded in tsconfig.json
---
=> chore(typedoc): remove exclusion of test folder

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java
Internal JS-3014
Fixes the issue with endpoint generation in https://github.com/aws/aws-sdk-js-v3/pull/3163
Skips empty variants with tags
Verified that CI will be successful when endpoints are regenerated in WIP PR https://github.com/aws/aws-sdk-js-v3/pull/3169
---
=> fix(codegen): skip variants which only contains tags

clients/client-auto-scaling/src/protocols/Aws_query.ts, clients/client-cloudformation/src/protocols/Aws_query.ts, clients/client-cloudfront/src/protocols/Aws_restXml.ts, clients/client-cloudsearch/src/protocols/Aws_query.ts, clients/client-cloudwatch/src/protocols/Aws_query.ts, clients/client-cognito-identity-provider/src/protocols/Aws_json1_1.ts, clients/client-docdb/src/protocols/Aws_query.ts, clients/client-elastic-beanstalk/src/protocols/Aws_query.ts, clients/client-elastic-load-balancing-v2/src/protocols/Aws_query.ts, clients/client-elastic-load-balancing/src/protocols/Aws_query.ts, clients/client-elasticache/src/protocols/Aws_query.ts, clients/client-iam/src/protocols/Aws_query.ts, clients/client-kms/src/protocols/Aws_json1_1.ts, clients/client-memorydb/src/protocols/Aws_json1_1.ts, clients/client-neptune/src/protocols/Aws_query.ts, clients/client-organizations/src/protocols/Aws_json1_1.ts, clients/client-rds/src/protocols/Aws_query.ts, clients/client-redshift/src/protocols/Aws_query.ts, clients/client-route-53/src/protocols/Aws_restXml.ts, clients/client-service-quotas/src/protocols/Aws_json1_1.ts, clients/client-ses/src/protocols/Aws_query.ts, clients/client-sns/src/protocols/Aws_query.ts, clients/client-sqs/src/protocols/Aws_query.ts, clients/client-sts/src/protocols/Aws_query.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java, private/aws-protocoltests-query/src/protocols/Aws_query.ts, private/aws-protocoltests-query/test/functional/awsquery.spec.ts
Internal JS-2681
smithy-ts: https://github.com/awslabs/smithy-typescript/pull/489
Similar to: https://github.com/aws/aws-sdk-go-v2/pull/1283
Adds support for awsQueryError trait
Protocol tests are successful
---
=> feat: Support awsQueryError trait

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DefaultsModeConfigGenerator.java
Unblock codegen-ci/java 8 CI test
---
=> chore(format): fix java checkstyle

lib/lib-storage/package.json, packages/credential-provider-web-identity/package.json
Noticed during attempt to yarn to 3.1.1 in https://github.com/aws/aws-sdk-js-v3/pull/3235
Sorts browser entries
N/A
---
=> chore(package.json): sort browser entries

codegen/CHANGELOG.md, codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts
This builds locally, but will not pass CI until https://github.com/awslabs/smithy-typescript/pull/507 is merged
---
=> chore(codegen): bump to 0.9.0

package.json
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3300
This manual update is required till the issue is fixed in release automation. Follow-up being tracked in JS-3106
Manually update version to `v3.51.0` to unblock next release
---
=> fix(package.json): update version to v3.51.0

private/aws-protocoltests-restjson/src/models/models_0.ts, private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts
The protocol tests update was missed in https://github.com/aws/aws-sdk-js-v3/pull/3288
CI
---
=> chore(protocoltests): update post smithy 1.17.x bump

package.json
Internal JS-2896
Sets root version to `0.0.0` 
Setting the current version was failing, and required manual updates:
* https://github.com/aws/aws-sdk-js-v3/pull/3315
* https://github.com/aws/aws-sdk-js-v3/pull/3300
We read global version from `lerna.json`, so setting the version in root package.json is not required.
Verified that `yarn lerna:version` works correctly after setting root package.json to `0.0.0`
<details>
<summary>yarn lerna:version</summary>
```console
$ yarn lerna:version
yarn lerna:version        
$ lerna version --exact --conventional-commits --no-push --no-git-tag-version --no-commit-hooks --loglevel silent --yes
Changes:
- @aws-sdk/client-accessanalyzer: 3.51.0 => 3.52.0
- @aws-sdk/client-account: 3.51.0 => 3.52.0
- @aws-sdk/client-acm-pca: 3.51.0 => …
```
=> fix(package.json): set root version to 0.0.0

clients/client-s3/test/flexibleChecksums.spec.ts
Internal JS-3102
Adds integration tests for flexible checksums
Tested in https://github.com/aws/private-aws-sdk-js-v3/pull/106
This PR will be rebased after clients are updated on 02/24
---
=> test(client-s3): integration tests for flexible checksums

README.md, packages/middleware-sdk-s3/src/S3SignatureV4.ts
Add a section describing the SDK features requiring optional dependency on `aws-crt`.
---
=> docs(README): update installing crt error message

packages/middleware-sdk-s3/package.json, packages/signature-v4-crt/package.json, yarn.lock
=> chore(signature-v4-crt): bump aws-crt version to 1.12.1

CHANGELOG.md, clients/client-docdb/CHANGELOG.md, clients/client-eventbridge/CHANGELOG.md, clients/client-personalize/CHANGELOG.md, clients/client-pi/CHANGELOG.md, clients/client-sagemaker/CHANGELOG.md
=> docs: update changelogs from release 3.66.0

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/doc-client-utils.ts
The CD pipeline blocks due to generated code for lib-dynamodb is updated in #3539 but the code generator is no updated accrodingly. This change synchronizes them.
In the long term, we should add a comment on each generated file to prevent from PR updating them.
---
=> chore(codegen): update codegen for lib-dynamodb to reflect #3539

clients/client-transcribe-streaming/README.md, scripts/generate-clients/copy-to-clients.js
Provide hand-written example for transcribe streaming. It was overwritten earlier by the client generator.
---
=> docs(transcribe-streaming): update README

packages/shared-ini-file-loader/src/parseIni.ts
Improve the ini file parsing behavior. This does not change the functionality, and is covered by existing unit tests.
Existing unit tests.
related: https://github.com/aws/aws-sdk-js/pull/4125
=> fix(shared-ini-file-loader): update ini parsing

UPGRADING.md
Update the UPGRADE.md. Now all the missing client configurations AND subclasses from v2 SDK have been implemented v3 SDK.
---
=> docs: add delivered features in UPGRADING.md

packages/polly-request-presigner/README.md
=> docs(polly-request-presigner): update NPM badge

package.json, yarn.lock
Bump lerna to 5.1.4
Confirmed the CI/CD pipeline completes successfully.
---
=> chore(deps-dev): bump lerna to 5.1.4

package.json, yarn.lock
=> chore(deps-dev): bump @mixer/parallel-prettier to 2.0.3

clients/client-s3/karma.conf.js, clients/client-s3/test/e2e/S3.ispec.ts, clients/client-s3/test/e2e/helpers.ts, package.json, yarn.lock
Browser E2E test and bundler benchmark test
---
=> chore(deps-dev): bump webpack dependencies

package.json, yarn.lock
=> chore(deps-dev): bump cucumber to 6.0.7

package.json, yarn.lock
=> chore(deps-dev): bump commitlint to 17.0.2

package.json, yarn.lock
=> chore(deps-dev): remove unused codecov dep

clients/client-appsync/src/models/models_0.ts, clients/client-appsync/src/protocols/Aws_restJson1.ts, codegen/sdk-codegen/aws-models/appsync.json
internal
fix appsync URLs
None
=> fix(client-appsync): fix domainnames routes

clients/client-emr-containers/src/protocols/Aws_restJson1.ts, codegen/sdk-codegen/aws-models/emr-containers.json
aws-models/pull/789
Update the Date shape's timestampFormat trait
---
=> feat(client-emr-containers): set timestampFormat for Date

clients/client-billingconductor/src/protocols/Aws_restJson1.ts, clients/client-chime-sdk-media-pipelines/src/protocols/Aws_restJson1.ts, clients/client-connectcampaigns/src/protocols/Aws_restJson1.ts, clients/client-emr-serverless/src/protocols/Aws_restJson1.ts, clients/client-gamesparks/src/protocols/Aws_restJson1.ts, clients/client-ivschat/src/protocols/Aws_restJson1.ts, clients/client-keyspaces/src/protocols/Aws_json1_0.ts, clients/client-m2/src/protocols/Aws_restJson1.ts, clients/client-pinpoint-sms-voice-v2/src/protocols/Aws_json1_0.ts, clients/client-redshift-serverless/src/protocols/Aws_json1_1.ts, clients/client-rolesanywhere/src/protocols/Aws_restJson1.ts
Updates following https://github.com/aws/aws-sdk-js-v3/pull/3371
Update codegen from old PR.
n/a
=> chore(codegen): update codegen after merging PR 3371

clients/client-lex-runtime-v2/src/protocols/Aws_restJson1.ts, clients/client-s3/src/protocols/Aws_restXml.ts, clients/client-s3/test/e2e/S3.ispec.ts, clients/client-transcribe-streaming/src/protocols/Aws_restJson1.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
Related to https://github.com/awslabs/smithy-typescript/pull/572
Codegen for code generator change from upstream
* Integration Test: S3 & Transcribe-Streaming
* Manual integration test: Lex-runtime-v2
---
=> chore(clients): refactor eventstream code generation

packages/util-endpoints/src/resolveEndpoint.ts, packages/util-endpoints/src/utils/evaluateCondition.ts, packages/util-endpoints/src/utils/evaluateRules.ts, packages/util-endpoints/src/utils/evaluateTemplate.ts
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3884
Post updates to dynamic endpoint resolver which weren't take up as author was on vacation
ToDo
---
=> chore(util-endpoints): updates to dynamic endpoint resolver

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java, private/aws-protocoltests-json-10/test/functional/awsjson1_0.spec.ts
Internal JS-2681
Skips Json10WithQueryCompatibleGreetingError protocol test
N/A
---
=> test(aws-protocoltests-json-10): skip Json10WithQueryCompatibleGreetingError

packages/shared-ini-file-loader/package.json
=> chore(shared-ini-file-loader): move @aws-sdk/types to runtime dep

packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts, packages/middleware-endpoint/src/integration-tests/integration.spec.ts, packages/middleware-endpoint/src/integration-tests/s3/generated-tests.json, packages/middleware-endpoint/src/integration-tests/s3/o.json, packages/middleware-endpoint/src/integration-tests/s3/oa.json, packages/middleware-endpoint/src/integration-tests/s3/ol.json, packages/middleware-endpoint/src/integration-tests/s3/s.json, packages/middleware-endpoint/src/service-customizations/s3.ts, packages/util-endpoints/src/resolveEndpoint.ts
- additional fixes for endpoints 2.0 based on S3 tests
=> fix(endpoint): misc endpoints 2.0 fixes for s3

tests/endpoints-2.0/endpoints-integration.spec.ts
Internal JS-3668
Compares href of URL object created from expected URL.
Verified endpoints-2.0 tests are successful
```console
$ endpoints-2.0> npx jest
...
Tests:       75 skipped, 21961 passed, 22036 total
Time:        39.958 s
```
---
=> test(endpoints): compare href of URL object from expected url string

clients/client-s3-control/test/S3Control.spec.ts
internal P73764220
- temporarily skip failing tests while a fix is being worked on
yarn test in s3-control
=> fix(endpoint): s3 control tests to unblock CI

packages/types/src/logger.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4102
Adds trace function to logger
N/A
---
=> chore(types): add trace function to logger

packages/util-endpoints/src/lib/aws/partitions.json
mirror https://github.com/awslabs/smithy/pull/1487
Updates partitions.json manually while we haven't implemented automation around it yet.
none
=> chore(util-endpoints): update partitions.json

private/aws-protocoltests-ec2/src/endpoints.ts, private/aws-protocoltests-json-10/src/endpoints.ts, private/aws-protocoltests-json/src/endpoints.ts, private/aws-protocoltests-query/src/endpoints.ts, private/aws-protocoltests-restjson/src/endpoints.ts, private/aws-protocoltests-restxml/src/endpoints.ts
Noticed internally that endpoints.ts was not updated for protocoltests.
Update endpoints.ts for protocoltests while a fix is being worked on in our release code
CI
---
=> chore(aws-protocoltests): update endpoints.ts

packages/middleware-token/jest.config.js, packages/middleware-token/package.json, packages/middleware-token/src/configurations.ts, packages/middleware-token/src/resolveTokenConfig.spec.ts, packages/middleware-token/src/resolveTokenConfig.ts, packages/middleware-token/src/tokenDefaultProvider.browser.spec.ts, packages/middleware-token/src/tokenDefaultProvider.browser.ts, packages/middleware-token/src/tokenDefaultProvider.spec.ts, packages/middleware-token/src/tokenDefaultProvider.ts
Internal JS-3873
Adds tokenDefaultProvider
Unit testing in CI
---
=> chore(middleware-token): add tokenDefaultProvider

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTokenAuthPlugin.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsTraitsUtils.java, codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
Internal JS-3873
Adds TokenAuthPlugin which adds Token config and middleware when HttpBearerAuthTrait trait is set
Done in JS-3873
---
=> feat(codegen): add TokenAuthPlugin

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
=> fix(codegen): remove unused import

private/aws-client-retry-test/src/ClientRetryTest.spec.ts
confirmed with original author:
> The current and new implementation can yield delays of less than the base of 100.
new implementation: https://github.com/aws/aws-sdk-js-v3/blob/a2579b770d929ad038cafed565028608a20dd911/packages/util-retry/src/defaultRetryBackoffStrategy.ts#L8-L10
> existing: https://github.com/aws/aws-sdk-js-v3/blob/a2579b770d929ad038cafed565028608a20dd911/packages/middleware-retry/src/delayDecider.ts#L7
=> fix(aws-client-retry-test): correct retry delay assertion

clients/client-marketplace-entitlement-service/src/models/models_0.ts, clients/client-marketplace-entitlement-service/src/protocols/Aws_json1_1.ts, codegen/sdk-codegen/aws-models/marketplace-entitlement-service.json
https://github.com/aws/aws-sdk-js-v3/issues/3029
after internal discussion with the service team, we will be releasing a model update to prevent the expectUnion error from happening
codegen and CI
=> fix(client-marketplace-entitlement-service): update model to fix expectUnion error

packages/middleware-flexible-checksums/package.json, packages/util-utf8/src/toUint8Array.spec.ts
fix(util-utf8): add missing dependency in middleware-flexible-checksums
---
=> fix(util-utf8): add missing dependency in middleware-flexible-checksums

features/s3/step_definitions/objects.js
=> chore(e2e): fix feature test util-utf8

packages/signature-v4-crt/package.json, yarn.lock
Internal JS-4005
Bump aws-crt to ^1.15.9
CI
---
=> chore(deps-dev): bump aws-crt to ^1.15.9

features/cloudfront/cloudfront.feature, features/ec2/ec2.feature, features/elb/elb.feature, features/opsworks/opsworks.feature, features/rds/rds.feature, features/s3/objects.feature, features/storagegateway/storagegateway.feature
=> test: remove error message `to be` checks

features/cloudfront/cloudfront.feature
=> test(cloudfront): remove status code 404 error check

codegen/CHANGELOG.md, codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts
N/A.
ump code generator versions to 0.14.0.
Note: CI expected to fail until awslabs/smithy-typescript#691 is merged.
See this commit on a personal branch to see CI passing: https://github.com/syall/aws-sdk-js-v3/commit/1349dde339efcf5e5cddaefb7b49671f8c1a73ab.
N/A.
---
=> feat(codegen): bump codegen version to 0.14.0

packages/types/src/dns.ts
N/A.
Updates a comment on `HostResolver.resolveAddress` to be more accurate.
N/A.
Part of the `util-dns` work.
---
=> chore(types): update comment on HostResolver.resolveAddress

README.md
n/a
Add some Node.js version history to readme.
=> docs(readme): add Node.js version information

clients/client-application-auto-scaling/src/commands/DeleteScheduledActionCommand.ts, clients/client-application-auto-scaling/src/commands/DescribeScheduledActionsCommand.ts, clients/client-application-auto-scaling/src/commands/ListTagsForResourceCommand.ts, clients/client-application-auto-scaling/src/commands/PutScheduledActionCommand.ts, clients/client-application-auto-scaling/src/commands/TagResourceCommand.ts, clients/client-application-auto-scaling/src/commands/UntagResourceCommand.ts
=> chore(client-application-auto-scaling): update examples

packages/core-theme-documentation-generator/src/theme.tsx
Fix identified accessibility issues in Api Reference theming.
`yarn build:docs` and manual accessibility testing
---
=> docs(a11y): improve api reference accessibility

packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-connection-manager.ts, packages/node-http-handler/src/node-http2-connection-pool.ts, packages/node-http-handler/src/node-http2-handler.spec.ts, packages/node-http-handler/src/node-http2-handler.ts, packages/types/src/connection/config.ts, packages/types/src/connection/manager.ts, packages/types/src/connection/pool.ts, packages/types/src/http.ts, packages/types/src/transfer.ts
Implement new connections pool and manager interfaces
yarn test:all
---
=> feat(node-http-handler): implement connections pool and manager interfaces

packages/core-theme-documentation-generator/src/theme.tsx
Fix for issues found in accessibility audit
`yarn build:docs`
---
=> docs(a11y): fix audited issues

packages/core-theme-documentation-generator/src/theme.tsx
A11y audit
Improve the screen reader experience for the "Jump to content" feature
`yarn build:docs`
---
=> docs(fix): screen reader experience for jump-to-content

packages/credential-providers/README.md
fix missing quote in fromSSO example code
n/a
Just fixes a comment in a code example
My linter doesn't complain any more
---
=> Update README.md - fix missing quote in fromSSO

private/aws-util-test/src/requests/test-http-handler.spec.ts
CI is having trouble running this test because of the build dependency on a private client
=> test(aws-util-test): disable private test

packages/core-theme-documentation-generator/src/theme.tsx
Add a banner announcing the preview of the new api reference docs
`yarn build:all && yarn build:docs`
---
=> docs(preview): add developer preview banner

README.md
Add preview link to README
---
=> docs(preview): add preview to README

clients/client-kinesis/test/Kinesis.e2e.spec.ts
=> test(client-kinesis): skip e2e test for CI

packages/middleware-sdk-sqs/src/middleware-sdk-sqs.integ.spec.ts
=> test(middleware-sdk-sqs): use mock credential in test

packages/middleware-serde/package.json, packages/middleware-serde/src/middleware-serde.integ.spec.ts, packages/middleware-signing/package.json, packages/middleware-signing/src/middleware-signing.integ.spec.ts, packages/middleware-ssec/package.json, packages/middleware-ssec/src/middleware-ssec.integ.spec.ts, packages/middleware-stack/package.json, packages/middleware-token/package.json, packages/middleware-token/src/middleware-token.integ.spec.ts, packages/middleware-user-agent/package.json, packages/middleware-user-agent/src/middleware-user-agent.integ.spec.ts, packages/middleware-websocket/package.json, packages/middleware-websocket/src/middleware-websocket.integ.spec.ts
previous part: https://github.com/aws/aws-sdk-js-v3/pull/4686
=> test(middleware): add request integration tests to middleware, part 3

.gitignore, CONTRIBUTING.md, codegen/settings.gradle.kts
Add gradle composite build
Validate local dependency changes are included automatically when `local.properties` exists
---
=> feat(composite-build): add gradle composite build

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/validation/UnaryFunctionCall.java
Fixes access modifier for UnaryFunctionCall class
---
=> fix(codegen): fix UnaryFunctionCall access

private/aws-restjson-server/src/protocols/Aws_restJson1.ts
N/A
This is the codegen PR for https://github.com/awslabs/smithy-typescript/pull/764.
yarn generate-clients && yarn test:protocols
---
=> fix(codegen): do not trim query params in request output

api-extractor.lib.json, lib/lib-dynamodb/api-extractor.json, lib/lib-dynamodb/package.json, lib/lib-storage/api-extractor.json, lib/lib-storage/package.json
Add api-extractor files to `lib/*`
`yarn lerna run --scope "@aws-sdk/lib-*" build`
---
=> docs(lib): add api-extractor to lib-dynamodb and lib-storage

features/ec2/step_definitions/ec2.js, packages/middleware-sdk-ec2/src/middleware-sdk-ec2.integ.spec.ts
n/a
increase timeout for ec2 e2e tests and add one test case in integration
ran these tests
=> test(client-ec2): increase timeout in ec2 tests and add isob test case

packages/middleware-sdk-ec2/src/middleware-sdk-ec2.integ.spec.ts
avoid DNS lookup of the isob domain
=> test: skip dns lookup

packages/util-user-agent-browser/src/index.native.spec.ts, packages/util-user-agent-browser/src/index.native.ts, packages/util-user-agent-browser/src/index.spec.ts, packages/util-user-agent-browser/src/index.ts, packages/util-user-agent-node/src/index.spec.ts, packages/util-user-agent-node/src/index.ts
Requested after changing ua 2.0 changes:
* https://github.com/aws/aws-sdk-js-v3/pull/4778
* https://github.com/aws/aws-sdk-js-v3/pull/4784
Add ua 2.0 metadata
CI
---
=> chore(util-user-agent): add ua 2.0 metadata

packages/middleware-websocket/src/websocket-fetch-handler.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4806
breakout of https://github.com/aws/aws-sdk-js-v3/pull/4813
=> fix(middleware-websocket): move event listener functions outside of async iterator

clients/client-auto-scaling/package.json, clients/client-cloudformation/package.json, clients/client-cloudfront/package.json, clients/client-cloudsearch/package.json, clients/client-cloudwatch/package.json, clients/client-docdb/package.json, clients/client-ec2/package.json, clients/client-elastic-beanstalk/package.json, clients/client-elastic-load-balancing-v2/package.json, clients/client-elastic-load-balancing/package.json, clients/client-elasticache/package.json, clients/client-iam/package.json, clients/client-neptune/package.json, clients/client-rds/package.json, clients/client-redshift/package.json, clients/client-route-53/package.json, clients/client-s3-control/package.json, clients/client-s3/package.json, clients/client-ses/package.json, clients/client-sns/package.json, clients/client-sqs/package.json, clients/client-sts/package.json, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java, private/aws-protocoltests-ec2/package.json, private/aws-protocoltests-query/package.json, private/aws-protocoltests-restxml/package.json, yarn.lock
https://github.com/aws/aws-sdk-js-v3/issues/4870
=> chore(deps): bump fast-xml-parser to 4.2.5

codegen/CHANGELOG.md
This PR updates the codegen changelog to reflect the real release date.
---
=> chore(codegen): update codegen changelog

README.md
n/a
fix link in readme
manually
=> docs: fix link in root readme

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
Fix file line length that is causing CI check to fail.
Fixes https://github.com/aws/aws-sdk-js-v3/pull/4986
---
=> fix(codegen): fix line length

UPGRADING.md, clients/client-lex-runtime-service/test/LexRuntimeService.spec.ts, clients/client-mediastore-data/test/MediaStoreData.spec.ts, clients/client-s3/src/runtimeConfig.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java, packages/middleware-flexible-checksums/src/stringHasher.spec.ts, tests/endpoints-2.0/endpoints-integration.spec.ts, tests/endpoints-2.0/integration-test-types.ts, yarn.lock
This PR updates some import statements for packages that have been migrated to https://github.com/awslabs/smithy-typescript and the @smithy scope.
---
=> fix(packages): fix migrated package imports

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DefaultsModeConfigGenerator.java
=> fix(codegen): remove defaults mode provider codegen

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DefaultsModeConfigGenerator.java
This codegen was temporarily commented out. This PR uncomments the code, but leaves it disabled so that imports can be left in place.
See https://github.com/aws/aws-sdk-js-v3/pull/4993
---
=> fix(codegen): temporarily disable unused codegen

package.json
run version consistency check on pre-commit
=> chore: commit hook for version lint

packages/token-providers/README.md, packages/token-providers/package.json, packages/token-providers/scripts/esbuild.js, packages/token-providers/src/bundle/client-sso-oidc-browser.ts, packages/token-providers/src/bundle/client-sso-oidc-node.ts, packages/token-providers/src/getNewSsoOidcToken.spec.ts, packages/token-providers/src/getNewSsoOidcToken.ts, packages/token-providers/src/getSsoOidcClient.spec.ts, packages/token-providers/src/getSsoOidcClient.ts, packages/token-providers/src/index.ts
fixes https://github.com/aws/aws-sdk-js-v3/issues/5056
use a static version of the client sso oidc bundle, instead of trying to generate it at build time.
=> fix(token-providers): use static version of bundled sso oidc client

features/ec2/step_definitions/ec2.js
Internal JS-4645
increasing timeout in EC2 snapshot test
local integration testing succeeded
command: `yarn test:e2e:legacy -t @ec2`
---
=> test(client-ec2): increase timeout in ec2 tests

codegen/gradle.properties, private/aws-protocoltests-ec2/src/models/models_0.ts, private/aws-protocoltests-ec2/src/protocols/Aws_ec2.ts, private/aws-protocoltests-ec2/test/functional/ec2query.spec.ts, private/aws-protocoltests-json/src/models/models_0.ts, private/aws-protocoltests-json/src/protocols/Aws_json1_1.ts, private/aws-protocoltests-json/test/functional/awsjson1_1.spec.ts, private/aws-protocoltests-query/src/models/models_0.ts, private/aws-protocoltests-query/src/protocols/Aws_query.ts, private/aws-protocoltests-query/test/functional/awsquery.spec.ts, private/aws-protocoltests-restjson/src/models/models_0.ts, private/aws-protocoltests-restjson/src/protocols/Aws_restJson1.ts, private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts, private/aws-protocoltests-restxml/src/models/models_0.ts, private/aws-protocoltests-restxml/src/protocols/Aws_restXml.ts, private/aws-protocoltests-restxml/test/functional/restxml.spec.ts, private/aws-restjson-server/src/models/models_0.ts, private/aws-restjson-server/src/protocols/Aws_restJson1.ts, private/aws-restjson-server/test/functional/restjson1.spec.ts, private/aws-restjson-validation-server/test/functional/restjson1.spec.ts, scripts/generate-clients/config.js
N/A.
Upgrade to Smithy 1.37.0.
Ran `yarn generate-clients -g codegen/sdk-codegen/aws-models/sts.json && yarn test:protocols && yarn test:server-protocols`.
See: https://github.com/awslabs/smithy-typescript/pull/906
---
=> chore(codegen): upgrade to Smithy 1.37.0

packages/region-config-resolver/api-extractor.json
Internal JS-4687
Adds the `api-extractor.json` for the region-config-resolver-package
---
=> chore(region-config-resolver): add api-extractor.json to the package

clients/client-s3/test/e2e/S3.ispec.ts
The test is failing with 
```
TypeError: Failed to fetch
```
With the 1MB test object. Reducing it allows the test to pass.
=> test: fix s3 ispec putObject

codegen/CHANGELOG.md, codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts
This reverts commit c51bd48b4a35a4e806d44fea5a1c95a108908bf3.
=> Revert "feat(codegen): bump codegen version to 0.18.0 (#5310)"

.github/ISSUE_TEMPLATE/bug-report.yml
=> chore: update bug-report.yml

lib/lib-dynamodb/src/test/lib-dynamodb.e2e.spec.ts
use consistent read in e2e tests for lib-dynamodb
=> test(lib-dynamodb): use consistent read in e2e tests

packages/signature-v4-crt/package.json, yarn.lock
Internal AWSCRT-1266
Bump `aws-crt` to ^1.18.1
CI
---
=> chore(deps-dev): bump aws-crt to ^1.18.1

packages/credential-provider-http/package.json
fixes https://github.com/aws/aws-sdk-js-v3/issues/5362
=> fix(credential-provider-http): add undeclared dependency

package.json, packages/credential-provider-http/package.json, packages/token-providers/package.json, scripts/runtime-dependency-version-check/check-dependencies.js
add a script to check for undeclared dependencies since we haven't decided to switch package managers yet
=> chore: run dependency check on commit hook

CHANGELOG.md, clients/client-quicksight/CHANGELOG.md
Internal V1094202814
Updates changelog for release 3.442.0
N/A
---
=> docs(client-quicksight): update changelog for release 3.442.0

packages/core/package.json
add the tslib dependency to core
=> fix(core): add tslib

packages/cloudfront-signer/package.json, scripts/runtime-dependency-version-check/check-dependencies.js
add tslib in cloudfront and add commit hook check
=> fix(cloudfront-signer): add tslib

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
fix codegen for deserializing unions containing list members
=> fix(codegen): deserialize unions with list members

lib/lib-dynamodb/package.json
=> fix(lib-dynamodb): move smithy devDeps to deps

packages/xml-builder/package.json, packages/xml-builder/src/XmlNode.spec.ts, packages/xml-builder/src/XmlNode.ts
Related:
https://github.com/smithy-lang/smithy-typescript/pull/1107
add additional functions to shorten protocol serde code for XML
added unit tests
=> feat(xml-builder): additional serde helper methods

private/aws-util-test/package.json
N/A.
Add version field to fix a nit warning message about missing a version field.
N/A.
N/A.
---
=> chore(aws-util-test): add version field

.github/ISSUE_TEMPLATE/v2-to-v3-migration.yml
Adding a new issue template targeting migration related issues.
=> chore: add migration issue template for SDK v2 to v3 upgrade

packages/credential-provider-node/src/credential-provider-node.integ.spec.ts
initialize client with a region in integ test
=> test(credential-provider-node): add region to test client

supplemental-docs/AWS_LAMBDA.md
n/a
add doc remarks about AWS Lambda initialization practices
=> docs: add supplemental doc on AWS Lambda usage

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/visitor/MemberDeserVisitor.java
same as https://github.com/smithy-lang/smithy-typescript/pull/1174 but for AWS
generated Lambda, a JSON service, and no diff.
=> chore(codegen): add _json fn import to call site

clients/client-migrationhuborchestrator/package.json
=> chore(client-migrationhuborchestrator): update uuid version

scripts/generate-clients/config.js
=> chore: update smithy for uuid version

scripts/runtime-dependency-version-check/check-dependencies.js
https://github.com/aws/aws-sdk-js-v3/issues/5866
Checks all packages that aren't node libraries, instead of only `@aws-sdk` and `@smithy`.
Catches missing `fast-xml-parser`.
=> chore(build): update dependency validation script

codegen/build.gradle.kts
Updates the codegen package to use the [jreleaser](https://jreleaser.org/) plugin to simplify the release process for releasing a maven artifact.
N/A
Previous update to `smithy-typescript` to use jreleaser for maven releases: https://github.com/smithy-lang/smithy-typescript/pull/1205
- [N/A] If you wrote E2E tests, are they resilient to concurrent I/O?
- [N/A] If adding new public functions, did you add the `@public` tag and enable doc generation on the package?
---
=> chore(codegen): use Jreleaser for maven releases

codegen/CHANGELOG.md, scripts/generate-clients/config.js
chore(codegen): bump version to 0.20.1
---
=> chore(codegen): bump version to 0.20.1

codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts
chore(codegen): update smithy-typescript version in build.gradle.kts
---
=> chore(codegen): update smithy-typescript version in build.gradle.kts

codegen/sdk-codegen/build.gradle.kts
=> chore(codegen): add smoke test model dep

codegen/build.gradle.kts
Checkstyle looks for suppressions based on the configDirectory, which I didn't update when changing the config dir -> gradleConfig.
=> chore(codegen): fix checkstyle config

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
make doc trait optional on s3 expires preprocessModel step
=> fix(codegen): add doc trait conditionally

scripts/generate-clients/config.js
Adopting https://github.com/smithy-lang/smithy-typescript/pull/1249
The code change was manually done in https://github.com/aws/aws-sdk-js-v3/pull/6034
Update smithy-ts commit to update engines to node >= 16
CI
---
=> chore(codegen): update smithy-ts commit to update engines to node >= 16

supplemental-docs/CLIENTS.md
supplemental docs for S3 `followRegionRedirect` option
---
=> docs: followRegionRedirect for S3

clients/client-ec2/src/protocols/Aws_ec2.ts, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/Ec2ShapeSerVisitor.java, codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java, private/aws-protocoltests-ec2/src/protocols/Aws_ec2.ts
follows https://github.com/aws/aws-sdk-js-v3/pull/6117
do not serialize empty lists for EC2 protocol only
protocol tests included in smithyVersion=1.49.0
some prior context:
https://github.com/aws/aws-sdk-js-v3/pull/4003
=> fix(client-ec2): ec2 query no longer serialize empty lists

supplemental-docs/CLIENTS.md
=> docs: fix typo in CLIENTS.md

supplemental-docs/README.md
=> docs: update supplemental root README.md

codegen/CHANGELOG.md
Follow up to #6125 to add the missing change log entries.
=> chore(codegen): bump version to 0.21.0, changlog entries

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AddSTSAuthCustomizations.java
fix for incorrect path for the sts test (codegen -> client copy)
---
=> fix(codegen): fix path for copying sts test file

codegen/protocol-test-codegen/smithy-build.json, private/aws-protocoltests-json-machinelearning/.gitignore, private/aws-protocoltests-json-machinelearning/LICENSE, private/aws-protocoltests-json-machinelearning/README.md, private/aws-protocoltests-json-machinelearning/api-extractor.json, private/aws-protocoltests-json-machinelearning/jest.config.js, private/aws-protocoltests-json-machinelearning/package.json, private/aws-protocoltests-json-machinelearning/src/MachineLearning.ts, private/aws-protocoltests-json-machinelearning/src/MachineLearningClient.ts, private/aws-protocoltests-json-machinelearning/src/auth/httpAuthExtensionConfiguration.ts, private/aws-protocoltests-json-machinelearning/src/auth/httpAuthSchemeProvider.ts, private/aws-protocoltests-json-machinelearning/src/commands/PredictCommand.ts, private/aws-protocoltests-json-machinelearning/src/commands/index.ts, private/aws-protocoltests-json-machinelearning/src/endpoints.ts, private/aws-protocoltests-json-machinelearning/src/extensionConfiguration.ts, private/aws-protocoltests-json-machinelearning/src/index.ts, private/aws-protocoltests-json-machinelearning/src/models/MachineLearningServiceException.ts, private/aws-protocoltests-json-machinelearning/src/models/index.ts, private/aws-protocoltests-json-machinelearning/src/models/models_0.ts, private/aws-protocoltests-json-machinelearning/src/protocols/Aws_json1_1.ts, private/aws-protocoltests-json-machinelearning/src/runtimeConfig.browser.ts, private/aws-protocoltests-json-machinelearning/src/runtimeConfig.native.ts, private/aws-protocoltests-json-machinelearning/src/runtimeConfig.shared.ts, private/aws-protocoltests-json-machinelearning/src/runtimeConfig.ts, private/aws-protocoltests-json-machinelearning/src/runtimeExtensions.ts, private/aws-protocoltests-json-machinelearning/test/functional/awsjson1_1.spec.ts, private/aws-protocoltests-json-machinelearning/tsconfig.cjs.json, private/aws-protocoltests-json-machinelearning/tsconfig.es.json, private/aws-protocoltests-json-machinelearning/tsconfig.json, private/aws-protocoltests-json-machinelearning/tsconfig.types.json
Internal JS-5057
Adds MachineLearning client in RestJson Protocol tests
CI
---
=> test(protocoltests): add MachineLearning client

package.json, yarn.lock
=> chore: update devDependency webpack

scripts/compilation/Inliner.js
n/a
Update Inliner.js for verbosity in build:cjs tasks. 
Also turns off rewriteStubs as we have deprecated deep path imports.
CI, `npx turbo run build`
=> chore(scripts): update Inliner.js script

clients/client-appconfig/src/protocols/Aws_restJson1.ts, clients/client-bedrock-runtime/src/protocols/Aws_restJson1.ts, clients/client-billingconductor/src/protocols/Aws_restJson1.ts, clients/client-cloudsearch-domain/src/protocols/Aws_restJson1.ts, clients/client-codeguruprofiler/src/protocols/Aws_restJson1.ts, clients/client-deadline/src/protocols/Aws_restJson1.ts, clients/client-lex-runtime-service/src/protocols/Aws_restJson1.ts, clients/client-lex-runtime-v2/src/protocols/Aws_restJson1.ts, clients/client-lookoutvision/src/protocols/Aws_restJson1.ts, clients/client-mediapackagev2/src/protocols/Aws_restJson1.ts, clients/client-mediastore-data/src/protocols/Aws_restJson1.ts, clients/client-nimble/src/protocols/Aws_restJson1.ts, clients/client-s3/src/protocols/Aws_restXml.ts, clients/client-sagemaker-runtime/src/protocols/Aws_restJson1.ts, clients/client-tnb/src/protocols/Aws_restJson1.ts, private/aws-protocoltests-restjson/src/protocols/Aws_restJson1.ts, private/aws-restjson-server/src/protocols/Aws_restJson1.ts, scripts/generate-clients/config.js
Codegen for https://github.com/smithy-lang/smithy-typescript/pull/1327
Adds automatic id tokens for header values
CI
---
=> chore(clients): add automatic id tokens for header values

clients/client-sts/src/defaultStsRoleAssumers.ts, clients/client-sts/test/defaultRoleAssumers.spec.ts, codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts, codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts, packages/credential-provider-env/src/fromEnv.spec.ts, packages/credential-provider-env/src/fromEnv.ts, packages/credential-provider-ini/src/resolveStaticCredentials.spec.ts, packages/credential-provider-ini/src/resolveStaticCredentials.ts, packages/credential-provider-process/src/ProcessCredentials.ts, packages/credential-provider-process/src/getValidatedProcessCredentials.spec.ts, packages/credential-provider-process/src/getValidatedProcessCredentials.ts, packages/credential-provider-process/src/resolveProcessCredentials.spec.ts, packages/credential-provider-process/src/resolveProcessCredentials.ts, packages/credential-provider-sso/src/resolveSSOCredentials.spec.ts, packages/credential-provider-sso/src/resolveSSOCredentials.ts
This reverts commit 83cd2537bd6e9bfbd6e6535012c913b017a26bca.
=> chore: revert to 3.618.0

.github/workflows/codegen-ci.yml
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/6436
Runs codegen-ci.yml on self edits
Verified that codegen-ci was run for this PR
---
=> chore(ci): run codegen-ci.yml on self-edits

codegen/CHANGELOG.md
The month was off by 1
N/A
---
=> chore(codegen): Fix 0.22.0 release date

supplemental-docs/ERROR_HANDLING.md
Adds error handling supplemental docs.
=> docs: add ERROR_HANDLING.md supplemental

UPGRADING.md, supplemental-docs/AWS_LAMBDA.md, supplemental-docs/CLIENTS.md, supplemental-docs/README.md, supplemental-docs/performance/README.md, supplemental-docs/performance/parallel-workloads-node-js.md
docs only
- cleans up a few parts of the upgrading doc
- creates new performance docs section about Node.js parallel request performance
=> docs: create new Node.js performance docs section and clean up upgrading docs

codegen/CHANGELOG.md, codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts, scripts/generate-clients/config.js
=> chore(codegen): bump smithy-typescript-codegen version to 0.24

clients/client-s3/src/commands/DeleteObjectCommand.ts, clients/client-s3/src/commands/GetObjectTaggingCommand.ts, clients/client-s3/src/commands/PutObjectCommand.ts, clients/client-s3/src/commands/UploadPartCopyCommand.ts, codegen/gradle.properties, private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts, private/aws-protocoltests-restxml/test/functional/restxml.spec.ts, private/aws-protocoltests-smithy-rpcv2-cbor/src/protocols/Rpcv2cbor.ts, private/aws-protocoltests-smithy-rpcv2-cbor/test/functional/rpcv2cbor.spec.ts, scripts/generate-clients/config.js
https://github.com/smithy-lang/smithy-typescript/pull/1434
Updates smithy to 1.52.0
CI
---
=> chore(codegen): update smithy to 1.52.0

scripts/turbo/index.js
=> test: temporarily ignore turbo error

jest.config.js
=> test: update jest.config.js to remove private folder

packages/middleware-flexible-checksums/src/selectChecksumAlgorithmFunction.spec.ts
update unit test to match behavior of `selectChecksumAlgorithmFunction`
=> test(middleware-flexible-checksums): update selectAlgo unit test

scripts/generate-clients/index.js
Internal JS-5573
set ci env empty
---
=> chore(scripts): set env empty for CI

UPGRADING.md
Internal JS-5597
Uses array/map/set example for removeUndefinedValues
N/A
---
=> docs: use array/map/set example for removeUndefinedValues

lib/lib-dynamodb/README.md, packages/util-dynamodb/src/marshall.ts
add more details to comments on `removeUndefinedValues`
=> docs(lib-dynamodb): add details to description of removeUndefinedValues

packages/util-user-agent-node/src/nodeAppIdConfigOptions.ts
shared config file setting name correction for appId
---
=> fix(util-user-agent-node): appId config file name correction

packages/crt-loader/CHANGELOG.md, packages/crt-loader/LICENSE, packages/crt-loader/README.md, packages/crt-loader/api-extractor.json, packages/crt-loader/package.json, packages/crt-loader/src/index.ts, packages/crt-loader/tsconfig.cjs.json, packages/crt-loader/tsconfig.es.json, packages/crt-loader/tsconfig.types.json, packages/signature-v4-crt/package.json, packages/signature-v4-crt/src/CrtSignerV4.spec.ts, packages/signature-v4-crt/src/CrtSignerV4.ts, packages/signature-v4-crt/src/index.ts, yarn.lock
Internal JS-5396
Adds crt-loader module to load CRT, so that if other modules which are dependent on CRT can be added in future
CI
---
=> chore(crt-loader): add crt-loader

README.md, packages/crc64-nvme-crt/CHANGELOG.md, packages/crc64-nvme-crt/LICENSE, packages/crc64-nvme-crt/README.md, packages/crc64-nvme-crt/api-extractor.json, packages/crc64-nvme-crt/package.json, packages/crc64-nvme-crt/src/CrtCrc64Nvme.spec.ts, packages/crc64-nvme-crt/src/CrtCrc64Nvme.ts, packages/crc64-nvme-crt/src/index.ts, packages/crc64-nvme-crt/tsconfig.cjs.json, packages/crc64-nvme-crt/tsconfig.es.json, packages/crc64-nvme-crt/tsconfig.types.json, packages/crc64-nvme-crt/vitest.config.ts, yarn.lock
Internal JS-5396
Adds a module to help compute CRC64-NVME checksums using AWS CRT
CI
---
=> chore(crc64-nvme-crt): add CrtCrc64Nvme

packages/credential-providers/README.md
=> docs(credential-providers): fix link casing

codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfigTest.java
Fixes unit test in AddAwsRuntimeConfig codegen
=> test(codegen): fix runtimeconfig unit tests

scripts/generate-clients/copy-to-clients.js
update TS version in a template
=> chore(codegen): update template typescript version

scripts/compilation/Inliner.js
secondary issue stated in https://github.com/aws/aws-sdk-js-v3/issues/6816
this fixes import path modifications in the inlining of submodules
added assertions that run during the inliner script
=> fix(nested-clients): fix inliner build script

package.json, yarn.lock
=> chore: bump turbo to 2.3.3

packages/credential-providers/src/fromTemporaryCredentials.browser.ts
minor string change for placeholder commit
=> chore(credential-providers): minor code cleanup

packages/nested-clients/src/index.ts
ensure a change in this package for versioning purposes
=> chore(nested-clients): no-op change to publish new version

scripts/generate-clients/config.js
https://github.com/smithy-lang/smithy-typescript/pull/1526
Updates smithy-ts commit to include unknown union member serialization in CBOR
* CI
* The generated clients are not updated, since none use CBOR.
---
=> chore(codegen): unknown union member serialization in CBOR

scripts/generate-clients/config.js
* Internal JS-5749
* MultiSelect List https://github.com/smithy-lang/smithy-typescript/pull/1536
* Flatten https://github.com/smithy-lang/smithy-typescript/pull/1537
Updates smithy-ts commit to support JMESPath MultiSelect List and Flatten in OperationContextParams
N/A, since the code in existing clients was not updated.
---
=> chore(codegen): support JMESPath MultiSelect List and Flatten in OperationContextParams

codegen/gradle.properties, scripts/generate-clients/config.js
Internal JS-5755
Upgrades smithy version to 1.54.0
CI
=> chore(codegen): upgrade to smithy 1.54.0

supplemental-docs/AWS_LAMBDA.md
add information about creating lambda layers to our AWS Lambda supplemental docs
=> docs: how to create a layer in AWS Lambda

packages/rds-signer/README.md
this fixes a very simple typo.
---
=> docs(rds-signer): fix simple typo

packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.spec.ts
add unit tests for https://github.com/aws/aws-sdk-js-v3/pull/6961
related to https://github.com/aws/aws-sdk-js-v3/issues/6960
=> test(core/httpAuthSchemes): add unit test for sigv4 configResolver

scripts/generate-clients/config.js
Update the commit hash to the latest commit of smithy-typescript
=> chore(codegen): update commit hash

packages/core/src/submodules/httpAuthSchemes/aws_sdk/NODE_AUTH_SCHEME_PREFERENCE_OPTIONS.spec.ts, packages/core/src/submodules/httpAuthSchemes/aws_sdk/NODE_AUTH_SCHEME_PREFERENCE_OPTIONS.ts, packages/core/src/submodules/httpAuthSchemes/aws_sdk/index.ts, packages/core/src/submodules/httpAuthSchemes/utils/getArrayForCommaSeparatedString.spec.ts, packages/core/src/submodules/httpAuthSchemes/utils/getArrayForCommaSeparatedString.ts
Internal JS-5811
Adds Auth Scheme Preference config selector
CI
---
=> chore(core): add Auth Scheme Preference config selector

packages/signature-v4-multi-region/src/eventbridge-sigv4a-put-api.e2e.spec.ts
Internal JS-5884
long-lived resources for events e2e test for sigv4a
```console
✓ src/cloudfront-kvs-sigv4a.e2e.spec.ts (2) 7574ms
✓ src/eventbridge-sigv4a-put-api.e2e.spec.ts (2) 1043ms
Test Files  2 passed (2)
Tests  4 passed (4)
Start at  19:21:04
Duration  8.33s (transform 478ms, setup 0ms, collect 1.01s, tests 8.62s, environment 0ms, prepare 156ms)
```
---
=> test(signature-v4-multi-region): use long-lived resources for sigv4a events test

codegen/gradle.properties, private/aws-restjson-validation-server/test/functional/restjson1.spec.ts, scripts/generate-clients/config.js
Internal JS-5700
Update smithy to 1.57.0
CI
---
=> chore(codegen): upgrade to smithy-1.57.0

scripts/generate-clients/config.js
brings in https://github.com/smithy-lang/smithy-typescript/pull/1585, no codegen changes
=> fix(codegen): allow overwriting protocol priority order

codegen/CHANGELOG.md, codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts, scripts/generate-clients/config.js
=> chore(codegen): bump codegen version to 0.30.0

codegen/CHANGELOG.md, codegen/build.gradle.kts, codegen/smithy-aws-typescript-codegen/build.gradle.kts
paired with https://github.com/smithy-lang/smithy-typescript/pull/1635
=> chore(codegen): bump codegen version to 0.32.0

codegen/gradle.properties, private/aws-protocoltests-restjson-schema/src/schemas/schemas.ts, scripts/generate-clients/config.js
Internal JS-6089
Upgrade smithy to 1.61.0
* CI
* PR will be marked as ready with updated commit when https://github.com/smithy-lang/smithy-typescript/pull/1653 is merged
---
=> chore(codegen): upgrade smithy to 1.61.0

.github/workflows/pull-request-build-yml
Internal JS-6097
This adds a script to trigger automated build workflow when PRs are approved.
Dry run is successful
---
=> chore(ci): integrate build workflow for PRs

.github/workflows/pull-request-build.yml
Sanitize head ref variable.
---
=> fix(ci): Use HEAD_REF variable for branch reference in workflow

codegen/sdk-codegen/aws-models/rekognitionstreaming.json
n/a
removes endpoint tests that are out of date
=> test(rekognitionstreaming): remove outdated endpoint tests

codegen/build.gradle.kts
Internal JS-6279
* Sets duplicatesStrategy to EXCLUDE
* The EXCLUDE strategy was verified in https://github.com/aws/aws-sdk-js-v3/pull/7409#discussion_r2409017532
Internal JS-6279
---
=> chore(codegen): set duplicatesStrategy to EXCLUDE
