packages/eventstream-marshaller/src/Message.ts

Internal JS-3350
Change *HeaderValue from an interface to type
Tested in [TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAEhCGATCAnAavANgVwgHgGkoIAPYCAO0QGcprgUBLCgcwBoo0A+KAXigDeUUJABcUAgG4oANyy5xaaQF9JAKDUjoAIQD2uzAgpwkqDDmj8TydPPwAiAEb7D8CvY7ODRrurUBjXQp6KC9XYwQbcwUoPW83azM7PkE1KGFwCHEnFyMPNNk7cQZcNWUNAHoKqABREkZ6ZhZiMkpqRiDaXQAzKANEKGZyFG74f2gACmwKTEYAaxRMEA5GXrcQAEooAHddbEwB3ZQ5tSHUUfGoADF9AEkKYYvoUnIqWjjwxNsLVPTu-XE9CYrHU5QCnWAUH+umiWWudwe5zGll+GTEUBy8XcbAKcgs4lGmGoEBxfwBGMc8BQ9jKQA)
```js
type HeaderValue<K extends string, V> = { type: K; value: V; };
type BooleanHeaderValue = HeaderValue<"boolean", boolean>;
const booleanHeaderValue: BooleanHeaderValue = {
type: "boolean",
value: true
}
// Existing extensions of old interface (unlikrly, if any) would …
```

chore(eventstream-marshaller): change HeaderValue to type

---

packages/eventstream-serde-browser/package.json
packages/eventstream-serde-browser/src/EventStreamMarshaller.ts
packages/eventstream-serde-node/package.json
packages/eventstream-serde-node/src/EventStreamMarshaller.ts

Internal JS-3350
Removes unused dependency on `@aws-sdk/eventstream-marshaller`
CI
---

chore(eventstream-serde): remove unused eventMarshaller

---

packages/s3-request-presigner/src/getSignedUrl.spec.ts
packages/s3-request-presigner/src/getSignedUrl.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/3672
The original solution will injest a middleware to S3 client to intersect the request to generate a presigned URL. The new solution will create a shallow clone of the input client's middleware stack and use it to generate presigned URL.
Unit test
---

fix(s3-request-presigner): not mutate client middleware stack

---

packages/eventstream-handler-node/package.json
packages/eventstream-handler-node/src/EventSigningStream.spec.ts
packages/eventstream-handler-node/src/EventSigningStream.ts
packages/eventstream-handler-node/src/EventStreamPayloadHandler.spec.ts
packages/eventstream-handler-node/src/EventStreamPayloadHandler.ts
packages/eventstream-serde-universal/package.json
packages/eventstream-serde-universal/src/EventStreamMarshaller.ts
packages/eventstream-serde-universal/src/getUnmarshalledStream.spec.ts
packages/eventstream-serde-universal/src/getUnmarshalledStream.ts

Internal JS-3350
Replaces EventStreamMarshaller imports and usage with new EventStreamCodec
CI
~~This PR will be rebased from main after https://github.com/aws/aws-sdk-js-v3/pull/3747 is merged.~~ Ready!
---

chore: use EventStreamCodec instead of EventStreamMarshaller

---

clients/client-lex-runtime-v2/src/protocols/Aws_restJson1.ts
clients/client-transcribe-streaming/src/protocols/Aws_restJson1.ts

Associated with: https://github.com/awslabs/smithy-typescript/pull/567
Ref: P66766800
Populate the `:content-type` header for all the event messages. It was missed previously. When the payload shape is `blob`, the value is `application/octet-stream`; When the payload shape is `string`, the value is `text/plain`, When the payload shape is `Union` or `Structure`, the value is the protocol's content type.
* Transcribe-streaming
automated integration test
* Lex-runtime-v2
Manual test, automated integration test not added because it relies on other client to spin up resources. Will create follow-up item.
```ts
import { LexRuntimeV2Client, StartConversationCommand } from "@aws-sdk/client-lex-runtime-v2";
const client = new LexRuntimeV2Client({});
const stream = async function* () {
yield { …
```

fix: populate content-type header for all event messages

---

packages/eventstream-handler-node/package.json
packages/eventstream-handler-node/src/EventSigningStream.ts

Came across ToDo which can be implemented as we now support Node.js 12+
Set autoDestroy in EventSigningStream
ToDo
---

chore(eventstream-handler-node): set autoDestroy in EventSigningStream

---

tests/e2e/ensure-test-stack.js

ref: V616675319
The E2E test requires a CFM template including certain resources to be deployed. There was an issue with the deploy script causing changeset to mismatch. This chanage sets the CFM changeset name to be different every time to prevent the mismatch exception
E2E test
---

test(e2e): fix e2e resources stack deployment

---

package.json
yarn.lock

Internal JS-3470
Moves glob and yargs to devDependencies, as they're called from internal scripts
* yargs is called from scripts:
* https://github.com/aws/aws-sdk-js-v3/blob/d90490dadbaa16840d70901e7e84de2472bdb676/scripts/copy-models/index.js#L2
* https://github.com/aws/aws-sdk-js-v3/blob/d90490dadbaa16840d70901e7e84de2472bdb676/scripts/downlevel-dts/index.mjs#L4
* https://github.com/aws/aws-sdk-js-v3/blob/d90490dadbaa16840d70901e7e84de2472bdb676/scripts/generate-clients/index.js#L2
* glob is also called from scripts:
* https://github.com/aws/aws-sdk-js-v3/blob/d90490dadbaa16840d70901e7e84de2472bdb676/scripts/generate-clients/get-model-filepaths.js#L2
Verified that generate-clients script is successful.
```console
$ git status
On branch move-devDeps
Your branch is up to date with …
```

chore(deps-dev): move glob and yargs to devDeps

---

packages/types/src/serde.ts

Add shared types for utilities to runtime-specific stream implementation. It includes transforming stream into byte array, string and web stream. 
---

feat(types): add types to sdk stream utility mixin

---

packages/types/src/eventStream.ts

Internal JS-3350
Adds generic StreamType to EventStreamMarshaller
Integration test on client-transcribe-streaming is successful:
```console
$ client-transcribe-streaming> yarn test:integration
$ jest --config jest.integ.config.js
PASS  test/index.integ.spec.ts (32.259 s)
TranscribeStream client
✓ should stream the transcript (28982 ms)
Tests:       1 passed, 1 total
Time:        32.317 s
Done in 33.61s.
```
~~This PR will be rebased from main after https://github.com/aws/aws-sdk-js-v3/pull/3791 is merged.~~ Ready!
---

chore(types): add generic StreamType to EventStreamMarshaller

---

packages/signature-v4/src/getCanonicalHeaders.spec.ts
packages/signature-v4/src/getCanonicalHeaders.ts

Follow up to: https://github.com/aws/aws-sdk-js-v3/pull/3789
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/3796
Ref: V632120242
For H2 services(Kinesis, Lex, Transcribe Streaming), `":authority": ""` header is required for correct signing. The previous change mistakenly removed this header from the signature. This fix adds it back
Unit test
TODO: find out why Transcribe streaming e2e test didn't catch this error.
---

fix(signature-v4): allow empty string as canonical header value

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts
package.json
packages/fetch-http-handler/src/fetch-http-handler.ts
packages/xhr-http-handler/.gitignore
packages/xhr-http-handler/LICENSE
packages/xhr-http-handler/README.md
packages/xhr-http-handler/jest.config.js
packages/xhr-http-handler/karma.conf.js
packages/xhr-http-handler/package.json
packages/xhr-http-handler/src/index.spec.ts
packages/xhr-http-handler/src/index.ts
packages/xhr-http-handler/src/request-timeout.ts
packages/xhr-http-handler/src/xhr-http-handler.spec.ts
packages/xhr-http-handler/src/xhr-http-handler.ts
packages/xhr-http-handler/tsconfig.cjs.json
packages/xhr-http-handler/tsconfig.es.json
packages/xhr-http-handler/tsconfig.types.json
yarn.lock

Finer upload progress grain (https://github.com/aws/aws-sdk-js-v3/issues/3101)
Adds an XMLHttpRequest http handler. This can be used instead of the fetch handler in certain cases.
Specifically, it gives fine-grained progress updates for single part and multi-part uploads via `lib-storage`'s`Upload`.
Unit tests and manual browser testing with `Upload` from `lib-storage`.
This has only been tested against S3 in browsers.

feat(xhr-http-handler): add XMLHttpRequest http handler to use with lib-storage Upload

---

packages/xhr-http-handler/README.md

n/a
doc only, redundant wording

docs(xhr-http-request): fix redundant wording

---

clients/client-kinesis/src/protocols/Aws_json1_1.ts

Fixes: #2131 
Fixes: #2418 
Related to: https://github.com/awslabs/smithy-typescript/pull/573
Codegen for upstream refactor to support event stream in RPC protocols.
Manual testing: 
```javascript
import {
DescribeStreamCommand,
KinesisClient,
ListStreamConsumersCommand,
RegisterStreamConsumerCommand,
SubscribeToShardCommand,
} from "@aws-sdk/client-kinesis";
const client = new KinesisClient({});
const { StreamDescription } = await client.send(
new DescribeStreamCommand({
StreamName: "test-data-stream",
})
);
const { StreamARN } = StreamDescription;
const { Consumers } = await client.send(
new ListStreamConsumersCommand({
StreamARN,
})
);
console.log(Consumers);
let Consumer = Consumers.find((x) => x.ConsumerName == "tester");
if (Consumer == null) {
const consumerData = await …
```

fix(client-kinesis): support eventstream in subscribeToShard

---

packages/smithy-client/src/date-utils.spec.ts
packages/smithy-client/src/date-utils.ts

Resolves #3813 
The regexp does not handle times with single digit hours
Presently, if a date-time value comes back with a single digit for the hour, the regular expression checks fail throwing back `TypeError: Invalid RFC-7231 date-time value`
By adjusting the regular expression to accept either 1 or 2 length digits for the hour, the checks now pass.
Unit testing
---

fix(smithy-client): rfc-7231 date-time value

---

clients/client-kinesis/src/runtimeConfig.ts
clients/client-lex-runtime-v2/src/runtimeConfig.ts
clients/client-transcribe-streaming/src/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttp2Dependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTranscribeStreamingDependency.java

Fixes #3809 
Currently all the H2 services are affected by #3809. Likely related to event loop issue with H2. This fix will make sure new H2 session is created for each H2 requests. We are already doing it for TranscribeStreaming client.
---

fix(clients): create new session for every H2 requests

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientCommandGenerator.java
lib/lib-dynamodb/README.md
lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.spec.ts
lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.ts
lib/lib-dynamodb/src/commands/BatchExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/BatchGetCommand.ts
lib/lib-dynamodb/src/commands/BatchWriteCommand.ts
lib/lib-dynamodb/src/commands/DeleteCommand.ts
lib/lib-dynamodb/src/commands/ExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/ExecuteTransactionCommand.ts
lib/lib-dynamodb/src/commands/GetCommand.ts
lib/lib-dynamodb/src/commands/PutCommand.ts
lib/lib-dynamodb/src/commands/QueryCommand.ts
lib/lib-dynamodb/src/commands/ScanCommand.ts
lib/lib-dynamodb/src/commands/TransactGetCommand.ts
lib/lib-dynamodb/src/commands/TransactWriteCommand.ts
lib/lib-dynamodb/src/commands/UpdateCommand.ts
lib/lib-dynamodb/src/index.ts
packages/util-dynamodb/src/marshall.ts

revision 2 of https://github.com/aws/aws-sdk-js-v3/pull/3756
https://github.com/aws/aws-sdk-js-v3/issues/3095
current workaround: add middleware to the client instead of individual Commands.
- turns the "marshall" and "unmarshall" transform steps of the `@aws-sdk/lib-dynamodb` package into middleware on its client.
- allow use of middleware on individual Commands in that package

fix(lib-dynamodb): make command middleware useable, turn marshalling into middleware

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/test/resources/software/amazon/smithy/aws/typescript/codegen/NotSame.smithy

P68697060
The codegen will break if the service shape's doc trait contains `${}` when generating the README. This change escapes all the `$` that would cause problems with generating the doc.
Unit test
---

chore(codegen): escape the service doc containing $

---

.github/ISSUE_TEMPLATE/bug-report.yml

The AWS SDK for JavaScript (v3) bug report template was heavily customized based on triaging issues.
It was overwritten by a standard template in https://github.com/aws/aws-sdk-js-v3/pull/3506
Re-add customizations in bug report template
* Merged on trivikr fork:  https://github.com/trivikr/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=TITLE+FOR+BUG+REPORT
* Created new issue using the template https://github.com/trivikr/aws-sdk-js-v3/issues/394
---

fix(docs): re-add customizations in bug report template

---

yarn.lock

Internal JS-3363
Bumps json-schema to 0.4.0
Required as per https://github.com/advisories/GHSA-896r-f27r-55mw
Not needed, as json-schema is transitive dependency of verdaccio
---

chore(deps-dev): bump json-schema to 0.4.0

---

packages/util-body-length-browser/src/calculateBodyLength.spec.ts
packages/util-body-length-browser/src/calculateBodyLength.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3559
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3610
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3467
Handles trail surrogate character in case of string length computation on browser
Unit testing
StackOverflow: https://stackoverflow.com/a/23329386
---

fix(util-body-length-browser): handle trail surrogate character

---

clients/client-s3/test/S3.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/3874#issuecomment-1224522821
Mocha has some issue with mocking response in S3 tests.
```console
$ yarn run ts-mocha test/S3.spec.ts                       
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/ts-mocha test/S3.spec.ts
endpoint
✔ users can override endpoint from client.
Endpoints from ARN
Accesspoint ARN
✔ should succeed with access point ARN
✔ should sign request with region from ARN is useArnRegion is set
Outposts ARN
✔ should succeed with outposts ARN
Object Lambda ARN
✔ should succeed with Object Lambda ARN
✔ should update endpoint of WriteGetObjectResponse command
Throw 200 response
when response body is empty
✔ should throw if CopyObject() return with 200 and empty payload
✔ should throw if …
```

test(client-s3): separate 200 response empty and error

---

packages/token-providers/package.json

N/A
Move `@aws-sdk/client-sso-oidc` in dependencies of token-providers, as it's used in https://github.com/aws/aws-sdk-js-v3/blob/bf7efa91e14dbca131554d4cc733a024c089bb26/packages/token-providers/src/getNewSsoOidcToken.ts#L1
Issues like this won't happen if we move to yarn modern (2+) versions.
We've attempted moving to yarn modern in the past https://github.com/aws/aws-sdk-js-v3/pull/3235
Local testing
---

fix(token-providers): move client-sso-oidc in dependencies

---

clients/client-sts/jest.config.js
clients/client-sts/package.json
clients/client-sts/src/defaultRoleAssumers.ts
clients/client-sts/test/defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.ts
packages/credential-providers/README.md
packages/credential-providers/src/fromIni.spec.ts
packages/credential-providers/src/fromIni.ts
packages/credential-providers/src/fromNodeProviderChain.spec.ts
packages/credential-providers/src/fromNodeProviderChain.ts
packages/credential-providers/src/fromTemporaryCredentials.spec.ts
packages/credential-providers/src/fromTemporaryCredentials.ts
packages/credential-providers/src/fromTokenFile.spec.ts
packages/credential-providers/src/fromTokenFile.ts
packages/credential-providers/src/fromWebToken.spec.ts
packages/credential-providers/src/fromWebToken.ts

Ref: V693851885
Provide an easier way to inject middleware to the default STS client used by the credential providers. Now users can use the `clientPlugins` option to add middleware to the underlying STS client. A typical usecase is adding custom headers to the assume-role API calls to prevent [confused deputy problem](https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html).
Unit test
---

fix(credential-providers): support custom middleware for sts client

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
packages/smithy-client/src/parse-utils.spec.ts
packages/smithy-client/src/parse-utils.ts

internal P70766077
- allow unambiguous type conversions instead of throwing
- e.g. expectNumber("5") gives 5 with warning instead of throwing "5" is not a number.
- e.g. expectString(5) gives "5" with warning instead of throwing 5 is not a string.
unit tests updated

feat(smithy-client): allow unambiguous type conversions in parse-utils

---

packages/util-dynamodb/src/models.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2896
Similar type declaration to https://github.com/aws/aws-sdk-js-v3/pull/3889
Manual test
---

fix(lib-dynamodb): declare File interface without requiring dom lib

---

packages/types/src/serde.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/3807
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/3063
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2522
https://github.com/aws/aws-sdk-js-v3/issues/2896 will be fixed in follow-up PR with similar fix.
The SDK clients have reference to `ReadableStream` interface only available in `dom`. It causes building issue for users that don't have dependency over `dom`.  This is a minimal fix to eliminate `error TS2304: Cannot find name 'ReadableStream'`. How it works is decribed in https://github.com/microsoft/TypeScript/issues/31894. 
Manual test with repro:
https://github.com/aws/aws-sdk-js-v3/issues/3063#issuecomment-980473477
This can be removed when TypeScript comes up with solution that supports runtime-specific types. …

fix(types): declare ReadableStream type without requiring dom

---

packages/signature-v4/src/SignatureV4.spec.ts
packages/signature-v4/src/SignatureV4.ts

Resolves #2282 
Resolves #2898 
Validate the resolved AWS credentials in the Sigv4 signer and throw more meaningful error when invalid credential is encountered.
Reproduction:
```javascript
import {S3} from "@aws-sdk/client-s3";
(async () => {
const s3Client = new S3({credentials: {} as unknown as any, region: "us-west-2"});
const data = (await s3Client.getObject({
"Bucket": "js-sdk-test-bucket",
"Key": "data.txt"
}));
console.log(data.Body);
})();
```
```bash
const fromArrayBuffer = (input, offset = 0, length = input.byteLength - offset) => {
^
TypeError: Cannot read properties of undefined (reading 'byteLength')
...
```
---

feat(signature-v4): validate credential is valid before signing

---

packages/middleware-sdk-s3/src/throw-200-exceptions.spec.ts
packages/middleware-sdk-s3/src/throw-200-exceptions.ts
yarn.lock

Fixes: #3856
Process errors with 200 status code in throw200ExceptionsMiddleware
Unit testing
---

fix(middleware-sdk-s3): process errors with 200 status code

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/load-json-error-code-stub.ts

https://github.com/awslabs/smithy/issues/1170
This change adds support for multiple values in the x-amzn-errortype header. The reason for this is that API-Gateway always adds its own x-amzn-errortype header on [gateway responses](https://docs.aws.amazon.com/apigateway/latest/developerguide/supported-gateway-response-types.html). This header that APIG adds and does not let the customer configure will almost never match the specific errors that customers model for their API. As an aside, I have logged a feature request for APIG to support configuration of this header - however this is unlikely to be delivered any time soon.
Anyone using this package today to generate clients of their own therefore cannot use gateway responses and have a functioning SDK for their errors. It isn't possible to …

feat: support multiple error headers

---

packages/types/src/endpoint.ts
packages/util-endpoints/src/lib/aws.ts
packages/util-endpoints/src/lib/aws/index.ts
packages/util-endpoints/src/lib/aws/parseArn.spec.ts
packages/util-endpoints/src/lib/aws/parseArn.ts
packages/util-endpoints/src/lib/aws/partition.spec.ts
packages/util-endpoints/src/lib/aws/partition.ts
packages/util-endpoints/src/lib/aws/partitions.json
packages/util-endpoints/src/lib/index.ts

Internal JS-3541
Adds endpoint ruleset library specific to aws
Unit testing
---

chore(util-endpoints): add endpoint ruleset library specific to aws

---

private/aws-echo-service/src/protocols/Aws_restJson1.ts

Missed in https://github.com/aws/aws-sdk-js-v3/pull/3904
Adds check for comma in aws-echo-service
CI
---

chore(aws-echo-service): add check for comma

---

features/extra/helpers.js
features/sqs/step_definitions/queues.js

Fix the `eventually` helper function.
```
npx cucumber-js --fail-fast -t @queues --format json:cucumber-report.json
```

fix(e2e): fix "eventually" helper in e2e tests

---

packages/middleware-retry/src/StandardRetryStrategy.spec.ts
packages/middleware-retry/src/StandardRetryStrategy.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3894
Checks error response for `Retry-Header`, and uses that value for delay if it's present and higher that delay decided by Standard Retry Strategy.
ToDo
MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After
---

fix(middleware-retry): use delay from response header if it's higher

---

packages/util-endpoints/src/resolveEndpoint.spec.ts
packages/util-endpoints/src/resolveEndpoint.ts

Noticed while going integration testing in https://github.com/aws/aws-sdk-js-v3/pull/3926
Populate default params before checking required values while resolving endpoint
Unit testing
---

fix(util-endpoints): populate default params before checking for required values

---

packages/util-endpoints/src/utils/getReferenceValue.spec.ts
packages/util-endpoints/src/utils/getReferenceValue.ts

Noticed during integration tests in https://github.com/aws/aws-sdk-js-v3/pull/3926
The utility `getReferenceValue` used to throw error when value is not present. This is not required, as ruleset engine checks if the value if set.
Unit testing
---

chore(util-endpoints): return undefined when value absent in referenceRecord

---

packages/util-endpoints/src/lib/aws/index.ts

Noticed during integration tests in https://github.com/aws/aws-sdk-js-v3/pull/3926
The endpoint ruleset library specific to aws was added in https://github.com/aws/aws-sdk-js-v3/pull/3909
However, the function `parseArn` wasn't exported from lib/aws. This PR exports the function.
Done in https://github.com/aws/aws-sdk-js-v3/pull/3926
---

fix(util-endpoints): export parseArn from lib/aws

---

packages/util-endpoints/src/utils/callFunction.spec.ts
packages/util-endpoints/src/utils/callFunction.ts

Noticed during integration tests in https://github.com/aws/aws-sdk-js-v3/pull/3926
The endpoint ruleset library specific to aws was added in https://github.com/aws/aws-sdk-js-v3/pull/3909
However, the callFunction method was not updated to call multi-level functions, i.e. call lib.aws.partition for function name "aws.partition"
This PR makes that change.
Unit testing
---

fix(util-endpoints): call multi-level functions from callFunction

---

packages/util-endpoints/src/utils/evaluateCondition.spec.ts
packages/util-endpoints/src/utils/evaluateCondition.ts

Noticed in integration tests https://github.com/aws/aws-sdk-js-v3/pull/3926
When function call returns an empty string, the condition needs to be evaluated to true.
Unit testing
---

chore(util-endpoints): evaluate condition to true for empty string

---

packages/util-endpoints/src/utils/evaluateTemplate.spec.ts
packages/util-endpoints/src/utils/evaluateTemplate.ts

Noticed while writing integration tests in https://github.com/aws/aws-sdk-js-v3/pull/3926
Escapes tilde when evaluating template
Unit testing
---

fix(util-endpoints): escape tilde when evaluating template

---

scripts/downlevel-dts/downlevelWorkspace.mjs

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3847
Skips files with stripped comments if there is incorrect JavaScript.
Verified that files with incorrect JavaScript are not overwritten:
```console
$ yarn build:types:downlevel
$ node --es-module-specifier-resolution=node ./scripts/downlevel-dts
(node:35884) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
Failed to format "clients/client-apigatewayv2/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-cloudfront/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-elastic-load-balancing-v2/dist-types/ts3.4/models/ …
```

fix(scripts): skip files with stripped comments containing incorrect JavaScript

---

packages/util-endpoints/src/lib/aws/parseArn.spec.ts
packages/util-endpoints/src/lib/aws/parseArn.ts

Noticed during integration testing in https://github.com/aws/aws-sdk-js-v3/pull/3926
Return null in parseArn when partition, service or resourceId is empty
Unit testing
---

fix(util-endpoints): return null in parseArn for some empty elements

---

packages/types/src/endpoint.ts
packages/util-endpoints/src/lib/parseURL.spec.ts
packages/util-endpoints/src/lib/parseURL.ts

Internal JS-3566
The AWS SDK for JavaScript implementation did not add normalizedPath in the past, as it was similar to path in most cases, and we wanted to drive a consensus to enforce `path` implement ending with `/` in internal specification.
We couldn't arrive at that consensus, so we need to introduce normalizedPath.
Integration tests in https://github.com/aws/aws-sdk-js-v3/pull/3926
Unit testing
---

chore(util-endpoints): add normalizedPath which ends with a /

---

jest.config.integ.js
packages/util-endpoints/jest.config.integ.js
packages/util-endpoints/src/__mocks__/test-cases/aws-region.json
packages/util-endpoints/src/__mocks__/test-cases/default-values.json
packages/util-endpoints/src/__mocks__/test-cases/eventbridge.json
packages/util-endpoints/src/__mocks__/test-cases/fns.json
packages/util-endpoints/src/__mocks__/test-cases/headers.json
packages/util-endpoints/src/__mocks__/test-cases/local-region-override.json
packages/util-endpoints/src/__mocks__/test-cases/parse-arn.json
packages/util-endpoints/src/__mocks__/test-cases/parse-url.json
packages/util-endpoints/src/__mocks__/test-cases/partition-fn.json
packages/util-endpoints/src/__mocks__/test-cases/substring.json
packages/util-endpoints/src/__mocks__/test-cases/uri-encode.json
packages/util-endpoints/src/__mocks__/test-cases/valid-hostlabel.json
packages/util-endpoints/src/__mocks__/valid-rules/aws-region.json
packages/util-endpoints/src/__mocks__/valid-rules/default-values.json
packages/util-endpoints/src/__mocks__/valid-rules/eventbridge.json
packages/util-endpoints/src/__mocks__/valid-rules/fns.json
packages/util-endpoints/src/__mocks__/valid-rules/headers.json
packages/util-endpoints/src/__mocks__/valid-rules/local-region-override.json
packages/util-endpoints/src/__mocks__/valid-rules/parse-arn.json
packages/util-endpoints/src/__mocks__/valid-rules/parse-url.json
packages/util-endpoints/src/__mocks__/valid-rules/partition-fn.json
packages/util-endpoints/src/__mocks__/valid-rules/substring.json
packages/util-endpoints/src/__mocks__/valid-rules/uri-encode.json
packages/util-endpoints/src/__mocks__/valid-rules/valid-hostlabel.json
packages/util-endpoints/src/resolveEndpoint.integ.spec.ts
packages/util-endpoints/src/utils/getReferenceValue.spec.ts

Internal JS-3566
Add integration tests for resolving endpoint
Integration testing
```console
$ aws-sdk-js-v3> yarn test:integration
...
Test Suites: 3 passed, 3 total
Tests:       77 passed, 77 total
Time:        8.435 s
Ran all test suites in 3 projects.
Done in 9.57s.
$ util-endpoints> yarn test src/resolveEndpoint.integ.spec.ts --config jest.config.integ.js
...
Tests:       75 passed, 75 total
Time:        3.278 s, estimated 4 s
Ran all test suites matching /src\/resolveEndpoint.integ.spec.ts/i.
Done in 4.19s.
```
---

test(util-endpoints): add integration tests for resolving endpoint

---

README.md

This PR fixes documentation typo.

docs(readme): fix credenitials -> credentials 

---

package.json
scripts/downlevel-dts/downlevelWorkspace.mjs
yarn.lock

Refs https://github.com/aws/aws-sdk-js-v3/issues/3847
Replaces stripComments with decomment for removing comments
<details>
<summary>Running the script</summary>
main branch
```console
$ yarn build:types:downlevel
...
Failed to format "clients/client-apigatewayv2/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-cloudfront/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-elastic-load-balancing-v2/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-glacier/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-lex-runtime-service/dist-types/ts3.4/models/models_0.d.ts". Skipping...
Failed to format "clients/client-lex-runtime-v2/dist-types/ts3.4/models/models_ …
```

chore(scripts): replace stripComments with decomment

---

codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsTraitsUtils.java
lib/lib-storage/src/Upload.ts
scripts/downlevel-dts/downlevelWorkspace.mjs
scripts/generate-clients/code-gen.js

endpoints v2 codegen changes, split from https://github.com/aws/aws-sdk-js-v3/pull/3927
see also https://github.com/awslabs/smithy-typescript/pull/586

feat(endpoint): endpoints v2 codegen

---

cucumber.json

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/3946
Cucumber shows info about publishing reports. This configuration disables it.
<details>
```console
$ yarn run cucumber-js -t @sqs
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js -t @sqs
.......................
17 steps (17 passed)
0m02.400s (executing steps: 0m02.350s)
┌──────────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io     │
│                                                                              │
│ Command line option:    --publish                                            │
│ Environment variable: …
```

chore: disable info about publishing reports in cucumber

---

features/sqs/messages.feature
features/sqs/queues.feature
features/sqs/step_definitions/queues.js
features/sqs/step_definitions/sqs.js
yarn.lock

Alternative to https://github.com/aws/aws-sdk-js-v3/pull/3918
Move deletion of sqs queues to After call. This way, the queues will get deleted even if integration test fails
Verified that cleanup happens when:
<details>
<summary>Integration tests are successful</summary>
```console
$ aws sqs list-queues
$ yarn run cucumber-js --fail-fast -t @sqs       
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @sqs
......................
13 steps (13 passed)
0m01.761s (executing steps: 0m01.710s)
Done in 2.91s.
$ aws sqs list-queues
```
</details>
<details>
<summary>Integration tests fail</summary>
```console
$ git diff
diff --git a/features/sqs/messages.feature b/features/sqs/messages.feature
index …
```

fix(e2e): move deletion of sqs queues to After call

---

features/cloudwatchlogs/cloudwatchlogs.feature
features/cloudwatchlogs/step_definitions/cloudwatchlogs.js

Deletes cloudwatch groups in After call
<details>
```console
$ aws logs describe-log-groups --log-group-name-prefix aws-js-sdk
{
"logGroups": []
}
$ yarn run cucumber-js --fail-fast -t @cloudwatchlogs
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @cloudwatchlogs
...........
0m00.254s (executing steps: 0m00.222s)
Done in 1.03s.
$ aws logs describe-log-groups --log-group-name-prefix aws-js-sdk
{
"logGroups": []
}
```
</details>
---
By submitting this pull request, I confirm that you can use, …

fix(e2e): delete cloudwatch groups in After call

---

codegen/build.gradle.kts

Refs: https://github.com/awslabs/smithy-typescript/pull/589
Bumps smithy to 1.25.x, verified that clients are not updated on running `yarn generate-clients`.
CI
---

chore(codegen): bump smithy to 1.25.x

---

features/elastictranscoder/elastictranscoder.feature
features/elastictranscoder/step_definitions/elastictranscoder.js
features/iam/iam.feature
features/iam/step_definitions/iam.js
features/opsworks/opsworks.feature
features/opsworks/step_definitions/opsworks.js

Deletes IAM+OpsWorks+ElasticTranscoder resources in After call
<details>
```console
$ aws iam list-users | jq '.Users[].UserName| select(startswith("js-test"))'
$ aws iam list-roles | jq '.Roles[].RoleName| select(startswith("aws-sdk-js"))'
$ aws opsworks describe-user-profiles | jq '.UserProfiles[].Name| select(startswith("aws-js-sdk"))'
$ aws elastictranscoder list-pipelines
{
"Pipelines": []
}
$ yarn run cucumber-js --fail-fast -t "@iam or @opsworks or @elastictranscoder"
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t '@iam or …
```

fix(e2e): delete IAM+ resources in After call

---

features/sns/sns.feature
features/sns/step_definitions/sns.js

Moves deletion of SNS topic in After call
<details>
```console
$ aws sns list-topics | jq '.Topics[].TopicArn | select(startswith("aws-js-sdk"))'
$ yarn run cucumber-js --fail-fast -t @sns                                         
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @sns
...........
0m00.303s (executing steps: 0m00.268s)
Done in 1.09s.
$ aws sns list-topics | jq '.Topics[].TopicArn | select(startswith("aws-js-sdk"))'
```
</details>
---
By submitting this pull request, I confirm that …

fix(e2e): delete sns topic in After call

---

features/elasticbeanstalk/elasticbeanstalk.feature
features/elasticbeanstalk/step_definitions/elasticbeanstalk.js

Moves deletion of elasticbeanstalk app in After call
<details>
```console
$ aws elasticbeanstalk describe-applications
{
"Applications": []
}
$ yarn run cucumber-js --fail-fast -t @elasticbeanstalk
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @elasticbeanstalk
..............
8 steps (8 passed)
0m01.091s (executing steps: 0m01.047s)
Done in 1.88s.
$ aws elasticbeanstalk describe-applications           
{
"Applications": []
}
```
</details>
---
By submitting this pull request, I confirm that you can use, …

fix(e2e): delete elasticbeanstalk app in After call

---

features/elasticache/elasticache.feature
features/elasticache/step_definitions/elasticache.js

Moves deletion of elasticache resources in After call
<details>
```console
$ aws elasticache describe-cache-parameter-groups | jq '.CacheParameterGroups[].CacheParameterGroupName | select(startswith("aws-js-sdk"))'
$ yarn run cucumber-js --fail-fast -t @elasticache                   
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @elasticache
..............
8 steps (8 passed)
0m00.345s (executing steps: 0m00.302s)
Done in 1.13s.
$ aws elasticache describe-cache-parameter-groups | jq …
```

fix(e2e): delete elasticache resources in After call

---

features/dynamodb/step_definitions/dynamodb.js
features/dynamodb/tables.feature

Moves deletion of DynamoDB table in AfterAll call
<details>
```console
$ aws dynamodb list-tables | jq '.TableNames[] | select(startswith("aws-sdk-js-integration"))'
$ yarn run cucumber-js --fail-fast -t @dynamodb
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @dynamodb
..........................
5 scenarios (5 passed)
16 steps (16 passed)
0m20.360s (executing steps: 0m20.243s)
Done in 21.18s.
$ aws dynamodb list-tables | jq '.TableNames[] | select(startswith("aws-sdk-js-integration"))'
```
</details>
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

fix(e2e): delete DynamoDB table in AfterAll call

---

features/cloudwatch/cloudwatch.feature
features/cloudwatch/step_definitions/cloudwatch.js

Moves deletion of cloudwatch alarms in After call
<details>
```console
$ aws cloudwatch describe-alarms --alarm-name-prefix aws-js-sdk-alarm
{
"MetricAlarms": [],
"CompositeAlarms": []
}
$ yarn run cucumber-js --fail-fast -t @cloudwatch                    
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @cloudwatch
...........
0m00.355s (executing steps: 0m00.322s)
Done in 1.14s.
$ aws cloudwatch describe-alarms --alarm-name-prefix aws-js-sdk-alarm
{
"MetricAlarms": [],
"CompositeAlarms": []
} …
```

fix(e2e): delete cloudwatch alarms in After call

---

packages/s3-request-presigner/src/presigner.spec.ts
packages/s3-request-presigner/src/presigner.ts

Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2886
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2121
Add the port to host header in the request presigner. This change has to effect on custom host header.
Unit test
---

fix(s3-request-presigner): add port to host name if missed

---

features/elastictranscoder/elastictranscoder.feature
features/elastictranscoder/step_definitions/elastictranscoder.js
features/extra/hooks.js
features/s3/buckets.feature
features/s3/step_definitions/buckets.js

Move S3 buckets deletion in After call.
The shared integration test buckets are cleaned up in global AfterAll call
https://github.com/aws/aws-sdk-js-v3/blob/37f574fe33546720177866ed1c34333c68066c8e/features/extra/cleanup.js#L12-L17
<details>
```console
$ aws s3api list-buckets | jq '.Buckets[].Name | select(startswith("aws-sdk-js-integration"))'
$ yarn run cucumber-js --fail-fast -t @elastictranscoder
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/cucumber-js --fail-fast -t @elastictranscoder
................
10 steps (10 passed)
0m01.828s (executing steps: 0m01.784s)
Done in 2.64s.
$ aws s3api list-buckets | jq '.Buckets[].Name | …
```

fix(e2e): delete s3 buckets in After Call

---

codegen/sdk-codegen/aws-models/amplifyuibuilder.json
codegen/sdk-codegen/aws-models/evidently.json
codegen/sdk-codegen/aws-models/identitystore.json
codegen/sdk-codegen/aws-models/inspector2.json

Internal JS-3581
Update models with smithy default trait.
These models were missing some default traits earlier and were fixed with Smithy 1.25.0. Picking up the updated models.
N/A, as generated code is not updated.
---

chore(models): update models with smithy default trait

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

The CI won't pass until https://github.com/awslabs/smithy-typescript/pull/591 is merged
---

chore(codegen): bump code generators to 0.12.0

---

packages/util-endpoints/src/__mocks__/test-cases/is-virtual-hostable-s3-bucket.json
packages/util-endpoints/src/__mocks__/valid-rules/is-virtual-hostable-s3-bucket.json
packages/util-endpoints/src/lib/aws/index.ts
packages/util-endpoints/src/lib/aws/isVirtualHostableS3Bucket.spec.ts
packages/util-endpoints/src/lib/aws/isVirtualHostableS3Bucket.ts
packages/util-endpoints/src/lib/isIpAddress.spec.ts
packages/util-endpoints/src/lib/isIpAddress.ts
packages/util-endpoints/src/lib/parseURL.ts

Internal JS-3583
Adds new implementation in ruleset standard library: `aws.isVirtualHostableS3Bucket`
Unit testing and integration testing
---

feat(util-endpoints): add aws.isVirtualHostableS3Bucket

---

clients/client-sns/README.md

The SNS sample in the readme uses AddPermissionCommand as the sample.  The most common use case would the PublishCommand.  Updated the v3 sample from AddPermissionCommand to PublishCommand
https://github.com/sravimohan/aws-sdk-js-v3/blob/main/clients/client-sns/README.md
---

docs(client-sns):  updated sns client readme v3 sample

---

packages/middleware-signing/package.json

#3947 added a dependency on `util-middleware` but failed to declare it.
In a Yarn v3 project I have added to `.yarnrc.yml`:
```
packageExtensions:
"@aws-sdk/middleware-signing@3":
dependencies:
"@aws-sdk/util-middleware": 3
```
And my project now starts again.
---

fix(middleware-signing): add missing dependency

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts
lib/lib-storage/src/types.ts

#3872
This optionally exposes the abortController on the `Upload` object.
Wrote new test in Jest
_N/A_
---

feat(upload-abort-controller): add optional abortController param for Upload

---

packages/util-waiter/src/poller.spec.ts
packages/util-waiter/src/poller.ts

https://github.com/aws/aws-sdk-js-v3/issues/2809
When generating the waiter result, we are not taking into account the reason. We should expose the result from the underlying API call and add that to the `reason` property as expected.
Unit tests
---

feat(util-waiter): include reason on waiter result

---

packages/smithy-client/src/exceptions.spec.ts
packages/smithy-client/src/exceptions.ts

resolves: https://github.com/aws/aws-sdk-js-v3/issues/3492
The `message` property is being excluded in `ExceptionOptionType`.
From the type-system perspective, we were not allowed to pass the message whenever instantiating any Exception generated by the Smithy TypeScript generator.
Unit test
---

fix(smithy-client): exception option missing message property

---

packages/signature-v4-crt/package.json
yarn.lock

Internal P67533319
Bump aws-crt to `v1.13.2`, which reduced install size from `22.1MB` to `17.7MB`. 
CI
* PackagePhobia https://packagephobia.com/result?p=aws-crt@1.13.2
* https://github.com/awslabs/aws-crt-nodejs/issues/333
---

chore(deps): bump aws-crt to 1.13.2

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-json-10/test/functional/awsjson1_0.spec.ts

Reverts https://github.com/aws/aws-sdk-js-v3/pull/3990
The protocol test was removed upstream in https://github.com/awslabs/smithy/pull/1424
Remove Json10WithQueryCompatibleGreetingError
N/A
---

test(aws-protocoltests-json-10): remove Json10WithQueryCompatibleGreetingError

---

packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts
packages/middleware-endpoint/src/endpointMiddleware.ts
packages/middleware-endpoint/src/getEndpointPlugin.ts
packages/middleware-endpoint/src/integration-tests/integration-test-types.ts
packages/middleware-endpoint/src/integration-tests/integration.spec.ts
packages/middleware-endpoint/src/integration-tests/s3/custom-tests.json
packages/middleware-endpoint/src/service-customizations/index.ts
packages/middleware-endpoint/src/service-customizations/s3.ts
packages/util-endpoints/src/lib/isValidHostLabel.spec.ts
packages/util-endpoints/src/lib/isValidHostLabel.ts
packages/util-endpoints/src/utils/evaluateCondition.ts
packages/util-endpoints/src/utils/getEndpointUrl.ts

- misc fixes for endpoints 2.0 based on S3 service unit tests (not shown here).
I have not imported the test cases I used because they are not public yet. Added here are only some revealed fixes and the test case runner code. 
**REQUIRES**: https://github.com/awslabs/smithy-typescript/pull/600

fix(endpoint): misc fixes for endpoints 2.0 based on service unit tests

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/populate-body-with-query-compatibility-code-stub.ts

* This commit adds query compatible header handling for JSON protocols only
* When an AWS service sends a `x-amzn-query-error` header, it contains an error code and type.
* Example header: `x-amzn-query-error:InternalFailure;Receiver`
* `InternalFailure` is the error code
* `Receiver` is the Type
* Note: The value is always a `;` delimited string e.g. `InternalFailure;Receiver`, `MalformedInput;Sender`
* Generated clients using json protocol
* Verified code generation is correct
---

feat(codegen): add query compatible header error code handling for JSON protocols

---

package.json
yarn.lock

Bumps lerna and parse-url. Lerna bump to 5.5.2, required for parse-url bump to 8.0.1.
`build:all` is successful. Verifies all the build commands.
```console
...
lerna success - @aws-sdk/aws-echo-service
lerna success - @aws-sdk/aws-protocoltests-ec2
lerna success - @aws-sdk/aws-protocoltests-json-10
lerna success - @aws-sdk/aws-protocoltests-json
lerna success - @aws-sdk/aws-protocoltests-query
lerna success - @aws-sdk/aws-protocoltests-restjson
lerna success - @aws-sdk/aws-protocoltests-restxml
Done in 434.82s.
```
Also verified that diff is created for release `v3.180.0`, contains the CHANGELOG. 
```console
$ git checkout tags/v3.180.0 -b v3.180.0
$ git reset --hard HEAD~
$ git cherry-pick 78670f22e9b86e4afdeb90ac9a3294b1987ce0ac
$ yarn && git add yarn.lock && git …
```

chore(deps-dev): bump lerna to 5.5.2

---

clients/client-s3-control/src/runtimeConfig.shared.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java

SigV4 canonical path expects S3 to set signingEscapePath=false.
This was the case for S3, but not for S3Control. This prevents the `S3Control::describeMultiRegionAccessPointOperation` operation from being signed correctly.

fix(s3-control): default config.signingEscapePath to false

---

packages/node-http-handler/src/constants.ts
packages/service-error-classification/src/constants.ts
packages/service-error-classification/src/index.ts

internal P72696063
The NodeHttpHandler is supposed to decorate any caught errors with `{ name: "TimeoutError" }` if it recognizes a nodejs timeout error. However, there have been observed cases of a nodejs timeout error reaching the retry strategy check without having this name decoration. This causes the retry decider to abandon the request early. 
- This PR duplicates the NodeJS error.code check for timeout errors at the retry decider to prevent fallthrough of NodeJS timeout errors that were not caught and decorated by the Node HTTP handler.

fix(node-http-handler): check for error code in isTransientError

---

codegen/build.gradle.kts
codegen/generic-client-test-codegen/build.gradle.kts
codegen/gradle.properties
codegen/protocol-test-codegen/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

N/A
This applies the same changes from https://github.com/awslabs/smithy-typescript/pull/611/, moving Smithy version settings to `gradle.properties` for consistency.
ran `./gradlew clean build` from the codegen directory to assure gradle properties were still set correctly.
---

chore(codegen): move smithy version settings to gradle properties

---

codegen/gradle.properties

Refs: https://github.com/awslabs/smithy-typescript/pull/605
Bumps smithy to 1.26.x, verified that clients are not updated on running `yarn generate-clients`.
CI
---

chore(codegen): bump smithy to 1.26.x

---

README.md
packages/types/src/serde.ts

- update readme to make stream mixin helpers known
- fix the type declaration for `WithSdkStreamMixin<OutputType, OutputStreamMemberKey>`

docs(streams): add readme section about stream mixins

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointsV2ParameterNameMap.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts
packages/credential-providers/src/fromTemporaryCredentials.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts
packages/middleware-bucket-endpoint/src/configurations.ts
packages/middleware-endpoint-discovery/src/resolveEndpointDiscoveryConfig.ts
packages/middleware-sdk-eventbridge/src/inject-endpoint-id.spec.ts
packages/middleware-sdk-eventbridge/src/inject-endpoint-id.ts
packages/middleware-sdk-s3-control/src/configurations.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/parse-outpost-arnables.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/update-arnables-request.ts
packages/middleware-sdk-s3-control/src/redirect-from-postid.ts
packages/middleware-sdk-sts/src/index.ts
packages/s3-request-presigner/src/getSignedUrl.spec.ts
packages/token-providers/src/getNewSsoOidcToken.spec.ts
packages/util-endpoints/src/index.ts

- takes the endpoints-2.0 branch for all service models in aws-models repo and tests codegen + compilation
- fixes resulting TS compilation errors

fix(endpoint): endpoints 2.0 all-service TS compilation fixes

---

features/extra/hooks.js
features/rds/rds.feature
features/rds/step_definitions/rds.js
package.json
packages/middleware-endpoint/src/endpointMiddleware.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/parse-outpost-arnables.ts
packages/middleware-signing/src/configuration.spec.ts
packages/middleware-signing/src/configurations.ts
packages/middleware-signing/src/middleware.ts
packages/s3-request-presigner/src/getSignedUrl.ts
packages/types/src/auth.ts
yarn.lock

- fixes e2e feature tests when in endpoints 2.0 mode
- codegen a defaultSigningName for endpoint resolutions without an authScheme.signingName
- correctly rename signingScope to signingName
- fix RDS feature test
tested with
```
yarn copy-models (aws-models endpoints-2.0 branch)
yarn generate-clients
yarn build:all
yarn test:all
npx cucumber-js
```
This PR requires https://github.com/awslabs/smithy-typescript/pull/615

fix(endpoint): e2e test fixes for endpoints 2.0 all services

---

clients/client-s3/test/S3.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointsV2ParameterNameMap.java
packages/util-endpoints/src/lib/parseURL.spec.ts
packages/util-endpoints/src/lib/parseURL.ts

paired with https://github.com/awslabs/smithy-typescript/pull/616
- fix duplication of clientContext and builtIn param names (this is a new bug uncovered by a preview build, previous models did not have duplication).
- default new parameter names to idiomatic `camelCase`
- some test fixes for s3

fix(endpoint): dedupe clientContext/builtIn params, fix s3 unit test

---

packages/middleware-signing/src/middleware.ts

when a sigv4a authscheme is reslved, set signingRegion using the `*` from `authScheme.signingRegionSet`, allowing S3's MultiRegionSigv4 signer to go into Sigv4a mode.
This fixes a bug uncovered by `S3.ispec.ts` browser mode.

fix(endpoint): use sigv4a signing region override

---

clients/client-chime-sdk-messaging/package.json
clients/client-chime-sdk-messaging/src/endpoint/endpointResolver.ts
clients/client-cloudtrail/package.json
clients/client-cloudtrail/src/endpoint/endpointResolver.ts
clients/client-config-service/package.json
clients/client-config-service/src/endpoint/endpointResolver.ts
clients/client-connect/package.json
clients/client-connect/src/endpoint/endpointResolver.ts
clients/client-eventbridge/package.json
clients/client-eventbridge/src/endpoint/endpointResolver.ts
clients/client-frauddetector/package.json
clients/client-frauddetector/src/endpoint/endpointResolver.ts
clients/client-greengrass/package.json
clients/client-greengrass/src/endpoint/endpointResolver.ts
clients/client-managedblockchain/package.json
clients/client-managedblockchain/src/endpoint/endpointResolver.ts
clients/client-s3-control/package.json
clients/client-s3-control/src/endpoint/endpointResolver.ts
clients/client-s3/package.json
clients/client-s3/src/endpoint/endpointResolver.ts
clients/client-sagemaker/package.json
clients/client-sagemaker/src/endpoint/endpointResolver.ts
clients/client-servicediscovery/package.json
clients/client-servicediscovery/src/endpoint/endpointResolver.ts
clients/client-sesv2/package.json
clients/client-sesv2/src/endpoint/endpointResolver.ts
clients/client-support-app/package.json
clients/client-support-app/src/endpoint/endpointResolver.ts
clients/client-workspaces-web/package.json
clients/client-workspaces-web/src/endpoint/endpointResolver.ts

Refs: https://github.com/awslabs/smithy-typescript/pull/619
Adds @aws-sdk/util-endpoints dependency in clients which depend on it.
Verified that clean build with dependencies is successful in `client-sesv2`
```console
$ aws-sdk-js-v3> git clean -dfx && yarn
$ aws-sdk-js-v3> cd clients/client-sesv2
$ client-sesv2> yarn build:include:deps
...
Done in 136.08s.
```
Also verified that `@aws-sdk/util-endpoints` dependency is added in `package.json` of 15 clients, which imported the dependency in `src/endpoint/endpointResolver.ts`
---

fix(clients): add @aws-sdk/util-endpoints dependency

---

packages/middleware-signing/src/middleware.ts
packages/types/src/auth.ts

Today's release only includes signingRegionSet with single values. This fix is for future rulesets that may have more.
testing
- ran endpoints integration spec
- ran s3 ispec

fix(endpoint): join authScheme signingRegionSet values instead of taking first only

---

clients/client-eventbridge/package.json
clients/client-eventbridge/src/commands/PutEventsCommand.ts
clients/client-eventbridge/test/EventBridge.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventBridgePlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java

Internal JS-3669
Removes middleware-sdk-eventbridge, as the injection is done by endpoints 2.0 ruleset
Unit test is successful
```console
$ client-eventbridge> yarn ts-mocha test/EventBridge.spec.ts                                         
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/ts-mocha test/EventBridge.spec.ts
EventBridge
putEvents
✔ should use sign request with sigv4a with EventId presents
1 passing (18ms)
Done in 0.84s.
```
---

fix(client-eventbridge): remove middleware-sdk-eventbridge

---

clients/client-s3-control/test/S3Control.spec.ts
packages/middleware-endpoint/src/endpointMiddleware.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/getOutpostEndpoint.ts
packages/types/src/middleware.ts
tests/endpoints-2.0/endpoints-integration.spec.ts

split out from https://github.com/aws/aws-sdk-js-v3/pull/4064
internal P73764220
- fix unit tests in s3-control client
Verify unit tests are successful
```console
$ client-s3-control> yarn build:include:deps
$ client-s3-control> yarn ts-mocha test/S3Control.spec.ts
S3Control Client
CreateBucket
✔ should populate correct endpoint and signing region
✔ should populate correct endpoint and signing region if OutpostId is supplied
ListRegionalBuckets
✔ should populate correct endpoint and signing region
✔ should populate correct endpoint and signing region if OutpostId is supplied
Outposts Access Point ARN
✔ should populate correct endpoint if Access Point name is non-ARN
✔ should populate correct endpoint and signing region if Access Point name is ARN
Outposts Bucket ARN
✔ should populate …
```

fix(endpoint): test fixes for s3-control related to endpoints 2.0

---

scripts/copy-models/index.js

internal JS-3670
- enables model wire protocol filter in the script `yarn copy-models`
- example: `yarn copy-models -m ../_models -p restXml`

feat(endpoint): add wire protocol filtering option to copy models script

---

packages/util-endpoints/src/lib/aws/partition.ts

Attempting fix for https://github.com/aws/aws-sdk-js-v3/issues/4067
Uses default import for parititions.json, as users seem to be getting error when trying to bundle `@aws-sdk/util-endpoints`.
We already use default import for package.json in runtimeConfig.ts, and that has been working well with bundlers.
Example in client-acm: https://github.com/aws/aws-sdk-js-v3/blob/41bb10dc09390b4fe0a6578feb6584c15b8b8186/clients/client-acm/src/runtimeConfig.ts#L3
Unit tests:
```console
$ util-endpoints> yarn test src/lib/aws/partition.spec.ts 
$ jest src/lib/aws/partition.spec.ts
PASS  src/lib/aws/partition.spec.ts
partition
✓ should throw an error when the default partition is not found, and region doesn't match in partition array or regex (7 ms)
should reuturn data when default …
```

fix(util-endpoints): use default import for partitions.json

---

.vscode/settings.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/4074
Runs eslint on file save on VSCode
Tested with code in `lib-storage`
<details>
<summary>Screen recording</summary>
https://user-images.githubusercontent.com/16024985/197638022-d4f7ece6-0a8a-46b4-9484-c6380ece85a2.mov
</details>
VSCode settings https://code.visualstudio.com/docs/getstarted/settings
---

chore(vscode): run eslint on file save

---

package.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/4074
Closes: https://github.com/aws/aws-sdk-js-v3/issues/2050
Enabled lint on precommit for `lib/*`
Verified that lint is run for the code in `lib/*`
```console
$ git diff
diff --git a/lib/lib-storage/src/index.ts b/lib/lib-storage/src/index.ts
index 4a6222b183..786357bf1e 100644
--- a/lib/lib-storage/src/index.ts
+++ b/lib/lib-storage/src/index.ts
@@ -1,2 +1,2 @@
-export * from "./Upload";
export * from "./types";
+export * from "./Upload";
$ git add .
$ git commit -m "chore(lib-storage): commit without lint"
husky > pre-commit (node v16.17.1)
✔ Preparing...
✔ Running tasks...
✖ Prevented an empty git commit!
✔ Reverting to original state because of errors...
✔ Cleaning up...
⚠ lint-staged prevented an empty git commit.
Use the …
```

chore(lint-staged): enable lint on precommit for lib/*

---

packages/smithy-client/src/default-error-handler.ts

N/A
Found small typo `"UnknowError"` when it probably should be `"UnknownError"`.
```shell
cd packages/smithy-client
yarn
yarn build:include:deps
yarn test
```
2. Repo Level
```shell
yarn
yarn build:all
lerna run test --scope @aws-sdk/smithy-client
```
N/A
---

fix(smithy-client): fix default error typo

---

packages/middleware-endpoint/src/adaptors/createConfigValueProvider.spec.ts
packages/middleware-endpoint/src/adaptors/createConfigValueProvider.ts
packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.spec.ts
packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts

https://github.com/aws/aws-sdk-js-v3/issues/4076
https://github.com/aws/aws-sdk-js-v3/issues/4095
convert endpoint to string when passing from client config (where it may have been converted to a v1 endpoint by resolveEndpointConfig) to the `endpointParams` resolver input object.
- `client.config.endpoint` can be a string, V1, or V2 endpoint object
- `resolveEndpointConfig` normalizes all of these to a `Provider<Endpoint>`
- when the `endpointParams` are generated from the config mapping instructions, the provider is resolved but the object is not converted to a `string`, which is expected by the endpoints spec and ruleset.

fix(endpoint): normalize endpoint to string when passing from client config to endpointParams

---

packages/eventstream-handler-node/src/EventStreamPayloadHandler.spec.ts
packages/eventstream-handler-node/src/EventStreamPayloadHandler.ts

- Update eventStream-handler-node to also get priorSignature from query string
- This fixes frame signing issues when signature is in query string
- Unit tested, tested locally on private branch with new streaming client
---

fix: update eventStreamPayloadHandler to also get prior signature from query string

---

package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4074
Adds lint scripts for CI and release
```console
$ git checkout -b test-lint
$ git cherry-pick 334fa3dbc6ec38359dc0e4ca93ba1c5b266ecf06
$ git clean -dfx && yarn
$ yarn lerna exec --since origin/main --exclude-dependents 'eslint --quiet src/**/*.ts'
...
lerna notice cli v5.5.2
lerna notice filter changed since "main"
lerna notice filter excluding dependents
lerna info Looking for changed packages since main
lerna info Executing command in 1 package: "eslint --quiet src/**/*.ts"
lerna success exec Executed command in 1 package: "eslint --quiet src/**/*.ts"
$ temp_file=$(mktemp)
$ source_file=packages/util-dynamodb/src/index.ts
$ sed -n '{h;${p;q;};n;G;p;}' $source_file > $temp_file && cp $temp_file $source_file
$ git diff
diff --git …
```

chore(scripts): add lint scripts for CI and release

---

CONTRIBUTING.md
README.md
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sdk-default-configuration.json
packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts
packages/middleware-endpoint-discovery/src/updateDiscoveredEndpointInCache.ts
packages/middleware-endpoint/src/endpointMiddleware.ts
packages/url-parser/src/index.ts
packages/xhr-http-handler/README.md
packages/xhr-http-handler/src/xhr-http-handler.ts
scripts/generate-clients/README.md
tests/e2e/delete-stale-changesets.js

N/A
Only fixing formatting on files using prettier.
* Prettier version: v2.7.1 (as specified in package.json)
* Command used: `npx prettier --write '**/*.{ts,js,md,json}'`
---

chore: fix formatting with prettier

---

packages/util-endpoints/src/debug/debugId.ts
packages/util-endpoints/src/debug/index.ts
packages/util-endpoints/src/debug/toDebugString.ts
packages/util-endpoints/src/resolveEndpoint.ts
packages/util-endpoints/src/utils/evaluateCondition.ts
packages/util-endpoints/src/utils/evaluateConditions.ts
packages/util-endpoints/src/utils/evaluateEndpointRule.ts

internal JS-3672 & https://github.com/aws/aws-sdk-js-v3/pull/4064
Outputs decision information during endpoints ruleset resolution at the debug log level.
Local testing with a filtered logger:
```js
const client = new S3({
endpoint: "https://s3.amazonaws.com",
forcePathStyle: true,
logger: {
error(...ignored) {},
warn(...ignored) {},
info(...ignored) {},
debug(id, ...rest) {
if (id === "endpoints") {
console.debug(...rest);
}
},
},
});
```
Sample output:
```
Initial EndpointParams: {
"Bucket": "TEST_BUCKET",
"ForcePathStyle": true,
"UseArnRegion": false,
"DisableMultiRegionAccessPoints": false,
"Accelerate": false,
"UseGlobalEndpoint": false,
"UseFIPS": false,
"Endpoint": "https://s3.amazonaws.com/",
"Region": "us-east-1",
"UseDualStack": false
}
evaluateCondition: isSet($Region) = true …
```

feat(endpoint): log endpoint decisions at debug level

---

packages/util-endpoints/src/debug/toDebugString.ts
packages/util-endpoints/src/resolveEndpoint.ts
packages/util-endpoints/src/utils/evaluateCondition.ts
packages/util-endpoints/src/utils/evaluateConditions.ts
packages/util-endpoints/src/utils/evaluateEndpointRule.ts

JS-3672
Adds a space between function args, formatting only.

chore(endpoint): add spacing to debug output

---

packages/types/src/logger.ts

* Internal JS-3681
* Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/4104
Makes `trace` an optional function on logger, to preserve backward compatibility.
The logger enforced functions debug, info, warn, error since GA. Adding trace should be optional to not break folks who're using logger without trace function.
Verified that unit test for package `middleware-sdk-s3` which mocks logger is successful
```console
$ middleware-sdk-s3> yarn test
...
Test Suites: 4 passed, 4 total
Tests:       19 passed, 19 total
Time:        4.587 s
Done in 5.78s.
```
---

fix(types): make logger.trace an optional function

---

packages/eventstream-serde-browser/package.json
packages/eventstream-serde-node/package.json
packages/middleware-content-length/package.json
packages/middleware-eventstream/package.json
packages/middleware-sdk-sts/package.json
packages/polly-request-presigner/src/getSignedUrls.spec.ts
packages/querystring-builder/package.json
packages/util-utf8-node/package.json

As of https://github.com/aws/aws-sdk-js-v3/pull/4085, we're running test scripts only on changed packages.
While verifying the change, we noticed that some configurations are not correct.
This issue was not visible earlier, as jest was run globally and it always came across tests. Also, there is no duplicate configuration at global level.
Fixes issues with jest script and configurations:
* Adds `exit 0` for packages which do not have unit tests.
* Removes duplicate jest configuration, if present, in any packages.
Verified that `yarn lerna run test` is successful.
```console
$ yarn lerna run test
...
Done in 110.33s.
```
---

fix(packages): issues with jest script and configuration

---

package.json

Internal JS-3681
Include dependents when running tests in CI
Verified that test in dependent `middleware-sdk-s3` is run when `types` is updated.
```console
$ git diff
diff --git a/packages/types/src/logger.ts b/packages/types/src/logger.ts
index 48db02d082..9e8a7a82bf 100644
--- a/packages/types/src/logger.ts
+++ b/packages/types/src/logger.ts
@@ -22,7 +22,7 @@ export interface LoggerOptions {
*/
export interface Logger {
trace?: (...content: any[]) => void;
-  debug: (...content: any[]) => void;
+  debug?: (...content: any[]) => void;
info: (...content: any[]) => void;
warn: (...content: any[]) => void;
error: (...content: any[]) => void;
$ yarn test:ci
...
lerna notice cli v5.5.2
lerna notice filter changed since "origin/main"
lerna info Looking for changed packages since origin/main …
```

chore(scripts): include dependents when running tests in CI

---

package.json

CI failure: [sdk-staging-test:a618a080-3694-4f34-904c-fe6aefe4e1d7](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiYkthUUxndUkzQ2FreVlQVlFaUmM2RWU4SXFrd3VwbStjcGZ5NXhORjFlQ1BnTlU5RmFJcmdwU2FnSGRhdmo0dVhudlM2Tm1rTG02U1NMaGkydU5LZUFiQlNPSTh6cXVxN1Zta2pMdkhINTduIiwiaXZQYXJhbWV0ZXJTcGVjIjoiblFJTmhOdFkzZ2FEZXZSaCIsIm1hdGVyaWFsU2V0U2VyaWFsIjoxfQ%3D%3D/build/a618a080-3694-4f34-904c-fe6aefe4e1d7)
```console
...
/codebuild/output/src077611159/src/github.com/aws/aws-sdk-js-v3/clients/client-sso-oidc/src/protocols/Aws_restJson1.ts
51:3  error  'body' is never reassigned. Use 'const' instead  prefer-const
82:3  error  'body' is never reassigned. Use 'const' instead  prefer-const
108:3  error  'body' is never reassigned. Use 'const' instead  prefer-const
✖ 3 problems (3 …
```

fix(scripts): skip clients while linting in CI

---

packages/smithy-client/src/emitWarningIfUnsupportedVersion.spec.ts
packages/smithy-client/src/emitWarningIfUnsupportedVersion.ts

Internal JS-3680
Support for Node.js 12.x ended in https://github.com/aws/aws-sdk-js-v3/pull/4123
Skips emitting warning for Node.js 12.x
N/A
Node.js 12.x doesn't parse [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing), so clients will not work in Node.js 12.x
```js
// test.js
const { DynamoDB } = require("../aws-sdk-js-v3/clients/client-dynamodb");
const { S3 } = require("../aws-sdk-js-v3/clients/client-s3");
const dynamodbClient = new DynamoDB();
const s3Client = new S3();
```
```console
$ node -v
v12.22.12
$ node test.js 
/local/home/trivikr/workspace/aws-sdk-js-v3/clients/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3547
ClientRequestToken: input.ClientRequestToken ?? (0, uuid_1.v4)(),
^
SyntaxError: …
```

chore(smithy-client): skip emitting warning for Node.js 12.x

---

clients/client-s3-control/src/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java

internal V750691458
restricts the context param Bucket and uri segment Bucket deduplication to only S3.

fix(client-s3-control): restrict Bucket param dedupe to S3 only

---

clients/client-auto-scaling/src/protocols/Aws_query.ts
clients/client-cloudformation/src/protocols/Aws_query.ts
clients/client-cloudsearch/src/protocols/Aws_query.ts
clients/client-cloudwatch/src/protocols/Aws_query.ts
clients/client-codebuild/src/commands/RetryBuildCommand.ts
clients/client-docdb/src/protocols/Aws_query.ts
clients/client-ec2/src/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing/src/protocols/Aws_query.ts
clients/client-elasticache/src/protocols/Aws_query.ts
clients/client-iam/src/protocols/Aws_query.ts
clients/client-managedblockchain/src/commands/ListNodesCommand.ts
clients/client-neptune/src/protocols/Aws_query.ts
clients/client-rds/src/protocols/Aws_query.ts
clients/client-redshift/src/protocols/Aws_query.ts
clients/client-ses/src/protocols/Aws_query.ts
clients/client-sns/src/protocols/Aws_query.ts
clients/client-sqs/src/protocols/Aws_query.ts
clients/client-sts/src/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/QueryShapeSerVisitor.java
private/aws-protocoltests-ec2/src/protocols/Aws_ec2.ts
private/aws-protocoltests-ec2/test/functional/ec2query.spec.ts
private/aws-protocoltests-json/test/functional/awsjson1_1.spec.ts
private/aws-protocoltests-query/src/protocols/Aws_query.ts
private/aws-protocoltests-query/test/functional/awsquery.spec.ts

- set an empty array for empty list/set collections in aws query
- aims to fix https://github.com/aws/aws-sdk-js-v3/issues/3896
previous
```js
RollbackConfiguration: {
RollbackTriggers: []
}
->
// (no serialization of this empty list)
```
proposed
```js
RollbackConfiguration: {
RollbackTriggers: []
}
->
"RollbackConfiguration.RollbackTriggers": []
```

fix(codegen): aws-query protocol, distinguish explicit empty list

---

packages/util-endpoints/src/utils/evaluateErrorRule.ts
packages/util-endpoints/src/utils/evaluateTemplate.spec.ts
packages/util-endpoints/src/utils/evaluateTemplate.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4121
Use a simple custom parser for evaluating template instead of RegExp or Function
Unit testing
---

fix(util-endpoints): evaluateTemplate implementation without RegExp/Function

---

packages/chunked-blob-reader-native/package.json
packages/chunked-blob-reader-native/src/index.ts
packages/fetch-http-handler/karma.conf.js
packages/fetch-http-handler/package.json
packages/fetch-http-handler/src/stream-collector.ts
packages/md5-js/package.json
packages/md5-js/src/index.spec.ts
packages/util-stream-browser/package.json
packages/util-stream-browser/src/sdk-stream-mixin.spec.ts
packages/util-stream-browser/src/sdk-stream-mixin.ts
packages/xhr-http-handler/package.json

Internal JS-3705
Respective PR for clients https://github.com/aws/aws-sdk-js-v3/pull/4140
Replaces dependency util-base64-* with util-base64
Node.js and Browser testing was done in https://github.com/aws/aws-sdk-js-v3/pull/4140
---

chore(packages): replace util-base64-* with util-base64

---

codegen/gradle.properties

Internal JS-3822
Pin smithy-cli version to 1.26.1, as there's an issue downloading range of versions from JCenter
<details>
```console
$ yarn generate-clients
...
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':generic-client-test-codegen'.
> Could not resolve all artifacts for configuration ':generic-client-test-codegen:classpath'.
> Could not resolve software.amazon.smithy:smithy-cli:[1.26.0,1.27.0[.
Required by:
project :generic-client-test-codegen
> Failed to list versions for software.amazon.smithy:smithy-cli.
> Unable to load Maven meta-data from https://plugins.gradle.org/m2/software/amazon/smithy/smithy-cli/maven-metadata.xml.
> Could not get resource …
```

fix(codegen): pin smithy-cli version to 1.26.1

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts

https://github.com/aws/aws-sdk-js-v3/issues/4109
endpoints rulesets can resolve with the bucket already prefixed in the hostname, but custom endpoints might not include it. Therefore this PR proposes that we check for the bucket prefix when constructing an upload Location.
This is a best-guess heuristic. If someone has an identical hostname and bucket like hostname `abcd.com` and a bucket of `abcd`, it will not append the bucket name to create `abcd.abcd.com/key`. In such cases the user will have to specify a hostname including the bucket name.
added unit tests

fix(lib-storage): fix bucket duplication in hostname

---

packages/credential-provider-ini/src/resolveSsoCredentials.spec.ts
packages/credential-provider-ini/src/resolveSsoCredentials.ts
packages/credential-provider-sso/package.json
packages/credential-provider-sso/src/fromSSO.spec.ts
packages/credential-provider-sso/src/fromSSO.ts
packages/credential-provider-sso/src/isSsoProfile.spec.ts
packages/credential-provider-sso/src/isSsoProfile.ts
packages/credential-provider-sso/src/resolveSSOCredentials.spec.ts
packages/credential-provider-sso/src/resolveSSOCredentials.ts
packages/credential-provider-sso/src/types.ts
packages/credential-provider-sso/src/validateSsoProfile.spec.ts
packages/credential-provider-sso/src/validateSsoProfile.ts
packages/shared-ini-file-loader/src/getSSOTokenFilepath.ts
packages/shared-ini-file-loader/src/getSSOTokenFromFile.ts
packages/token-providers/src/fromSso.spec.ts
packages/token-providers/src/fromSso.ts
packages/token-providers/src/validateTokenKey.spec.ts
packages/token-providers/src/validateTokenKey.ts
packages/token-providers/src/writeSSOTokenToFile.ts

internal JS-3637
- use the SSO token provider if a compatible sso profile format is detected.
Additional test instructions will be documented internally.

feat(sso): use SSOTokenProvider in SSOCredentialProvider

---

package.json
scripts/docs-custom-js/aws-footer.js
scripts/docs-custom-js/index.js
scripts/docs-custom-js/prepend-script.js

internal JS-3710
Modifies docs build to prepend a script customization to the docs main.js script file. This applies a footer from AWS Docs.
ran `yarn build:docs`

chore(docs): add docs footer customization

---

packages/smithy-client/src/NoOpLogger.ts
packages/smithy-client/src/index.ts

internal JS-3687 and https://github.com/aws/aws-sdk-js-v3/issues/4113
Added a no-op logger implementation to be used as default in clients.

fix(clients): use default no-op logger to preserve type safety

---

packages/util-base64-browser/README.md
packages/util-base64-node/README.md

Internal JS-3705
* A single module `util-64` was created in https://github.com/aws/aws-sdk-js-v3/pull/4137
* The runtime specific modules were replaced in https://github.com/aws/aws-sdk-js-v3/pull/4140
Adds deprecation message in README of runtime specific modules
N/A
---

docs(util-base64): add deprecation in README of runtime specific modules

---

private/aws-echo-service/src/runtimeConfig.shared.ts
private/aws-protocoltests-ec2/src/runtimeConfig.shared.ts
private/aws-protocoltests-json-10/src/runtimeConfig.shared.ts
private/aws-protocoltests-json/src/runtimeConfig.shared.ts
private/aws-protocoltests-query/src/runtimeConfig.shared.ts
private/aws-protocoltests-restjson/src/runtimeConfig.shared.ts
private/aws-protocoltests-restxml/src/runtimeConfig.shared.ts

Skipped in https://github.com/aws/aws-sdk-js-v3/pull/4171
Uses default no-op logger in aws-protocoltests
N/A
---

fix(aws-procotoltests): use default no-op logger

---

packages/credential-provider-sso/src/fromSSO.spec.ts
packages/credential-provider-sso/src/fromSSO.ts

https://github.com/aws/aws-sdk-js-v3/issues/4183
Add existence check to `profile.sso_session` access.

fix(credential-provider-sso): add existence check to profile

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointsV2ParameterNameMap.java

internal JS-3690
Sometimes this map is not set when the Smithy Command Generator is running, leading to incorrect names being written to the Command classes.
- because setting the map is no-op, it is ok to trigger it additional times
- this PR adds additional calls to set the map on the Integration event methods "customize" and "preprocessModel".

fix(codegen): trigger endpoints param name map setter on additional events

---

features/ec2/step_definitions/ec2.js
features/extra/helpers.js
features/s3/step_definitions/buckets.js

Our feature tests (`npx cucumber-js`) currently stall with no output when certain preconditions are not met, such as
AWS config in ~/.aws/config missing region, or no unexpired credentials in default chain.
This change surfaces errors so the developer knows what to do to continue testing. 
```
npx cucumber-js
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```

chore(e2e): surface errors better in e2e test helper

---

features/s3/step_definitions/buckets.js

followup to https://github.com/aws/aws-sdk-js-v3/pull/4195
noticed that the bucket is expected to be unset synchronously
```
npx cucumber-js
....................................................................................................................................................................................................
....................................................................................................................................................................................................
....................................................................................................................................................................................................
.................................................................... …
```

chore(e2e): unset bucket synchronously

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEc2.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsQuery.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientCommandGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/Ec2ShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java
packages/token-providers/README.md
packages/types/src/shapes.ts
packages/util-waiter/src/poller.ts

n/a
The smithy docs are now located at smithy.io, so this updates all the links to point there. It also makes sure they point to idl 2.0.
All links were checked manually
https://github.com/awslabs/smithy-typescript/pull/637
---

Update links to point to smithy.io

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/doc-client-utils.ts
lib/lib-dynamodb/src/commands/utils.ts
packages/util-dynamodb/src/convertToNative.spec.ts
packages/util-dynamodb/src/convertToNative.ts

https://github.com/aws/aws-sdk-js-v3/issues/4151
paired with https://github.com/awslabs/smithy-typescript/pull/638
- reduce object copying in iterators
This reducer style makes pointless object copies via `{ ...acc}`:
```js
.reduce((acc, [key, val]) => ({ ...acc, [key]: val }), {});
```
We know that removing these copies will have no side-effects because the initial accumulator value is `{}`, and not an external object that should not be mutated.
New pattern:
```js
.reduce((acc, [key, val]) => (acc[key] = val, acc), {});
```

chore(lib-dynamodb): reduce object copying in iterators

---

.github/workflows/codegen-ci.yml

The v3 uses Node.js 16 LTS instead of EoL 12 https://github.com/actions/checkout/blob/main/CHANGELOG.md#v300
Bumps actions/checkout to v3
CI
---

chore(ci): bump actions/checkout to v3

---

.github/workflows/codegen-ci.yml

The v1 internally uses Node.js 12 actions which are deprecated.
Example run: https://github.com/aws/aws-sdk-js-v3/actions/runs/3484641753
Bumps actions/setup-java to v3
The warnings related to actions/setup-java are removed in CI run https://github.com/aws/aws-sdk-js-v3/actions/runs/3490394233
---

chore(ci): bump actions/setup-java to v3

---

.github/workflows/codegen-ci.yml

Refs: https://github.com/awslabs/smithy-typescript/pull/641
We're switching to `corretto` distribution as it's used internally at Amazon
Switches to corretto distribution in setup-java
CI
---

chore(ci): switch to corretto distribution in setup-java

---

packages/util-utf8/.gitignore
packages/util-utf8/CHANGELOG.md
packages/util-utf8/LICENSE
packages/util-utf8/README.md
packages/util-utf8/jest.config.js
packages/util-utf8/package.json
packages/util-utf8/src/fromUtf8.browser.spec.ts
packages/util-utf8/src/fromUtf8.browser.ts
packages/util-utf8/src/fromUtf8.spec.ts
packages/util-utf8/src/fromUtf8.ts
packages/util-utf8/src/index.ts
packages/util-utf8/src/toUint8Array.spec.ts
packages/util-utf8/src/toUint8Array.ts
packages/util-utf8/src/toUtf8.browser.spec.ts
packages/util-utf8/src/toUtf8.browser.ts
packages/util-utf8/src/toUtf8.spec.ts
packages/util-utf8/src/toUtf8.ts
packages/util-utf8/tsconfig.cjs.json
packages/util-utf8/tsconfig.es.json
packages/util-utf8/tsconfig.types.json

Internal JS-3708
Create a new package with merged utf8 node and browser implementations
yarn build && yarn test
TODO: deprecate utf8 node and browser packages in a subsequent PR
---

feat(util-utf8): merge node and browser implementations

---

packages/types/src/checksum.ts
packages/types/src/crypto.ts
packages/types/src/index.ts

Add checksum interface
yarn test:all
---

feat(types): add checksum interface

---

packages/types/src/index.ts
packages/types/src/retry.ts
packages/util-retry/CHANGELOG.md
packages/util-retry/LICENSE
packages/util-retry/README.md
packages/util-retry/jest.config.js
packages/util-retry/package.json
packages/util-retry/src/AdaptiveRetryStrategy.spec.ts
packages/util-retry/src/AdaptiveRetryStrategy.ts
packages/util-retry/src/DefaultRateLimiter.spec.ts
packages/util-retry/src/DefaultRateLimiter.ts
packages/util-retry/src/StandardRetryStrategy.spec.ts
packages/util-retry/src/StandardRetryStrategy.ts
packages/util-retry/src/config.ts
packages/util-retry/src/constants.ts
packages/util-retry/src/defaultRetryBackoffStrategy.spec.ts
packages/util-retry/src/defaultRetryBackoffStrategy.ts
packages/util-retry/src/defaultRetryToken.spec.ts
packages/util-retry/src/defaultRetryToken.ts
packages/util-retry/src/index.ts
packages/util-retry/src/types.ts
packages/util-retry/tsconfig.cjs.json
packages/util-retry/tsconfig.es.json
packages/util-retry/tsconfig.types.json

This PR adds the `util-retry` package, which adds `StandardRetryStrategy` and `AdaptiveRetryStrategy`.
These changes were broken out of the draft PR https://github.com/aws/aws-sdk-js-v3/pull/4187.
`middleware-retry` will be updated in another PR to use these new retry strategies.
---

feat(utl-retry): add util-retry package and its types

---

lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.spec.ts
lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.ts
packages/middleware-logger/src/loggerMiddleware.spec.ts
packages/middleware-logger/src/loggerMiddleware.ts
packages/types/src/middleware.ts

https://github.com/aws/aws-sdk-js-v3/issues/3846
DynamoDBDocument client changes input and output shapes. The logger middleware calls filter functions that expect the base shapes and results in errors.
in this PR:
- in logger middleware, use the overrides for log filtering if they exist
- in dynamodbdocument base command, use the previously implemented middleware to insert overrides for log filtering into the handler context
This ensures filtering functions are called on the original input and output shapes unaffected by dynamodbdocument marshaling. 
manual Put and Query command using the dynamodbdocument client.

fix(lib-dynamodb): fix use of log filters in conjunction with DynamDBDocumentClient

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java

internal JS-3641
- let the AWS auth plugin set the default signing name, instead of Smithy-TS.
paired with https://github.com/awslabs/smithy-typescript/pull/652
`yarn generate-clients`, verified no diff resulted

chore(codegen): awsAuthPlugin to set default signing name

---

packages/credential-provider-ini/src/resolveProcessCredentials.spec.ts
packages/credential-provider-ini/src/resolveProcessCredentials.ts
packages/credential-provider-ini/src/resolveProfileData.ts

#3505 
Allows credential-provider-ini to get the source profile from a process
See repro steps in #3505
---

Allow loading credentials from credential_process referenced from a source_profile

---

packages/credential-provider-node/README.md

I've filed no issue for this.
As a user of IRSA, I found this bit of documentation to be misleading both verbally and programmatically.
You need to invoke `getDefaultRoleAssumerWithWebIdentity`, otherwise everything goes inscrutably wrong if you don't have typescript to save you.
I have not tested this change, beyond verifying that everything was horribly busted using the example code verbatim and is now fixed with my changes.
---

docs(credential-provider-node): clarify IRSA boilerplate, fix example code

---

packages/cloudfront-signer/src/sign.spec.ts
packages/cloudfront-signer/src/sign.ts

getSIgnedUrl need new params of passphrase of RSA Key.
- Issue #4231
Add new params of passphrase to fix issue.
Add new sample of passpharse to fix issue.
But, in testcode, aws have string type of privateKey.
So, I sugggest new privateKey and passphrase from AWS officials.
Please consider its.
Now, getSignedUrl isn't working...

fix(cloudfront-signer): accept passphrase when signing

---

clients/client-accessanalyzer/src/protocols/Aws_restJson1.ts
clients/client-amp/src/protocols/Aws_restJson1.ts
clients/client-amplifyuibuilder/src/protocols/Aws_restJson1.ts
clients/client-codeguruprofiler/src/protocols/Aws_restJson1.ts
clients/client-connect/src/protocols/Aws_restJson1.ts
clients/client-finspace-data/src/protocols/Aws_restJson1.ts
clients/client-iotfleethub/src/protocols/Aws_restJson1.ts
clients/client-iotsitewise/src/protocols/Aws_restJson1.ts
clients/client-scheduler/src/protocols/Aws_restJson1.ts
clients/client-wellarchitected/src/protocols/Aws_restJson1.ts
private/aws-protocoltests-restjson/src/protocols/Aws_restJson1.ts
private/aws-protocoltests-restxml/src/protocols/Aws_restXml.ts

internal P75309097
Currently we provide a default idempotency token (uuid v4) if a request structure member has the smithy trait.
We do not provide one if the member is a query parameter. 
- This PR adds the idempotency default token (`uuid.v4()`) for query parameters. 
from https://smithy.io/1.0/spec/core/behavior-traits.html#idempotencytoken-trait
> A unique identifier (typically a [UUID](https://tools.ietf.org/html/rfc4122)) SHOULD be used by the client when providing the value for the request token member. When the request token is present, the service MUST ensure that the request is not replayed within a service-defined period of time. This allows the client to safely retry operation invocations, including operations that are not read-only, that fail due to networking issues or …

fix(codegen): generate idempotencyToken default for queryParams

---

private/aws-client-retry-test/src/ClientRetryTest.spec.ts

followup to https://github.com/aws/aws-sdk-js-v3/pull/4274
switch the sample client to S3, which is already known to be built since tests in `private/aws-client-api-test` work.

fix(aws-client-retry-test): use s3 client in case x-ray is not built

---

packages/config-resolver/src/endpointsConfig/resolveCustomEndpointsConfig.spec.ts
packages/config-resolver/src/endpointsConfig/resolveCustomEndpointsConfig.ts
packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.spec.ts
packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts
packages/config-resolver/src/regionConfig/resolveRegionConfig.spec.ts
packages/config-resolver/src/regionConfig/resolveRegionConfig.ts

#4270
We will fallback to a `false` value whenever the client SDKs input properties `useDualstackEndpoint` and `useFipsEndpoint` are not set instead of using the TypeScript Non-null assertion operator (`!`).
Unit tests
N/A
---

fix(config-resolver): replace non-null assertions

---

clients/client-s3/test/e2e/S3.ispec.ts

I need to disable this test temporarily to unblock preview builds so I can work on a different issue.

chore(client-s3): disable a failing test temporarily

---

private/aws-protocoltests-ec2/test/functional/ec2query.spec.ts
private/aws-protocoltests-json-10/test/functional/awsjson1_0.spec.ts
private/aws-protocoltests-json/test/functional/awsjson1_1.spec.ts
private/aws-protocoltests-query/test/functional/awsquery.spec.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts
private/aws-protocoltests-restxml/test/functional/restxml.spec.ts
private/aws-restjson-server/test/functional/restjson1.spec.ts
private/aws-restjson-validation-server/test/functional/restjson1.spec.ts

* https://github.com/awslabs/smithy-typescript/pull/645
* https://github.com/awslabs/smithy-typescript/pull/657
Adds generated code for error printout and broken reference to fail
CI
---

fix(private): error printout and broken reference to fail

---

clients/client-s3-control/src/S3ControlClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java
packages/middleware-sdk-s3-control/src/host-prefix-deduplication/deduplicateHostPrefix.spec.ts
packages/middleware-sdk-s3-control/src/host-prefix-deduplication/deduplicateHostPrefix.ts
packages/middleware-sdk-s3-control/src/host-prefix-deduplication/hostPrefixDeduplicationMiddleware.ts
packages/middleware-sdk-s3-control/src/index.ts

revealed by https://github.com/aws/aws-sdk-js-v3/pull/4284
deduplicates identical position 1 and position 2 host prefixes in s3-control.

fix(client-s3-control): add prefix dedupe middleware

---

packages/smithy-client/src/default-error-handler.ts

https://github.com/aws/aws-sdk-js-v3/issues/4209
add 3rd variation off amzn request id to header detection
CI

fix(smithy-client): add header check for x-amz-request-id

---

packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts
packages/config-resolver/src/regionConfig/resolveRegionConfig.spec.ts
packages/config-resolver/src/regionConfig/resolveRegionConfig.ts

follow up to https://github.com/aws/aws-sdk-js-v3/pull/4279
- slightly more type safe `useFipsEndpoint` function
- add deprecation message to resolveEndpointsConfig

chore(config-resolver): update useFipsEndpoint resolution

---

packages/credential-provider-ini/package.json
packages/middleware-retry/package.json

https://github.com/aws/aws-sdk-js-v3/issues/4264
This PR adds the following missing dependencies:
* Adds `@aws-sdk/credential-provider-process` to `@aws-sdk/credential-provider-ini`
* Adds `@aws-sdk/util-retry` to `@aws-sdk/middleware-retry`
N/A
N/A
---

Add missing `credential-provider-process` and `util-retry` dependencies

---

scripts/cli-dispatcher/index.js
scripts/cli-dispatcher/lib/Package.js
scripts/cli-dispatcher/lib/findFolders.js
scripts/cli-dispatcher/lib/findScripts.js
scripts/cli-dispatcher/lib/matchSorter.js
scripts/cli-dispatcher/lib/matcher.js
scripts/cli-dispatcher/readme.md
scripts/cli-dispatcher/set-alias.sh

n/a
This adds an optional CLI helper.
I have spent a fair amount of time in CLI navigating across folders in clients, packages, etc and running commands like `yarn build` or `yarn test`. 
This CLI helper assists in the dispatch of commands to package contexts.
Command bin/exe
```
b # if you apply the suggested alias
```
Usage examples
```
b s3 - b
```
yarn **b**uild in clients/client-**s3**
```
b mar ent - doc
```
yarn build:**doc**s in clients/client-**mar**ketplace-**ent**itlement-service
```
b m sign - t
```
yarn **t**est in packages/**m**iddleware-**sign**ing
```
b (package name query) - (npm script query)
```
The package name query is used to find the package within clients, lib, or packages, and the npm script query is used to 
find a command to execute.
In both queries, you can use …

chore(scripts): add cli dispatcher helper

---

packages/xhr-http-handler/src/xhr-http-handler.spec.ts
packages/xhr-http-handler/src/xhr-http-handler.ts

https://github.com/aws/aws-sdk-js-v3/issues/4250
Add a wrapper to allow consistent identification of errors coming from the xhr-http-handler of the SDK.
added unit test

feat(xhr-http-handler): add consistent wrapper to XHR error handler

---

.github/workflows/codegen-ci.yml
codegen/build.gradle.kts

https://github.com/awslabs/smithy-typescript/issues/632
Upgrading to support Java 17 in smithy-typescript and AWS specific code generation, which will impact the artifact [`software.amazon.smithy.typescript:smithy-aws-typescript-codegen`](https://mvnrepository.com/artifact/software.amazon.smithy.typescript/smithy-aws-typescript-codegen).
1. Built smithy-typescript and aws-sdk-js-v3 locally
2. CI checks
N/A.
---

chore(codegen): upgrade to Java 17

---

private/aws-protocoltests-ec2/src/endpoints.ts
private/aws-protocoltests-json-10/src/endpoints.ts
private/aws-protocoltests-json/src/endpoints.ts
private/aws-protocoltests-query/src/endpoints.ts
private/aws-protocoltests-restjson/src/endpoints.ts
private/aws-protocoltests-restxml/src/endpoints.ts

Release automation is no longer updating protocoltests endpoints.
This can be taken up when protocoltests move to endpoints 2.0
Update endpoints for protocol tests.
CI
---

chore(protocoltests): update endpoints

---

packages/eventstream-serde-node/src/EventStreamMarshaller.ts

N/A, noticed while browsing code.
Removes the check for Readable.from as it's available in all Node.js supported by v3 (14+)
Docs: https://nodejs.org/api/stream.html#streamreadablefromiterable-options
The integration tests in transcribe streaming is successful
```console
$ client-transcribe-streaming> node -v
v14.0.0
$ client-transcribe-streaming> yarn test:integration
$ jest --config jest.integ.config.js
PASS  test/index.integ.spec.ts (9.137 s)
TranscribeStream client
✓ should stream the transcript (5081 ms)
Tests:       1 passed, 1 total
Time:        9.192 s
Done in 10.03s
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

chore(eventstream-serde-node): use Readable.from for serializing

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
packages/middleware-api-key/.gitignore
packages/middleware-api-key/LICENSE
packages/middleware-api-key/README.md
packages/middleware-api-key/jest.config.js
packages/middleware-api-key/package.json
packages/middleware-api-key/src/configurations.spec.ts
packages/middleware-api-key/src/configurations.ts
packages/middleware-api-key/src/index.ts
packages/middleware-api-key/src/middleware.spec.ts
packages/middleware-api-key/src/middleware.ts
packages/middleware-api-key/tsconfig.cjs.json
packages/middleware-api-key/tsconfig.es.json
packages/middleware-api-key/tsconfig.types.json
packages/middleware-token/src/getTokenPlugin.spec.ts
packages/middleware-token/src/getTokenPlugin.ts
packages/middleware-token/src/tokenMiddleware.spec.ts
packages/middleware-token/src/tokenMiddleware.ts
packages/types/src/auth.ts
packages/types/src/middleware.ts

We will create a new middleware to handle API keys in the context of Smithy generated models (probably not applicable for AWS specific services). The code is based heavily on [this PR](https://github.com/awslabs/smithy-typescript/pull/473) from the Smithy TypeScript repository.
In order for it to work, we need to ensure the Bearer token middleware succeeds even when the `token` is not set. 
Unit tests
---

feat(middleware-api-key): add new auth middleware

---

clients/client-s3/src/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java

This PR updates serialization for restXml where a timestampFormat is on the target.
This clears the way to upgrade Smithy past 1.26.1, picking up the protocol tests for timestampFormat added in https://github.com/awslabs/smithy/pull/1440.
Made change, ran `yarn generate-clients`. Successfully ran `yarn test:protocols` as well.
Additionally, the version of Smithy in `codegen/gradle.properties` and these changes were confirmed with the added protocol tests in https://github.com/awslabs/smithy/pull/1440.
A separate PR will be submitted after this is merged to update Smithy to the latest, 1.27.1, along with the updated protocol tests that will include.
---
By submitting this pull request, I confirm that you can use, modify, copy, and …

fix(clients): fix restXml protocol test for timestampFormat targets

---

package.json
packages/body-checksum-browser/package.json
packages/body-checksum-browser/src/index.spec.ts
packages/body-checksum-node/package.json
packages/body-checksum-node/src/index.spec.ts
packages/eventstream-codec/package.json
packages/eventstream-codec/src/EventStreamCodec.spec.ts
packages/eventstream-codec/src/HeaderMarshaller.spec.ts
packages/eventstream-handler-node/package.json
packages/eventstream-handler-node/src/EventSigningStream.spec.ts
packages/eventstream-serde-node/package.json
packages/eventstream-serde-universal/package.json
packages/eventstream-serde-universal/src/getUnmarshalledStream.spec.ts
packages/md5-js/package.json
packages/md5-js/src/index.ts
packages/sha256-tree-hash/package.json
packages/sha256-tree-hash/src/index.spec.ts
packages/util-stream-browser/package.json
packages/util-stream-browser/src/sdk-stream-mixin.spec.ts
packages/util-stream-browser/src/sdk-stream-mixin.ts

chore(util-utf8): import fromUtf8 and toUtf8 from util-utf8
Also see https://github.com/awslabs/smithy-typescript/pull/672
yarn test:all
---

chore(packages): import fromUtf8 and toUtf8 from util-utf8

---

packages/node-config-provider/src/configLoader.spec.ts
packages/node-config-provider/src/fromEnv.spec.ts
packages/node-config-provider/src/fromEnv.ts

node-config-provider
Changed the NodeJS.ProcessEnv type (in the node-config-provider package), to a Record<string, string | undefined> type. This removes the dependency on @types/node for the node-config-provider. This means that when the types are compiled there is no reliance on it and it can be therefore used in more non-node environments, for example cloudflare worker environments, without any type mismatches or errrors.
Changed the type of `envVarGetter` variable in the `fromEnv.spec.ts` file, to match the new type file. Because its only a type change, there is only minimal test changes.
---

fix(types): changed NodeJS.ProcessEnv type to Record in node-config-provider

---

private/aws-client-api-test/src/client-interface-tests/client-s3/impl/initializeWithMaximalConfiguration.ts

Internal JS-3708
Import fromUtf8 and toUrf8 from util-utf8 in aws-client-api-test
CI
---

chore(aws-client-api-test): import fromUtf8 and toUrf8 from util-utf8

---

package.json

CI failure in PR: https://github.com/aws/aws-sdk-js-v3/pull/4368
CodeBuild run: https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiYkthUUxndUkzQ2FreVlQVlFaUmM2RWU4SXFrd3VwbStjcGZ5NXhORjFlQ1BnTlU5RmFJcmdwU2FnSGRhdmo0dVhudlM2Tm1rTG02U1NMaGkydU5LZUFiQlNPSTh6cXVxN1Zta2pMdkhINTduIiwiaXZQYXJhbWV0ZXJTcGVjIjoiblFJTmhOdFkzZ2FEZXZSaCIsIm1hdGVyaWFsU2V0U2VyaWFsIjoxfQ%3D%3D/build/5fcc87f8-479a-498d-99e9-000192b488b1
Builds util-utf8-browser in build:crypto-dependencies as `@aws-crypto/*` packages still depend on it.
Code search: https://github.com/search?q=repo%3Aaws%2Faws-sdk-js-crypto-helpers%20util-utf8-browser&type=code
Verified that the tests for middleware-flexible-checksums succeed
```console
$ yarn build:crypto-dependencies
...
$ yarn lerna run build --scope …
```

fix(package.json): build util-utf8-browser in build:crypto-dependencies

---

packages/util-utf8-browser/README.md
packages/util-utf8-node/README.md

A single module util-utf8 was created in https://github.com/aws/aws-sdk-js-v3/pull/4206
The runtime specific modules were replaced in https://github.com/awslabs/smithy-typescript/pull/672
Adds  deprecation in README of runtime specific modules for util-utf8
util-utf8-node
util-utf8-browser
---

docs(util-utf8): add deprecation in README of runtime specific modules

---

packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts

internal
append content-encoding aws-chunked instead of replacing it
unit tests, manual s3 putObject test
```js
const { S3 } = require("@aws-sdk/client-s3");
const { Readable } = require("stream");
(async () => {
const s3 = new S3({});
s3.middlewareStack.add(
(next, context) => async (args) => {
const result = await next(args);
console.log(args.request);
return result;
},
{
step: "finalizeRequest",
name: "x",
tags: [],
}
);
await s3.putObject({
Bucket: "......",
Key: "temp.txt",
Body: Readable.from(Buffer.from("abcdefg")),
ContentLength: 7,
ContentEncoding: "gzip",
ChecksumAlgorithm: "SHA1",
});
})();
```

fix(middleware-flexible-checksums): append aws-chunked to content-encoding

---

.github/CODEOWNERS

The CODEOWNERS file was set up with incorrect syntax and precedence rules. Previously, the syntax meant that smithy were owners on only files in the root of each specified directory, but not any subdirectories. Additionally, the precedence rules meant that Smithy would be codeowners on these files, rather than both the Smithy team and JS team. This PR fixes both issues.
N/A
[Codeowners documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
---

fix(codeowners): fix syntax and precedence

---

tests/e2e/IntegTestResourcesStack.template.json
tests/e2e/get-integ-test-resources.js

n/a
Add a versioning and encryption policy to the e2e test bucket cloudformation template.
I deployed the stack to my personal account, which validates the JSON.

chore(e2e): add bucket versioning and encryption policies

---

packages/smithy-client/src/date-utils.spec.ts
packages/smithy-client/src/date-utils.ts

https://github.com/awslabs/smithy/pull/1502 introduced protocol test coverage for datetimes with offsets for clients.
This PR adds a `parseRfc3339DateTimeWithOffset` function to handle positive and negative offsets.
For now, the function is unused by any clients.
This was tested in conjunction with [smithy-typescript changes](https://github.com/awslabs/smithy-typescript/pull/681) to use the `parseRfc3339DateTimeWithOffset` function in place of the existing `parseRfc3339DateTime` function for clients.  `parseRfc3339DateTime` is retained for servers. `yarn generate-clients && yarn test:protocols` was successfully run.
The smithy-typescript changes will be paired with codegen changes to use the new parsing function within clients.
Add any other …

feat(smithy-client): parse datetime offsets

---

clients/client-s3/test/e2e/S3.ispec.ts

n/a
- fix the test setup for S3 ispec MRAP to push to the MRAP bucket and not the default bucket.
- otherwise the MRAP bucket could be empty and fail the test assertion even though it is correct
s3 e2e ispec tests

chore(client-s3): fix mrap integration test

---

clients/client-s3/test/e2e/S3.ispec.ts

MRAP bucket calls are not available by default in the browser

chore(client-s3): use mrap when not browser

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

N/A
Bump code generator versions to 0.13.0
N/A
CI will fail until awslabs/smithy-typescript#673 is merged. See [personal branch pointed to smithy-typescript](https://github.com/syall/aws-sdk-js-v3/commit/28c200717f3e629ffa352fa017338561f742be95) to see that the Codegen CI passes.
---

chore(codegen): bump code generators to 0.13.0

---

packages/s3-presigned-post/package.json

Internal JS-4004
deactivate e2e in s3-presigned-post temporarily to investigate automated test

chore(s3-presigned-post): temporarily deactivate e2e

---

packages/middleware-sdk-transcribe-streaming/src/websocket-handler.spec.ts
packages/middleware-sdk-transcribe-streaming/src/websocket-handler.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/3922
Closes sockets on WebSocketHandler.destroy()
CI
---

fix(middleware-sdk-transcribe-streaming): close sockets on WebSocketHandler.destroy()

---

packages/protocol-http/src/Field.ts
packages/protocol-http/src/FieldPosition.ts
packages/protocol-http/src/Fields.ts

Adds `Field`, `FieldPosition`, and `Fields` types to `protocol-http`.
`yarn test:all`
---

feat(protocol-http): add types for field

---

features/dynamodb/tables.feature

Internal JS-4012
Removes the "error should be" testing from the improper table deletion scenario
---

fix(features-dynamodb): remove testing for error-should-be message

---

packages/types/src/serde.ts

#4204
Declare `Blob` type without requiring dom.
1. GitHub CI
2. `yarn build`
N/A.
---

fix(types): declare Blob type without requiring dom

---

packages/types/src/dns.ts
packages/types/src/index.ts
packages/util-dns/CHANGELOG.md
packages/util-dns/LICENSE
packages/util-dns/README.md
packages/util-dns/jest.config.js
packages/util-dns/package.json
packages/util-dns/src/HostResolver.browser.spec.ts
packages/util-dns/src/HostResolver.browser.ts
packages/util-dns/src/HostResolver.spec.ts
packages/util-dns/src/HostResolver.ts
packages/util-dns/src/NodeDnsLookupHostResolver.spec.ts
packages/util-dns/src/NodeDnsLookupHostResolver.ts
packages/util-dns/src/NodeDnsResolveHostResolver.spec.ts
packages/util-dns/src/NodeDnsResolveHostResolver.ts
packages/util-dns/src/index.browser.ts
packages/util-dns/src/index.ts
packages/util-dns/tsconfig.cjs.json
packages/util-dns/tsconfig.es.json
packages/util-dns/tsconfig.types.json

N/A.
---
Adds a new DNS interface `HostResolver` and implementations for both Node.js and browser-like platforms.
This PR adds 2 commits:
- feat(types): add DNS interfaces
- feat(util-dns): add initial HostResolver implementations
---
1. GitHub CI passes
2. In `packages/util-dns`:
- `yarn build`
- `yarn build:include:deps`
- `yarn test`
---
N/A.
---

feat(types): add DNS interfaces, feat(util-dns): add initial HostResolver implementations

---

features/cloudfront/cloudfront.feature
features/elb/elb.feature
features/opsworks/opsworks.feature
features/rds/rds.feature
features/s3/objects.feature
features/storagegateway/storagegateway.feature

Internal JS-4016
The PR https://github.com/aws/aws-sdk-js-v3/pull/4415 missed to prefix error while checking error status codes.
If error prefix is not present, the code checks for metadata from `this.data`
https://github.com/aws/aws-sdk-js-v3/blob/96459bc78eca6d9fb05a9478d1ddd5a7428c0fd1/features/extra/hooks.js#L103-L106
Verified that integration test is successful
```console
$ yarn test:integration:legacy
...
147 scenarios (147 passed)
488 steps (488 passed)
1m14.666s (executing steps: 1m13.799s)
Done in 76.61s.
```
---

fix: prefix error when checking for error status codes

---

packages/types/src/shapes.ts

Add some explanation around a deprecated type that has no explanation.
n/a

chore(types): add deprecation explanation to SdkError

---

.github/CODEOWNERS

N/A.
Adds @aws/smithy to CODEOWNERS for `util-dns`.
N/A.
N/A.
---

chore(CODEOWNERS): add smithy to CODEOWNERS for util-dns

---

packages/util-dns/src/DnsCache.ts
packages/util-dns/src/NodeDnsLookupHostResolver.ts

noticed by automation
remove getter declarations from interfaces for compatibility. 
build downlevel types in util-dns

fix(util-dns): fix types downlevel compatibility

---

packages/xhr-http-handler/src/xhr-http-handler.ts

Resolve 4417, fix will lose part of XML when request is completed.
#4417
Collect the response flow in `xhr.readyState === XMLHttpRequest.LOADING` which is often missing.
So in `xhr.readyState === XMLHttpRequest.DONE` collect the response flow again to complete.
---

fix(xhr-http-handler): read response body is incomplete

---

packages/s3-presigned-post/package.json
packages/s3-presigned-post/src/createPresignedPost.integ.spec.ts

follows https://github.com/aws/aws-sdk-js-v3/pull/4391
- use real endpoints for URL test to prevent lookup error
- do not attempt to create bucket, an existing one is passed in
- make adaptive rmSync to avoid error noisiness

chore(s3-request-presigner): fix e2e compatibility with test environment

---

codegen/config/checkstyle/checkstyle.xml

Update checkstyle to allow Apache 2.0 short-form license header, that does not include the copyright year.
Existing, long-form copyright headers with years are still allowed.
As files are added or re-written, they should use the short-form license header:
```
/*
* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
* SPDX-License-Identifier: Apache-2.0
*/
```
---

chore(codegen): allow short-form license header

---

clients/client-auto-scaling/package.json
clients/client-cloudformation/package.json
clients/client-cloudfront/package.json
clients/client-cloudsearch/package.json
clients/client-cloudwatch/package.json
clients/client-docdb/package.json
clients/client-ec2/package.json
clients/client-elastic-beanstalk/package.json
clients/client-elastic-load-balancing-v2/package.json
clients/client-elastic-load-balancing/package.json
clients/client-elasticache/package.json
clients/client-iam/package.json
clients/client-neptune/package.json
clients/client-rds/package.json
clients/client-redshift/package.json
clients/client-route-53/package.json
clients/client-s3-control/package.json
clients/client-s3/package.json
clients/client-ses/package.json
clients/client-sns/package.json
clients/client-sqs/package.json
clients/client-sts/package.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
private/aws-protocoltests-ec2/package.json
private/aws-protocoltests-query/package.json
private/aws-protocoltests-restxml/package.json
yarn.lock

https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616
Bump fast-xml-parser to 4.1.2
CI
---

chore(deps): bump fast-xml-parser to 4.1.2

---

packages/middleware-host-header/src/index.spec.ts
packages/middleware-host-header/src/index.ts

Missing port in host header caused issues for smithy-typescript generic clients calling a service running on a non standard port.
The service used host header to build responses (An OICD redirect_url) causing the service's hostname to be referenced without the correct port. 
> The Host request header specifies the host _and_port_ number of the
> server to which the request is being sent.
>
> Host: <host>:<port>
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/host
* Added unit test
* Modified dist-cjs/index.js in node_modules in my generated client and confirmed correct headers are sent, and service responded as expected.
N/A
---

fix(middleware-host-header): add port in host header if defined

---

typedoc.client.json

Omit the ruleset from API docs. The variable names in the file are mangled and not helpful in the API docs list.

chore(docs): omit endpoints ruleset generated files from typedoc

---

packages/smithy-client/src/default-error-handler.ts

Additional fix for [#2861](https://github.com/aws/aws-sdk-js-v3/issues/2861)
After the fix for [#2861](https://github.com/aws/aws-sdk-js-v3/issues/2861) was merged, we are getting `TypeError: Cannot read properties of undefined (reading 'code') at throwDefaultError (/usr/src/service/node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:9:26)` because `parsedBody` can be undefined now
codegen and CI
---

fix(smithy-client): optional param in error handling path

---

packages/protocol-http/src/Fields.ts

N/A
This allows usage of `Fields` class without thinking about case-sensitivity. The actual `Field`s stored by `Fields` maintain their casing.
CI
[Field implementation allows case insensitivity](https://github.com/aws/aws-sdk-js-v3/blob/083d53f44456eabee2863047495355a62e80fa39/packages/protocol-http/src/Field.ts#L16), so we can
normalize them in `Fields`.
---

feat(protocol-http): use lowercase keys in Fields class

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/enums-to-strip.json

* Add unnamed enums to `enums-to-strip.json` to prevent names from being populated. This ensures backwards compatibility.
yarn test:all
---

fix(clients): add unnamed enums to enums-to-strip.json

---

packages/s3-presigned-post/package.json

This is imported in `createPresignedPost.ts`, so must be a listed as a normal dependency to be guaranteed to work. (E.g. yarn PnP will not allow it otherwise.)
---

fix(s3-presigned-post): Move @aws-sdk/client-s3 to a normal dependency

---

packages/middleware-logger/src/loggerMiddleware.spec.ts
packages/middleware-logger/src/loggerMiddleware.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1912
Logs to `logger.error` if the next function rejects or throws.
Other than unit tests, this is essentially the custom middleware I've been using in our auth code for about a week now (including going through our tests).
This probably isn't 100% - e.g. it doesn't test for `logger.info` being present but not a function, and I'm not sure if it's OK to use `?.`.
Note that you can't get the `output` for an error response, since it failed to create it, logically enough!
It's probably worthwhile documenting the logging output format, though I don't know where that should go.
---

feat(middleware-logger): log request errors

---

packages/shared-ini-file-loader/README.md
packages/shared-ini-file-loader/src/loadSharedConfigFiles.ts
packages/shared-ini-file-loader/src/slurpFile.spec.ts
packages/shared-ini-file-loader/src/slurpFile.ts

#3396
Adds an optional property `ignoreCache` to the shared credential loader that allows to ignore the existing cache. So that newly updated credential files can be loaded.
A test case has been added to the unit test suite.
-
---

feat(shared-ini-file-loader): enable uncached credential loading

---

packages/middleware-logger/src/loggerMiddleware.ts

A previous PR https://github.com/aws/aws-sdk-js-v3/pull/4252 changed the order of the `next()` call and filter override retrieval in the logger middleware.
This PR fixes that.
```js
const { DynamoDB } = require("@aws-sdk/client-dynamodb");
const { DynamoDBDocument } = require("@aws-sdk/lib-dynamodb");
const d = new DynamoDB({
// logger: {
//   ...console,
//   debug() {},
// },
});
const c = DynamoDBDocument.from(d);
(async () => {
await c.put({
TableName: "test",
Item: {
id: "123",
NullField: null,
NestedNullField: 5,
Status: "blah",
},
});
console.log(
await c.get({
TableName: "test",
Key: {
id: "123",
},
})
);
})();
```
Above test results in an error without this fix.

fix(middleware-logger): retrieve filter overrides after middleware returns

---

private/aws-protocoltests-ec2/test/functional/ec2query.spec.ts
private/aws-protocoltests-json-10/test/functional/awsjson1_0.spec.ts
private/aws-protocoltests-json/test/functional/awsjson1_1.spec.ts
private/aws-protocoltests-query/test/functional/awsquery.spec.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts
private/aws-protocoltests-restxml/test/functional/restxml.spec.ts
private/aws-restjson-server/test/functional/restjson1.spec.ts
private/aws-restjson-validation-server/test/functional/restjson1.spec.ts

This commit contains changes from the codegen changes in https://github.com/awslabs/smithy-typescript/pull/698. It updates protocol tests to construct the HttpResponse object, instead of using a regular object.
yarn test:protocols
Relevant codegen changes: https://github.com/awslabs/smithy-typescript/pull/698
---

chore(protocoltests): use HttpResponse constructor

---

packages/util-waiter/src/poller.ts
packages/util-waiter/src/utils/sleep.ts
packages/util-waiter/src/utils/validate.ts
packages/util-waiter/src/waiter.ts

n/a
Add TSDoc release tags to util-waiters
Ran `yarn build:all` successfully
---

docs(tsdoc): add release tags to util-waiters

---

packages/smithy-client/src/NoOpLogger.ts
packages/smithy-client/src/client.ts
packages/smithy-client/src/command.ts
packages/smithy-client/src/constants.ts
packages/smithy-client/src/date-utils.ts
packages/smithy-client/src/default-error-handler.ts
packages/smithy-client/src/defaults-mode.ts
packages/smithy-client/src/emitWarningIfUnsupportedVersion.ts
packages/smithy-client/src/exceptions.ts
packages/smithy-client/src/extended-encode-uri-component.ts
packages/smithy-client/src/get-array-if-single-item.ts
packages/smithy-client/src/get-value-from-text-node.ts
packages/smithy-client/src/lazy-json.ts
packages/smithy-client/src/object-mapping.ts
packages/smithy-client/src/parse-utils.ts
packages/smithy-client/src/resolve-path.ts
packages/smithy-client/src/ser-utils.ts
packages/smithy-client/src/split-every.ts

n/a
Add TSDoc release tags to smithy-client
Ran `yarn build:all` successfully
---

docs(tsdoc): add release tags to smithy-client

---

packages/middleware-sdk-ec2/src/fixture.ts
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-ec2/src/index.ts

internal request
explanation inline with code
tested locally with
```js
const ec2 = new EC2Client({ region: "us-iso-east-1" });
const copySnapshotCommand = new CopySnapshotCommand({
SourceRegion: "us-iso-west-1",
SourceSnapshotId: "snap-0c5f208e931abe79f",
});
```
and confirmed that the request used the source region's resolved endpoint for the presigned url and the target region's resolved endpoint for the regular request.

fix(middleware-sdk-ec2): use endpoints v2 for source region endpoint

---

packages/core-packages-documentation-generator/src/sdk-index-link-client.ts
packages/core-theme-documentation-generator/src/theme.tsx
typedoc.client.json

Correct base path for Api reference
`yarn build:all && yarn build:docs`
P83685987
---

fix(docs): change basepath to render correctly in prod

---

scripts/generate-clients/copy-to-clients.js

Noticed during Smithy 1.28.1 upgrade in https://github.com/aws/aws-sdk-js-v3/pull/4534
Formats client typedoc.json using prettier
Ran `yarn generate-clients` and verified that typedoc.json format was not updated.
---

chore(codegen): prettier format client typedoc.json

---

package.json
packages/credential-provider-ini/src/resolveCredentialSource.ts
packages/credential-provider-ini/src/resolveProcessCredentials.ts
packages/credential-provider-ini/src/resolveSsoCredentials.spec.ts
packages/credential-provider-process/src/getValidatedProcessCredentials.ts
packages/credential-provider-process/src/resolveProcessCredentials.ts
packages/credential-providers/src/fromContainerMetadata.ts
packages/credential-providers/src/fromInstanceMetadata.ts
packages/credential-providers/src/fromTemporaryCredentials.ts
packages/eventstream-handler-node/src/EventStreamPayloadHandler.spec.ts
packages/middleware-endpoint-discovery/src/getCacheKey.ts
packages/middleware-host-header/src/index.spec.ts
packages/middleware-token/src/normalizeTokenProvider.ts
packages/types/src/checksum.ts
packages/types/src/credentials.ts
packages/types/src/middleware.ts
packages/types/src/profile.ts
packages/types/src/serde.ts
packages/types/src/token.ts
packages/types/src/util.ts
packages/util-waiter/src/waiter.ts
yarn.lock

Require for TypeScript 5.0 bump https://github.com/prettier/prettier/pull/14391
Bumps prettier to 2.8.5
* CI
* Verified that `yarn generate-clients` does not format the clients code.
* The formatted code in lib/packages was updated.
---

chore(deps-dev): bump prettier to 2.8.5

---

clients/client-auto-scaling/src/protocols/Aws_query.ts
clients/client-cloudformation/src/protocols/Aws_query.ts
clients/client-cloudfront/src/protocols/Aws_restXml.ts
clients/client-cloudsearch/src/protocols/Aws_query.ts
clients/client-cloudwatch/src/protocols/Aws_query.ts
clients/client-docdb/src/protocols/Aws_query.ts
clients/client-ec2/src/protocols/Aws_ec2.ts
clients/client-elastic-beanstalk/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing-v2/src/protocols/Aws_query.ts
clients/client-elastic-load-balancing/src/protocols/Aws_query.ts
clients/client-elasticache/src/protocols/Aws_query.ts
clients/client-iam/src/protocols/Aws_query.ts
clients/client-neptune/src/protocols/Aws_query.ts
clients/client-rds/src/protocols/Aws_query.ts
clients/client-redshift/src/protocols/Aws_query.ts
clients/client-route-53/src/protocols/Aws_restXml.ts
clients/client-s3-control/src/protocols/Aws_restXml.ts
clients/client-s3/src/protocols/Aws_restXml.ts
clients/client-ses/src/protocols/Aws_query.ts
clients/client-sns/src/protocols/Aws_query.ts
clients/client-sqs/src/protocols/Aws_query.ts
clients/client-sts/src/protocols/Aws_query.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java
private/aws-protocoltests-ec2/src/protocols/Aws_ec2.ts
private/aws-protocoltests-query/src/protocols/Aws_query.ts
private/aws-protocoltests-restxml/src/protocols/Aws_restXml.ts
private/aws-restjson-server/src/models/models_0.ts
private/aws-restjson-validation-server/src/models/models_0.ts

This PR updates the XML deserializer code generation to create empty objects instead of objects with properties set to `undefined`.
For example, instead of generating this:
```
const contents: any = {
ActivityId: undefined,
AutoScalingGroupName: undefined,
Description: undefined,
Cause: undefined,
StartTime: undefined,
EndTime: undefined,
StatusCode: undefined,
StatusMessage: undefined,
Progress: undefined,
Details: undefined,
AutoScalingGroupState: undefined,
AutoScalingGroupARN: undefined,
};
```
And empty object is created instead:
```
const contents: any = {}
```
This reduces artifact size.
The updated XML-based protocol clients were hand tested to assure that deserialization was still successful. …

Reduce xml deser size with empty object

---

packages/config-resolver/package.json
packages/credential-providers/package.json
packages/eventstream-serde-node/package.json
packages/hash-blob-browser/package.json
packages/middleware-bucket-endpoint/package.json
packages/middleware-endpoint-discovery/package.json
packages/middleware-endpoint/package.json
packages/middleware-sdk-sts/package.json
packages/middleware-sdk-transcribe-streaming/package.json
packages/middleware-user-agent/package.json
packages/polly-request-presigner/package.json
packages/s3-presigned-post/package.json
packages/s3-request-presigner/package.json
packages/signature-v4-crt/package.json
packages/signature-v4-multi-region/package.json
packages/signature-v4/package.json
packages/util-user-agent-browser/package.json
packages/util-user-agent-node/package.json

N/A
There were some packages that had AWS SDK dependencies which were no longer being used, including devDependencies. This PR removes those dependencies.
yarn build:all, CI
N/A
---

chore(packages): remove unused dependencies

---

api-extractor.json

Fix a paths in `api-extractor.json` to output files in repo root
`yarn extract:docs`
---

docs(fix): api-extractor paths

---

clients/client-s3/test/S3.spec.ts

Followup to #4523
The S3 client uses a configuration option, `signingEscapePath`, set to false by default, to tell the signer not to encode the URL path. The serializer will encode these paths, so if the signer did as well, the paths would be encoded multiple times. S3 is the only client that uses this config option, and there were no tests that verified paths are encoded.
To verify it fails properly:
- Added `request.path = decodeURIComponent(request.path);` to [signature-v4/prepareRequest.ts](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/signature-v4/src/prepareRequest.ts), to make the path unencoded before it reaches the request handler.
- Added `.skip` to [signature-v4/SignatureV4.spec.ts](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/signature-v4/src/SignatureV4.sp …

feat(client-s3): add path encoding test

---

typedoc.client.json
typedoc.json

P84530735
Defaults "protected" types to being visible (e.g. Paginators) as reported [by customer](https://twitter.com/mattbonig/status/1640442723659554818) 
`yarn build:docs` and visual inspection
---

fix(docs): reveal protected types

---

packages/middleware-serde/src/deserializerMiddleware.spec.ts
packages/middleware-serde/src/deserializerMiddleware.ts

https://github.com/aws/aws-sdk-js-v3/issues/4576
Due to https://github.com/aws/aws-sdk-js-v3/pull/3426, the raw response is not visible by default on a deserialization error. This can be confusing to users who do not know about the hidden `$response` field.
manual test and new unit test
Example
```
TypeError: stream.pipe is not a function
To see the raw response, inspect the hidden field {error}.$response on this object.
at aws/aws-sdk-js-v3/packages/node-http-handler/dist-cjs/stream-collector/index.js:7:12
at new Promise (<anonymous>)
at Object.streamCollector (/aws/aws-sdk-js-v3/packages/node-http-handler/dist-cjs/stream-collector/index.js:5:37)
at collectBody (/aws/aws-sdk-js-v3/clients/client-s3/dist-cjs/protocols/Aws_restXml.js:9707:20)
at collectBodyString …
```

chore(middleware-serde): add hint for raw error response

---

packages/abort-controller/src/AbortController.ts
packages/types/package.json
packages/types/src/abort.spec.ts
packages/types/src/abort.ts
packages/types/tsconfig.test.json

https://github.com/aws/aws-sdk-js-v3/issues/4582
Add message to not use the SDK's AbortController in browsers. Make global AbortController compatible with our interface (type fix)
added unit test

docs(abort-controller): add message about browsers

---

packages/node-http-handler/src/node-http2-connection-manager.ts
packages/node-http-handler/src/node-http2-connection-pool.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/types/src/connection/index.ts
packages/types/src/index.ts

Add types introduced in https://github.com/aws/aws-sdk-js-v3/commit/86a6046af170784a9858f101e84cf3d97df84a21 to declaration file entry point, `index.ts`, and fix imports in `@aws-sdk/node-http-handler`
`yarn build:all` and `yarn lerna run --scope="@aws-sdk/node-http-handler" test`
Forcing types to be imported from a TypeScript source file is a _[poor practice](https://api-extractor.com/pages/messages/ae-wrong-input-file-type/)_, the preferred method is to allow the compiler to choose from  source and declaration files based on context.
It also causes documentation extraction to break with an `ae-wrong-input-file-type` error.
---

fix(types): node-http-handler type imports and @aws-sdk/types exports

---

clients/client-rekognitionstreaming/package.json
clients/client-rekognitionstreaming/src/RekognitionStreamingClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddRekognitionStreamingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
packages/middleware-sdk-rekognitionstreaming/.gitignore
packages/middleware-sdk-rekognitionstreaming/README.md
packages/middleware-sdk-rekognitionstreaming/jest.config.js
packages/middleware-sdk-rekognitionstreaming/package.json
packages/middleware-sdk-rekognitionstreaming/src/index.ts
packages/middleware-sdk-rekognitionstreaming/src/middleware-port.spec.ts
packages/middleware-sdk-rekognitionstreaming/src/middleware-port.ts
packages/middleware-sdk-rekognitionstreaming/src/plugin.ts
packages/middleware-sdk-rekognitionstreaming/tsconfig.cjs.json
packages/middleware-sdk-rekognitionstreaming/tsconfig.es.json
packages/middleware-sdk-rekognitionstreaming/tsconfig.types.json

n/a
Adds a port middleware to rekognitionstreaming mostly identical to the one used by transcribe-streaming
unit testing and manual endpoint testing

feat(middleware-sdk-rekognitionstreaming): create port middleware

---

packages/smithy-client/src/object-mapping.spec.ts
packages/smithy-client/src/object-mapping.ts

n/a
This adds a serde helper called `take`. The anticipated usage is as follows:
current:
```js
{
CreationDateTime:
output.CreationDateTime != null
? __expectNonNull(__parseEpochTimestamp(__expectNumber(output.CreationDateTime)))
: undefined,
GlobalTableArn: __expectString(output.GlobalTableArn),
GlobalTableName: __expectString(output.GlobalTableName),
GlobalTableStatus: __expectString(output.GlobalTableStatus),
ReplicationGroup:
output.ReplicationGroup != null
? deserializeAws_json1_0ReplicaDescriptionList(output.ReplicationGroup, context)
: undefined,
}
```
new:
```js
take(output, {
CreationDateTime: [, _ => __expectNonNull(__parseEpochTimestamp(__expectNumber(_)))],
GlobalTableArn: __expectString,
GlobalTableName: __expectString, // single fn is equivalent to [,fn,]
GlobalTableStatus: …
```

feat(codegen): add serde helper function

---

packages/middleware-sdk-ec2/package.json
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-ec2/src/index.ts

internal
Fix non-default KMS key not being set during CopySnapshot because the middleware mutates the command input but may be placed after the serializer middleware.
Ensure that you have a source snapshot and a non-default KMS key. Make a copy snapshot request with Encrypted=true and the KMS key id in question. The new snapshot should have the designated KMS key and not the default key.
```js
const copySnapshotCommand = new CopySnapshotCommand({
SourceRegion: "<...>",
SourceSnapshotId: "snap-<...>",
KmsKeyId: "<...>",
Encrypted: true,
});
```

fix(middleware-sdk-ec2): serialize presignedUrl into request body

---

codegen/generic-client-test-codegen/build.gradle.kts
codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

When attempting to run `yarn generate-clients --server-artifacts` the locally published changes to Smithy protocol tests are not picked up (after running `./gradlew clean build publishToMavenLocal` in the Smithy repository.
Adds mavenLocal repository to each of the codegen build.gradle.kts files where it is missing.
Run `./gradlew clean build publishToMavenLocal` from Smithy repository to publish protocol test changes locally.
Run `yarn generate-clients --server-artifacts`.
Verify that expected changes appear in generated server artifacts appropriate `/private` directory.
---

chore(codegen): add mavenLocal repo

---

packages/cloudfront-signer/src/sign.spec.ts
packages/cloudfront-signer/src/sign.ts

I didn't file an issue for this bug but I'd be happy to make and link one if needed.
The prior implementation of the URL construction for `getSignedUrl` naiively copied the parsed query param values back into the output URL.  That method will fail for any query param that has encoded segments.
Not only is that a problem because the query params need to be encoded in general, but it also renders the signature invalid since the signed url doesn't match the output url.
This change moves to a simpler implementation using the `URL` class to parse the input query params and the `encodeURIComponent` function to ensure query parameters are properly escaped on the way out.  These _should_ be symmetric, but I suppose there's still a chance that the query parsing and re-encoding results in a query …

fix(cloudfront-signer): fix URL construction to maintain escapes

---

private/aws-util-test/.gitignore
private/aws-util-test/README.md
private/aws-util-test/jest.config.js
private/aws-util-test/package.json
private/aws-util-test/src/requests/test-http-handler.spec.ts
private/aws-util-test/src/requests/test-http-handler.ts
private/aws-util-test/tsconfig.cjs.json
private/aws-util-test/tsconfig.json
private/aws-util-test/tsconfig.types.json
scripts/cli-dispatcher/index.js

Create a test helper in a private package.
The test helper accepts matchers and asserts against outgoing requests from smithy clients.
This is a testing utility, but the package contains a unit test as an example.

test(aws-util-test): create request testing private package

---

README.md
packages/core-theme-documentation-generator/src/theme.tsx

Accessibility Audit
Update alt text to explicitly match the image text
`yarn build:all && yarn build:docs`
---

docs(a11y): update badge text to an exact match of content

---

tests/e2e/index.js

Try using ~npx~ yarn to launch lerna. CI is having issues but no error output.
works locally

fix(e2e): use yarn to find lerna executable

---

package.json

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/4660
Fixes typo in folder name integ-e2e -> e2e-legacy
Internal
---

fix(e2e): typo folder name integ-e2e -> e2e-legacy

---

packages/node-http-handler/src/node-http-handler.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4668
Undeprecates connectionTimeout, and destroys the request if it's timed out before before socket is available.
Using repro code:
```js
import { NodeHttpHandler } from "../aws-sdk-js-v3/packages/node-http-handler/dist-cjs/index.js";
const client = new S3({
requestHandler: new NodeHttpHandler({
// For repro this value should be between time taken for socket assigned, and time taken by request.
connectionTimeout: 40,
}),
});
await client.listBuckets({});
```
The request incorrectly times out, as it assigns connectionTimeout in requestTimeout.
```console
/local/home/trivikr/workspace/aws-sdk-js-v3/packages/node-http-handler/dist-cjs/node-http-handler.js:91 …
```

fix(node-http-handler): undeprecate connectionTimeout

---

clients/client-amplifybackend/src/protocols/Aws_restJson1.ts
clients/client-apigatewayv2/src/protocols/Aws_restJson1.ts
clients/client-guardduty/src/protocols/Aws_restJson1.ts
clients/client-iot-1click-devices-service/src/protocols/Aws_restJson1.ts
clients/client-kafka/src/protocols/Aws_restJson1.ts
clients/client-macie2/src/protocols/Aws_restJson1.ts
clients/client-mediaconnect/src/protocols/Aws_restJson1.ts
clients/client-mediaconvert/src/protocols/Aws_restJson1.ts
clients/client-medialive/src/protocols/Aws_restJson1.ts
clients/client-mediapackage-vod/src/protocols/Aws_restJson1.ts
clients/client-mediapackage/src/protocols/Aws_restJson1.ts
clients/client-mq/src/protocols/Aws_restJson1.ts
clients/client-pinpoint/src/protocols/Aws_restJson1.ts
clients/client-route53-recovery-readiness/src/protocols/Aws_restJson1.ts
clients/client-serverlessapplicationrepository/src/protocols/Aws_restJson1.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java

https://github.com/aws/aws-sdk-js-v3/issues/4653
Reference: https://github.com/aws/aws-sdk-js-v3/pull/4657
The generated string for one deserialization case (JsonName-having fields that deserialized container shapes) was incorrect.
Notes
There is a testing gap here since compilation checks, unit, integration, and protocol tests did not catch this issue. 
The mistaken generated type coincidentally fit the signature of the function call it sits in.
The object can be a Record having values that are either triplets or functions.
```ts
{
A: (_) => _ // function, OK
B: [,(_) => _,] // triplet with middle value being a function, OK
C: (_) => [,,] // incorrect generated syntax, but accepted as function
}
```

fix(clients): deserialization of jsonName complex shapes

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Bump code generator version to 0.15.0.
Note: CI expected to fail until https://github.com/awslabs/smithy-typescript/pull/751 is merged.
---

feat(codegen): bump codegen version to 0.15.0

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

This reverts commit 83421a1d562d79cb49a534543532674ffb822f8b.
Revert 0.15.0 version bump.
---

Revert "feat(codegen): bump codegen version to 0.15.0 (#4678)"

---

packages/middleware-endpoint-discovery/src/middleware-endpoint-discovery.integ.spec.ts
packages/middleware-sdk-sqs/src/middleware-sdk-sqs.integ.spec.ts
private/aws-util-test/src/requests/test-http-handler.ts

followup to https://github.com/aws/aws-sdk-js-v3/pull/4697
In the test-http-handler testing wrapper, set client credentials to avoid default credential chain lookup
`yarn test:integration`

test(aws-util-test): use mock credentials in test-http-handler

---

packages/node-http-handler/src/constants.ts
packages/service-error-classification/src/constants.ts

#4466 
This adds "ECONNREFUSED", to the list of retryable errors that the SDK should retry.
There are currently no test for the other transient error status, so I didnt write a test for it.
[Go](https://github.com/distribution/distribution/blob/main/vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go#L192-L196) SDK retries connection refused error the same way.
---

fix(service-error-classification): add ECONNREFUSED to list of retryable errors

---

packages/middleware-retry/src/retryMiddleware.ts
packages/types/src/retry.ts
packages/util-retry/README.md
packages/util-retry/src/AdaptiveRetryStrategy.ts
packages/util-retry/src/ConfiguredRetryStrategy.spec.ts
packages/util-retry/src/ConfiguredRetryStrategy.ts
packages/util-retry/src/DefaultRateLimiter.ts
packages/util-retry/src/StandardRetryStrategy.ts
packages/util-retry/src/config.ts
packages/util-retry/src/constants.ts
packages/util-retry/src/defaultRetryToken.ts
packages/util-retry/src/index.ts

https://github.com/aws/aws-sdk-js-v3/issues/3611
- Add readme to util-retry
- Mark module public
- Expand constructor signature for StandardRetryStrategy to `number | Provider<number>`
- Add a retry class "ConfiguredRetryStrategy" that allows customizing the backoff computation.
unit tests, manual test
```ts
import { S3 } from "@aws-sdk/client-s3";
import { HttpResponse } from "@aws-sdk/protocol-http";
import { ConfiguredRetryStrategy } from "@aws-sdk/util-retry";
class MockRequestHandler {
// Returns 429 error to cause a retry in the client.
// No network request is made.
async handle() {
console.log("    Request (mock) responding with 429 throttling error.");
return {
response: new HttpResponse({
statusCode: 429,
body: Buffer.from(""),
}),
};
}
}
let n = 0;
console.log("Time:", n++); …
```

docs(util-retry): add readme for util-retry, add configurable backoff

---

packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts

https://github.com/aws/aws-sdk-js-v3/issues/4398
https://github.com/aws/aws-sdk-js-v3/issues/4369
Add null check for `fetch` API response.body. 
For affected users' clients, you can apply a code workaround until such time that you upgrade to a version of the AWS SDK for JavaScript v3 that contains this fix.
```ts
import { S3 } from "@aws-sdk/client-s3";
const s3 = new S3({
credentials,
});
// this example is on an S3 client. The middlewareStack property is available on all clients.
// add this middleware to default a fetch response body to an empty Uint8Array, 
// before making any requests.
s3.middlewareStack.addRelativeTo(
(next) => async (args) => {
const { response } = await next(args);
if (response.body == null) {
response.body = new Uint8Array();
}
return {
response,
};
},
{
name: …
```

fix(fetch-http-handler): check for null fetch response.body

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/validation/UnaryFunctionCall.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/validation/UnaryFunctionCallTest.java

This PR updates the Shape visitors and protocol generators to use the SerdeElision KnowledgeIndex that was converted in https://github.com/awslabs/smithy-typescript/pull/759
It also adds the UnaryFunctionCall class that was originally added to smithy-typescript (and which is removed in https://github.com/awslabs/smithy-typescript/pull/760).
Ran `yarn generate-clients` to assure there were no generated code differences.
Additionally, ran `./gradlew clean build` from the `codegen` directory to assure that the `java.lang.OutOfMemoryError: Java heap space` errors were not thrown as described in https://github.com/aws/aws-sdk-js-v3/pull/4692.
---
By submitting this pull request, I confirm that you can use, …

Use serde elision index

---

.github/workflows/codegen-ci.yml

While attempting to release a new version of the code generator, it was uncovered that running `./gradle clean build` from the `/codegen` directory results in `java.lang.OutOfMemoryError: Java heap space`.
This PR updates the CI workflow to run the `sdk-codegen:build` task, which invokes the `buildSdk` task, which generates clients for each of the model files within the `codegen/sdk-codegen/aws-models` directory.
These errors started with the changes introduced in https://github.com/aws/aws-sdk-js-v3/pull/4625 and https://github.com/awslabs/smithy-typescript/pull/735.
This is expected to fail until changes from https://github.com/awslabs/smithy-typescript/pull/760, https://github.com/awslabs/smithy-typescript/pull/759 and …

fix(codegen): buildSdk on ci

---

packages/util-endpoints/src/resolveEndpoint.spec.ts
packages/util-endpoints/src/resolveEndpoint.ts

#4650
Improving debug message of resolveEnpoints.js
Add a new test case of the mocked logger.
Make sure that the mocked logger was called with correct parameter.
``` lerna run test --scope @aws-sdk/util-endpoints  ```
na
---

fix(util-endpoints): improve resolveEndpoints usage of option.logger.debug

---

tsconfig.json

Remove hardcoded `src` in tsconfig paths for `packages/*` to allow definition files to resolve `dist-types/*.d.ts` instead of being forced to use `src/*.ts` files
`yarn build:all`
This resolves the root cause of errors in extracting documentation from `packages/*` and `lib/*`
---

fix(tsconfig): correct paths definition for packages/

---

tests/e2e/index.js

add reminder comment not to change the syntax, if this turns out to fix the build issue.

chore(e2e): add e2e yarn lerna usage comment

---

packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts
packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/node-http-handler/src/write-request-body.ts

https://github.com/aws/aws-sdk-js-v3/issues/4332
Open a promise while write-body is pending. Wait for its closure before resolving `HttpHandler::handle`. 
This fix is experimental because I can't reproduce the original issue in the ticket with the given examples.

fix(node-http-handler): open promise handle while waiting for http continue

---

packages/util-retry/README.md

To just change the maxAttempts, the user does not have to provide custom retryStrategy.
The client will use Standard Retry Strategy with provided maxAttempts.
Mention maxAttempts configuration in default case
N/A
---

docs(util-retry): mention maxAttempts configuration in basic case

---

packages/util-retry/README.md

While debugging, a user provided both maxAttempts and retryStrategy and wondered which one takes precedence.
This update explicitly mentions why retryStrategy takes precedence.
Document that retryStrategy gets precedence over maxAttempts
N/A
---

docs(util-retry): retryStrategy gets precedence over maxAttempts

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentBareBonesClientGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientCommandGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientPaginationGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientUtils.java
lib/lib-dynamodb/src/DynamoDBDocument.ts
lib/lib-dynamodb/src/DynamoDBDocumentClient.ts
lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.ts
lib/lib-dynamodb/src/commands/BatchExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/BatchGetCommand.ts
lib/lib-dynamodb/src/commands/BatchWriteCommand.ts
lib/lib-dynamodb/src/commands/DeleteCommand.ts
lib/lib-dynamodb/src/commands/ExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/ExecuteTransactionCommand.ts
lib/lib-dynamodb/src/commands/GetCommand.ts
lib/lib-dynamodb/src/commands/PutCommand.ts
lib/lib-dynamodb/src/commands/QueryCommand.ts
lib/lib-dynamodb/src/commands/ScanCommand.ts
lib/lib-dynamodb/src/commands/TransactGetCommand.ts
lib/lib-dynamodb/src/commands/TransactWriteCommand.ts
lib/lib-dynamodb/src/commands/UpdateCommand.ts
lib/lib-dynamodb/src/pagination/Interfaces.ts
lib/lib-dynamodb/src/pagination/QueryPaginator.ts
lib/lib-dynamodb/src/pagination/ScanPaginator.ts

Add release tags and re-exports to correctly extract `lib-dynamodb`'s documentation.  This PR contains both updates to codegen and output from updated codegen.
`yarn generate-clients && yarn build:all && yarn extract:docs`
---

docs(lib-dynamodb): add release tags and re-exports to lib-dynamodb

---

packages/hash-node/api-extractor.json
packages/hash-node/package.json
packages/middleware-endpoint/api-extractor.json
packages/middleware-endpoint/package.json
packages/signature-v4-multi-region/api-extractor.json
packages/signature-v4-multi-region/package.json

JS team initially determined these packages should be documented, upon further review we determined they should be internal.
`yarn build:all`
---

docs(internal): remove api-extraction from internal packages

---

packages/node-http-handler/src/write-request-body.ts

https://github.com/aws/aws-sdk-js-v3/issues/4769
This only affects some Node.js versions.
clear the open timeout when proceeding past it
existing unit tests

fix(node-http-handler): clear open timeout on continue

---

packages/middleware-user-agent/src/middleware-user-agent.integ.spec.ts
packages/middleware-user-agent/src/user-agent-middleware.spec.ts
packages/middleware-user-agent/src/user-agent-middleware.ts

Internal JS-4206
Uses '#' as a separator for version if name contains '/'
CI
---

chore(middleware-user-agent): use '#' as a separator for version

---

packages/middleware-user-agent/src/constants.ts
packages/middleware-user-agent/src/user-agent-middleware.spec.ts
packages/middleware-user-agent/src/user-agent-middleware.ts

Internal JS-4206
Uses hyphen for escaping instead of underscore
CI
---

chore(middleware-user-agent): use hyphen for escaping instead of underscore

---

packages/middleware-user-agent/src/constants.ts
packages/middleware-user-agent/src/user-agent-middleware.spec.ts
packages/middleware-user-agent/src/user-agent-middleware.ts

Missed in https://github.com/aws/aws-sdk-js-v3/pull/4778
Escapes '#' in user-agent name with '_', now that '#' is used as a separator
CI
---

fix(middleware-user-agent): escape '#' in user-agent name

---

packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts
packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts
packages/protocol-http/src/httpResponse.ts
packages/types/src/http.ts

N/A
Adds `reason` property to HttpResponse, which is a simple message explaining the status code. The property is optional, so adding it is backward compatible. Http handlers were updated to populate this property when constructing the HttpResponse, except for the Node http2 handler, because http2 doesn't support an equivalent.
Tests were added to Http handlers to make sure the property is populated when available.
Unit tests, CI, and `yarn test:integration:legacy`
---

feat(protocol-http): add reason to HttpResponse

---

packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts
packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts
packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts
packages/protocol-http/src/httpRequest.ts
packages/types/src/http.ts
packages/types/src/index.ts
packages/types/src/uri.ts
packages/util-format-url/src/index.ts

N/A
Adds the URI type to types package, and uses it in HttpRequest. The URI type adds additional properties that didn't exist on Endpoint. Http handlers were updated to use these new properties when constructing request URLs. Tests were also added to make sure handlers construct URLs properly with the new properties.
Unit tests and `yarn test:integration:legacy`
The added properties are optional, so this change is backward compatible with existing types.
---

feat(protocol-http): add uri type and implementation

---

clients/client-auto-scaling/package.json
clients/client-cloudformation/package.json
clients/client-cloudfront/package.json
clients/client-cloudsearch/package.json
clients/client-cloudwatch/package.json
clients/client-docdb/package.json
clients/client-ec2/package.json
clients/client-elastic-beanstalk/package.json
clients/client-elastic-load-balancing-v2/package.json
clients/client-elastic-load-balancing/package.json
clients/client-elasticache/package.json
clients/client-iam/package.json
clients/client-neptune/package.json
clients/client-rds/package.json
clients/client-redshift/package.json
clients/client-route-53/package.json
clients/client-s3-control/package.json
clients/client-s3/package.json
clients/client-ses/package.json
clients/client-sns/package.json
clients/client-sqs/package.json
clients/client-sts/package.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
private/aws-protocoltests-ec2/package.json
private/aws-protocoltests-query/package.json
private/aws-protocoltests-restxml/package.json
yarn.lock

Refs: https://github.com/NaturalIntelligence/fast-xml-parser/commit/39b0e050bb909e8499478657f84a3076e39ce76c
Closes: https://github.com/aws/aws-sdk-js-v3/pull/4795
Bump fast-xml-parser to 4.2.4
CI
---

chore(deps): bump fast-xml-parser to 4.2.4

---

packages/middleware-websocket/src/EventStreamPayloadHandler.spec.ts
packages/middleware-websocket/src/EventStreamPayloadHandler.ts
packages/middleware-websocket/src/eventstream-payload-handler-provider.ts
packages/middleware-websocket/src/get-event-signing-stream.spec.ts
packages/middleware-websocket/src/get-event-signing-stream.ts

Mirror of https://github.com/aws/aws-sdk-js-v3/pull/4802 on upstream repo.
Posted as GitHub has an incident with PRs https://www.githubstatus.com/incidents/1g1gkh0qpyvs
Closes https://github.com/aws/aws-sdk-js-v3/pull/4802
Update `eventStreamHandler` to use `MessageSigner` for `middleware-websocket` package
* `yarn test` in `middleware-socket`
* `yarn test:integration` in `middleware-socket`
* Test fix with minimal repro using instructions in https://github.com/aws/aws-sdk-js-v3/pull/4802#issuecomment-1581210285
---

fix(middleware-websocket): update eventStreamHandler to use MessageSigner

---

packages/node-http-handler/src/write-request-body.spec.ts
packages/node-http-handler/src/write-request-body.ts

https://github.com/aws/aws-sdk-js-v3/issues/4799
Release the 100-continue lock on an error event.
new unit tests

fix(node-http-handler): stop waiting for continue event on error

---

packages/credential-provider-cognito-identity/src/localStorage.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4807
breakout of https://github.com/aws/aws-sdk-js-v3/pull/4813

test(credential-provider-cognito-identity): compat for Node.js 18

---

clients/client-s3/package.json

Update fast-xml-parser to 4.2.4 to release `@aws-sdk/client-s3@3.6.3`
```console
$ client-s3> yarn test:unit
$ mocha **/cjs/**/*.spec.js
endpoint
✓ users can override endpoint from client.
Accesspoint ARN
✓ should succeed with access point ARN
✓ should sign request with region from ARN is useArnRegion is set
✓ should succeed with outposts ARN
Throw 200 response
✓ should throw if CopyObject() return with 200 and empty payload
✓ should throw if CopyObject() return with 200 and error preamble
✓ should throw if UploadPartCopy() return with 200 and empty payload
✓ should throw if UploadPartCopy() return with 200 and error preamble
✓ should throw if CompleteMultipartUpload() return with 200 and empty payload
✓ should throw if CompleteMultipartUpload() return …
```

chore: update fast-xml-parser for 3.6.3 release

---

clients/client-cognito-identity-provider/package.json
clients/client-cognito-identity/package.json
clients/client-sts/package.json
clients/client-sts/src/protocols/Aws_query.ts
clients/client-sts/src/protocols/xml-parser.ts

Update fast-xml-parser to 4.2.4 to release:
* `@aws-sdk/client-sts@3.54.2`
* `@aws-sdk/client-cognito-identity@3.54.2`
* `@aws-sdk/client-cognito-identity-provider@3.54.2`
```console
...........
Done in 0.97s.
```
* [aws-sdk-client-sts-3.54.2.tgz](https://github.com/aws/aws-sdk-js-v3/files/11725302/aws-sdk-client-sts-3.54.2.tgz)
* [aws-sdk-client-cognito-identity-3.54.2.tgz](https://github.com/aws/aws-sdk-js-v3/files/11725304/aws-sdk-client-cognito-identity-3.54.2.tgz)
* …

chore: update fast-xml-parser for 3.54.2 release

---

clients/client-lex-runtime-service/package.json
clients/client-lex-runtime-v2/package.json
clients/client-location/package.json
clients/client-sts/package.json

Update fast-xml-parser to 4.2.4 to release:
* `@aws-sdk/client-sts@3.186.2`
* `@aws-sdk/client-location@3.186.2`
* `@aws-sdk/client-lex-runtime-service@3.186.2`
* `@aws-sdk/client-lex-runtime-v2@3.186.2`
```console
...........
Done in 0.97s.
```
* [aws-sdk-client-sts-3.186.2.tgz](https://github.com/aws/aws-sdk-js-v3/files/11725239/aws-sdk-client-sts-3.186.2.tgz)
* [aws-sdk-client-location-3.186.2.tgz](https://github.com/aws/aws-sdk-js-v3/files/11725241/aws-sdk-client-location-3.186.2.tgz)
* …

chore: update fast-xml-parser for 3.186.2 release

---

clients/client-pinpoint/package.json
clients/client-sts/package.json

Update fast-xml-parser to 4.2.4 to release:
* `@aws-sdk/client-sts@3.335.1`
* `@aws-sdk/client-pinpoint@3.335.1`
```console
...........
Done in 0.97s.
```
* [aws-sdk-client-sts-3.335.1.tgz](https://github.com/aws/aws-sdk-js-v3/files/11725506/aws-sdk-client-sts-3.335.1.tgz)
* [aws-sdk-client-pinpoint-3.335.1.tgz](https://github.com/aws/aws-sdk-js-v3/files/11725507/aws-sdk-client-pinpoint-3.335.1.tgz)
The tarballs were created by running:
* `git clean -dfx`
* `yarn`
* `yarn lerna run --scope @aws-sdk/client-sts --scope …

chore: update fast-xml-parser for 3.335.1 release

---

packages/util-dynamodb/src/marshall.ts

The improved ordering of overload signatures ensures more specific ones match before very general ones such as when data is any object or instance.
Fixes: #4828
This change reorders the overload signatures of the marshall function so that the more specific signatures matches before the more general ones.
Made sure this compiles:
```
const ss: AttributeValue.SSMember = marshall(new Set(['a']));
const ns: AttributeValue.NSMember = marshall(new Set([0]));
const bs: AttributeValue.BSMember = marshall(new Set([new Uint8Array()]));
const s: AttributeValue.SMember = marshall('a');
const n: AttributeValue.NMember = marshall(0);
const nil: AttributeValue.NULLMember = marshall(null);
const bool: AttributeValue.BOOLMember = marshall(false);
const array: AttributeValue[] = marshall([]);
const object: …
```

fix(util-dynamodb): reorder marshall function overload signatures

---

packages/credential-provider-imds/src/remoteProvider/httpRequest.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/4827
Aborts nock pending requests when testing timeout
```console
$ yarn test --detectOpenHandles
...
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
●  Timeout
8 | export function httpRequest(options: RequestOptions): Promise<Buffer> {
9 |   return new Promise((resolve, reject) => {
> 10 |     const req = request({
|                        ^
11 |       method: "GET",
12 |       ...options,
13 |       // Node.js http module doesn't accept hostname with square brackets
at new InterceptedRequestRouter (../../node_modules/nock/lib/intercepted_request_router.js:78:13)
at new OverriddenClientRequest (../../node_modules/nock/lib/intercept.js:286:25)
at ../../node_modules/nock/lib/intercept.js:423:14
at …
```

test(credential-provider-imds): abort nock pending requests in timeout check

---

clients/client-cognito-identity/karma.conf.js

Internal JS-4369
Increases process kill timeout to 5000ms for karma tests in client-cognito-identity
E2E test was successful on client-cognito-identity
---

test(client-cognito-identity): increase process kill timeout to 5000ms

---

clients/client-cognito-identity/karma.conf.js
clients/client-s3/karma.conf.js
lib/lib-storage/karma.conf.js
package.json
packages/fetch-http-handler/karma.conf.js
packages/hash-blob-browser/karma.conf.js
packages/xhr-http-handler/karma.conf.js
yarn.lock

Internal, where we had to set up Chromium and Firefox on CodeBuild
Removes puppeteer dependency, and requests callee to set up Chrome and Firefox browsers in their environments.
The E2E test in release automation have already set up Chrome and Firefox browsers
---

chore(deps-dev): remove puppeteer dependency

---

packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4827
Just checks for string 'Unexpected token' of SyntaxError, as it's updated in Node.js 20
Verified that the test is successful in Node.js 18 and 20.
---

test(credential-provider-imds): check for 'Unexpected token' of SyntaxError

---

package.json
yarn.lock

Testing if Benchmark test hanging in Ubuntu Standard 6.0+ is related to verdaccio version
Bumps verdaccio to 5.25.0
Verified that Benchmark size tests, which use verdaccio, are successful:
```console
$ yarn test:size --since last_release
...
Report is updated, validating the new result with the limit configurations.
Done in 159.05s.
```
---

chore(deps-dev): bump verdaccio to 5.25.0

---

packages/property-provider/src/chain.spec.ts
packages/property-provider/src/chain.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/2263
Simplifies debugging with "uncaught exceptions" by skipping generation of default rejected promise when chaining
VSCode does not pause in chain function when "uncaught exceptions" are checked.
<details>
<summary>Screen recording</summary>
https://github.com/aws/aws-sdk-js-v3/assets/16024985/65e0e86e-109a-4b05-b78d-e677f2d8dbcd
</details>
---

fix(property-provider): avoid generating default rejected promise when chaining

---

private/aws-util-test/src/requests/test-http-handler.ts

this might help prevent dns lookup in integ tests with the test http handler

test: stub credentialDefaultProvider in test-http-handler

---

packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/4848
rejoin main promise when error thrown in writeRequestBody
new unit test

fix(node-http-handler): rejoin on error in writeRequestBody

---

clients/client-s3/package.json

Internal JS-4435
Update fast-xml-parser to 4.2.5 to release `@aws-sdk/client-s3@3.6.4`
```console
$ client-s3> yarn test:unit
$ mocha **/cjs/**/*.spec.js
endpoint
✓ users can override endpoint from client.
Accesspoint ARN
✓ should succeed with access point ARN
✓ should sign request with region from ARN is useArnRegion is set
✓ should succeed with outposts ARN
Throw 200 response
✓ should throw if CopyObject() return with 200 and empty payload
✓ should throw if CopyObject() return with 200 and error preamble
✓ should throw if UploadPartCopy() return with 200 and empty payload
✓ should throw if UploadPartCopy() return with 200 and error preamble
✓ should throw if CompleteMultipartUpload() return with 200 and empty payload
✓ should throw if CompleteMultipartUpload() return …
```

chore: update fast-xml-parser for 3.6.4 release

---

clients/client-lex-runtime-service/package.json
clients/client-lex-runtime-v2/package.json
clients/client-location/package.json
clients/client-sts/package.json

Update fast-xml-parser to 4.2.5 to release:
* `@aws-sdk/client-sts@3.186.3`
* `@aws-sdk/client-location@3.186.3`
* `@aws-sdk/client-lex-runtime-service@3.186.3`
* `@aws-sdk/client-lex-runtime-v2@3.186.3`
```console
...........
Done in 0.97s.
```
* [aws-sdk-client-sts-3.186.3.tgz](https://github.com/aws/aws-sdk-js-v3/files/11874044/aws-sdk-client-sts-3.186.3.tgz)
* [aws-sdk-client-location-3.186.3.tgz](https://github.com/aws/aws-sdk-js-v3/files/11874045/aws-sdk-client-location-3.186.3.tgz)
* …

chore: update fast-xml-parser for 3.186.3 release

---

packages/util-retry/src/ConfiguredRetryStrategy.spec.ts
packages/util-retry/src/StandardRetryStrategy.spec.ts
packages/util-retry/src/StandardRetryStrategy.ts
private/aws-client-retry-test/src/ClientRetryTest.spec.ts

This PR fixes the attempts count used in `StandardRetryStrategy` in `util-retry`. The number of attempts made is one more than the number of retries. The correct attempts count is then used to compare against `maxAttempts` to determine if retries should be made.
This corrects the behavior of `StandardRetryStrategy` to be congruent with the documentation here: https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html
Updated tests to cover case where max attempts is set to 1 which should disable any retries.
---

fix(util-retry): correct attempts count on StandardRetryStrategy

---

packages/core-theme-documentation-generator/src/theme.tsx

Change banner to show deprecation of TypeDoc reference
`yarn build:all && yarn build:docs`
---

docs(api-reference): deprecation message on TypeDoc api reference

---

packages/service-error-classification/src/constants.ts

Fixes: #4871
Fixes: #4872 
AbortError is defined as a transient error, which defeats the purposes of aborting mid execution. This causes the retry middleware, to retry even after abort singal was sent. 
This does not affect sending the request itself, as the signal is evaluated by the request handler at invocation time.
Existing Implementation without the change demonstrating retries happening, finally the handler throws abortError.
```js
import { Lambda } from "@aws-sdk/client-lambda";
import { StandardRetryStrategy } from "@aws-sdk/util-retry";
const abortSignal = AbortSignal.timeout(1_000);
const lambdaClient = new Lambda({
region: 'us-west-2',
retryStrategy: new StandardRetryStrategy(7),
requestHandler: {
async handle(_, { abortSignal } = {}) {
await new Promise((r) => setTimeout(r, …
```

fix(service-error-classification): remove AbortError from transient errors

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts

Currently, the `sdkVersions.properties` resource file is generated with the current version of each client and dependency package including packages that have been deprecated.
For example, `karma-credential-loader` has been deprecated and the last published version was `3.40.0`: https://www.npmjs.com/package/@aws-sdk/karma-credential-loader
However, the `sdkVersions.properties` resource file is currently being generated with this line:
```
@aws-sdk/karma-credential-loader=3.363.0
```
This PR updates build.gradle.kts to exclude packages which have been deprecated by setting `private: true` in their package.json.
Ran `./gradlew clean build` from the `/codegen` directory and confirmed that  the generate file at …

fix(codegen): remove deprecated packages from sdkVersions.properties

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Also uses 0.16.0 smithy-typescript, PR here https://github.com/awslabs/smithy-typescript/pull/805
---

feat(codegen): bump codegen version to 0.16.0

---

packages/util-dynamodb/src/marshall.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4901
Reopens: https://github.com/aws/aws-sdk-js-v3/issues/4828
Reverts reorder of marshall function overload signatures
N/A, reverting recent change
---

fix(util-dynamodb): revert reorder of marshall function overload signatures

---

private/aws-middleware-test/tsconfig.cjs.json
private/aws-middleware-test/tsconfig.es.json
private/aws-middleware-test/tsconfig.types.json

Internal JS-4460
The internal builds started failing since the https://github.com/aws/aws-sdk-js-v3/pull/4850 was merged with Error:
```console
[Error: ENOENT: no such file or directory, open 'private/aws-middleware-test/tsconfig.types.json'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: 'private/aws-middleware-test/tsconfig.types.json'
}
```
This PR just adds default TSConfig files, copied from aws-client-api-test
N/A
---

fix(aws-middleware-test): add tsconfig files from aws-client-api-test

---

scripts/downlevel-dts/index.mjs

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4912
Skips downleveling of packages in private folder
ToDo: Verified that `yarn build:types:downlevel` succeeded with the repo setup prior to fix in https://github.com/aws/aws-sdk-js-v3/pull/4911
```console
$ yarn build:all && yarn build:types:downlevel
...
Done in 114.59s.
```
Verified that downlevel types were created for clients.
```console
$ ls clients/client-s3/dist-types/ts3.4
commands  index.d.ts  pagination  runtimeConfig.browser.d.ts  runtimeConfig.native.d.ts  S3Client.d.ts  waiters
endpoint  models      protocols   runtimeConfig.d.ts          runtimeConfig.shared.d.ts  S3.d.ts
$ ls private/aws-echo-service/dist-types/ts3.4
ls: cannot access private/aws-echo-service/dist-types/ts3.4: No such file or directory
```
---
By …

fix(scripts): skip downleveling of packages in private folder

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Uses smithy-typescript 0.17.0: https://github.com/awslabs/smithy-typescript/pull/809
---

feat(codegen): bump codegen version to 0.17.0

---

packages/hash-blob-browser/package.json

#4631 
Adds back the chunked-blob-reader-native dependency. It was removed in https://github.com/aws/aws-sdk-js-v3/pull/4571 because it wasn't being used in the TS code anywhere, but it is depended on in the package.json [here](https://github.com/aws/aws-sdk-js-v3/blob/797001ffd8bd81595049c6271167891e01b419c1/packages/hash-blob-browser/package.json#L38).
CI
---

fix(hash-blob-browser): add back missing dep

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

Uses smithy-typescript 0.17.1: https://github.com/awslabs/smithy-typescript/pull/819
---

feat(codegen): bump codegen version to 0.17.1

---

packages/middleware-sdk-s3-control/package.json
packages/middleware-sdk-s3-control/src/host-prefix-deduplication/deduplicateHostPrefix.spec.ts
packages/middleware-sdk-s3-control/src/host-prefix-deduplication/deduplicateHostPrefix.ts
packages/middleware-sdk-s3-control/src/middleware-sdk-s3-control.integ.spec.ts
packages/util-endpoints/src/index.ts

n/a
Do not deduplicate the two leading hostname components if they are part of an IP address.
new unit test

fix(middleware-sdk-s3-control): ignore IP address in host prefix dedupe

---

lib/lib-storage/package.json

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4942
Add @smithy/abort-controller to dependencies of "@aws-sdk/lib-storage"
modify package.json and link package locally
---

fix(lib-storage): add @smithy/abort-controller to dependencies

---

lib/lib-dynamodb/package.json
lib/lib-storage/package.json
packages/core-theme-documentation-generator/package.json
packages/middleware-websocket/package.json
private/aws-client-api-test/package.json
private/aws-client-retry-test/package.json
private/aws-middleware-test/package.json
scripts/runtime-dependency-version-check/runtime-dep-version-check.js
yarn.lock

n/a
fix a typo in the script that checks consistent dependency versions, and make devDep versions consistent.

chore: consistent devDep versions

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBodyChecksumGeneratorDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventStreamHandlingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttp2Dependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/EndpointGenerator.java

This PR refactors the use of `addImport`. The deprecated `addImport(String name, String as, String from)` is no longer used, and `addImport(String name, String as, PackageContainer from)` or `addRelativeImport(String name, String as, Path from)` are used instead.
There are no resulting changes to the generated clients from this change.
This change requires this change: https://github.com/awslabs/smithy-typescript/pull/837
---

chore(codegen): refactor addImport usage

---

codegen/build.gradle.kts

Updates build.gradle.kts to include resource files in source jars.
See same change in https://github.com/smithy-lang/smithy/pull/1877 and https://github.com/awslabs/smithy-typescript/pull/841.
---

fix(codegen): include resource files in source jars

---

features/s3/step_definitions/objects.js

Internal JS-4559
Imports from `@smithy` packages where needed
All legacy integration tests are successful
```console
$ yarn test:e2e:legacy
...
149 scenarios (149 passed)
492 steps (492 passed)
2m40.959s (executing steps: 2m40.094s)
Done in 163.80s.
```
---

fix(e2e): import from `@smithy` packages where needed

---

packages/middleware-websocket/src/WebsocketSignatureV4.spec.ts
packages/middleware-websocket/src/WebsocketSignatureV4.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/5011
When systemClockOffset is set for RekognitionStreamingClient, the updated signingDate is not passed in presigned URL, and the presigner uses default Date.now(). This results in InvalidSignatureException on a websocket connection.
This PR passes the signing options while presigning the URL which includes updated signing date.
Used repro from https://github.com/aws/aws-sdk-js-v3/issues/5011
<details>
<summary>No system clock offset</summary>
System time is 8:28am Pacific, and X-Amz-Date is 152800 UTC. No errors are returned
</details>
<details>
<summary>System Clock Offset of one hour</summary>
In this setup, the system time is manually set ahead by one hour, and a systemClockOffset of negative one hour (-3600000) passed in …

fix(middleware-websocket): pass options to presign in WebsocketSignatureV4 sign

---

package.json
packages/token-providers/README.md
packages/token-providers/package.json
packages/token-providers/scripts/api/source.ts
packages/token-providers/scripts/esbuild.js
packages/token-providers/src/getNewSsoOidcToken.spec.ts
packages/token-providers/src/getNewSsoOidcToken.ts
packages/token-providers/src/getSsoOidcClient.spec.ts
packages/token-providers/src/getSsoOidcClient.ts
packages/token-providers/src/index.ts
yarn.lock

client-sso-oidc is used in token-providers. However, that client may use token providers in its default credential chain. This would create a cyclical dependency chain that breaks `yarn build:all` and turbopack.
This PR proposes that a minimal bundle of the parts of the sso-oidc client are included within token-providers for its use. This increases (before minification) the size of the token-providers package by 76K. To compare, the full sso-oidc client is 112K. 
This means a savings of 36K when not using the full sso-oidc client, but a redundancy of 76K when doing so. 
The alternative of making the client a peer dependency would be better, but the loss of a required dependency may be too disruptive of a breaking change. 
existing unit tests

fix(token-providers): break dependency cycle with sso-oidc

---

packages/token-providers/scripts/esbuild.js

Sets esbuild externals to all of `@aws-sdk/*` instead of specific patterns. 
Since the bundle file imports from the client source (TypeScript) file, we no longer need to avoid setting the client itself as an external.

chore: set esbuild externals

---

scripts/benchmark-size/runner/utils.ts
scripts/benchmark-size/runner/workspace.ts

Testing if Benchmark test hanging in Ubuntu Standard 6.0+ is related to lerna being called from node_modules
Uses lerna from yarn instead of node_modules for running benchmark
Verified that Benchmark size tests, which use verdaccio, are successful:
```console
$ yarn test:size --since last_release
...
Report is updated, validating the new result with the limit configurations.
Done in 159.05s.
```
---

chore(scripts): use lerna from yarn instead of node_modules

---

CONTRIBUTING.md
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventBridgePlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventStreamHandlingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTokenAuthPlugin.java

N/A.
Dependent on awslabs/smithy-typescript#857.
As part of feature development of `experimentalIdentityAndAuth`, add
control branches for existing behavior in existing integrations,
particularly `@aws.auth#sigv4` and `@httpBearerTokenAuth`:
- `AddAwsAuthPlugin`
- `AddAwsRuntimeConfig`
- `AddBuiltinPlugins`
- `AddEventBridgePlugin`
- `AddS3Config`
- `AddS3ControlDependency`
- `AddTokenAuthPlugin`
- `AddEventStreamHandlingDependency`
Also, add a section in `CONTRIBUTING.md` about experimental features in `smithy-typescript`
used in `aws-sdk-js-v3`.
1. Build changes from awslabs/smithy-typescript#857 using `./gradlew clean build check publishToMavenLocal`
2. Run …

feat(experimentalIdentityAndAuth): add `experimentalIdentityAndAuth` flag

---

scripts/benchmark-size/runner/utils.ts
scripts/benchmark-size/runner/workspace.ts

Internal JS-4618 
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/4835
Runs yarn lerna in silent mode
```console
$ ./node_modules/.bin/lerna --version
5.5.2
$ yarn lerna --version
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/lerna --version
5.5.2
Done in 0.21s.
$ yarn --silent lerna --version
5.5.2
```
Verified that Benchmark size tests, which use verdaccio, are successful:
```console
$ yarn test:size --since last_release
...
Report is updated, validating the new result with the limit configurations.
Done in 154.13s.
```
---

fix(scripts): run yarn lerna in silent mode

---

CONTRIBUTING.md
scripts/cli-dispatcher/index.js
scripts/cli-dispatcher/readme.md
scripts/cli-dispatcher/set-alias.sh
scripts/cli-dispatcher/workspace.js
scripts/utils/walk.js

adds a devtool to execute scripts in the `/workspace` and subfolders (unversioned) by partial substring matching

chore: create script runner devtool

---

scripts/prepare-smithy-typescript.sh

This script will be run during a build to prepare the smithy-typescript checkout.

chore(scripts): add smithy-ts version pointer

---

UPGRADING.md

add docs on Lambda invoke in v2 and v3.

docs(upgrading): add notes on Lambda invoke

---

clients/client-cognito-identity/karma.conf.js
clients/client-s3/karma.conf.js
package.json
yarn.lock

Internal JS-4583
We're temporarily disabling browser testing in Firefox, as AL2023 does not support Firefox and we need to move to AL2023.
It will be re-added when AL2023 adds support for Firefox.
For details, check https://github.com/amazonlinux/amazon-linux-2023/discussions/418
Verified that E2E test is successful in Chrome with bucket in dev-account
```console
$ AWS_SMOKE_TEST_REGION=[Region] AWS_SMOKE_TEST_BUCKET=[Bucket] yarn test:e2e
```
---

test(e2e): temporarily disable testing in Firefox

---

packages/credential-provider-sso/src/resolveSSOCredentials.spec.ts
packages/credential-provider-sso/src/resolveSSOCredentials.ts

Fixes #4798 
Originally, the SDK decided to reject SSO tokens that were within 15 minutes of their expiry time as already expired, but the SSO refresh process only ran if there were 5 minutes left on the token. That means that if calls were made between 5 and 15 minutes of expiry, users would have to manually refresh the token.
The Java SDK decided to remedy this by removing that 15 minute check (https://github.com/aws/aws-sdk-java-v2/pull/4157). This pull implements the same fix.
`yarn test` in the changed package; all tests pass.
See also:
https://github.com/aws/aws-cdk/issues/24782
https://github.com/aws/aws-sdk-js/issues/4441
https://github.com/aws/aws-sdk/issues/531
---
By submitting this pull request, I confirm …

fix(credential-provider-sso): accept tokens till they expire

---

scripts/runtime-dependency-version-check/runtime-dep-version-check.js

fixes: https://github.com/aws/aws-sdk-js-v3/issues/5136
Make private test packages as non-clients in `runtime-dep-version-check` script.
Verified that no error are thrown by `runtime-dep-version-check` script in https://github.com/aws/aws-sdk-js-v3/pull/5137
---

fix(scripts): treat private test packages as non-clients

---

scripts/generate-clients/build-smithy-typescript.js
scripts/generate-clients/index.js

Internal JS-4624
Add ability to build smithy-typescript codegen from specific commit.
The smithy-typescript is checked out in sibling folder
```console
$ aws-sdk-js-v3> rm -rf ~/.m2/repository
$ aws-sdk-js-v3> [ -d ../smithy-typescript ] && echo "Yes" || echo "No"
Yes
$ aws-sdk-js-v3> yarn generate-clients -g codegen/sdk-codegen/aws-models/acm.json -n
...
Done in 18.86s.
$ aws-sdk-js-v3> git status
On branch publish-smithy-ts-before-codegen
Your branch is up to date with 'origin/publish-smithy-ts-before-codegen'.
nothing to commit, working tree clean
```
The smithy-typescript is not checked out in sibling folder
```console
$ aws-sdk-js-v3> rm -rf ~/.m2/repository
$ aws-sdk-js-v3> [ -d ../smithy-typescript ] && echo "Yes" || echo "No"
No
$ aws-sdk-js-v3> yarn generate-clients -g …
```

chore(scripts): build smithy-typescript from specific commit during codegen

---

packages/middleware-flexible-checksums/package.json
packages/middleware-flexible-checksums/src/configuration.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.ts
packages/middleware-flexible-checksums/src/getFlexibleChecksumsPlugin.ts
packages/middleware-flexible-checksums/src/streams/create-read-stream-on-buffer.browser.ts
packages/middleware-flexible-checksums/src/streams/create-read-stream-on-buffer.spec.ts
packages/middleware-flexible-checksums/src/streams/create-read-stream-on-buffer.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/5125
If checksum validation of the response is requested but the response is a stream, we fully gather the stream before passing it to the checksum validator and then the user. 
This has performance downsides due to collecting the stream in memory. However, if the user is opting into a checksum validation of the response, do we have an alternative? I'm not entirely certain after reading the internal spec for this.
revert the await from [3.383.0](https://github.com/aws/aws-sdk-js-v3/pull/5043), but that creates a potentially uncatchable error, which may crash user applications.
update unit tests
manual test
```js
import { GetObjectCommand, S3 } from "@aws-sdk/client-s3";
const s3Client = new S3({
region: "us-west-2",
});
const bucket = …
```

fix(middleware-flexible-checksums): split stream when validating response checksum

---

scripts/generate-clients/config.js
scripts/generate-clients/index.js
scripts/prepare-smithy-typescript.sh

Fixes JS-4624
Pins generate-clients to specific commit from smithy-ts
Clients are not updated by default, as it uses the latest commit
```console
$ yarn generate-clients -g codegen/sdk-codegen/aws-models/acm.json -n
...
$ git status
On branch pin-codegen-smithy-ts-commit
Your branch is up to date with 'origin/pin-codegen-smithy-ts-commit'.
nothing to commit, working tree clean
```
Clients are updated, when switching to commit with codegen prior to defaultExtensionConfiguration
```console
$ git diff
diff --git a/scripts/generate-clients/config.js b/scripts/generate-clients/config.js
index e7ac552eb5b..2f0b6219c06 100644
--- a/scripts/generate-clients/config.js
+++ b/scripts/generate-clients/config.js
@@ -1,4 +1,4 @@
// Update this commit when taking up new changes from smithy-typescript. …
```

chore(scripts): pin generate-clients to specific commit from smithy-ts

---

scripts/generate-clients/config.js

Internal JS-4665
The internal build are failing with error:
```console
fatal: 'd942a87' is not a commit
```
Using the full commit hash in client codegen
Verified that client codegen was successful
```console
$ yarn generate-clients -g codegen/sdk-codegen/aws-models/acm.json
...
Done in 56.50s.
$ git status
On branch smithy-ts-full-commit
Your branch is up to date with 'origin/smithy-ts-full-commit'.
nothing to commit, working tree clean
```
---

fix(scripts): use full commit hash in client codegen

---

scripts/generate-clients/build-smithy-typescript.js
scripts/generate-clients/config.js

Internal JS-4680 
Our internal CI was doing shallow clone till the last tag for smithy-typescript. When new tag was released in commit https://github.com/awslabs/smithy-typescript/commit/e9a378b5b0f7537006c63c07b8d6ee87dbaffc1f, our preview/release builds started failing as default commit was not available.
This PR calls git fetch origin for the provided commit in codegen, so that the commit is available.
Verified that codegen is successful by default (smithy-typescript is shallow cloned)
```console
$ aws-sdk-js-v3> yarn generate-clients -g codegen/sdk-codegen/aws-models/acm.json -n
...
Cloning into '/local/home/trivikr/workspace/smithy-typescript'...
From https://github.com/awslabs/smithy-typescript
* branch            d942a87081c0ca101f77b2336042773b26b0b9b1 -> FETCH_HEAD
Switched to a …
```

fix(scripts): git fetch origin provided commit in codegen

---

packages/credential-provider-ini/package.json
packages/credential-provider-node/package.json
packages/credential-provider-process/package.json
packages/credential-provider-sso/package.json
packages/token-providers/package.json
yarn.lock

Refs https://github.com/aws/aws-sdk-js-v3/issues/4345
Bumps shared-ini-file-loader to include os.homedir() cache fix
Since we use `^2.0.0`, the customers will get it if they don't use lockfiles or update their lockfiles. This change ensures that we explicitly request for version which contains the fix.
CI
---

chore(deps): bump shared-ini-file-loader to include os.homedir() cache fix

---

UPGRADING.md

update the retryer doc link to use the new docs.
https://github.com/aws/aws-sdk-js-v3/issues/5170

docs: update retry link

---

packages/region-config-resolver/CHANGELOG.md
packages/region-config-resolver/LICENSE
packages/region-config-resolver/README.md
packages/region-config-resolver/jest.config.js
packages/region-config-resolver/package.json
packages/region-config-resolver/src/extensions/index.ts
packages/region-config-resolver/src/index.ts
packages/region-config-resolver/src/regionConfig/config.spec.ts
packages/region-config-resolver/src/regionConfig/config.ts
packages/region-config-resolver/src/regionConfig/getRealRegion.spec.ts
packages/region-config-resolver/src/regionConfig/getRealRegion.ts
packages/region-config-resolver/src/regionConfig/index.ts
packages/region-config-resolver/src/regionConfig/isFipsRegion.spec.ts
packages/region-config-resolver/src/regionConfig/isFipsRegion.ts
packages/region-config-resolver/src/regionConfig/resolveRegionConfig.spec.ts
packages/region-config-resolver/src/regionConfig/resolveRegionConfig.ts
packages/region-config-resolver/tsconfig.cjs.json
packages/region-config-resolver/tsconfig.es.json
packages/region-config-resolver/tsconfig.types.json
packages/types/src/extensions/index.ts
packages/types/src/index.ts

* Migrate region config related files from smithy-typescript's `config-resolver` package to aws-sdk-js-v3's `region-config-provider` package
* Add runtime extension for region
* yarn build
* See codegen changes https://github.com/aws/aws-sdk-js-v3/pull/5157
---

feat(region-config-provider): Add region-config-provider package

---

packages/region-config-resolver/package.json

Internal JS-4687
Removes the `test:e2e` script from the `package.json` for region-config-resolver package.
---

chore(region-config-resolver): remove test:e2e script

---

packages/middleware-bucket-endpoint/package.json

Replacement for https://github.com/aws/aws-sdk-js-v3/pull/2928
move @smithy/node-config-provider to deps
CI
---

fix(middleware-bucket-endpoint): move @smithy/node-config-provider to deps

---

codegen/generic-client-test-codegen/build.gradle.kts
codegen/generic-client-test-codegen/model/weather.smithy
codegen/generic-client-test-codegen/smithy-build.json
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AwsCustomizeSigv4AuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

N/A.
Register `AwsCustomizeSigv4AuthPlugin` integration to customize
`@aws.auth#sigv4` to use:
- Browser: a function that throws an error saying `credentials` is
missing
- Node.js: `decorateDefaultCredentialProvider(credentialDefaultProvider)` from
`@aws-sdk/credential-provider-node` and `aws-sdk/client-sts`.
Dependent on: https://github.com/awslabs/smithy-typescript/pull/907
Everything is gated behind `experimentalIdentityAndAuth`.
Complete generic codegen client diff: https://gist.github.com/syall/5f0b85d33094e8182042f1b0e98c5ef7#file-pr-5179-diff
The diffs for `credentialDefaultProvider` and `region` were removed under the experimental flag in …

feat(experimentalIdentityAndAuth): customize `@aws.auth#sigv4` identity providers for the AWS SDK

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTokenAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AwsCustomizeHttpBearerTokenAuthPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

N/A.
Register `AwsCustomizeHttpBearerTokenAuthPlugin` integration to
customize `@httpBearerAuth` to use:
- Browser: a function that throws an error saying `token` is missing
- Node.js: `nodeProvider` from `@aws-sdk/token-providers`
Dependent on: https://github.com/awslabs/smithy-typescript/pull/907
Everything is gated behind `experimentalIdentityAndAuth`.
Complete generic codegen client diff: https://gist.github.com/syall/72886efc2450c04f73495351188ed61e#file-pr-5169-diff
The diffs for `credentialDefaultProvider` and `region` were removed under the experimental flag in https://github.com/aws/aws-sdk-js-v3/pull/5065, and will be added back in later PRs.
The main …

feat(experimentalIdentityAndAuth): customize `@httpBearerAuth` identity providers for the AWS SDK

---

packages/signature-v4-crt/package.json
packages/signature-v4-crt/src/index.ts
packages/signature-v4-multi-region/package.json
packages/signature-v4-multi-region/src/SignatureV4MultiRegion.spec.ts
packages/signature-v4-multi-region/src/SignatureV4MultiRegion.ts
packages/signature-v4-multi-region/src/index.ts
packages/signature-v4-multi-region/src/load-crt.browser.ts
packages/signature-v4-multi-region/src/load-crt.ts
packages/signature-v4-multi-region/src/signature-v4-crt-container.ts

related to https://github.com/aws/aws-sdk-js-v3/issues/5135
mentioned in https://github.com/aws/aws-sdk-js-v3/issues/4797
fixes https://github.com/aws/aws-sdk-js-v3/issues/4464
related to https://github.com/aws/aws-sdk-js-v3/issues/2822
partially addresses https://github.com/aws/aws-sdk-js-v3/issues/4126
fixes https://github.com/aws/aws-sdk-js-v3/issues/4373
- inverts the dependency between `signature-v4-crt` and `signature-v4-multi-region`. `crt` now depends on `multi-region`, and `multi-region` does not depend on `crt`, even optionally. 
- why? To avoid the conditional runtime require being analyzed as a static import by bundlers. Now, if you install `signature-v4-crt`, it will inject itself into a container that is used by `signature-v4-multi-region`.
revision 1:
- created node and …

fix(signature-v4-multi-region): make conditional require call in node.js only

---

packages/credential-provider-ini/src/resolveAssumeRoleCredentials.spec.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.ts

https://github.com/aws/aws-sdk-js-v3/issues/4589
This expands the assume role interface to be able to read `DurationSeconds` that is already provided by the ini file. Until now that value was not read even though it was technically available to consume, thus preventing from explicitly setting a duration on the session.
**ini file:**
```
[profile myrole]
role_arn=arn:aws:iam::1234567890123:role/my_role
duration_seconds=1534
source_profile=default
[default]
aws_access_key_id = YOUR_ACCESS_KEY
aws_secret_access_key = YOUR_SECRET_ACCESS_KEY
region = us-east-1
```
**repro code:**
```js
import { decorateDefaultCredentialProvider } from '@aws-sdk/client-sts'
import { defaultProvider } from '@aws-sdk/credential-provider-node'
const provider = decorateDefaultCredentialProvider(defaultProvider)({}) …
```

fix(credential-provider-ini): add DurationSeconds to assumeRole params

---

packages/util-endpoints/src/lib/aws/partition.spec.ts

use a static test partitions data to avoid automatic updates causing test failures

chore(util-endpoints): use static partitions test data

---

packages/middleware-sdk-s3/package.json
packages/middleware-sdk-s3/src/check-content-length-header.spec.ts
packages/middleware-sdk-s3/src/check-content-length-header.ts

partially addresses https://github.com/aws/aws-sdk-js-v3/issues/4979
- use console warn if logger is no-op

fix(middleware-sdk-s3): use console warn if logger is no-op

---

packages/util-dynamodb/package.json

this makes it consistent with lib-dynamodb, which has `^3.0.0` in peerDeps but `*` in devDeps

fix(util-dynamodb): update dependency version

---

packages/middleware-endpoint-discovery/src/endpointDiscoveryMiddleware.ts

N/A.
Assert `clientName` and `commandName` in `context`, since TypeScript says it can possible be `undefined` after https://github.com/awslabs/smithy-typescript/pull/931.
N/A.
N/A.
---

fix(middleware-endpoint-discovery): assert `clientName` and `commandName` in `context`

---

packages/credential-provider-http/.gitignore
packages/credential-provider-http/CHANGELOG.md
packages/credential-provider-http/README.md
packages/credential-provider-http/jest.config.js
packages/credential-provider-http/package.json
packages/credential-provider-http/src/fromHttp/checkUrl.spec.ts
packages/credential-provider-http/src/fromHttp/checkUrl.ts
packages/credential-provider-http/src/fromHttp/fromHttp.browser.ts
packages/credential-provider-http/src/fromHttp/fromHttp.spec.ts
packages/credential-provider-http/src/fromHttp/fromHttp.ts
packages/credential-provider-http/src/fromHttp/fromHttpTypes.ts
packages/credential-provider-http/src/fromHttp/requestHelpers.spec.ts
packages/credential-provider-http/src/fromHttp/requestHelpers.ts
packages/credential-provider-http/src/fromHttp/retry-wrapper.ts
packages/credential-provider-http/src/index.ts
packages/credential-provider-http/tsconfig.cjs.json
packages/credential-provider-http/tsconfig.es.json
packages/credential-provider-http/tsconfig.types.json
packages/credential-providers/README.md
packages/credential-providers/src/index.browser.ts
packages/credential-providers/src/index.ts

replaces https://github.com/aws/aws-sdk-js-v3/pull/5242
Adds an HTTP credential provider, a general form of the fromContainerMetadata provider.

feat(credential-providers): add fromHttp credential provider

---

packages/credential-provider-http/package.json
packages/credential-provider-http/src/index.browser.ts
packages/credential-provider-http/src/index.ts
packages/credential-providers/src/index.browser.ts

uses an alternate entry point for credential provider http in the browser so it does not export the fetch handler to Node.js users

fix(credential-provider-http): use alternate browser entry point

---

packages/middleware-sdk-ec2/src/index.ts

the presigner was receiving an incorrect value type (boolean) which led to the signature being wrong when the input had a boolean in it.

fix(middleware-sdk-ec2): fix presigning of boolean query param

---

.github/workflows/codegen-ci.yml
scripts/generate-clients/build-smithy-typescript-ci.js

N/A.
`codegen-ci` was building with the latest smithy-typescript commit, but should be building with the specified smithy-typescript commit.
CI passes.
N/A.
---

chore(codegen): update codegen-ci with configured smithy-typescript commit

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts

typescript codegen version bump https://github.com/awslabs/smithy-typescript/pull/984
---

feat(codegen): bump codegen version to 0.18.0

---

packages/util-endpoints/package.json
packages/util-endpoints/src/getEndpointUrlConfig.spec.ts
packages/util-endpoints/src/getEndpointUrlConfig.ts

Internal JS-4281
Adds utility to read service specific endpoints from environment variables and config.
CI
Previous attempt: https://github.com/aws/aws-sdk-js-v3/pull/5318
---

chore(util-endpoints): add utility to read service specific endpoints

---

clients/client-s3/src/S3Client.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
packages/middleware-sdk-s3/jest.config.e2e.js
packages/middleware-sdk-s3/package.json
packages/middleware-sdk-s3/src/index.ts
packages/middleware-sdk-s3/src/region-redirect-endpoint-middleware.ts
packages/middleware-sdk-s3/src/region-redirect-middleware.e2e.spec.ts
packages/middleware-sdk-s3/src/region-redirect-middleware.spec.ts
packages/middleware-sdk-s3/src/region-redirect-middleware.ts
packages/middleware-sdk-s3/src/s3Configuration.ts

#1807 
Adds a middleware for following region redirects to support S3 global client.
Unit tests and E2E tests added and confirmed that they succeed. 
E2E test:
```console
$ jest -c jest.config.e2e.js
PASS  src/region-redirect-middleware.e2e.spec.ts (17.917 s)
S3 Global Client Test
✓ Should be able to put objects following region redirect (8106 ms)
✓ Should be able to get objects following region redirect (1740 ms)
✓ Should delete objects following region redirect (876 ms)
Tests:       3 passed, 3 total
Time:        17.958 s
Done in 18.65s.
```
Unit test:
```console
$ jest
PASS  src/check-content-length-header.spec.ts
PASS  src/validate-bucket-name.spec.ts
PASS …
```

feat(middleware-sdk-s3): add middleware for following region redirects

---

packages/middleware-sdk-machinelearning/src/middleware-sdk-machinelearning.integ.spec.ts
packages/middleware-sdk-machinelearning/src/predict-endpoint.ts

the Predict command's middleware rewrites the request.
However, it may rewrite the query to `undefined`. This fails the `HttpRequest.isInstance` check for the AWS signer and the request goes unsigned, causing it to fail.
The PR ensures the query field is an object on the request.

fix(middleware-sdk-machinelearning): ensure request query is object

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientCommandGenerator.java
lib/lib-dynamodb/src/commands/BatchExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/BatchGetCommand.ts
lib/lib-dynamodb/src/commands/BatchWriteCommand.ts
lib/lib-dynamodb/src/commands/DeleteCommand.ts
lib/lib-dynamodb/src/commands/ExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/ExecuteTransactionCommand.ts
lib/lib-dynamodb/src/commands/GetCommand.ts
lib/lib-dynamodb/src/commands/PutCommand.ts
lib/lib-dynamodb/src/commands/QueryCommand.ts
lib/lib-dynamodb/src/commands/ScanCommand.ts
lib/lib-dynamodb/src/commands/TransactGetCommand.ts
lib/lib-dynamodb/src/commands/TransactWriteCommand.ts
lib/lib-dynamodb/src/commands/UpdateCommand.ts

Internal JS-4758 
Normalize the import path of `utils` in lib-dynamodb so that api-extractor does not crash
---

docs(lib-dynamodb): fix import path for api extractor compatibility

---

lib/lib-dynamodb/src/test/lib-dynamodb.e2e.spec.ts

no issue
Increase the timeout for lib dynamodb to 2 minutes table creation and 3 minutes total.
Currently the tests can complete in 10s without table creation and 30s with table creation, so the timeout is enough.
But I'd like to give it more time in case table creation time deviates due to congestion in the service or anything like that.

test(lib-dynamodb): increase e2e timeout for lib-dynamodb

---

packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.spec.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/5126
Add tests for flexibleChecksumsResponseMiddleware
CI
---

test(middleware-flexible-checksums): flexibleChecksumsResponseMiddleware.spec.ts

---

packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.ts
packages/middleware-flexible-checksums/src/getFlexibleChecksumsPlugin.ts

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/5342
Splits FlexibleChecksumsMiddlewareConfig into request/response
* CI
* Verified that new interfaces are subset of the old one.
---

chore(middleware-flexible-checksums): split FlexibleChecksumsMiddlewareConfig into request/response

---

packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.ts
packages/middleware-flexible-checksums/src/isChecksumWithPartNumber.spec.ts
packages/middleware-flexible-checksums/src/isChecksumWithPartNumber.ts
packages/middleware-flexible-checksums/src/selectChecksumAlgorithmFunction.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.spec.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/5032
Skips checksum validation for s3 whole-object multipart GET as per internal specification
> If GetObject response has checksum value ending with `-#` where `#` is an integer between 1 and 10000, clients **MUST** skip checksum validation. Checksum ending with `-#` indicates GetObject API returned a whole multipart object. Client can not validate such checksums, as checksum for whole multipart object is checksum of checksum for all the individual parts that conform the whole multipart object.
>
> If the GetObject request is called with a range which aligns to a part boundary or specific part number, then the response will have the checksum with the part number `-#`. If it's an arbitrary range, not matching a part boundary, then …

fix(middleware-flexible-checksums): skip checksum validation for s3 whole-object multipart GET

---

lib/lib-dynamodb/src/test/lib-dynamodb.e2e.spec.ts

internal JS-4767
Adds a timestamp component to the table name. While this unbounds the limit on the number of possible tables, the test deletes its table in `afterAll`, so there should only be leftover tables in unusual cases like process termination, which can be cleaned up manually.

test(lib-dynamodb): add timestamp to table name in e2e tests

---

packages/middleware-sdk-s3/src/region-redirect-middleware.e2e.spec.ts

Internal JS-4773
Increase timeout in E2E test for region-redirect-middleware
E2E tests pass locally
---

test(middleware-sdk-s3): increase timeout in E2E test

---

clients/client-s3/test/e2e/S3.ispec.ts

restore s3 ispec to 1mb payload after fixes to fetch keepalive

test(client-s3): update S3.ispec.ts

---

packages/middleware-host-header/src/index.spec.ts
packages/middleware-host-header/src/index.ts

Internal JS-4777
Populates the `:authority` pseudo-header with the authority section of target URI instead of the pseudo-header being populated by an empty string in all cases. Updates the test accordingly. 
```console
PASS  src/index.spec.ts
hostHeaderMiddleware
✓ should set host header if not already set (4 ms)
✓ should include port in host header when set (1 ms)
✓ should not set host header if already set (1 ms)
✓ should set :authority header for H2 requests (1 ms)
Tests:       4 passed, 4 total
Time:        3.375 s, estimated 5 s
Done in 3.98s.
```
Specification: https://www.rfc-editor.org/rfc/rfc9113.html#name-request-pseudo-header-field
---
By submitting this pull request, I confirm that you can use, modify, …

fix(middleware-host-header): populate :authority pseudo-header with authority section of target URI

---

packages/core/package.json
packages/core/src/index.ts
packages/core/src/protocols/index.ts
packages/core/src/protocols/json/awsExpectUnion.spec.ts
packages/core/src/protocols/json/awsExpectUnion.ts

internal JS-4668, JS-4669
adds a parsing util that differs slightly from the default smithy expectUnion fn
new unit tests

chore(core): add awsExpectUnion function

---

packages/middleware-host-header/src/middleware-host-header.integ.spec.ts

Internal JS-4777
Adds a test case in integration test to check that the `:authority` pseudo-header is set when using HTTP/2.0
Integration tests pass.
```console
PASS  src/middleware-host-header.integ.spec.ts
middleware-host-header
SageMaker
✓ should set the host header (51 ms)
✓ should set the authority header when using http2 (3 ms)
Tests:       2 passed, 2 total
Time:        4.891 s, estimated 6 s
Done in 5.57s.
```
PR that adds the authority section of target URI to the `:authority` pseudo-header: https://github.com/aws/aws-sdk-js-v3/pull/5369
---

test(middleware-host-header): add test for :authority header in integ test

---

packages/middleware-sdk-s3/src/region-redirect-middleware.e2e.spec.ts
packages/middleware-sdk-s3/src/region-redirect-middleware.ts

#5388 
Removes the check for error name as HEAD operations don't have that error name (but still have the 301 status code). This allows users to opt in for region redirection for HEAD operations as well. 
E2E tests pass
```console
PASS  src/region-redirect-middleware.e2e.spec.ts (19.069 s)
S3 Global Client Test
✓ Should be able to put objects following region redirect (8377 ms)
✓ Should be able to get objects following region redirect (3847 ms)
✓ Should delete objects following region redirect (907 ms)
Tests:       3 passed, 3 total
Time:        19.112 s
Done in 19.81s.
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

fix(middleware-sdk-s3): remove error name check to allow for region redirect for HEAD operations

---

packages/credential-provider-web-identity/package.json
packages/middleware-flexible-checksums/package.json
packages/middleware-token/package.json
packages/rds-signer/package.json
packages/token-providers/package.json
packages/types/package.json
packages/util-dns/package.json
packages/util-user-agent-browser/package.json
scripts/runtime-dependency-version-check/check-dependencies.js
scripts/runtime-dependency-version-check/package-json-enforcement.js

paired with https://github.com/awslabs/smithy-typescript/pull/1066 (see explanation there)

chore: add package entrypoints enforcement script

---

clients/client-sagemaker/src/protocols/Aws_json1_1.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonShapeDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlMemberDeserVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/protocols/DeserializerElisionDenyList.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/visitor/MemberDeserVisitor.java

Created a deserialization fn elision denylist.
What this means is that for services in the list, the JSON serde elision optimization will not be applied.
The optimization reduces deserialization to `JSON.parse` instead of nested functions.
Initially, this is for SageMaker, which wants to restrict the deserialized fields to only those listed in the model.
```
npx cucumber-js -t @sagemaker
.........
```

fix(codegen): create deser fn elision denylist

---

README.md

#5010
#4867
#5017
#V1101561159
Our Readme is clearly missing an example using Lambda. This is a constant source of confusion. Since our developer guide needs a reboot, the main doc page is the best place in my mind to put this.

docs(readme): add recommendations for SDK use in Lambda

---

packages/types/src/identity/TokenIdentity.ts

Types should not be defined in @aws-sdk/types when the equivalent type exists in the @smithy/types package. Instead, they should just be re-exported.
See related issue in https://github.com/smithy-lang/smithy-typescript/issues/1048#issuecomment-1781610644.
This PR removes the `TokenIdentity` and `TokenIdentityProvider` types and re-exports the equivalent types that are defined in the `@smithy/types` package.
Re-built packages after types change.
---

chore(packages): re-export TokenIdentity types

---

lib/lib-storage/src/Upload.ts

The return types for `Upload#done()` incorrectly included `AbortMultipartUploadCommandOutput` in the return type. In reality, it's clear that only `CompleteMultipartUploadCommandOutput` will be returned. If to upload is aborted, the returned promise is rejected with an `AbortError`.
Fixes #5513.
---

fix(lib-storage): use correct return type for done()

---

packages/xhr-http-handler/src/xhr-http-handler.ts

Add a static factory method for XHR handler to be consistent with https://github.com/smithy-lang/smithy-typescript/pull/1089

feat(xhr-http-handler): add static factory method for XHR handler

---

Makefile

helper commands to link and unlink smithy in an adjacent JSv3 folder

chore: create smithy link/unlink in Makefile

---

packages/credential-providers/README.md
packages/credential-providers/src/fromCognitoIdentity.ts
packages/credential-providers/src/fromCognitoIdentityPool.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3112
Updates credential-providers docs to update that cognito identity providers accepts client and not clientConfig.
It might have been a miss in the past when creating docs. I went through git blame.
* The original PR which added cognito identity credential providers accepted `client` https://github.com/aws/aws-sdk-js-v3/pull/109
* Git history for the file https://github.com/aws/aws-sdk-js-v3/commits/main/packages/credential-provider-cognito-identity/src/CognitoProviderParameters.ts
N/A
---

docs(credential-providers): cognito identity providers accepts client and not config

---

clients/client-workspaces-thin-client/src/index.ts
codegen/config/checkstyle/checkstyle.xml
scripts/generate-clients/customizations/workspaces-thin-client.js
scripts/generate-clients/index.js
scripts/generate-clients/single-service.js

corrects names and adds aliases for backwards compatibility to the WorkspacesThinClient service

fix(client-workspaces-thin-client): add naming aliases

---

clients/client-cloudfront/src/protocols/Aws_restXml.ts
clients/client-s3-control/src/protocols/Aws_restXml.ts
clients/client-s3/src/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
private/aws-protocoltests-restxml/src/protocols/Aws_restXml.ts

N/A.
Codegen for `@aws.protocols#restXml` serialization was duplicated due to `super` invocations for payload serialization.
This PR dedupes the serialization by removing the `super` invocations.
TODO:
CI passes.
Identified affected services:
```shell
$ cd codegen/sdk-codegen/aws-models/
$ smithy select --selector "[trait|aws.protocols#restXml]" --allow-unknown-traits .
com.amazonaws.cloudfront#Cloudfront2020_05_31
com.amazonaws.route53#AWSDnsV20130401
com.amazonaws.s3#AmazonS3
com.amazonaws.s3control#AWSS3ControlServiceV20180820
```
Route53 did not end up having any codegen changes, but CloudFront, S3, and S3 Control did. …

fix(codegen): dedupe `@aws.protocols#restXml` serialization

---

codegen/generic-client-test-codegen/build.gradle.kts
codegen/generic-client-test-codegen/model/weather.smithy

N/A.
Add `endpointRuleSet` trait to generic client test.
CI passes.
N/A.
---

feat(experimentalIdentityAndAuth): add `endpointRuleSet` trait to generic client test

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventStreamHandlingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddWebsocketPlugin.java

N/A.
Add event streaming input integrations relative to auth.
- feat(experimentalIdentityAndAuth): remove `AddEventStreamHandlingDependency` experimental branch
- feat(experimentalIdentityAndAuth): add order for `AddWebsocketPlugin`
See the diff in this branch: https://github.com/syall/aws-sdk-js-v3/tree/TEMP-streaming
- commit (may be outdated): https://github.com/syall/aws-sdk-js-v3/commit/82f2e6f3b19516248d3c223cf79e3a72e4403858
The following clients (services with event stream inputs) compile correctly:
- `client-lex-runtime-v2`
- `client-rekognitionstreaming`
- `client-transcribe-streaming`
```shell
yarn generate-clients -n -g \ …
```

feat(experimentalIdentityAndAuth): add event streaming input integrations relative to auth

---

packages/middleware-sdk-s3/src/region-redirect-middleware.ts

#5554 
for region redirect middleware -- safely access nested properties for error, namely `$metadata` and `httpStatusCode`
```
.
.
PASS  src/region-redirect-middleware.spec.ts (6.543 s)
.
.
Test Suites: 9 passed, 9 total
Tests:       20 passed, 20 total
Time:        6.868 s
Done in 7.36s.
```
---

fix(middleware-sdk-s3): safely access nested properties for error

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventBridgePlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AwsSdkCustomizeEndpointRuleSetHttpAuthSchemeProvider.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

N/A.
Add `@smithy.rules#endpointRuleSet` auth scheme providers.
See branch with generated `client-s3` and `client-eventbridge` diffs: https://github.com/syall/aws-sdk-js-v3/tree/TEMP-endpointRuleSet
- `client-s3` (may be outdated): https://github.com/aws/aws-sdk-js-v3/commit/542f9262566322947e37257ba987b731ac96edda
- `client-eventbridge` (may be outdated): https://github.com/aws/aws-sdk-js-v3/commit/c96adb8941652875d1a0ff90c7f725ba43f58e0f
Clients compile successfully.
N/A.
---

feat(experimentalIdentityAndAuth): add `@smithy.rules#endpointRuleSet` auth scheme providers

---

packages/core/package.json
packages/core/src/httpAuthSchemes/aws-sdk/AWSSDKSigV4Signer.ts
packages/core/src/httpAuthSchemes/aws-sdk/index.ts
packages/core/src/httpAuthSchemes/aws-sdk/resolveAWSSDKSigV4Config.ts
packages/core/src/httpAuthSchemes/aws-sdk/throwAWSSDKSigningPropertyError.ts
packages/core/src/httpAuthSchemes/index.ts
packages/core/src/httpAuthSchemes/utils/getDateHeader.ts
packages/core/src/httpAuthSchemes/utils/getSkewCorrectedDate.spec.ts
packages/core/src/httpAuthSchemes/utils/getSkewCorrectedDate.ts
packages/core/src/httpAuthSchemes/utils/getUpdatedSystemClockOffset.spec.ts
packages/core/src/httpAuthSchemes/utils/getUpdatedSystemClockOffset.ts
packages/core/src/httpAuthSchemes/utils/index.ts
packages/core/src/httpAuthSchemes/utils/isClockSkewed.spec.ts
packages/core/src/httpAuthSchemes/utils/isClockSkewed.ts
packages/core/src/index.ts

N/A.
Add AWS SDK SigV4 support in `experimentalIdentityAndAuth`.
This is heavily based on https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-signing.
CI passes in staging PR, tested with STS and DynamoDB commands: https://github.com/aws/aws-sdk-js-v3/pull/5587
N/A.
---

feat(core): add AWS SDK SigV4 support

---

packages/core/src/httpAuthSchemes/aws-sdk/resolveAWSSDKSigV4Config.ts

https://github.com/aws/aws-sdk-js-v3/issues/5591
Wrap `credentialDefaultProvider` with `memoizeIdentityProvider`.
Using the repro from: https://github.com/aws/aws-sdk-js-v3/issues/5591, and also testing it without a configured `credentialDefaultProvider`:
```javascript
const { STSClient, GetCallerIdentityCommand } = require("@aws-sdk/client-sts")
const client = new STSClient({
"region": "us-west-2"
})
const command = new GetCallerIdentityCommand({})
client.send(command).then((res) => { console.log(res) }).catch((err) => { console.log("ERR:", err) })
```
When passing in `defaultProvider` like done in the repro, the types are …

fix(core): wrap `credentialDefaultProvider` with `memoizeIdentityProvider`

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEndpointDiscoveryPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventBridgePlugin.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTranscribeStreamingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddWebsocketPlugin.java

N/A
Uses TypeScriptDependency in addImport calls, as using string is deprecated
Verified that imports were not updated
---

chore(codegen): use TypeScriptDependency in addImport calls

---

packages/middleware-bucket-endpoint/package.json
packages/middleware-sdk-s3/package.json
packages/region-config-resolver/package.json
yarn.lock

* Required for https://github.com/aws/aws-sdk-js-v3/pull/5620
* Missed in https://github.com/aws/aws-sdk-js-v3/pull/5621
Bump @smithy/util-config-provider to 2.1.0
N/A
---

chore(deps): bump @smithy/util-config-provider to 2.1.0

---

packages/middleware-compression/CHANGELOG.md
packages/middleware-compression/api-extractor.json
packages/middleware-compression/package.json

Internal JS-4947
Adds missing @aws-sdk prefix in package name, along with CHANGLOG and docs generation config/commands.
Verified that `test:size` is successful
```console
$ yarn test:size --since last_release
...
Updating 45 rows in the report /local/home/trivikr/workspace/aws-sdk-js-v3/benchmark/size/report.md
Report is updated, validating the new result with the limit configurations.
Done in 542.39s.
```
---

fix(middleware-compression): add missing @aws-sdk prefix in package name

---

packages/middleware-compression/src/NODE_DISABLE_REQUEST_COMPRESSION_CONFIG_OPTIONS.spec.ts
packages/middleware-compression/src/NODE_DISABLE_REQUEST_COMPRESSION_CONFIG_OPTIONS.ts
packages/middleware-compression/src/NODE_REQUEST_MIN_COMPRESSION_SIZE_BYTES_CONFIG_OPTIONS.spec.ts
packages/middleware-compression/src/NODE_REQUEST_MIN_COMPRESSION_SIZE_BYTES_CONFIG_OPTIONS.ts

Required in https://github.com/aws/aws-sdk-js-v3/pull/5625, to set default in shared environments
Export default configuration values for middleware-compression
CI
---

chore(middleware-compression): export default configuration values

---

packages/types/package.json
packages/types/src/blob/runtime-blob-types.browser.ts
packages/types/src/blob/runtime-blob-types.node.ts

Remove unused types.
These types were not used anywhere and not exported from this package.
The real version of these types are declared in https://github.com/smithy-lang/smithy-typescript/blob/main/packages/types/src/blob/blob-payload-input-types.ts with different names.

chore(types): remove unused un-exported types

---

packages/middleware-compression/package.json
packages/middleware-websocket/package.json
packages/region-config-resolver/package.json
packages/util-endpoints/package.json
scripts/runtime-dependency-version-check/check-dependencies.js

- fix the dependency check script, a `.slice(1)` was omitting one of the matches that should have been checked.
- then add any detected missing dependencies.

fix: dependency check script and undeclared dependencies

---

packages/middleware-compression/README.md
packages/middleware-compression/src/configurations.ts

The middleware-compression was moved to `@smithy` in https://github.com/smithy-lang/smithy-typescript/pull/1128
Add deprecation message in README and code for `@aws-sdk/middleware-compression`
N/A
---

docs(middleware-compression): add deprecation messages

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts

for multipart upload (for files > 5mb) the `CompleteMultipartUploadCommand` returns the Location of the file with `%2f` symbol which is encoded `/` slash.
After migrating aws-sdk from v2 to v3 we've noticed that for large files (> 5m) the final S3 url contains `%2f` instead of `/` (it broke our frontend app, clients lost and access to such files). 
i've found out this issue was fixed in similar PR for `aws-sdk-js-v2` [#1420](https://github.com/aws/aws-sdk-js/pull/1420)
also this issue was discussed and similarly fixed in `aws-sdk-go` [issue #1385](https://github.com/aws/aws-sdk-go/issues/1385) and [fix PR #2453](https://github.com/aws/aws-sdk-go/pull/2453)

fix(lib-storage): URI-decoding of object Locations for Multipart Upload

---

codegen/sdk-codegen/build.gradle.kts

Adds a dependency on smithy-smoke-test-traits in the sdk code gen package so aws service models that use the smokeTests trait won't fail to build because of unknown traits.
Generated a client with a smoke test and confirmed there was no diff.
Adding the dependency in the code gen package since it's the models that need the dependency, not the code generator. When smoke tests are implemented in the generator, we can add the dep there.
---

chore: add smoke test traits dep

---

scripts/compilation/Inliner.js
scripts/compilation/inline.js

n/a
This is paired with the `index inlining` feature from https://github.com/smithy-lang/smithy-typescript/pull/1113.
manual testing
- `n/a` If you wrote E2E tests, are they resilient to concurrent I/O?
- `n/a` If adding new public functions, did you add the `@public` tag and enable doc generation on the package?

feat: cjs inline build

---

clients/client-cloudfront-keyvaluestore/package.json
clients/client-cloudfront-keyvaluestore/src/runtimeConfig.shared.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddCloudFrontKeyValueStorePlugin.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

This PR changes the default signer to `SignatureV4MultiRegion` for `@aws-sdk/client-cloudfront-keyvaluestore`.
Without this change, to use certain features, users must manually set the signer like so:
```js
const { SignatureV4MultiRegion } = require("@aws-sdk/signature-v4-multi-region");
require("@aws-sdk/signature-v4-crt");
const client = new CloudFrontKeyValueStoreClient({
region: "us-east-1",
signerConstructor: SignatureV4MultiRegion,
});
```
After this change is released:
```js
require("@aws-sdk/signature-v4-crt");
const client = new CloudFrontKeyValueStoreClient({
region: "us-east-1",
// default signer is SignatureV4MultiRegion, no need to explicitly set it
});
```

fix(client-cloudfront-keyvaluestore): use sigv4a signer by default

---

packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.e2e.spec.ts

enable e2e tests for s3 express

chore(middleware-sdk-s3): enable s3 express e2e tests

---

UPGRADING.md

#5712
Adds a section for S3 global client in UPGRADING.md
---

chore(upgrading): add section for S3 global client

---

clients/client-s3/src/commands/GetObjectCommand.ts
clients/client-s3/src/commands/HeadObjectCommand.ts
clients/client-s3/src/models/models_0.ts
clients/client-s3/src/models/models_1.ts
clients/client-s3/src/protocols/Aws_restXml.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
packages/middleware-sdk-s3/src/index.ts
packages/middleware-sdk-s3/src/s3-expires-middleware.e2e.spec.ts
packages/middleware-sdk-s3/src/s3-expires-middleware.ts
scripts/generate-clients/s3-hack.js

n/a
Modifies S3 operation responses that contain the `Expires` timestamp. In cases where this value is not a well-formatted Rfc7231DateTime, the operation will now complete with a fallback behavior and warning instead of throwing an exception.
The string value of the Expires field will be placed in an adjacent field called `ExpiresString`. This currently applies to the GetObject and HeadObject responses.
added unit and e2e tests

chore(middleware-sdk-s3): add string fallback for S3#Expires field

---

packages/token-providers/src/bundle/client-sso-oidc-node.ts

My team was pretty consistently seeing "Token is expired. To refresh this SSO session run 'aws sso login' with the corresponding profile." errors when trying to use the AWS JS SDK.  After doing some debugging, I was able to boil it down to the following error:
```
ReferenceError: _CreateTokenCommand is not defined
at CreateTokenCommand.resolveMiddleware (......./node_modules/@aws-sdk/token-providers/dist-cjs/bundle/client-sso-oidc-node.js:914:94)
at SSOOIDCClient.send (......./node_modules/@smithy/smithy-client/dist-cjs/index.js:110:29)
at getNewSsoOidcToken (......./node_modules/@aws-sdk/token-providers/dist-cjs/index.js:57:24)
at ......./node_modules/@aws-sdk/token-providers/dist-cjs/index.js:155:35
at async resolveSSOCredentials …
```

Use correct CreateTokenCommand

---

packages/middleware-sdk-s3/src/check-content-length-header.spec.ts
packages/middleware-sdk-s3/src/check-content-length-header.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/5722

fix(middleware-sdk-s3): do not warn when content-length is 0

---

clients/client-sts/package.json

because STS has a circular dep, when building types it must be cleaned first

fix: sts build script

---

packages/credential-provider-ini/src/resolveProfileData.spec.ts
packages/credential-provider-ini/src/resolveProfileData.ts
packages/credential-provider-ini/src/resolveSsoCredentials.spec.ts
packages/credential-provider-ini/src/resolveSsoCredentials.ts

Fixes #4757.
Previously, when credential-provider-ini resolved credentials for a source profile, it loaded the profile properties, checked if the profile was an SSO profile, validated that all required sso_* properties were present and then resolved credentials with credential-provider-sso module.
When source profile was an SSO profile that did not use an SSO session, this logic worked fine as the profile must include all the sso_* properties for SSO to succeed. However, when source profile was an SSO profile that used an SSO session, credential-provider-ini only resolved profile properties directly from the profile but not from the related SSO session.
This caused sso-session based profiles to fail validation as some of the required sso_* properties are only defined in the referenced …

fix(credential-provider-ini): support sso-session based profile as source_profile

---

packages/credential-provider-node/src/defaultProvider.spec.ts
packages/credential-provider-node/src/defaultProvider.ts

fixes a secondary issue reported in https://github.com/aws/aws-sdk-js-v3/issues/4757
only skip the SSO provider within the default credential chain for Node.js if _all_ SSO fields are not present.
added unit test

fix(credential-provider-node): only skip sso init if all sso fields are not present

---

packages/credential-provider-http/src/fromHttp/fromHttp.ts
packages/credential-provider-ini/src/resolveProfileData.spec.ts
packages/credential-provider-ini/src/resolveProfileData.ts
packages/credential-provider-ini/src/resolveSsoCredentials.ts
packages/credential-provider-ini/src/resolveWebIdentityCredentials.ts
packages/credential-provider-node/package.json
packages/credential-provider-node/src/remoteProvider.spec.ts
packages/credential-provider-node/src/remoteProvider.ts
packages/credential-provider-sso/src/fromSSO.spec.ts
packages/credential-provider-sso/src/fromSSO.ts
packages/credential-provider-sso/src/resolveSSOCredentials.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/5709
- adds the `fromHttp` generalized credential provider ahead of the `fromContainerMetadata` provider.
fixes https://github.com/aws/aws-sdk-js-v3/issues/5743
- prefers the SSO region from config file if initializing from an SSO profile

fix(credential-provider-node): add fromHttp credential provider to default chain

---

lib/lib-dynamodb/src/commands/marshallInput.spec.ts
lib/lib-dynamodb/src/commands/utils.spec.ts
lib/lib-dynamodb/src/commands/utils.ts
packages/util-dynamodb/src/marshall.spec.ts

#5686 
skipping function properties when processing data objects for DynamoDB
---

fix(lib-dynamodb): skip function properties in data objects for DynamoDB

---

clients/client-sso-oidc/package.json
clients/client-sts/package.json
scripts/update-versions/current.mjs
scripts/update-versions/default.mjs
scripts/update-versions/peers.mjs
scripts/update-versions/updateVersions.mjs

client-sts and client-sso-oidc are marked as credential clients and have a peer dependency on credential-provider-node due to circular dependencies. 
This PR sets the minimum value of the peer during both the pre-commit and the pre-publish steps.

chore: set peer workspace version during publish

---

tsconfig.cjs.json
tsconfig.es.json

https://github.com/aws/aws-sdk-js-v3/issues/5750
There's no reason to set noEmitHelpers=true, because we don't provide global helper functions as is intended when this flag is true. 
https://www.typescriptlang.org/tsconfig#noEmitHelpers
Ran build:cjs and confirmed helper present.

fix(build): set noEmitHelpers=false due to importHelpers=true

---

packages/credential-provider-node/jest.config.integ.js
packages/credential-provider-node/package.json
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

tests for https://github.com/aws/aws-sdk-js-v3/pull/5758
integ test the Node.js default credential provider chain

test(credential-provider-node): add integ test for default credential chain

---

packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

Internal JS-5011
supply region explicitly to sts client
---

test(credential-provider-node): supply region explicitly to sts client

---

README.md
private/aws-client-api-test/src/client-interface-tests/client-s3/impl/initializeWithMaximalConfiguration.ts
supplemental-docs/CLIENTS.md
supplemental-docs/README.md

Adds a supplemental docs folder as a collection point, as a quick way for maintainers to write docs local to the code repo.

docs: add supplemental docs

---

clients/client-sts/src/defaultRoleAssumers.ts
clients/client-sts/src/defaultStsRoleAssumers.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts
packages/core/src/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.ts
packages/credential-provider-ini/src/resolveWebIdentityCredentials.ts
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts
packages/credential-provider-web-identity/src/fromWebToken.ts
packages/middleware-signing/src/awsAuthConfiguration.ts
packages/types/src/credentials.ts

related to https://github.com/aws/aws-sdk-js-v3/issues/5749
related to https://github.com/aws/aws-sdk-js-v3/issues/5755
Currently, some credential providers have an "inner" or additional client not instantiated by the user. One example is the instantiation of an STS client for assumeRole, which is available to any SDK client without user input.
This inner client does not inherit configuration from the user instantiated, or "outer" client. That is because the credentialProvider functions (factories) are standalone and may be called outside of the context of an SDK client.
This PR passes in a reference to the outer client config (and its region) in one special case. 
- if the default credential provider is used without specification, i.e.
```ts
new Client({});
// only if no credentials are …
```

fix(credential-provider-node): pass client region to inner credential client region

---

supplemental-docs/CLIENTS.md

docs: update endpoint section

---

scripts/compilation/Inliner.js

fix a build step that renamed variables in a way that collided
pre-transform:
```js
var import_core = require("@smithy/core");
var import_core2 = require("@aws-sdk/core");
import_core.prop;
import_core2.prop;
var import_core3 = require("@smithy/core");
import_core3.prop;
var import_core4 = require("@aws-sdk/core");
import_core4.prop;
```
broken:
```js
var import_core = require("@smithy/core");
var import_core = require("@aws-sdk/core");
import_core.prop;
import_core.prop;
import_core.prop;
import_core.prop;
```
fix:
```js
var import_core = require("@smithy/core");
var import_core2 = require("@aws-sdk/core");
import_core.prop;
import_core2.prop;
import_core.prop;
import_core2.prop;
```

chore: fix inline script variable name collision

---

packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

When running `yarn test:integration` locally in `credential-provider-node`, the expiration for `container-authorization` would be off by a local offset.
```diff
Object {
"accessKeyId": "CONTAINER_ACCESS_KEY",
-   "expiration": 3000-01-01T08:00:00.000Z,
+   "expiration": 3000-01-01T00:00:00.000Z,
"secretAccessKey": "CONTAINER_SECRET_ACCESS_KEY",
"sessionToken": "CONTAINER_TOKEN",
}
```
Update date strings to use fully specified offsets.
1. `yarn test:integration`
2. CI passes
N/A.
---

fix(credential-provider-node): update date strings to use fully specified offsets

---

packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

slightly modifies the integ test to ensure that the SSO region is being checked in assertions

test(credential-provider-node): check sso region in integ test

---

UPGRADING.md

add upgrading remark on S3 getObject buffer vs stream

docs(UPGRADING): describe S3 getObject buffer vs. stream

---

clients/client-sts/src/defaultStsRoleAssumers.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

https://github.com/aws/aws-sdk-js-v3/issues/5799
This fixes the behavior of the STS role assumer internal client to use the parent client's region if available in any region, not just non-AWS partitions.
Added integ test case

fix(client-sts): use outer client region before default STS global region

---

clients/client-sts/src/defaultStsRoleAssumers.ts
clients/client-sts/test/defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts
packages/types/src/credentials.ts

https://github.com/aws/aws-sdk-js-v3/issues/5794
Add a default value for logger and requestHandler in the STS role assumer client using the parent client config if available.
Added unit test

fix(client-sts): pass parent logger & requestHandler to STS

---

packages/middleware-websocket/src/websocket-fetch-handler.ts

Picking up back where I left off earlier. 
Adding static factory to Websocket handler so it can behave uniformly with the other handlers that already have such a method.

chore(middleware-websocket): create static factory for Websocket handler

---

supplemental-docs/CLIENTS.md

add example on how to use shorter requestHandler configuration syntax

docs: requestHandler configuration short form example

---

packages/core/src/httpAuthSchemes/aws_sdk/AwsSdkSigV4Signer.spec.ts
packages/core/src/httpAuthSchemes/aws_sdk/AwsSdkSigV4Signer.ts

for https://github.com/smithy-lang/smithy-typescript/pull/1170
This PR adds an internal additional metadata field called "clockSkewCorrected" for the sigv4signer error handler. It indicates that the error resulted in a clock skew correction.
This will be used to retry as a transient error after the inclusion of https://github.com/smithy-lang/smithy-typescript/pull/1170.

fix(core): add error metadata indicating clock skew correction

---

UPGRADING.md

committing the guidance given in https://github.com/aws/aws-sdk-js-v3/issues/5812

docs(client-sqs): regarding multi-region SQS usage

---

packages/s3-presigned-post/README.md

update doc example to use `bucket-owner-full-control` instead of `public-read`

docs(s3-presigned-post): use bucket-owner-full-control in examples

---

packages/middleware-sdk-s3/src/bucket-endpoint-middleware.ts
packages/middleware-sdk-s3/src/middleware-sdk-s3.integ.spec.ts
packages/middleware-sdk-s3/src/s3Configuration.ts
packages/middleware-sdk-s3/src/validate-bucket-name.spec.ts
packages/middleware-sdk-s3/src/validate-bucket-name.ts
private/aws-client-api-test/src/client-interface-tests/client-s3/impl/initializeWithMaximalConfiguration.ts

https://github.com/aws/aws-sdk-js-v3/issues/4394
https://github.com/aws/aws-sdk-js-v3/issues/5052
Re-implement the missing `bucketEndpoint` config flag.
This allows the bucket value to replace the endpoint for requests from that client.

fix(middleware-sdk-s3): restore bucketEndpoint configurability

---

scripts/compilation/Inliner.js

Since we have had this disclaimer for a while: https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#stability-of-modular-packages
We can stop generating re-export stub files in clients.
Packages and libs continue to have re-export stubs.

chore: stop generating re-export stubs for clients

---

lib/lib-storage/src/Upload.ts
lib/lib-storage/src/types.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/5612
because we used our class as the type, it makes implementation details required. The interface should be used to allow interop with the recommended global implementation.

fix(lib-storage): use AbortController interface instead of class as type

---

README.md

Linking performance section added in https://github.com/aws/aws-sdk-js-v3/pull/5848
Adds link to performance section in README
Refer https://github.com/aws/aws-sdk-js-v3/blob/trivikr-patch-1/README.md
<details>
<summary>Screenshot</summary>
</details>
---

docs: add link to performance section in README

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddSigv4aPlugin.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

n/a
Add detection of the sigv4a auth trait and use the multiregion signer if that is the case.
Some services are already using sigv4a (hard-coded) but do not have the trait. This PR does not remove sigv4a from those services.

chore(codegen): add sigv4a trait detection

---

packages/core/package.json

https://github.com/aws/aws-sdk-js-v3/discussions/5865
https://github.com/aws/aws-sdk-js-v3/issues/5866
Add missing dependency. We need to update our validation, which currently doesn't check for packages outside our owned scopes.

fix(core): add missing fast-xml-parser dependency

---

packages/middleware-signing/src/awsAuthConfiguration.ts
packages/middleware-signing/src/awsAuthMiddleware.ts

n/a
In awsAuthMiddleware, select the second authScheme if:
- second auth scheme exists
- first auth scheme is sigv4a
- sigv4a is not available
existing unit test

fix(middleware-signing): attempt secondary authscheme selection during request signing

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentAggregatedClientGenerator.java
lib/lib-dynamodb/src/DynamoDBDocument.ts

This brings the dynamodb document client generator in line with https://github.com/smithy-lang/smithy-typescript/pull/1206
There is no actual diff because the DynamoDBDocument "client" does not extend any of the optional-args commands from DynamoDB like listTables.
code gen client-dynamodb which also generates lib-dynamodb

chore(codegen): accomodate optional inputs in lib-dynamodb generator

---

codegen/generic-client-test-codegen/model/weather.smithy

Resolves a number of minor smithy build warnings that were adding to build noise. All warnings were related to `GET` methods with no `readonly` trait.
Ran `./gradlew clean build` from `codegen` directory and verified no smithy validation events emitted.
- [N/A] If you wrote E2E tests, are they resilient to concurrent I/O?
- [N/A] If adding new public functions, did you add the `@public` tag and enable doc generation on the package?
---

chore: resolve smithy build warnings

---

codegen/build.gradle.kts
codegen/config/checkstyle/checkstyle.xml
codegen/gradle/wrapper/gradle-wrapper.properties
codegen/sdk-codegen/build.gradle.kts

Upgrades gradle version used for codegen package to 8.2.1
`./gradlew clean build` from `codegen` directory succeeds with no errors.
Follow up after updates to smithy-typescript gradle version.
- [N/A] If you wrote E2E tests, are they resilient to concurrent I/O?
- [N/A] If adding new public functions, did you add the `@public` tag and enable doc generation on the package?
---

chore: upgrade gradle version to 8.2.1

---

packages/middleware-ssec/src/index.spec.ts
packages/middleware-ssec/src/index.ts

#5863
Making a a more robust check for if the provided key is indeed a base64  by comparing the byte length to 32, since AES-256 specifies a cipher must be 256bits (32 bytes) we can assert that the cipher provided must have a byte length of 32.
> AES-256() The block cipher specifed in this Standard with 256-bit keys
https://csrc.nist.gov/pubs/fips/197/final
Added unit test coverage to cover the more of the middleware changes from https://github.com/aws/aws-sdk-js-v3/pull/5676
And additionally unit tests to cover the `isValidBase64EncodedSSECustomerKey` helper function.
Borrowed from edge case mentioned in #5863:
```js
async function putObjectWithMD5EncodedSSECKey(){
try {
const SSECustomerKey = crypto
.createHash("md5")
.update("foo")
.digest("hex");
const SSECustomerKeyMD5 = crypto …
```

fix(middleware-ssec): ssecMiddleware with strict base64 validation

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts

related to https://github.com/smithy-lang/smithy-typescript/pull/1213

chore: empty the contents of the sdkVersions.properties file when writing to it

---

tests/canary/canary-test-1.js
tests/canary/canary-test-2.js
tests/canary/canary.js

Creates a canary / smoke test that runs outside the workspace of this repo. 
`node tests/canary/canary`

test(canary): create an isolated workspace test

---

packages/cloudfront-signer/README.md
packages/cloudfront-signer/src/sign.spec.ts
packages/cloudfront-signer/src/sign.ts

Resolves #5836
Related #4516
`getSignedUrl()` now automatically gets the `url` from the `policy`'s Resource, allowing the `url` to be optionally typed when we're using `InputWithPolicy`.
Types are also updated.
I copied the package locally into a workspace project to test.
The issue #5836 talks about Yenfry's answer in #4516, in which, functionally, his example answer with `getSignedCookies()` works, but reporting types error about `url` parameter missing.
This PR fixes the issue and also improving `getSignedUrl()` to have the `url` optionally inputted (when using with `policy`).
---

feat(cloudfront-signer): allow `url` to be optional when using `policy`

---

.github/workflows/pre-commit-hooks.yml

Internal JS-5114
enables pre-commit hooks to run in CI as well to duplicate validation, in case of a commit that bypasses the pre-commit-hooks locally.
new check created and can be confirmed in the checks column. 
pushed an empty commit to confirm the new check runs whenever a new commit is pushed, and it runs when a new PR is opened (both of these against the `main` branch only). 
---

feat(ci): add pre-commit hooks to run in CI to duplicate validation

---

scripts/npm-registry/mark-version-as-latest.mjs
scripts/utils/spawn-process.js

This script can be run to generate a set of commands to tag a version-group (a set of versions that were the "latest" together at some point in time) as the latest on NPM.
Example output:
```sh
node scripts/npm-registry/mark-version-as-latest.mjs
What is the version that should become [latest] (e.g. 3.512.0 no v-prefix)?
3.100.0
npm dist-tag add @aws-sdk/lib-dynamodb@3.100.0 latest
npm dist-tag add @aws-sdk/lib-storage@3.100.0 latest
npm dist-tag add @aws-sdk/body-checksum-browser@3.78.0 latest
npm dist-tag add @aws-sdk/body-checksum-node@3.78.0 latest
npm dist-tag add @aws-sdk/chunked-stream-reader-node@3.55.0 latest
npm dist-tag add @aws-sdk/cloudfront-signer@3.90.0 latest
npm dist-tag add @aws-sdk/credential-provider-cognito-identity@3.100.0 latest
npm dist-tag add …
```

chore(scripts): adds script to tag a target version-group as latest

---

UPGRADING.md
clients/client-sqs/src/SQSClient.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddSqsDependency.java
packages/middleware-sdk-sqs/src/configurations.ts
packages/middleware-sdk-sqs/src/middleware-sdk-sqs.integ.spec.ts
packages/middleware-sdk-sqs/src/receive-message.ts
packages/middleware-sdk-sqs/src/receive-messages.spec.ts
packages/middleware-sdk-sqs/src/send-message-batch.ts
packages/middleware-sdk-sqs/src/send-message.ts

n/a
This adds the option to set md5=false in SQS to shut off its MD5 message checksum customization.
This is applicable to FIPS where md5 algorithm is avoided.
```ts
import { SQS } from "@aws-sdk/client-sqs";
new SQS({
md5: false
});
```
new unit test

feat(client-sqs): add option to prevent md5 computation

---

packages/middleware-sdk-sqs/src/middleware-sdk-sqs.integ.spec.ts

the test behaves differently in CI/release due to default credentials

test(middleware-sdk-sqs): use mock credentials in integ test

---

packages/ec2-metadata-service/README.md

link to `fromInstanceMetadata()` in `ec2-metadata-service` package.
---

chore(ec2-metadata-service): readme update to link to fromInstanceMetadata()

---

lib/lib-dynamodb/src/index.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/5981
Re-export options and NativeAttribute* types
Verified that there are no type errors:
```ts
import { NativeAttributeValue } from "../aws-sdk-js-v3/lib/lib-dynamodb";
const key: Record<string, NativeAttributeValue> = {
null: null,
undefined: undefined,
boolean: true,
number: 1234,
string: "string",
NumberValue: {
value: "1234",
},
bigint: BigInt(1234),
NativeAttributeBinary: new ArrayBuffer(8),
list: [
null,
undefined,
true,
1234,
"string",
{ value: "1234" },
BigInt(1234),
new ArrayBuffer(8),
],
map: {
null: null,
undefined: undefined,
boolean: true,
number: 1234,
string: "string",
NumberValue: {
value: "1234",
},
bigint: BigInt(1234),
NativeAttributeBinary: new ArrayBuffer(8),
},
};
```
---
By submitting this pull request, I confirm …

chore(lib-dynamodb): re-export options and NativeAttribute* types

---

package.json
tests/canary/canary.js

- adds Verdaccio to the canary test. This runs an isolated workspace test against the packages published to Verdaccio.
- this test is added to the end of `yarn test:e2e` to be run in CI.

test: canary test using Verdaccio

---

packages/core/src/protocols/xml/parseXmlBody.spec.ts
packages/core/src/protocols/xml/parseXmlBody.ts

n/a
This turns on XML validation for deserialization by fast-xml-parser.
new unit tests

feat(core): validate XML during deserialization

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsRestXml.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonMemberSerVisitor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/RestJsonProtocolGenerator.java
private/aws-client-api-test/package.json
private/aws-echo-service/package.json
scripts/runtime-dependency-version-check/check-dependencies.js

add dependency checking to private folder, add dependency registration of aws-sdk/core at import sites in code generation.

fix(private): add dependency checking to private folder

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts

N/A.
Update Gradle build script dependencies
CI passes
smithy-lang/smithy-typescript#1241
---

chore(codegen): update Gradle build script dependencies

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-restjson-server/test/functional/restjson1.spec.ts

Test fixed upstream in https://github.com/smithy-lang/smithy/pull/2167
Enables protocol test RestJsonZeroAndFalseQueryValues:ServerRequest
CI
---

test(aws-restjson-server): confirm query values of 0 and false are serialized

---

packages/credential-provider-node/src/defaultProvider.ts

Internal JS-5156
Statically imports `@aws-sdk/credential-provider-node` so that no additional time is spent on Lambda for dynamically importing the provider during request time.
The unit tests and integration tests are successful.
We benchmarked `@aws-sdk/client-dynamodb@v3.556.0` (latest version at the time of PR) listTables operation for 100 counts before and after the change. In this sample benchmark, the request time at p50 is reduced by ~40ms or 4.3% with no change in init_duration.
```console
╔════════════════════════════════════════════╤════════════════════╤════════╤════════╤════════╗
║                                            │ metric             │ p50    │ p90    │ stdDev ║
╟────────────────────────────────────────────┼────────────────────┼────────┼────────┼────────╢
║ [node …
```

chore(credential-provider-node): statically import credential-provider-env

---

packages/core/src/client/emitWarningIfUnsupportedVersion.spec.ts
packages/core/src/client/emitWarningIfUnsupportedVersion.ts

Internal JS-5174
Support for Node.js 14.x ended in https://github.com/aws/aws-sdk-js-v3/pull/6034
Skip emitting warning for Node.js 14.x
Build `client-dynamodb` in aws-sdk-js-v3
```console
$ client-dynamodb> yarn build:include:deps
```
Prepare test file in test package
```
$> echo 'import { DynamoDB } from "../aws-sdk-js-v3/clients/client-dynamodb/dist-cjs/index.js"; const client = new DynamoDB();' > index.mjs
```
```console
$> node -v
v14.21.3
$> node index.mjs
(node:38205) Warning: NodeDeprecationWarning: The AWS SDK for JavaScript (v3) will
no longer support Node.js 14.x on May 1, 2024.
To continue receiving updates to AWS services, bug fixes, and security
updates please upgrade to an active Node.js LTS version.
More information can be found at: https://a.co/dzr2AJd
(Use `node …
```

chore(core): skip emitting warning for Node.js 14.x

---

UPGRADING.md

clarifies the point made in https://github.com/aws/aws-sdk-js-v3/issues/2082
2082
clarifies the name change from v2 `ManagedUpload` into v3's `lib-storage`.

docs: clarify lib-storage name change between v2 and v3

---

packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.e2e.spec.ts

Internal JS-5161
adds a waiter for the bucket to exist in s3 express e2e tests.
```js
PASS  packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.e2e.spec.ts (6.226 s)
s3 express CRUD test suite
✓ can create a bucket (2 ms)
✓ can read/write/delete from a bucket
✓ can presign get (92 ms)
○ skipped can presign put
Tests:       1 skipped, 3 passed, 4 total
Time:        6.294 s, estimated 7 s
Ran all test suites matching /middleware-s3-express.e2e.spec.ts/i.
```
---

test(middleware-sdk-s3): add waiter for s3 express e2e test

---

packages/credential-provider-node/src/credential-provider-node.integ.spec.ts
packages/middleware-eventstream/src/middleware-eventstream.integ.spec.ts
packages/middleware-sdk-sqs/src/middleware-sdk-sqs.integ.spec.ts
packages/middleware-sdk-transcribe-streaming/src/middleware-sdk-transcribe-streaming.integ.spec.ts
packages/middleware-websocket/src/middleware-websocket.integ.spec.ts

fixes type errors in integ tests, ported from https://github.com/aws/aws-sdk-js-v3/pull/6053

chore: fix type errors in integ tests

---

scripts/update-versions/getUpdatedPackageJson.mjs
scripts/update-versions/getUpdatedPackageJsonSection.mjs

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/6059
Uses pinned version for client peerDependencies in credential providers
```
$ yarn update:versions:current
$ git diff --stat | tail -n1
457 files changed, 5261 insertions(+), 5261 deletions(-)
```
Credential providers have exact dependencies
```console
$ grep -rnI -A 2 peerDependencies packages/credential-provider-ini/package.json
46:  "peerDependencies": {
47-    "@aws-sdk/client-sts": "3.568.0"
48-  },
$ grep -rnI -A 2 peerDependencies packages/credential-provider-web-identity/package.json 
48:  "peerDependencies": {
49-    "@aws-sdk/client-sts": "3.568.0"
50-  },
$ grep -rnI -A 2 peerDependencies packages/token-providers/package.json 
43:  "peerDependencies": {
44-    "@aws-sdk/client-sso-oidc": "3.568.0"
45-  },
```
Other …

fix(credential-providers): use pinned version for client peerDependencies

---

lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.spec.ts
packages/cloudfront-signer/src/sign.spec.ts
packages/core/src/client/emitWarningIfUnsupportedVersion.spec.ts
packages/core/src/protocols/xml/parseXmlBody.spec.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.spec.ts
packages/credential-provider-process/src/getValidatedProcessCredentials.spec.ts
packages/credential-provider-sso/src/validateSsoProfile.spec.ts
packages/endpoint-cache/src/EndpointCache.spec.ts
packages/middleware-endpoint-discovery/src/configurations.spec.ts
packages/middleware-flexible-checksums/src/getChecksumAlgorithmForRequest.spec.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.spec.ts
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-s3/src/check-content-length-header.spec.ts
packages/middleware-signing/src/awsAuthMiddleware.spec.ts
packages/middleware-token/src/resolveTokenConfig.spec.ts
packages/middleware-websocket/src/EventStreamPayloadHandler.spec.ts
packages/region-config-resolver/src/regionConfig/isFipsRegion.spec.ts
packages/region-config-resolver/src/regionConfig/resolveRegionConfig.spec.ts
packages/s3-request-presigner/src/getSignedUrl.spec.ts
packages/token-providers/src/fromSso.spec.ts
packages/token-providers/src/getNewSsoOidcToken.spec.ts
packages/token-providers/src/getSsoOidcClient.spec.ts
packages/util-dynamodb/src/convertToNative.spec.ts
packages/util-endpoints/src/lib/aws/partition.spec.ts
packages/xhr-http-handler/src/xhr-http-handler.spec.ts

Unblocks https://github.com/aws/aws-sdk-js-v3/pull/6038
Fixes type checks in unit tests
All tests except `@ts-expect-error` for ES2020 are successful in https://github.com/aws/aws-sdk-js-v3/pull/6052
The `@ts-expect-error` comments will be removed on bumping TSConfig
---

test: fix type checks in unit tests

---

jest.config.base.js
private/aws-restjson-server/jest.config.js
private/aws-restjson-validation-server/jest.config.js
scripts/generate-clients/copy-to-clients.js

Noticed while working on https://github.com/aws/aws-sdk-js-v3/pull/6038
Removes deprecated ts-jest globals config
ts-jest emits warning
```console
$ aws-restjson-server> yarn test
...
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
..
Done in 13.89s.
```
ts-jest does not emit warning
```console
$ aws-restjson-server> yarn test
...
Done in 14.20s.
```
---

test: remove deprecated ts-jest globals config

---

lib/lib-dynamodb/src/test/lib-dynamodb.e2e.spec.ts

Internal JS-5189
1. Defines `NestedList` and `NestedMap` types to describe structure of nested arrays and objects within test data, addressing TS2322 errors.
2. Adds an index signature to the `DataType` interface for addressing TS7053 errors that occurred when attempting to index objects without explicit index signatures.
3. Explicitly types the `passError` parameter as `any`, for TS7006 errors.
```
PASS  src/test/lib-dynamodb.e2e.spec.ts (31.098 s)
DynamoDBDocument
✓ initializes using the static constructor
✓ is using a random TableName=js-sdk-dynamodb-test-1715128811-le0x (1 ms)
✓ describes the test table
✓ creates the test table if it does not exist
.
.
.
✓ can serialize class instances as maps (1 ms)
updateTransformFunction
✓ modifies all fields of an object (3 ms)
Test Suites: 1 …
```

test(lib-dynamodb): enhance type safety

---

packages/ec2-metadata-service/src/MetadataService.e2e.spec.ts
packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.e2e.spec.ts
packages/s3-presigned-post/src/createPresignedPost.e2e.spec.ts

* Internal JS-5189
* E2E equivalent for https://github.com/aws/aws-sdk-js-v3/pull/6071
Fixes type checks in e2e tests
E2E tests are successful
```console
$ yarn test:e2e
...
Done in 196.95s.
```
---

test: fix type checks in e2e tests

---

packages/middleware-expect-continue/src/index.ts

this is incidentally noticed while testing https://github.com/smithy-lang/smithy-typescript/pull/1256
skip the expect header if the requestHandler is `fetch`, which doesn't like that header.
CI integration tests

chore(middleware-expect-continue): do not set expect header if using FetchHttpHandler

---

packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.e2e.spec.ts

Internal JS-5161
Deletes only the s3-express bucket created by the test
Run `middleware-s3-express.e2e.spec.ts` test 3 times in parallel.
The tests fail, as they try to delete buckets in use by other tests.
```console
$ yarn test:e2e src/s3-express/middleware-s3-express.e2e.spec.ts & yarn test:e2e src/s3-express/middleware-s3-express.e2e.spec.ts & yarn test:e2e src/s3-express/middleware-s3-express.e2e.spec.ts
...
● s3 express CRUD test suite › can presign put
OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
4754 |     default:
4755 |       const parsedBody = parsedOutput.body;
> 4756 |       return throwDefaultError({
|              ^
4757 |         output,
4758 |         parsedBody,
4759 |         errorCode
...
``` …

test(middleware-sdk-s3): only delete the s3-express bucket created by the test

---

package.json

Yarn classic has released newer versions post 1.22.17
```console
$ npm view yarn time --json | tail
"1.22.14": "2021-09-29T21:29:39.264Z",
"1.22.15": "2021-09-30T00:08:58.440Z",
"1.22.16": "2021-10-16T11:16:11.322Z",
"1.22.17": "2021-10-16T15:16:07.228Z",
"1.22.18": "2022-03-18T14:57:39.688Z",
"1.22.19": "2022-06-08T00:52:26.933Z",
"1.22.20": "2023-11-14T11:42:20.051Z",
"1.22.21": "2023-11-14T19:09:53.328Z",
"1.22.22": "2024-03-09T21:35:40.868Z"
}
```
Bump yarn to 1.22.22
CI
---

chore(deps-dev): bump yarn to 1.22.22

---

packages/ec2-metadata-service/src/MetadataService.e2e.spec.ts
packages/ec2-metadata-service/src/MetadataService.ts

#6042 
set the timeout for requests to ec2-mds.
E2E tests for the package pass. 
```console
PASS  src/MetadataService.e2e.spec.ts
MetadataService E2E Tests
✓ should fetch metadata token successfully (6 ms)
✓ should fetch metadata successfully with token (4 ms)
✓ should fetch metadata successfully (without token -- disableFetchToken set to true) (2 ms)
✓ should handle TimeoutError by falling back to IMDSv1 (3 ms)
✓ should handle specific error codes by falling back to IMDSv1 (6 ms)
✓ should timeout as expected when a request exceeds the specified duration (4 ms)
Tests:       6 passed, 6 total
Time:        3.358 s, estimated 4 s
Done in 4.34s.
```
---
By submitting this pull request, I confirm that you can use, modify, …

fix(ec2-metadata-service): set timeout for requests

---

scripts/update-versions/getUpdatedPackageJson.mjs
scripts/update-versions/getUpdatedPackageJsonSection.mjs

Reverts aws/aws-sdk-js-v3#6060 to fix https://github.com/aws/aws-sdk-js-v3/issues/6098

fix(credential-providers): use latest version for client peerDependencies

---

packages/types/src/logger.ts

This change is made to release new versions for fix in https://github.com/aws/aws-sdk-js-v3/pull/6060
changes Logger import to a type-only import
Verified that `yarn lerna:version` updates credential provider packages
```console
$ yarn lerna:version
...
- @aws-sdk/credential-provider-cognito-identity: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-env: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-http: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-ini: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-node: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-process: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-sso: 3.576.0 => 3.576.1
- @aws-sdk/credential-provider-web-identity: 3.576.0 => 3.576.1
...
- @aws-sdk/token-providers: 3.576.0 => 3.576.1
...
```
---
By submitting …

chore(types): change Logger import to type-only

---

lib/lib-storage/src/chunks/getChunkStream.ts
lib/lib-storage/src/chunks/getDataReadableStream.spec.ts

should a single chunk if the stream is equal to partsize
If a stream's size is equal to partsize, current implement will generate two chunk (or, upload part), rather than a single chunk.
But if a buffer's size is equal to partsize, it only generate a single chunk.
See test case `should a single chunk if the stream is equal to partsize`
None.
---

fix(upload): should a single chunk if the stream is equal to partsize

---

packages/middleware-sdk-api-gateway/src/index.spec.ts
packages/middleware-sdk-api-gateway/src/index.ts
packages/middleware-sdk-api-gateway/src/middleware-sdk-api-gateway.integ.spec.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/6090
Only set `accept: application/json` for APIG if no accept header was set.
unit, integ, and manual e2e testing
v2 behavior: https://github.com/aws/aws-sdk-js/blob/master/lib/services/apigateway.js
implemented incorrectly in v3: https://github.com/aws/aws-sdk-js-v3/pull/473

fix(middleware-sdk-api-gateway): only set default accept header if none provided

---

lib/lib-storage/README.md
lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts
lib/lib-storage/src/lib-storage.e2e.spec.ts

related to https://github.com/aws/aws-sdk-js-v3/pull/4414
This PR modifies the behavior of `@aws-sdk/lib-storage`'s `Upload` class' `leavePartsOnError: boolean` to do what it sounds like it does instead of something meaningless.
Previous to this PR:
- when true, any error encountered during MPU would be thrown
- when false, any error encountered during MPU would be ignored
- default was false
As of this PR:
- when true, AbortMultipartUpload is not called in the event of a failed MPU
- when false, AbortMultipartUpload is called in the event of a failed MPU to mark the parts for cleanup as recommended by S3
- default is still false
new e2e test
Portion of docs from AWS SDK JSv2:
```
* ## Handling Multipart Cleanup
*
* By default, this class will automatically clean up any multipart uploads …
```

fix(lib-storage): call AbortMultipartUpload when failing to CompleteMultipartUpload

---

codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

https://github.com/aws/aws-sdk-js-v3/pull/6124
no codegen diff

chore(codegen): bump smithy-typescript version to 0.21.0

---

codegen/build.gradle.kts

Add a missed bump for `codegen;/build.gradle.kts`.

chore(codegen): bump version to 0.21.0

---

packages/core/package.json
packages/core/scripts/lint.js

https://github.com/aws/aws-sdk-js-v3/issues/6144
Add a module field to conditional exports in core. This field is not defined by Node.js, but is a convention for bundlers.
esbuild, webpack, node mjs, node cjs manual resolution testing

fix(core): set module exports field for bundlers

---

codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Refs: https://github.com/smithy-lang/smithy-typescript/pull/1299
Bumps smithy-typescript version to 0.21.1
There's no codegen diff, since it was merged in https://github.com/aws/aws-sdk-js-v3/pull/6171
N/A
---

chore(codegen): bump smithy-typescript version to 0.21.1

---

private/aws-protocoltests-ec2/test/functional/ec2query.spec.ts
private/aws-protocoltests-json-10/test/functional/awsjson1_0.spec.ts
private/aws-protocoltests-json/test/functional/awsjson1_1.spec.ts
private/aws-protocoltests-query/test/functional/awsquery.spec.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts
private/aws-protocoltests-restxml/test/functional/restxml.spec.ts
scripts/generate-clients/config.js

Codegen for https://github.com/smithy-lang/smithy-typescript/pull/1300
Validates resolvedHost from httpRequestTests in protocoltests
CI
---

test(protocoltests): validate resolvedHost from httpRequestTests

---

packages/credential-provider-http/src/fromHttp/requestHelpers.ts

Internal JS-5233
Removes warning when response content-type is not application/json
CI
---

chore(credential-provider-http): remove warning when response content-type is not application/json

---

packages/util-dynamodb/src/marshall.spec.ts
packages/util-dynamodb/src/marshall.ts
packages/util-dynamodb/src/models.ts

fixes https://github.com/aws/aws-sdk-js-v3/issues/4828
this re-attempts https://github.com/aws/aws-sdk-js-v3/pull/4829 (reverted)
reported issue causing the revert https://github.com/aws/aws-sdk-js-v3/issues/4901. I don't think this was valid in retrospect, we reverted hastily.
Fix overload signature resolution for `marshall()`, with tests this time.
type-checked unit tests

fix(util-dynamodb): fix signature overload resolution for marshall() fn

---

lib/lib-storage/src/Upload.ts

#4767 
The `UploadPartCommand` is passed the original parameters, which may include `ContentLength`. If the `ContentLength` is included in the original parameters, and the upload is larger than a single chunk, `UploadPartCommand` has an incorrect value for `ContentLength`. This change passes the actual size of the chunk as `ContentLength`, or makes sure it is undefined if the part size is not calculated.
After upgrading from SDK v2 to v3, our uploads were hanging and eventually timing out. Making this change in our local copy of the SDK fixed the uploads.
---

Specify ContentLength for part uploads

---

scripts/runtime-dependency-version-check/runtime-dep-version-check.js

This script often throws a `Error: Cannot find module` for `package.json` of recently removed clients. This change makes the script continue if the `package.json` doesn't exist instead of throwing, which was interrupting pre-commit hooks and CI at the least. 
We were doing a `git clean` to resolve this, but sometimes that's not desirable. 
---

chore(scripts): ignore directories with no package jsons

---

packages/credential-provider-node/README.md

The README of `credential-provider-node` currently refers to `fromEnv` (which does not exist in the package). This change fixes README to instead refer to `defaultProvider`.
N/A
Since the initial introduction of `packages/credential-provider-node/README.md` in https://github.com/aws/aws-sdk-js-v3/commit/012558d471faf3ef80dd83628f81ba065c286e8a, the README referred to `fromEnv`, which did not exist then, nor does it exist now.
Later sections of README refer to the same factory function as `defaultProvider`:
https://github.com/aws/aws-sdk-js-v3/blob/65eb2e631383a82deb009bcb0983ae114c0c7b26/packages/credential-provider-node/README.md?plain=1#L65-L67
This change fixes the inconsistency.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

chore(credential-provider-node): fix readme typo

---

packages/s3-request-presigner/README.md

Update documentation providing an example on using `getSignedUrl` method with and without signed headers.
N/A - docs
While working on setting up presigned urls with signed headers I noticed there was a lack of documentation regarding how to handle `x-amz-*` headers you wish to have signed. I hope this PR allows for others to find the solution quicker.
---

docs(s3-request-presigner): add in getSignedUrl example with and without signed headers

---

README.md

Internal JS-5255
Add CloudFront-KeyValueStore to the list of functionalities that require explicit sigv4a dependency/import.
---

docs: add CloudFront KeyValueStore in sigv4a dependency list

---

UPGRADING.md

N/A
Provides correct link to middleware stack blog post in UPGRADING.md
It's mistakenly linking to First-class TypeScript support blog post.
N/A
---

docs: fix link to middleware stack blog post

---

UPGRADING.md

N/A
The link to the docs was outdated and resulted in a 404 error. This PR updates the link to the correct and current URL.
Manually checked the new link to ensure it correctly directs to the intended documentation page.
For reference, see the similar PR: [docs: update retry link](https://github.com/aws/aws-sdk-js-v3/pull/5178)
---

docs: update NodeHttpHandler link

---

UPGRADING.md

N/A
The link to the docs was outdated and resulted in a 404 error. This PR updates the link to the correct and current URL.
Manually checked the new link to ensure it correctly directs to the intended documentation page.
For reference, see the similar PR: [docs: update retry link](https://github.com/aws/aws-sdk-js-v3/pull/5178)
---

docs: update FetchHttpHandler link

---

packages/core/src/submodules/client/emitWarningIfUnsupportedVersion.spec.ts
packages/core/src/submodules/client/emitWarningIfUnsupportedVersion.ts

Internal JS-5203
Emits warning for Node.js versions < 18.x
CI
---

chore(core): emit warning for Node.js versions < 18.x

---

Makefile

adds a phony target to rimraf nested node_modules folders
Note: not used in CI, this is for local development cleanup

chore: add clean-nested make target

---

packages/credential-provider-http/src/fromHttp/fromHttp.spec.ts
packages/credential-provider-http/src/fromHttp/requestHelpers.spec.ts
packages/middleware-eventstream/src/eventStreamHeaderMiddleware.ts
packages/middleware-eventstream/src/middleware-eventstream.integ.spec.ts
packages/middleware-sdk-transcribe-streaming/src/middleware-sdk-transcribe-streaming.integ.spec.ts
packages/middleware-websocket/src/middleware-websocket-endpoint.spec.ts
packages/middleware-websocket/src/middleware-websocket-endpoint.ts
packages/middleware-websocket/src/middleware-websocket.integ.spec.ts
packages/s3-request-presigner/src/presigner.spec.ts

n/a
improve header casing consistency
CI

fix(middleware-eventstream): lowercase headers more consistently

---

packages/util-dynamodb/src/models.ts

https://github.com/aws/aws-sdk-js-v3/issues/6253
This filters out any global interfaces with no definite properties to prevent incorrect signature matching too broadly for the marshall function.
tested in TypeScript https://www.typescriptlang.org/play/?#code/C4TwDgpgBAglC8UDeUCGAuKBXAdgEwgDMBLHCPKAXwG4AoUSKAIQWTQH5NcCSyKba9cNACyqEACMIAHgAqAPlZJKUCAA9gEfAGcosqOyhkAbhABOUTLLpDGADVZjJMpvOpA

fix(util-dynamodb): perform global interface check in NativeAttributeBinary union

---

clients/client-s3/test/unit/dotSegmentInUriLabel.spec.ts

Internal JS-5057
Adds unit tests for dog segment in URI label
CI
---

test(client-s3): dot segment in URI Label

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts

If S3 endpoint contained an explicit port (for example `http://localstack:4566/`), then the `Location` property of the `Upload` command didn't include it.
In AWS-SDK V2 `upload` command did include the port in the Location URL.
Relevant tests are added (and were failing before the fix).
---

fix(lib-storage): location in upload result must include custom port

---

packages/credential-provider-node/src/credential-provider-node.integ.spec.ts
packages/credential-provider-node/src/defaultProvider.spec.ts
packages/credential-provider-node/src/defaultProvider.ts

https://github.com/aws/aws-sdk-js-v3/issues/2549
Emit a warning when the environment sets AWS_PROFILE in addition to the pair AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY.
We should be resolving the credential pair based on AWS SDK JSv2, AWS CLI, and documentation, but the current implementation prefers AWS_PROFILE.
Because this has been released for a very long time, we should set a warning instead of directly switching over to preferring the credential pair. 
We could determine a specific date later on which to change the behavior over to preferring the credential pair.
manual, integ, unit

chore(credential-provider-node): emit warning when AWS_PROFILE is set alongside ENV credentials

---

packages/credential-provider-node/src/defaultProvider.spec.ts
packages/credential-provider-node/src/defaultProvider.ts

- uses more consistent (with prior functionality) control flow Exception to skip `fromEnv` in default credential provider chain instead of relying on the provider itself failing

test(credential-provider-node): fix tests related to defaultProvider chain

---

verdaccio/config.yaml

Fixes typos in the comments in `verdaccio/config.yaml` file.

docs: fix typos

---

packages/credential-providers/src/fromNodeProviderChain.ts

Update fromNodeProviderChain.ts docblock

---

packages/middleware-sdk-s3/package.json

set consistent dependency version for codegen issue

fix(middleware-sdk-s3): set consistent dependency versions

---

packages/middleware-sdk-s3/src/throw-200-exceptions.ts

https://github.com/aws/aws-sdk-js-v3/issues/6293
In case of a long response, from e.g. ListObjects with many objects, a Node.js stream may be partially read, and the Node.js runtime will error out with code 13, awaiting an async operation that will never resolve.
Tested manually in Node.js and browser.

fix(middleware-sdk-s3): fix error with partially-read Node.js streams

---

packages/credential-providers/jest.config.integ.js
packages/credential-providers/package.json
packages/credential-providers/src/fromSSO.integ.spec.ts

#5876
This PR adds an integration test for this change: https://github.com/smithy-lang/smithy-typescript/pull/1315
`yarn test:integration`
---

test(credential-providers): integration test for 'read config files from paths relative to homedir'

---

clients/client-sts/src/defaultStsRoleAssumers.ts
clients/client-sts/test/defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts
packages/credential-provider-env/src/fromEnv.spec.ts
packages/credential-provider-env/src/fromEnv.ts
packages/credential-provider-ini/src/resolveStaticCredentials.spec.ts
packages/credential-provider-ini/src/resolveStaticCredentials.ts
packages/credential-provider-process/src/ProcessCredentials.ts
packages/credential-provider-process/src/getValidatedProcessCredentials.spec.ts
packages/credential-provider-process/src/getValidatedProcessCredentials.ts
packages/credential-provider-process/src/resolveProcessCredentials.spec.ts
packages/credential-provider-process/src/resolveProcessCredentials.ts
packages/credential-provider-sso/src/resolveSSOCredentials.spec.ts
packages/credential-provider-sso/src/resolveSSOCredentials.ts

Internal JS-4633
Part 1 
Sources accountId from credential providers. 
```console
PASS  test/defaultRoleAssumers.spec.ts
getDefaultRoleAssumer
✓ should use supplied source credentials (59 ms)
✓ should return accountId in the credentials (7 ms)
✓ should use the STS client config (64 ms)
✓ should use the parent client config (13 ms)
✓ should use the STS client middleware (5 ms)
getDefaultRoleAssumerWithWebIdentity
✓ should use the STS client config (18 ms)
✓ should return accountId in the credentials (4 ms)
✓ should use the STS client middleware (6 ms)
Tests:       8 passed, 8 total
Time:        2.76 s, estimated 4 s
Done in 3.48s.
```
```console
PASS  src/isSsoProfile.spec.ts (5.651 s)
PASS …
```

feat(credential-providers): source accountId from credential providers

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmittedEndpointParams.java

Internal JS-4633
Part 2
Adds endpoint param names to be omitted from generation in the client interface.
Partner PR in smithy-typescript: https://github.com/smithy-lang/smithy-typescript/pull/1251
---

feat(codegen): specify endpoint param names to be omitted from generation in the client interface

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmittedEndpointParams.java
packages/core/package.json

corrects lex order for codegen imports for `AddOmittedEndpointParams` and updates dep versions (from our runtime dep check script)
CI
---

chore(codegen): correct lex order in omit param codegen

---

README.md

Refs: https://github.com/aws/aws-sdk-js-v3/issues/6269#issuecomment-2246449103
Mentions addition of web-streams-polyfill for react-native
Verified in tests repo https://github.com/aws-samples/aws-sdk-js-tests/pull/197
The absence of ReadableStream in react-native environment is extensively discussed. Using a polyfill is top solution
* https://stackoverflow.com/a/77744609
* https://github.com/ipfs/helia-verified-fetch/issues/7#issuecomment-1974946092
* https://github.com/facebook/hermes/discussions/1072#discussioncomment-8428209
---

docs: mention addition of web-streams-polyfill for react-native

---

packages/eventstream-handler-node/src/EventStreamPayloadHandler.spec.ts
packages/eventstream-handler-node/src/EventStreamPayloadHandler.ts
packages/middleware-eventstream/src/middleware-eventstream.integ.spec.ts
packages/middleware-websocket/src/middleware-websocket.integ.spec.ts

internal V1360694816
This sets the event stream payload handler to begin streaming the input payload without waiting for any server response. QBusiness does not send any initial response ack, whereas TranscribeStreaming does. However, since we don't need to handle this ack in any way, we can start the stream regardless in both cases. 
```ts
import { ChatCommand, QBusinessClient } from "@aws-sdk/client-qbusiness";
const client = new QBusinessClient;
const command = new ChatCommand({
applicationId: "49.....-....-....-....-.....c9",
inputStream: (async function* () {
yield { textEvent: { userMessage: "say hi" } };
yield { endOfInputEvent: {} };
})(),
});
const response = await client.send(command);
for await (const event of response.outputStream!) { …
```

fix(eventstream-handler-node): start streaming without waiting for response

---

clients/client-sts/src/defaultStsRoleAssumers.ts
clients/client-sts/test/defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts
packages/credential-provider-env/src/fromEnv.spec.ts
packages/credential-provider-env/src/fromEnv.ts
packages/credential-provider-ini/src/resolveStaticCredentials.spec.ts
packages/credential-provider-ini/src/resolveStaticCredentials.ts
packages/credential-provider-process/src/ProcessCredentials.ts
packages/credential-provider-process/src/getValidatedProcessCredentials.spec.ts
packages/credential-provider-process/src/getValidatedProcessCredentials.ts
packages/credential-provider-process/src/resolveProcessCredentials.spec.ts
packages/credential-provider-process/src/resolveProcessCredentials.ts
packages/credential-provider-sso/src/resolveSSOCredentials.spec.ts
packages/credential-provider-sso/src/resolveSSOCredentials.ts

this reverts aws/aws-sdk-js-v3#6308, which had to be reverted to allow for the codegen sync to take place first. 
this PR will release accountId-endpoints changes from PR: 
- https://github.com/aws/aws-sdk-js-v3/pull/6019

chore: release accountId-endpoints credential-provider changes

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAccountIdEndpointModeRuntimeConfig.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmittedEndpointParams.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
packages/core/account-id-endpoint.js
packages/core/package.json
packages/core/src/submodules/account-id-endpoint/AccountIdEndpointModeConfigResolver.ts
packages/core/src/submodules/account-id-endpoint/AccountIdEndpointModeConstants.spec.ts
packages/core/src/submodules/account-id-endpoint/AccountIdEndpointModeConstants.ts
packages/core/src/submodules/account-id-endpoint/NodeAccountIdEndpointModeConfigOptions.spec.ts
packages/core/src/submodules/account-id-endpoint/NodeAccountIdEndpointModeConfigOptions.ts
packages/core/src/submodules/account-id-endpoint/README.md
packages/core/src/submodules/account-id-endpoint/index.ts
packages/core/tsconfig.cjs.json
packages/core/tsconfig.es.json
packages/core/tsconfig.types.json

this reverts aws/aws-sdk-js-v3#6309, which had to be reverted to allow for the codegen sync to take place first.
this PR will release accountId-endpoints changes from PRs:
- https://github.com/aws/aws-sdk-js-v3/pull/6035
- https://github.com/aws/aws-sdk-js-v3/pull/6036

chore: release accountId-endpoints config and codegen changes

---

packages/core/package.json
private/aws-protocoltests-restxml/package.json
scripts/generate-clients/config.js
yarn.lock

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/6327
Bumps fast-xml-parser from 4.2.5 to 4.4.1
CI
---

chore(deps): bump fast-xml-parser from 4.2.5 to 4.4.1

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java

We've been using `fast-xml-parser` from `@aws-sdk/core` since v3.529.1 https://github.com/aws/aws-sdk-js-v3/pull/5869
Removes fast-xml-parser from AwsDependency
Verified that there are no consumers of `AwsDependency.XML_PARSER` in codegen
---

chore(codegen): remove fast-xml-parser from AwsDependency

---

packages/polly-request-presigner/src/getSignedUrls.spec.ts
packages/polly-request-presigner/src/getSignedUrls.ts

Adds a middleware override in the `getSignedUrl` function to prevent multiple instances of the same middleware from being added during concurrent calls. The accompanying test checks that concurrent calls to `getSignedUrl` do not add the middleware multiple times and complete without error.
Fixes 
https://github.com/aws/aws-sdk-js-v3/issues/2417
Reference: 
https://github.com/aws/aws-sdk-js-v3/pull/1884
https://github.com/aws/aws-sdk-js-v3/pull/2628

fix(polly-request-presigner): override middleware name to allow concurrent presigning

---

packages/cloudfront-signer/package.json
packages/core/package.json
packages/credential-provider-sso/package.json
packages/credential-provider-web-identity/package.json
packages/signature-v4-crt/package.json

So with the `fast-xml-parser` vulnerability I was trying to trace down if updating would help, and I started at the npm package page for [@aws-sdk/core](https://www.npmjs.com/package/@aws-sdk/core). The `homepage` link was out of date and led to a 404.
I looked at the `package.json` files in `clients/*` and `packages/*` looking for `homepage` values not using the `main` branch, and corrected them to `main`.
No code testing, a documentation change.
---

fix: package.json `homepage` links to use the `main` branch

---

package.json
turbo.json
yarn.lock

Updates the Turbo devDependency to the latest version. 
Local Build
---

chore(turbo): update Turborepo devDependency to 2.0.9

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientPaginationGenerator.java
lib/lib-dynamodb/src/pagination/QueryPaginator.ts
lib/lib-dynamodb/src/pagination/ScanPaginator.ts

Use pagination factory function (`createPaginator`) from `@smithy/core`
`yarn test` in `lib/lib-dynamodb` - all tests pass
`yarn test:e2e` in `lib/lib-dynamodb` - all tests pass
Used https://github.com/aws/aws-sdk-js-v3/pull/5590 for reference
---

chore(lib-dynamodb): use pagination factory from core

---

clients/client-transcribe-streaming/src/TranscribeStreamingClient.ts
clients/client-transcribe-streaming/src/commands/StartCallAnalyticsStreamTranscriptionCommand.ts
clients/client-transcribe-streaming/src/commands/StartMedicalStreamTranscriptionCommand.ts
clients/client-transcribe-streaming/src/commands/StartStreamTranscriptionCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTranscribeStreamingDependency.java

Internal JS-5337
Adds plugin only for operations with streaming trait
Internal
---

fix(client-transcribe-streaming): add plugin only for operations with streaming trait

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddEventStreamHandlingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddTranscribeStreamingDependency.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddWebsocketPlugin.java

Refs: https://github.com/aws/aws-sdk-js-v3/pull/6349#discussion_r1701930295
Makes hasEventStreamInput utilities public in AddEventStreamHandlingDependency, so that they can be used from dependent plugins
Verified that TranscribeStreaming and RekognitionStreaming client codegen succeeds, and there are no changes.
---

chore(codegen): make hasEventStreamInput utilities public

---

packages/karma-credential-loader/src/index.ts

Internal JS-5339
This appears to write some code with 
```js 
var credentials = `${JSON.stringify(credentials)}`
```
however this would not serialize a Date object correctly.
`b s3 - browser` (runs S3 client e2e browser tests)

test(karma-credential-loader): set credential expiration as date

---

clients/client-lex-runtime-service/package.json
clients/client-lex-runtime-v2/package.json
clients/client-location/package.json
clients/client-sts/package.json

Internal JS-5336
Update fast-xml-parser to `4.4.1` to release:
* `@aws-sdk/client-sts@3.186.4`
* `@aws-sdk/client-location@3.186.4`
* `@aws-sdk/client-lex-runtime-service@3.186.4`
* `@aws-sdk/client-lex-runtime-v2@3.186.4`
```console
...........
Done in 0.97s.
```
* [aws-sdk-client-lex-runtime-service-3.186.4.tgz](https://github.com/user-attachments/files/16501389/aws-sdk-client-lex-runtime-service-3.186.4.tgz)
* [aws-sdk-client-lex-runtime-v2-3.186.4.tgz](https://github.com/user-attachments/files/16501391/aws-sdk-client-lex-runtime-v2-3. …

chore: update fast-xml-parser for 3.186.4 release

---

package.json
scripts/turbo/index.js

Previously, Turborepo build errors due to package filtering or other optional arguments would result in a CI build failure. This code change adds a fallback for these errors, rebuilding the package without any optional arguments. It also removes unnecessary filtering from the build:ci script in package.json. 
---

fix(turbo): improve error handling in build script & remove unnecessary filtering from build:ci

---

scripts/validation/deprecated-packages.js

script which prints out the dependency graph of packages
current output of packages and their dependents:
```
@aws-sdk/cloudfront-signer: ---- NONE ----
@aws-sdk/ec2-metadata-service: ---- NONE ----
@aws-sdk/karma-credential-loader: -- devtool --
@aws-sdk/middleware-api-key: ---- NONE ----
@aws-sdk/middleware-sdk-sts: ---- NONE ----
@aws-sdk/middleware-token: ---- NONE ----
@aws-sdk/polly-request-presigner: ---- NONE ----
@aws-sdk/rds-signer: ---- NONE ----
@aws-sdk/s3-presigned-post: ---- NONE ----
@aws-sdk/s3-request-presigner: ---- NONE ----
@aws-sdk/smithy-client: ---- NONE ----
@aws-sdk/util-create-request: ---- NONE ----
@aws-sdk/util-dns: ---- NONE ----
@aws-sdk/util-locate-window: ---- NONE ----
@aws-sdk/xhr-http-handler: ---- NONE ----
@aws-sdk/lib-dynamodb: ---- NONE ---- …
```

chore(scripts): discover unused packages

---

clients/client-s3/src/models/models_0.ts
clients/client-s3/src/models/models_1.ts
codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

- Bumps codegen versions to `0.22.0`
- Changelog entry needs to be added
- Will generate clients and test before merging
---

Bump codegen version to 0.22.0

---

tests/endpoints-2.0/endpoints-integration.spec.ts

Internal JS-5234
Fixes TypeScript errors in endpoints-integration.spec.ts
```console
$ yarn jest -c tests/endpoints-2.0/jest.config.js tests/endpoints-2.0/endpoints-integration.spec.ts
yarn run v1.22.22
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/jest -c tests/endpoints-2.0/jest.config.js tests/endpoints-2.0/endpoints-integration.spec.ts
FAIL  tests/endpoints-2.0/endpoints-integration.spec.ts
● Test suite failed to run
tests/endpoints-2.0/endpoints-integration.spec.ts:22:7 - error TS7034: Variable 'defaultEndpointResolver' implicitly has type 'any' in some locations where its type cannot be determined.
22   let defaultEndpointResolver;
~~~~~~~~~~~~~~~~~~~~~~~
tests/endpoints-2.0/endpoints-integration.spec.ts:23:7 - error TS7034: Variable 'namespace' implicitly has type …
```

test: fix TypeScript errors in endpoints-integration.spec.ts

---

clients/client-cloudfront-keyvaluestore/src/auth/httpAuthSchemeProvider.ts
clients/client-cloudfront-keyvaluestore/src/runtimeConfig.ts
clients/client-eventbridge/src/auth/httpAuthSchemeProvider.ts
clients/client-eventbridge/src/runtimeConfig.ts
clients/client-s3/src/auth/httpAuthSchemeProvider.ts
clients/client-s3/src/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsTraitsUtils.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AwsSdkCustomizeSigV4Auth.java
packages/core/package.json
packages/core/src/submodules/httpAuthSchemes/aws_sdk/AwsSdkSigV4ASigner.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/AwsSdkSigV4Signer.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/index.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4AConfig.ts
private/aws-client-api-test/src/client-interface-tests/client-s3/impl/initializeWithMaximalConfiguration.ts

JS-4976
This adds a config resolver for sigv4a and its config field "sigv4aSigningRegionSet" which is an optional list of AWS regions.
usage:
```js
const s3 = new S3({
region: "us-west-2",
sigv4aSigningRegionSet: ["us-west-2", "us-east-1"],
});
```
This is quite optional at this point, because endpoint resolution for Amazon S3 always returns a signingRegionSet of `*` if resolving the auth scheme to sigv4a. This will support future developments in multi-auth and expanded usage of sigv4a.

feat(core/httpAuthSchemes): set configuration sources for sigv4a signingRegionSet

---

packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4AConfig.spec.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4AConfig.ts

n/a
the normalized provider for the config value `sigv4aSigningRegionSet` should return `undefined` by default instead of an empty array.
added unit test

fix(core/httpAuthSchemes): default sigv4aSigningRegionSet to undefined

---

clients/client-s3-control/src/commands/DeleteAccessPointCommand.ts
clients/client-s3-control/src/commands/DeleteAccessPointPolicyCommand.ts
clients/client-s3-control/src/commands/GetAccessPointCommand.ts
clients/client-s3-control/src/commands/GetAccessPointPolicyCommand.ts
clients/client-s3-control/src/commands/GetAccessPointPolicyStatusCommand.ts
clients/client-s3-control/src/commands/PutAccessPointPolicyCommand.ts
scripts/generate-clients/config.js

Codegen for https://github.com/smithy-lang/smithy-typescript/pull/1365
Populates memberName as contextParams value
* The `generate-clients` was run on all clients, and confirmed that only S3Control was impacted.
* Endpoint tests are successful https://github.com/aws/aws-sdk-js-v3/pull/6373#issuecomment-2284447381
---

fix(client-s3-control): populate memberName as contextParams value

---

tests/endpoints-2.0/endpoints-integration.spec.ts
tests/endpoints-2.0/integration-test-types.ts

Internal JS-5234
Simplifies endpoint integration tests as follows:
* removes unused variables/functions
* use describe.each
* pass namespace when running tests
* run tests which were skipped in the past
```console
$ yarn jest -c tests/endpoints-2.0/jest.config.js tests/endpoints-2.0/endpoints-integration.spec.ts
...
Tests:       124 skipped, 14548 passed, 14672 total
```
```console
$ yarn jest -c tests/endpoints-2.0/jest.config.js tests/endpoints-2.0/endpoints-integration.spec.ts
...
Tests:       14672 passed, 14672 total
```
---

test: simplify endpoint integration tests

---

packages/credential-providers/README.md

https://github.com/aws/aws-sdk-js-v3/issues/6272
Add more information about credential functions and chaining.
n/a

docs(credential-providers): add longer explanation about credential function and chaining

---

packages/util-endpoints/src/lib/aws/parseArn.spec.ts
packages/util-endpoints/src/lib/aws/parseArn.ts
tests/endpoints-2.0/endpoints-integration.spec.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/6379#issuecomment-2284943667
Check for entire resource-path being empty when parsing Arn
Unit and Endpoint tests are successful
```console
$ yarn jest -c tests/endpoints-2.0/jest.config.js tests/endpoints-2.0/endpoints-integration.spec.ts
...
Tests:       14672 passed, 14672 total
```
---

fix(util-endpoints): check for entire resource-path being empty

---

lib/lib-dynamodb/package.json

Changes in https://github.com/aws/aws-sdk-js-v3/commit/922292b66614ea3a08779053ae8740dc28509d83 introduced a new direct dependency on `@smithy/core`. It was forgotten to be added to `package.json`.
This becomes an issue in environments where production dependencies only are distributed.
---

Fix missing `@smithy/core` dependency in `@aws-sdk/lib-dynamodb`

---

clients/client-sts/src/defaultStsRoleAssumers.ts
clients/client-sts/test/defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts

https://github.com/aws/aws-sdk-js-v3/issues/5958
Avoid sharing the parent client requestHandler to the inner STS client if that handler is an HTTP2 handler.
All other types of known handlers: fetch, http1.1, websocket (because it defers to fetch for non-ws), xhr, are valid for STS.
Made a TranscribeStreaming (HTTP2 default requesthandler) request and used the default provider chain such that it involved an STS credentials request. 
Verified this PR makes the difference in that not working -> working.
Sample code:
```js
import { TranscribeStreaming } from "@aws-sdk/client-transcribe-streaming";
import { fromIni } from "@aws-sdk/credential-providers";
import { createReadStream } from "node:fs";
import { join } from "node:path";
const audio = createReadStream(join("numbers.wav")); …
```

fix(credential-providers): avoid sharing http2 requestHandler with inner STS

---

packages/util-endpoints/src/lib/aws/parseArn.spec.ts
packages/util-endpoints/src/lib/aws/parseArn.ts

* Refs: https://github.com/aws/aws-sdk-js-v3/pull/6380#discussion_r1714509368
* Confirmed internally that the resourceId for path `my:folder/my:file` should be `["my", "folder", "my", "file"]`
Handles case in parseArn when resourcePath contains both delimiters
Unit tests
---

fix(util-endpoints): parseArn when resourcePath contains both delimiters

---

packages/middleware-sdk-s3/src/throw-200-exceptions.ts

https://github.com/aws/aws-sdk-js-v3/issues/6324
Placeholder fix for the linked issue to avoid the error. 
Further changes or guidance needed to implement stream splitting of the `fetch` response body in React-Native.

fix(middleware-sdk-s3): skip stream inspection if non-stream-like body

---

UPGRADING.md

https://github.com/aws/aws-sdk-js-v3/issues/6396
Fixes broken link to RetryInputConfig from smithy/middleware-retry in [Notable Changes](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/).
---

docs: link to smithy/middleware-retry in Notable Changes

---

README.md

I was reading the readme, and noticed that there was a reference to pagination in the abortcontroller section.
It looks like it was just a copy and paste error, as the actual blog post for abortcontroller is linked below the next paragraph.
This PR removes the offending/confusing line.

remove stray copy and paste line

---

.github/workflows/codegen-ci.yml

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
Runs codegen-ci only if the files in codegen folder has changes
Verified that codegen-ci was not run for this PR
---

chore(ci): run codegen-ci only if the codegen folder has changes

---

scripts/generate-clients/config.js

JS-5396
Updates smithy commit to include codegen for string array and operation context params.
N/A, since there's no feature which uses these params yet.
---

chore(codegen): string array and operation context params

---

codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPluginTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfigTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPluginsTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddUserAgentDependencyTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegrationTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegrationTest.java

Equivalent of https://github.com/smithy-lang/smithy-typescript/pull/1387
Uses TypeScriptClientCodegenPlugin in codegen tests
CI
---

test(codegen): use TypeScriptClientCodegenPlugin

---

.github/workflows/codegen-ci.yml
.github/workflows/commit-message-lint.yml
.github/workflows/pre-commit-hooks.yml

* GitHub Blog https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md#v400
Updates actions/checkout to v4 as Node16 is deprecated
CI
---

chore(ci): update actions/checkout to v4

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AwsSdkCustomizeSigV4Auth.java
private/aws-util-test/src/clients/Weather.integ.spec.ts
private/weather/package.json
private/weather/src/runtimeConfig.browser.ts
private/weather/src/runtimeConfig.ts

internal
For the scenario of a non-AWS service with the sigv4 trait, this PR modifies the ID&Auth SRA codegen behavior to provide the AWS SDK default credential chain as the default credentials object, for consistency with the legacyAuth behavior.
This was not present in the SRA implementation, presumably because of the desired separation between AWS and white label clients.
This only applies to codegen that uses both smithy-typescript and smithy-typescript-aws. If you only use smithy-typescript, it isn't currently aware of sigv4 at all. Sigv4 handling may need to be moved into smithy-typescript, but is out of scope of this PR.
new integ test

fix(codegen): use AWS SDK default credentials as sigv4 default credentials

---

.github/workflows/codegen-ci.yml

Required for using Node.js 20.x in CI
* GitHub Blog https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
* Changelog for actions/setup-java@v4 https://github.com/actions/setup-java/releases/tag/v4.0.0
Update actions/setup-java to v4 as node 16 is deprecated
CI
---

chore(ci): update actions/setup-java to v4

---

packages/middleware-sdk-s3/src/s3-type-transforms.integ.spec.ts

https://github.com/aws/aws-sdk-js-v3/issues/4720
Adds an integration test for the combination of S3 and `@smithy/types` Client type transforms.

test(middleware-sdk-s3): add type transform integration test

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentBareBonesClientGenerator.java
lib/lib-dynamodb/src/DynamoDBDocumentClient.ts

This was missed in https://github.com/aws/aws-sdk-js-v3/pull/6449 as the codegen-ci was not run, likely to some issue with one of the paths configs https://github.com/aws/aws-sdk-js-v3/pull/6439
Fix the checkstyle issue to unblock https://github.com/aws/aws-sdk-js-v3/pull/6453
The investigation for why codegen-ci was not run will be done as a follow-up.
CI
---

fix(codegen): checkstyle issue in DocumentBareBonesClientGenerator

---

packages/middleware-flexible-checksums/package.json
packages/middleware-flexible-checksums/src/NODE_REQUEST_CHECKSUM_CALCULATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/NODE_RESPONSE_CHECKSUM_VALIDATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/constants.ts
packages/middleware-flexible-checksums/src/index.ts
packages/middleware-flexible-checksums/src/stringUnionSelector.spec.ts
packages/middleware-flexible-checksums/src/stringUnionSelector.ts

Internal JS-5396
Adds constants RequestChecksumCalculation and ResponseChecksumValidation.
They'll be set in clients in the following PR.
N/A
---

chore(middleware-flexible-checksums): add RequestChecksumCalculation and ResponseChecksumValidation

---

packages/core/package.json

This will force a version update to fix https://github.com/aws/aws-sdk-js-v3/issues/6464
Update description to force version update
Verified that the duplicate files are not there in `@aws-sdk/core`
```console
$ git clean -dfx && yarn && yarn build:all
$ ls -1a packages/core/dist-es/submodules/httpAuthSchemes/aws_sdk
.
..
AwsSdkSigV4ASigner.js
AwsSdkSigV4Signer.js
index.js
resolveAwsSdkSigV4AConfig.js
resolveAwsSdkSigV4Config.js
```
---

chore(core): change description to force version update

---

packages/middleware-flexible-checksums/package.json
packages/middleware-flexible-checksums/src/NODE_REQUEST_CHECKSUM_CALCULATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/NODE_RESPONSE_CHECKSUM_VALIDATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/constants.ts
packages/middleware-flexible-checksums/src/index.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.spec.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.ts

Internal JS-5396
Add resolver for flexible checksums.
This PR also moves default values for configurations to constants.
CI
---

chore(middleware-flexible-checksums): add config resolver

---

clients/client-s3/src/S3Client.ts
clients/client-s3/src/runtimeConfig.browser.ts
clients/client-s3/src/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java
private/aws-client-api-test/package.json
private/aws-client-api-test/src/client-interface-tests/client-s3/impl/initializeWithMaximalConfiguration.ts

Internal Internal JS-5396
Populates and resolves flexible checksums client config:
* requestChecksumCalculation
* responseChecksumValidation
CI
---

chore(clients): populate and resolve flexible checksums client config

---

packages/credential-provider-ini/src/resolveAssumeRoleCredentials.spec.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.ts
packages/credential-provider-ini/src/resolveProfileData.ts
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

https://github.com/aws/aws-sdk-js-v3/issues/6225
This fixes chained assume role with ini role_arns and correctly enables optionality of the `role_arn` in the `credential_source` terminal profile section.
```
[profile default]
source_profile=A
role_arn=1
[profile A]
source_profile=B
role_arn=2
[profile B]
credential_source=EcsContainer
```
The SDK will:
- enter default profile
- navigate to source profile A
- navigate to source profile B
- obtain source credentials from EcsContainer
- complete profile B
- complete profile A assume role with role_arn=2
- complete profile default assume role with role_arn=1
```
[profile default]
source_profile=A
role_arn=1
[profile A]
source_profile=B
role_arn=2
[profile B]
credential_source=EcsContainer
role_arn=3
```
The SDK will:
- enter default profile
- …

fix(credential-provider-ini): fix recursive assume role and optional role_arn in credential_source

---

packages/cloudfront-signer/src/sign.ts

CloudFront also support WebSockets protocols.
https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-cloudfront-announces-support-for-the-websocket-protocol/
Adds support for WebSockets to CloudFront signer
N/A
---

Add support for WebSockets to CloudFront signer

---

package.json
yarn.lock

Bumping prior to long-term fix in https://github.com/aws/aws-sdk-js-v3/issues/6464
Bumps turbo to v2.1.2
Remote Cache was updated in the first run, likely due to some update in cache key computation
```console
...
Tasks:    473 successful, 473 total
Cached:    0 cached, 473 total
Time:    6m42.667s 
```
The cache was reused in the second run
```console
...
Tasks:    473 successful, 473 total
Cached:    473 cached, 473 total
Time:    23.88s >>> FULL TURBO
```
---

chore(deps-dev): bump turbo to v2.1.2

---

scripts/turbo/index.js

https://turbo.build/repo/docs/telemetry
Disables turborepo telemetry
Telemetry events are emitted
```console
$ TURBO_TELEMETRY_DEBUG=1 yarn build:all
yarn run v1.22.22
$ node ./scripts/turbo build
turbo 2.1.2
[telemetry event]
{
"generic": {
"id": "9199be4c-f754-4e10-87eb-37379040604a",
"key": "execution",
"value": "started",
"parent_id": null
}
}
[telemetry event]
{
"generic": {
"id": "9199be4c-f754-4e10-87eb-37379040604a",
"key": "platform",
"value": "linux-64",
"parent_id": null
}
}
...
```
Telemetry events are not emitted
```console
$ TURBO_TELEMETRY_DEBUG=1 yarn build:all
yarn run v1.22.22
$ node ./scripts/turbo build
turbo 2.1.2
• Packages in scope: @aws-sdk/aws-client-api-test, ...
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

chore: disable turborepo telemetry

---

scripts/turbo/index.js

N/A
Passes turbo API and TOKEN in environment variables, so that they won't be printed in logs
Verified that Remote cache is used with values from environment variables
```console
...
Tasks:    473 successful, 473 total
Cached:    473 cached, 473 total
Time:    24.049s >>> FULL TURBO
Done in 24.85s.
```
Docs: https://turbo.build/repo/docs/reference/system-environment-variables
---

chore: pass turbo remote cache options in environment variables

---

scripts/turbo/index.js

N/A
Limits turbo output to only turbo-computed task hashes
The default full output is around 6K lines
[turbo-output-full.txt](https://github.com/user-attachments/files/17015469/turbo-output-full.txt)
The hash-only output is around 485 lines
[turbo-output-hash-only.txt](https://github.com/user-attachments/files/17015483/turbo-output-hash-only.txt)
---

chore: show only turbo-computed task hashes in output

---

scripts/turbo/index.js

N/A, we use yarn for running all commands
Use yarn for running turbo commands
```console
yarn run v1.22.22
$ node ./scripts/turbo build
turbo 2.1.2
• Packages in scope: @aws-sdk/aws-client-api-test, ...
...
Tasks:    473 successful, 473 total
Cached:    473 cached, 473 total
Time:    23.98s >>> FULL TURBO
Done in 24.73s.
```
```console
yarn run v1.22.22
$ node ./scripts/turbo build
$ /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/.bin/turbo run build --concurrency=100% --output-logs=hash-only
turbo 2.1.2
• Packages in scope: @aws-sdk/aws-client-api-test, ...
...
Tasks:    473 successful, 473 total
Cached:    473 cached, 473 total
Time:    23.701s >>> FULL TURBO
Done in 24.30s.
```
---
By submitting this pull request, I confirm that you can use, …

chore: use yarn for running turbo commands

---

scripts/turbo/index.js

* Internal JS-5438
* Long-term fix for https://github.com/aws/aws-sdk-js-v3/issues/6464
Allows Turborepo remote cache write only on AWS Codebuild.
* Turborepo docs https://turbo.build/repo/docs/reference/system-environment-variables
* Environment variable `CODEBUILD_BUILD_ARN` is used for detecting CodeBuild in userland library `ci-info` https://github.com/watson/ci-info/blob/3e1488e98680f1f776785fe8708a157b7f00e568/vendors.json#L19-L23
This will ensure that any developments outside of CodeBuild environments, like developer workspaces, do not pollute the remote cache.
Verified that updated local cache from developer workspace is not uploaded to remote cache.
```console
$ make turbo-clean
...
Tasks:    473 successful, 473 total
Cached:    473 cached, 473 total
Time: …
```

chore: allow turbo remote cache write only on AWS Codebuild

---

packages/middleware-flexible-checksums/src/NODE_REQUEST_CHECKSUM_CALCULATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/NODE_RESPONSE_CHECKSUM_VALIDATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.spec.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.ts
packages/middleware-flexible-checksums/src/stringUnionSelector.ts

Missed in https://github.com/aws/aws-sdk-js-v3/pull/6470
Use union for new config types `requestChecksumCalculation` and `responseChecksumValidation`
CI
---

fix(middleware-flexible-checksums): use union for new config types

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java

n/a
Remove incorrect fallback attempt to the service arn namespace when setting the default signing name.
CI

fix(codegen): fix setting of default signing name

---

packages/middleware-flexible-checksums/src/types.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/6499
Re-order checksum implementations based on performance
CI
The S3 backend doesn't sent multiple checksum values in the headers today. The checksum returned is for the value provided during putObject call. The existing implementation ensures that it goes through the priority order for selecting an algorithm if multiple checksum values are available.
---

chore(middleware-flexible-checksums): re-order checksum implementations based on performance

---

packages/core/account-id-endpoint.d.ts
packages/core/client.d.ts
packages/core/httpAuthSchemes.d.ts
packages/core/package.json
packages/core/protocols.d.ts
packages/core/scripts/lint.js

https://github.com/aws/aws-sdk-js-v3/issues/6502
Adds a `.d.ts` file in the core root so that an import like `@aws-sdk/core/submodule` not only maps via package.json exports, but also via traditional package relative pathing when contexts do not understand the exports metadata.
created new linting rules for core submodules

fix(core): add compatibility types for submodules

---

clients/client-docdb/src/waiters/waitForDBInstanceDeleted.ts
clients/client-elastic-load-balancing-v2/src/waiters/waitForLoadBalancerAvailable.ts
clients/client-elastic-load-balancing-v2/src/waiters/waitForLoadBalancerExists.ts
clients/client-elastic-load-balancing-v2/src/waiters/waitForLoadBalancersDeleted.ts
clients/client-elastic-load-balancing-v2/src/waiters/waitForTargetDeregistered.ts
clients/client-elastic-load-balancing/src/waiters/waitForInstanceDeregistered.ts
clients/client-elastic-load-balancing/src/waiters/waitForInstanceInService.ts
clients/client-elasticache/src/waiters/waitForCacheClusterDeleted.ts
clients/client-iam/src/waiters/waitForPolicyExists.ts
clients/client-iam/src/waiters/waitForRoleExists.ts
clients/client-iam/src/waiters/waitForUserExists.ts
clients/client-neptune/src/waiters/waitForDBInstanceDeleted.ts
clients/client-rds/src/waiters/waitForDBInstanceDeleted.ts
clients/client-rds/src/waiters/waitForDBSnapshotDeleted.ts
clients/client-redshift/src/waiters/waitForClusterAvailable.ts
clients/client-redshift/src/waiters/waitForClusterDeleted.ts
clients/client-s3/src/commands/DeleteObjectTaggingCommand.ts
clients/client-s3/src/commands/DeleteObjectsCommand.ts
clients/client-s3/src/commands/GetObjectTaggingCommand.ts
clients/client-s3/src/commands/PutObjectCommand.ts
clients/client-s3/src/commands/UploadPartCopyCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/ProcessAwsQueryWaiters.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

Fixes: https://github.com/aws/aws-sdk/issues/639
The SDK incorrectly uses the awsQuery error code as an error matcher for waiters. 
This PR pre-processes the aws query API models and swaps the error matcher code with the corresponding shapeID. 
```js
import { ElasticLoadBalancingV2Client, DeleteLoadBalancerCommand, waitUntilLoadBalancersDeleted } from "@aws-sdk/client-elastic-load-balancing-v2";
const client = new ElasticLoadBalancingV2Client({
region: "us-east-1",
});
async function deleteAndWaitForLoadBalancer(loadBalancerArn) {
try {
await client.send(new DeleteLoadBalancerCommand({ LoadBalancerArn: loadBalancerArn }));
console.log("Load balancer deletion initiated");
await waitUntilLoadBalancersDeleted(
{ 
client,
maxWaitTime: 600,
minDelay: 15,
maxDelay: 120
},
{ LoadBalancerArns: …
```

fix(codegen): preprocess AwsQuery error to shapeId in waiter errorType

---

.github/workflows/stale_issues.yml

Version bump for [stale-issue-cleanup](https://github.com/aws-actions/stale-issue-cleanup) and minor changes.
- [add permissions to stale_issues.yml](https://github.com/aws/aws-sdk-js-v3/commit/dfaae9897be484acbc115aa4984d48dfac30f9c8)
- [remove ancient-issue bot](https://github.com/aws/aws-sdk-js-v3/commit/dfd7e8c8c9a70c8cafc1177a447b76a98d2133f4)
- [bump stale-issue-cleanup to v6](https://github.com/aws/aws-sdk-js-v3/commit/6b971cbd8231f95a54cf08c4ced01054b7da4361)

chore: update stale-issue bot

---

lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.ts
packages/middleware-flexible-checksums/package.json
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/middleware-flexible-checksums.integ.spec.ts
packages/middleware-sdk-s3/src/s3-express/functions/s3ExpressMiddleware.ts
packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.integ.spec.ts
packages/middleware-user-agent/package.json
packages/middleware-user-agent/src/check-features.ts
packages/middleware-user-agent/src/configurations.ts
packages/middleware-user-agent/src/middleware-user-agent.integ.spec.ts
packages/middleware-user-agent/src/user-agent-middleware.ts
private/aws-util-test/src/requests/test-http-handler.ts

adds feature detection for:
- s3 express bucket
- dynamodb mapper
- account id endpoints modes
- flexible checksum algorithm name

chore(middleware-user-agent): add feature detection for account-id, s3-express, lib-dynamodb

---

packages/middleware-user-agent/src/check-features.ts

From the PR comment:
```
// Sometimes config.credentials is a function but only throws
// as a way of informing users that something is missing.
// That error and any other errors are not relevant for feature-checking
// and are ignored.
```

fix(middleware-user-agent): ignore errors from inspecting credentials

---

packages/middleware-user-agent/src/check-features.spec.ts
packages/middleware-user-agent/src/check-features.ts

https://github.com/aws/aws-sdk-js-v3/issues/6553
Avoid calling the credential provider in the user agent middleware. This causes an endless loop if the credential provider involves calling an SDK client operation with the same middleware attached.
New unit test

fix(credentials): used selected auth scheme identity instead of calling credentials provider

---

lib/lib-dynamodb/package.json

#6549
Changes added in dfda129  introduced a new direct dependency on `@aws-sdk/core` but it's not added in package.json. 
---

fix(lib-dynamodb): missing @aws-sdk/core dependency in lib-dynamodb

---

clients/client-s3/src/commands/GetBucketLifecycleConfigurationCommand.ts
clients/client-s3/src/commands/GetBucketReplicationCommand.ts
clients/client-s3/src/commands/PutBucketLifecycleConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketReplicationCommand.ts
clients/client-s3/src/models/models_0.ts
clients/client-s3/src/models/models_1.ts
clients/client-s3/src/protocols/Aws_restXml.ts
codegen/sdk-codegen/aws-models/s3.json

Fixes an issue in the S3 service model where two shapes were incorrectly modeled as unions.

fix(client-s3): correct shape type of two shapes from union to structure

---

packages/util-user-agent-browser/src/index.native.ts
packages/util-user-agent-browser/src/index.ts

for: https://github.com/aws/aws-sdk-js-v3/issues/6573
the native interface differed from the browser interface in this package, causing a runtime error

fix(util-user-agent-browser): make native interface consistent with browser

---

tests/e2e-legacy/preview.mjs

Internal JS-5505
Skips preview legacy:e2e tests if client is not found
Tested with preview build internal artifact
Error is thrown:
```console
$ yarn test:e2e:legacy:preview
yarn run v1.22.22
$ ./tests/e2e-legacy/preview.mjs
Updated packages: [object Set]
Couldn't find clients in commit messages:
''
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Error is not thrown
```console
$  yarn test:e2e:legacy:preview    
yarn run v1.22.22
$ ./tests/e2e-legacy/preview.mjs
Updated packages: 
Couldn't find clients in commit messages:
''
Done in 0.11s.
```
---

test(scripts): skip preview legacy:e2e tests if client is not found

---

codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/README.md.template

Fix "the this" typo to just read "this" under "Installing".
---

docs: update README.md.template to fix a typo

---

.github/workflows/pre-commit-hooks.yml
package.json
packages/core/integ/request-handlers/request-handlers.integ.spec.ts
packages/core/jest.config.integ.js
packages/core/jest.config.js
packages/core/package.json
packages/core/src/submodules/account-id-endpoint/AccountIdEndpointModeConstants.spec.ts
packages/core/src/submodules/account-id-endpoint/NodeAccountIdEndpointModeConfigOptions.spec.ts
packages/core/src/submodules/client/emitWarningIfUnsupportedVersion.spec.ts
packages/core/src/submodules/client/emitWarningIfUnsupportedVersion.ts
packages/core/src/submodules/client/setCredentialFeature.spec.ts
packages/core/src/submodules/client/setFeature.spec.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/AwsSdkSigV4Signer.spec.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4AConfig.spec.ts
packages/core/src/submodules/httpAuthSchemes/utils/getSkewCorrectedDate.spec.ts
packages/core/src/submodules/httpAuthSchemes/utils/getUpdatedSystemClockOffset.spec.ts
packages/core/src/submodules/httpAuthSchemes/utils/isClockSkewed.spec.ts
packages/core/src/submodules/protocols/coercing-serializers.spec.ts
packages/core/src/submodules/protocols/json/awsExpectUnion.spec.ts
packages/core/src/submodules/protocols/xml/parseXmlBody.spec.ts
packages/core/vitest.config.integ.ts
packages/core/vitest.config.ts
scripts/validation/vitest-validation.js
vite.workspace.ts
yarn.lock

Try out vitest in `@aws-sdk/core`.

test(core): install vitest

---

CHANGELOG.md
clients/client-athena/CHANGELOG.md

Internal JS-5516
updates release notes/changelog for the recent athena breaking change
---

chore(client-athena): update release notes for athena breaking change

---

Makefile
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

Mocking of STS caused a bug in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.667.0 to not be caught.
Removes the mocking of the STS and SSO clients in the credential provider chain's integration test. The mocking is moved to the HTTP Handler level.
CI / running these integration tests.
Verifying that this would've caught the issue in v3.667.0:
```
git checkout v3.667.0
make tpk # builds packages only
b cred prov node - integ # runs integration tests, hangs
```
```
git checkout v3.668.0 # patched version
make tpk # builds packages only
b cred prov node - integ # runs integration tests, succeeds
```

test(credential-provider-node): remove sts and sso client mocks

---

clients/client-s3/test/e2e/S3.browser.e2e.spec.ts
packages/middleware-sdk-s3/src/region-redirect-middleware.e2e.spec.ts

n/a
S3 has strong read-after-write consistency https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/.
However, some of our tests have failed randomly at certain read-after-write points, without clear error messaging. 
This PR adds loggers to the test clients and converts some read points to waiters to be more forgiving.
Ran the tests in question.

test(client-s3): convert some read ops to waiters

---

clients/client-s3/test/e2e/S3.e2e.spec.ts
packages/middleware-flexible-checksums/package.json
packages/middleware-flexible-checksums/src/getChecksum.spec.ts
packages/middleware-flexible-checksums/src/getChecksum.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.spec.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.ts

Internal JS-5537
Delays checksum validation until stream read
```js
import assert from "assert";
import { S3 } from "@aws-sdk/client-s3";
// import { S3 } from "../aws-sdk-js-v3/clients/client-s3/dist-cjs/index.js";
const s3 = new S3({ region: "us-west-2" });
const Bucket = "test-flexible-checksums"; // Change to your bucket name
const Key = "test.txt";
const Body = "helloworld".repeat(10_000_000); // A string of size ~100MB
await s3.putObject({ Bucket, Key, Body, ChecksumAlgorithm: "CRC32" });
const apiCallStart = performance.now();
const response = await s3.getObject({ Bucket, Key, ChecksumMode: "ENABLED" });
console.log("time taken for request:", (performance.now() - apiCallStart).toFixed(2), "ms");
const transformStart = performance.now();
const body = await …
```

chore(middleware-flexible-checksums): delay checksum validation until stream read

---

private/aws-restjson-server/jest.config.js
private/aws-restjson-server/package.json
private/aws-restjson-server/test/functional/restjson1.spec.ts
private/aws-restjson-validation-server/jest.config.js
private/aws-restjson-validation-server/package.json
private/aws-restjson-validation-server/test/functional/restjson1.spec.ts
vitest.config.protocols.integ.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/6627#discussion_r1830023311
Uses vitest for running unit tests in aws-restjson-*
CI
---

test(aws-restjson-*): use vitest

---

clients/client-s3/test/e2e/S3.browser.e2e.spec.ts
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts
packages/middleware-sdk-s3/src/s3-express/middleware-s3-express.integ.spec.ts
packages/middleware-user-agent/src/middleware-user-agent.integ.spec.ts
private/aws-util-test/src/requests/test-http-handler.integ.spec.ts

improve assertions in user agent tests

test(middleware-user-agent): more precise assertions

---

packages/middleware-flexible-checksums/src/getCrc32ChecksumAlgorithmFunction.ts
packages/middleware-flexible-checksums/src/selectChecksumAlgorithmFunction.spec.ts

Internal JS-5558
Move inline class NodeCrc32 outside the function, so that a new copy of it is not created.
It's not an issue right now, since the function getCrc32ChecksumAlgorithmFunction is called just once. But it lead to some test failures requiring us to disable a test case in https://github.com/aws/aws-sdk-js-v3/pull/6647
The `yarn test:unit` is successful on both Node.js 18 and 20.
---

chore(middleware-flexible-checksums): move inline class NodeCrc32 outside

---

lib/lib-dynamodb/README.md
packages/util-dynamodb/src/convertToAttr.spec.ts
packages/util-dynamodb/src/convertToAttr.ts
packages/util-dynamodb/src/convertToNative.spec.ts
packages/util-dynamodb/src/convertToNative.ts
packages/util-dynamodb/src/marshall.ts
packages/util-dynamodb/src/unmarshall.ts

https://github.com/aws/aws-sdk-js-v3/issues/6571
The SDK was throwing errors when handling large numbers (>MAX_SAFE_INTEGER) that worked in v2. This affected both:
1. Marshalling: `marshall({ foo: 1.23e+40 })` would throw an error
2. Unmarshalling: `unmarshall({ foo: { N: "1.23e+40" } })` required explicit handling
1. Added `marshallOptions.allowImpreciseNumbers`
- When true: Allows storing numbers > MAX_SAFE_INTEGER with potential precision loss (matches v2 behavior)
- When false (default): Maintains existing precision protection
2. expanded `unmarshallOptions.wrapNumbers`  - Now accepts a function: `(value: string) => number | bigint | NumberValue` where customers can provide their own custom unmarshalling logic.
3. Added unit test to cover the new marshal option and the expanded …

feat(lib-dynamodb): add support for imprecise numbers and custom number retrieval

---

clients/client-sqs/src/protocols/Aws_json1_0.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsJsonRpc1_1.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsSmithyRpcV2Cbor.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java
packages/middleware-sdk-sqs/src/middleware-sdk-sqs.integ.spec.ts

n/a, spec update
Send the HTTP header `x-amzn-query-mode` set to `true` when using awsQueryCompatible. This applies only to the two supported protocols `awsJson1.0` (not 1.1), and `smithyRpcV2Cbor`. 
added integration test assertion for qualifying service (SQS).

feat(codegen): send x-amzn-query-mode header

---

scripts/benchmark-size/runner/local-registry.ts

after confirming that the test:size script is working, we don't need this output anymore

chore(scripts): omit stdio in benchmark-size runner

---

scripts/generate-clients/index.js

Internal JS-5573
disable the `--immutable` flag (https://github.com/yarnpkg/berry/discussions/3486) to allow for lockfile modifications. 
---

chore(scripts): yarn install with --no-immutable to allow lockfile modification

---

clients/client-s3/src/commands/DeleteObjectsCommand.ts
clients/client-s3/src/commands/GetObjectCommand.ts
clients/client-s3/src/commands/PutBucketAccelerateConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketAclCommand.ts
clients/client-s3/src/commands/PutBucketCorsCommand.ts
clients/client-s3/src/commands/PutBucketEncryptionCommand.ts
clients/client-s3/src/commands/PutBucketLifecycleConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketLoggingCommand.ts
clients/client-s3/src/commands/PutBucketOwnershipControlsCommand.ts
clients/client-s3/src/commands/PutBucketPolicyCommand.ts
clients/client-s3/src/commands/PutBucketReplicationCommand.ts
clients/client-s3/src/commands/PutBucketRequestPaymentCommand.ts
clients/client-s3/src/commands/PutBucketTaggingCommand.ts
clients/client-s3/src/commands/PutBucketVersioningCommand.ts
clients/client-s3/src/commands/PutBucketWebsiteCommand.ts
clients/client-s3/src/commands/PutObjectAclCommand.ts
clients/client-s3/src/commands/PutObjectCommand.ts
clients/client-s3/src/commands/PutObjectLegalHoldCommand.ts
clients/client-s3/src/commands/PutObjectLockConfigurationCommand.ts
clients/client-s3/src/commands/PutObjectRetentionCommand.ts
clients/client-s3/src/commands/PutObjectTaggingCommand.ts
clients/client-s3/src/commands/PutPublicAccessBlockCommand.ts
clients/client-s3/src/commands/RestoreObjectCommand.ts
clients/client-s3/src/commands/UploadPartCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts

Refs: https://github.com/aws/aws-sdk-js-v3/pull/6492#issuecomment-2486389365
Use input from args and not middleware config in flexible checksums middleware.
This is because args.input will have updated values, while middlewareConfig.input will have initial values.
We're updating value in `input[requestAlgorithmMember]` in https://github.com/aws/aws-sdk-js-v3/pull/6492
CI
```js
import { NodeHttpHandler } from "@smithy/node-http-handler";
import { equal } from "assert";
// Prints checksum headers for request and response.
class CustomHandler extends NodeHttpHandler {
constructor() {
super();
}
printChecksumHeaders(prefix, headers) {
for (const [header, value] of Object.entries(headers)) {
if …
```

fix(middleware-flexible-checksums): use input from args and not middleware config

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/DocumentClientCommandGenerator.java
lib/lib-dynamodb/src/commands/BatchExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/BatchGetCommand.ts
lib/lib-dynamodb/src/commands/BatchWriteCommand.ts
lib/lib-dynamodb/src/commands/DeleteCommand.ts
lib/lib-dynamodb/src/commands/ExecuteStatementCommand.ts
lib/lib-dynamodb/src/commands/ExecuteTransactionCommand.ts
lib/lib-dynamodb/src/commands/GetCommand.ts
lib/lib-dynamodb/src/commands/PutCommand.ts
lib/lib-dynamodb/src/commands/QueryCommand.ts
lib/lib-dynamodb/src/commands/ScanCommand.ts
lib/lib-dynamodb/src/commands/TransactGetCommand.ts
lib/lib-dynamodb/src/commands/TransactWriteCommand.ts
lib/lib-dynamodb/src/commands/UpdateCommand.ts

edit of https://github.com/aws/aws-sdk-js-v3/pull/6676 with codegen changes applied

fix(lib-dynamodb): input types conflicts with client-dynamodb

---

packages/credential-provider-ini/src/fromIni.ts
packages/credential-provider-ini/src/resolveSsoCredentials.spec.ts
packages/credential-provider-ini/src/resolveSsoCredentials.ts
packages/credential-provider-sso/src/fromSSO.ts
packages/credential-provider-sso/src/resolveSSOCredentials.ts
packages/token-providers/src/fromSso.spec.ts
packages/token-providers/src/fromSso.ts
packages/token-providers/src/getNewSsoOidcToken.spec.ts
packages/token-providers/src/getNewSsoOidcToken.ts
packages/token-providers/src/getSsoOidcClient.spec.ts
packages/token-providers/src/getSsoOidcClient.ts

addresses https://github.com/aws/aws-sdk-js-v3/issues/6687
This change ensures `clientConfig`, a property shared by many credential providers, is used as the initialization config for all inner clients including SSO and SSOOIDC. Currently, it is only passed through for CognitoIdentity and STS clients. 
manual SSO testing

fix(credential-provider-ini): pass clientConfig to sso and sso-oidc inner clients

---

supplemental-docs/CLIENTS.md

update remarks on socket exhaustion with an example of the warning emitted.

docs: remarks on socket exhaustion warning

---

clients/client-s3/src/commands/DeleteObjectsCommand.ts
clients/client-s3/src/commands/PutBucketAccelerateConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketAclCommand.ts
clients/client-s3/src/commands/PutBucketCorsCommand.ts
clients/client-s3/src/commands/PutBucketEncryptionCommand.ts
clients/client-s3/src/commands/PutBucketLifecycleConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketLoggingCommand.ts
clients/client-s3/src/commands/PutBucketPolicyCommand.ts
clients/client-s3/src/commands/PutBucketReplicationCommand.ts
clients/client-s3/src/commands/PutBucketRequestPaymentCommand.ts
clients/client-s3/src/commands/PutBucketTaggingCommand.ts
clients/client-s3/src/commands/PutBucketVersioningCommand.ts
clients/client-s3/src/commands/PutBucketWebsiteCommand.ts
clients/client-s3/src/commands/PutObjectAclCommand.ts
clients/client-s3/src/commands/PutObjectCommand.ts
clients/client-s3/src/commands/PutObjectLegalHoldCommand.ts
clients/client-s3/src/commands/PutObjectLockConfigurationCommand.ts
clients/client-s3/src/commands/PutObjectRetentionCommand.ts
clients/client-s3/src/commands/PutObjectTaggingCommand.ts
clients/client-s3/src/commands/PutPublicAccessBlockCommand.ts
clients/client-s3/src/commands/RestoreObjectCommand.ts
clients/client-s3/src/commands/UploadPartCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts

* Will be consumed in https://github.com/aws/aws-sdk-js-v3/pull/6492
Creates and sets [httpHeader](https://smithy.io/2.0/spec/http-bindings.html#httpheader-trait) value for [requestAlgorithmMember](https://smithy.io/2.0/aws/aws-core.html#aws-protocols-httpchecksum-trait), if present. 
CI, as this PR just populates the middleware config.
The value will be consumed, and tested in https://github.com/aws/aws-sdk-js-v3/pull/6492
---

chore(middleware-flexible-checksums): add requestAlgorithmMemberHttpHeader

---

clients/client-sesv2/package.json
clients/client-sesv2/src/SESv2Client.ts
clients/client-sesv2/src/auth/httpAuthSchemeProvider.ts
clients/client-sesv2/src/runtimeConfig.shared.ts
clients/client-sesv2/src/runtimeConfig.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsTraitsUtils.java
yarn.lock

Enables sigv4a code generation for sesv2. The functionality is not available yet in the service itself.

chore(client-sesv2): enable sigv4a code generation in sesv2 ahead of service availability

---

package.json
packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts
packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.ts
packages/credential-provider-ini/package.json
packages/credential-provider-ini/src/fromIni.integ.spec.ts
packages/credential-provider-ini/src/fromIni.ts
packages/credential-provider-ini/src/resolveAssumeRoleCredentials.ts
packages/credential-provider-ini/vitest.config.integ.ts
packages/credential-provider-node/package.json
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts
packages/credential-provider-web-identity/src/fromWebToken.ts
packages/credential-providers/src/createCredentialChain.spec.ts
packages/credential-providers/src/createCredentialChain.ts
packages/credential-providers/src/fromIni.ts
packages/middleware-signing/README.md
packages/middleware-signing/src/awsAuthConfiguration.ts
packages/middleware-signing/src/awsAuthMiddleware.ts
packages/middleware-websocket/package.json
packages/token-providers/src/fromSso.ts
packages/types/src/identity/AwsCredentialIdentity.ts
yarn.lock

We [previously](https://github.com/aws/aws-sdk-js-v3/pull/5758) introduced the concept of a "parentClientConfig" for credential providers that create another (inner) SDK client such as STS. 
One problem was that if the provider was initialized outside of a client, this connection could not be made. This PR makes AWS credential providers accept a contextual client config, making them region aware at call time. The result is improved intuitiveness of default behavior, as shown below.
⚠️ when using a CODE level credential configuration, any potential spawning of an inner client such as STS for AssumeRole must be passed the region in a redundant manner. This is because `fromIni` is a standalone function that can resolve credentials without the context of an SDK client.
```js
import { DynamoDB …
```

feat(credential-providers): make credential providers aware of caller client region

---

packages/credential-provider-ini/src/fromIni.integ.spec.ts

set profile explicitly in integ test, which sometimes uses a different profile depending on runner environment

test(credential-provider-ini): set profile in integ test

---

scripts/generate-clients/config.js

Refs: https://github.com/smithy-lang/smithy-typescript/pull/1462
Updates smithy commit to include obj and array JS literals from JMESPath types for waiters.
N/A, as there are no changes in codegen.
---

chore(codegen): resolve obj and array JS literals from JMESPath types for waiters

---

packages/xhr-http-handler/src/xhr-http-handler.spec.ts
packages/xhr-http-handler/src/xhr-http-handler.ts

internal P179133623
use addEventListener for XHR abort signal

fix(xhr-http-handler): fix abort signal sharing for multiple requests

---

packages/crt-loader/package.json
yarn.lock

Allows using new APIs, like CRC64-NVME, in https://github.com/aws/aws-sdk-js-v3/pull/6736
Bumps aws-crt to ^1.24.0
CI
---

chore(crt-loader): bump aws-crt to ^1.24.0

---

clients/client-s3/src/commands/CreateBucketMetadataTableConfigurationCommand.ts
clients/client-s3/src/commands/DeleteObjectsCommand.ts
clients/client-s3/src/commands/PutBucketAccelerateConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketAclCommand.ts
clients/client-s3/src/commands/PutBucketCorsCommand.ts
clients/client-s3/src/commands/PutBucketEncryptionCommand.ts
clients/client-s3/src/commands/PutBucketLifecycleConfigurationCommand.ts
clients/client-s3/src/commands/PutBucketLoggingCommand.ts
clients/client-s3/src/commands/PutBucketPolicyCommand.ts
clients/client-s3/src/commands/PutBucketReplicationCommand.ts
clients/client-s3/src/commands/PutBucketRequestPaymentCommand.ts
clients/client-s3/src/commands/PutBucketTaggingCommand.ts
clients/client-s3/src/commands/PutBucketVersioningCommand.ts
clients/client-s3/src/commands/PutBucketWebsiteCommand.ts
clients/client-s3/src/commands/PutObjectAclCommand.ts
clients/client-s3/src/commands/PutObjectCommand.ts
clients/client-s3/src/commands/PutObjectLegalHoldCommand.ts
clients/client-s3/src/commands/PutObjectLockConfigurationCommand.ts
clients/client-s3/src/commands/PutObjectRetentionCommand.ts
clients/client-s3/src/commands/PutObjectTaggingCommand.ts
clients/client-s3/src/commands/PutPublicAccessBlockCommand.ts
clients/client-s3/src/commands/RestoreObjectCommand.ts
clients/client-s3/src/commands/UploadPartCommand.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttpChecksumDependency.java
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts

* Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/6694
Switches to using object for requestAlgorithmMember to avoid future confusion that requestAlgorithmMember and requestAlgorithmMemberHttpHeader can exist independently of each other
CI, as this PR just populates the middleware config.
The value in `httpHeader` will be consumed, and tested in https://github.com/aws/aws-sdk-js-v3/pull/6492
---

chore(middleware-flexible-checksums): use object for requestAlgorithmMember

---

packages/middleware-flexible-checksums/src/selectChecksumAlgorithmFunction.ts

* Switch is better since:
* In the past, we'd to decide whether to switch between different CRC32 implementations https://github.com/aws/aws-sdk-js-v3/pull/6641
* In near future, CRC64-NVME implementation will come from optional dependency https://github.com/aws/aws-sdk-js-v3/pull/6736, and we'll throw error if the optional dependency is not present.
Uses switch for selecting checksum algorithm function
CI
---

chore(middleware-flexible-checksums): use switch for selecting checksum algorithm function

---

packages/credential-providers/README.md
supplemental-docs/CLIENTS.md

documentation for https://github.com/aws/aws-sdk-js-v3/pull/6728

docs(clients): document client-level profile configuration

---

.github/workflows/pre-commit-hooks.yml

Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/6757, after which we switched to using globally installed yarn classic from GitHub runners to use local binary of yarn modern.
Skips enabling corepack in pre-commit-hooks.
Verified that `pre-commit-hooks` uses yarn@4.5.1
```console
Run yarn install --frozen-lockfile
...
➤ YN0000: · Yarn 4.5.1
```
Job: https://github.com/aws/aws-sdk-js-v3/actions/runs/12508374958/job/34896397427?pr=6760
---

chore(ci): skip enabling corepack

---

packages/credential-providers/src/createCredentialChain.ts
packages/credential-providers/src/fromCognitoIdentity.ts
packages/credential-providers/src/fromCognitoIdentityPool.ts
packages/credential-providers/src/fromContainerMetadata.ts
packages/credential-providers/src/fromEnv.ts
packages/credential-providers/src/fromIni.ts
packages/credential-providers/src/fromInstanceMetadata.ts
packages/credential-providers/src/fromNodeProviderChain.ts
packages/credential-providers/src/fromProcess.ts
packages/credential-providers/src/fromSSO.ts
packages/credential-providers/src/fromTemporaryCredentials.ts
packages/credential-providers/src/fromTokenFile.ts
packages/credential-providers/src/fromWebToken.ts
packages/credential-providers/src/loadSts.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts
packages/middleware-user-agent/src/user-agent-middleware.ts
packages/token-providers/src/fromStatic.ts
packages/xhr-http-handler/src/xhr-http-handler.ts

fixes various tsdoc annotations

docs: fix various tsdoc tags

---

clients/client-s3/package.json
clients/client-s3/test/e2e/S3.browser.e2e.spec.ts
clients/client-s3/vitest.config.browser.ts
clients/client-s3/vitest.config.e2e.ts
package.json
packages/credential-provider-ini/src/fromIni.integ.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostname.spec.ts
packages/s3-presigned-post/src/createPresignedPost.spec.ts
tests/e2e/get-integ-test-resources.js
yarn.lock

see also https://github.com/smithy-lang/smithy-typescript/pull/1496
updates to latest vitest from Dec 2024

test: update vitest to 2.1.8

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsPackageFixturesGeneratorIntegration.java

Handles the case where the service model has no operation shapes.
Of course, a service is not going to be very successful right now if it has no operations, but we do not want the preview build to fail. Some features are opened and run builds before the models get loaded into the feature.

fix(codegen): handle case when sample operation not found

---

.github/workflows/closed-issue-message.yml

Add Github action that sets a default message to be commented on all issues or pull requests when they get closed.
---

chore(ci): add closed-issue-message GitHub action

---

packages/middleware-flexible-checksums/src/constants.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/getChecksumAlgorithmForRequest.spec.ts
packages/middleware-flexible-checksums/src/getChecksumAlgorithmForRequest.ts
private/aws-middleware-test/src/middleware-serde.spec.ts

* Split from https://github.com/aws/aws-sdk-js-v3/pull/6492
Changes default checksum algorithm to CRC32, and deprecates MD5.
CI
---

chore(middleware-flexible-checksums): change default algorithm to CRC32

---

packages/middleware-flexible-checksums/src/configuration.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsInputMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsInputMiddleware.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.spec.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/getChecksumAlgorithmForRequest.spec.ts
packages/middleware-flexible-checksums/src/getChecksumAlgorithmForRequest.ts
packages/middleware-flexible-checksums/src/getFlexibleChecksumsPlugin.ts
packages/middleware-flexible-checksums/src/middleware-flexible-checksums.integ.spec.ts

* Split from https://github.com/aws/aws-sdk-js-v3/pull/6492
* Should be rebased after https://github.com/aws/aws-sdk-js-v3/pull/6749 is merged
Performs checksum calculation and validation by default based on values in RequestChecksumCalculation and ResponseChecksumValidation
Unit testing in CI
Verified that CRC32 checksums are computed by default
```js
import { NodeHttpHandler } from "../aws-sdk-js-v3/node_modules/@smithy/node-http-handler/dist-cjs/index.js";
import { equal } from "assert";
// Prints checksum headers for request and response.
class CustomHandler extends NodeHttpHandler {
constructor() {
super();
}
printChecksumHeaders(prefix, headers) {
for (const [header, value] of …
```

chore(middleware-flexible-checksums): perform checksum calculation and validation by default

---

clients/client-s3/test/e2e/S3.e2e.spec.ts

Internal JS-5678
Changes chunk size in E2E tests to 8 KB.
From [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html)
> The chunk size must be at least 8 KB. We recommend a chunk size of a least 64 KB for better performance. This chunk size applies to all chunks except the last one. The last chunk you send can be smaller than 8 KB. If your payload is small and can fit into one chunk, then it can be smaller than the 8 KB.
```console
$ client-s3> yarn test:e2e
...
❯ test/e2e/S3.e2e.spec.ts (8) 1905ms
❯ @aws-sdk/client-s3 (8) 1904ms
❯ PutObject (1)
× should succeed with Node.js readable stream body
...
FAIL  test/e2e/S3.e2e.spec.ts > @aws-sdk/client-s3 > PutObject > should succeed with Node.js readable stream body
InvalidChunkSizeError: Only the last chunk …
```

test(client-s3): use chunk size of 8 KB

---

clients/client-s3/test/e2e/S3.browser.e2e.spec.ts

Internal JS-5678
Temporarily skips blob body test for client-s3 in browser
```console
$ client-s3> yarn test:browser
...
FAIL  test/e2e/S3.browser.e2e.spec.ts > @aws-sdk/client-s3 > PutObject > should succeed with blob body
TypeError: readableStream.on is not a function
❯ getAwsChunkedEncodingStream ../../node_modules/@smithy/util-stream/dist-cjs/getAwsChunkedEncodingStream.js:13:20
❯ test/browser-build/browser-s3-bundle.js:5802:21
5800|     if (isStreaming(requestBody)) {
5801|       const { getAwsChunkedEncodingStream: getAwsChunkedEncodingStream2, bodyLengthChecker } = config;
5802|       updatedBody = getAwsChunkedEncodingStream2(requestBody, {
...
Test Files  1 failed | 2 passed (3)
Tests  1 failed | 25 passed | 1 skipped (27)
```
```console
$ lib-storage> yarn test:browser
...
Test …
```

test(client-s3): skip putObject blob body in browser

---

packages/crc64-nvme-crt/src/CrtCrc64Nvme.spec.ts
packages/crc64-nvme-crt/src/CrtCrc64Nvme.ts

Internal JS-5674
Returns checksum for empty string if called without data
Verified using internal test code that CRC64VME checksum if `"AAAAAAAAAAA="` when called for empty string.
---

fix(crc64-nvme-crt): return checksum for empty string if called without data

---

packages/nested-clients/src/submodules/sso-oidc/protocols/Aws_restJson1.ts
packages/nested-clients/src/submodules/sts/protocols/Aws_query.ts
scripts/generate-clients/index.js

chore(codegen): move nested client generation to end

---

packages/credential-providers/src/fromTemporaryCredentials.browser.ts
packages/credential-providers/src/fromTemporaryCredentials.spec.ts
packages/credential-providers/src/fromTemporaryCredentials.ts
packages/credential-providers/src/index.browser.ts
packages/nested-clients/package.json
packages/types/src/identity/AwsCredentialIdentity.ts

https://github.com/aws/aws-sdk-js-v3/issues/6816
This provides backup credentials to the `fromTemporaryCredentials()` provider.
Also fixes browser bundling for the nested clients.

fix(credential-providers): supply backup credentials to fromTemporaryCredentials

---

packages/nested-clients/package.json

key ordering created a diff during code generation

fix: fix key ordering for code generation build

---

packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.spec.ts
packages/middleware-flexible-checksums/src/validateChecksumFromResponse.ts

Fixes: https://github.com/aws/aws-sdk-js-v3/issues/6822
Skips checksum validation if CRC64NVME dependency is absent
Unit testing
Perform putObject with CRC64NVME dependency
```js
// putObject.mjs
import { S3, ChecksumAlgorithm } from "@aws-sdk/client-s3";
import "@aws-sdk/crc64-nvme-crt";
const client = new S3();
const Bucket = "test-flexible-checksums-v2"; // Change to your bucket name.
const Key = "foo";
const Body = "bar";
await client.putObject({ Bucket, Key, Body, ChecksumAlgorithm: ChecksumAlgorithm.CRC64NVME });
```
```js
// getObject.mjs
const client = new S3({ logger: console });
const Bucket = "test-flexible-checksums-v2";
const Key = "foo";
await client.getObject({ Bucket, Key });
```
Error is thrown …

fix(middleware-flexible-checksums): skip checksum validation if CRC64NVME dependency is absent

---

clients/client-s3/test/unit/S3.spec.ts
lib/lib-storage/src/Upload.spec.ts
packages/dsql-signer/src/runtimeConfig.spec.ts
packages/eventstream-handler-node/src/EventStreamPayloadHandler.spec.ts
packages/middleware-endpoint-discovery/src/resolveEndpointDiscoveryConfig.spec.ts
packages/middleware-sdk-s3/src/check-content-length-header.spec.ts
packages/middleware-token/src/normalizeTokenProvider.spec.ts
packages/middleware-websocket/src/EventStreamPayloadHandler.spec.ts
packages/rds-signer/src/runtimeConfig.spec.ts

clean up warnings and log output from unit tests
- await assertions on promises (vitest 2->3 warning)
- clean up S3 middleware logging in tests

test(packages): await promise assertions, cleanup test logging

---

.prettierignore
clients/client-sts/src/defaultStsRoleAssumers.ts
codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultStsRoleAssumers.ts
packages/credential-providers/package.json
packages/credential-providers/src/fromTemporaryCredentials.base.ts
packages/credential-providers/src/fromTemporaryCredentials.spec.ts
packages/nested-clients/src/submodules/sso-oidc/endpoint/ruleset.ts
packages/nested-clients/src/submodules/sts/defaultStsRoleAssumers.ts
packages/nested-clients/src/submodules/sts/endpoint/ruleset.ts
packages/types/src/identity/AwsCredentialIdentity.ts
yarn.lock

https://github.com/aws/aws-sdk-js-v3/issues/6565
- caller client options for region, profile, requestHandler, logger, credentialDefaultProvider are passed to the `fromTemporaryCredentials` inner STS client unless overridden with `fromTemporaryCredentials({ clientConfig })` fields.
new unit tests
existing credential integration tests

feat(credential-providers): pass caller client options to fromTemporaryCredentials inner STSClient

---

packages/credential-provider-node/src/remoteProvider.ts

Setting the environment variable `AWS_EC2_METADATA_DISABLED` to "false" causes the condition to evaluate as `true`, which disables the IMDS credentials check.

fix(credential-provider-node): handle string value `AWS_EC2_METADATA_DISABLED=false`

---

scripts/turbo/index.js

makes the read/write behavior of turborepo configurable with an env var

chore(build): set cache read/write based on build type

---

packages/credential-provider-ini/src/fromIni.spec.ts
packages/credential-provider-ini/src/fromIni.ts
supplemental-docs/CLIENTS.md

https://github.com/aws/aws-sdk-js-v3/issues/3396
Exposes the `ignoreCache` option for `fromIni` credential provider. 
To note, if you run a test script using the `fromIni` credential provider (loading credentials from the `~/.aws/credentials` file) separately each time, the Node.js process starts fresh each time, so there's no cached state between runs. But, if you modify the credentials file within the same running process, we can see the caching in effect - the credentials wouldn't update even after waiting for a while.
The exposed option `ignoreCache` will allow uncached/refreshed credentials from the credentials file to be used, even if the credentials file is modified within the same running process. 
`credential-provider-ini` package updated tests
```console
✓ src/fromIni.spec.ts …
```

feat(credential-provider-ini): add ignoreCache option

---

scripts/copy-smithy-dist-files.js

use node:fs to copy files in a script instead of `cp`, which is for some reason very slow on my computer

chore(scripts): use Node.js fs to copy Smithy folders instead of shell

---

packages/middleware-flexible-checksums/src/middleware-md5-fallback.e2e.spec.ts
supplemental-docs/MD5_FALLBACK.md

Documentation for using MD5 checksums as fallback.
`packages/middleware-flexible-checksums/src/middleware-md5-fallback.e2e.spec.ts`:
```console
✓ src/middleware-md5-fallback.e2e.spec.ts (2) 4465ms
✓ S3 MD5 Fallback for DeleteObjects (2) 4464ms
✓ should use CRC32 checksum by default for DeleteObjects
✓ should use MD5 checksum for DeleteObjects with middleware 309ms
Test Files  1 passed (1)
Tests  2 passed (2)
Start at  19:50:55
Duration  5.05s (transform 201ms, setup 0ms, collect 326ms, tests 4.46s, environment 0ms, prepare 84ms)
```
---

docs(supplemental-docs): md5 checksum fallback for s3

---

packages/middleware-flexible-checksums/src/configuration.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/middleware-flexible-checksums.e2e.spec.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.spec.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.ts
packages/middleware-sdk-s3/src/check-content-length-header.spec.ts
packages/middleware-sdk-s3/src/check-content-length-header.ts
private/aws-client-api-test/src/client-interface-tests/client-s3/impl/initializeWithMaximalConfiguration.ts
supplemental-docs/CLIENTS.md

helps with https://github.com/aws/aws-sdk-js-v3/issues/6859
Attempts to buffer input stream chunks to a minimum required size as required by S3, as described in https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html.
This is for input streams e.g. S3 PUT Object or Part.
With checksumming on, user streams go through a filter called AWS chunked encoding. This process annotates every stream chunk with its size and thus the chunks are sent to S3 as-is in whatever size the user provides them, instead of Node.js being able to automatically buffer smaller chunks.
S3 has always required a chunk size of 8kb, preferably 64kb, but due to automatic buffering this was rarely an issue prior to the introduction of default checksums.
As a mitigation / convenience feature, the JS SDK can …

fix(middleware-flexible-checksums): buffer stream chunks to minimum required size

---

scripts/generate-clients/config.js

https://github.com/smithy-lang/smithy-typescript/pull/1527
Update smithy-ts commit to include variable allocation in StringStore
* CI
* Verified that source code was not updated
---

fix(codegen): variable allocation in StringStore

---

codegen/generic-client-test-codegen/build.gradle.kts
codegen/gradle.properties
codegen/protocol-test-codegen/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts
codegen/settings.gradle.kts

https://github.com/smithy-lang/smithy-typescript/pull/1499
* Bumps smithy-gradle-version to `1.2.0`
* Introduces smithyPluginVersion property, and pins it to `0.6.0`
* CI
* Verified that generated clients were not updated
---

chore(codegen): bump smithy-gradle-version to 1.2.0

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-5739
Bumps codegen version to 0.27.0
CI
---

chore(codegen): bump codegen version to 0.27.0

---

packages/credential-providers/README.md

fix missing quote in fromSSO example code
The CommonJS "require" code in the example is missing a quote
```js
const { fromSSO } = require("@aws-sdk/credential-providers") // CommonJS import
```
---

credential-providers README - fix missing quote in fromSSO

---

supplemental-docs/MD5_FALLBACK.md

clarification regarding [`DeleteObjects`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) requiring Content-MD5 header.
---

chore(supplemental-docs): md5 fallback for DeleteObjects update

---

packages/cloudfront-signer/README.md
packages/cloudfront-signer/src/sign.spec.ts
packages/cloudfront-signer/src/sign.ts

#6403
This PR adds changes in the parseDate function to use date constructor instead of Date.parse() to support timestamps in milliseconds.
Locally by testing it with milliseconds and date format string inputs.
``` RUN  v2.1.9 /local/home/smilkuri/aws-sdk-js-v3/packages/cloudfront-signer
✓ src/sign.spec.ts (25)
✓ getSignedUrl (11)
✓ should maintain query params after signing a URL
✓ should include url path in policy of signed URL
✓ should sign a URL with a canned policy
✓ should sign a URL with a custom policy containing a start date
✓ should sign a URL with a custom policy containing an ip address
✓ should sign a URL with a custom policy containing a start date and ip address
✓ should allow an ip address with and without a mask
✓ should throw an error when the ip address is invalid
✓ …
```

fix(cloudfront-signer): parse date using Date constructor

---

packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.ts

#6960
Passes through credentials parameter object when wrapping the credential provider
Minimal reproduction example in linked issue
Fixes inadvertent behaviour change. Issue recently rolled out into bundled Lambda runtime.
---

fix: pass through credentials parameters when wrapping the provider

---

packages/core/api-extractor.json
packages/core/src/api-extractor-type-index.d.ts
packages/core/src/submodules/account-id-endpoint/AccountIdEndpointModeConfigResolver.ts
packages/core/src/submodules/account-id-endpoint/AccountIdEndpointModeConstants.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/AwsSdkSigV4Signer.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.ts
packages/core/src/submodules/protocols/json/parseJsonBody.ts
packages/core/src/submodules/protocols/xml/parseXmlBody.ts
packages/middleware-endpoint-discovery/api-extractor.json
packages/middleware-endpoint-discovery/src/configurations.ts
packages/middleware-endpoint-discovery/src/getEndpointDiscoveryPlugin.ts
packages/middleware-endpoint-discovery/src/resolveEndpointDiscoveryConfig.ts
packages/middleware-host-header/api-extractor.json
packages/middleware-host-header/src/index.ts
scripts/validation/submodules-linter.js

several parts of the public `client.config` interface lack API documentation because of missing access level annotations and missing api-extractor configs
additionally, api extractor [does not support multiple entry points](https://github.com/microsoft/rushstack/issues/3557), so I have created a fake type index for the `@aws-sdk/core` package. 
I noticed these while looking into https://github.com/aws/aws-sdk-js-v3/issues/6960

docs: fix api-extractor configuration and add missing annotations

---

packages/middleware-flexible-checksums/api-extractor.json
packages/middleware-flexible-checksums/package.json
packages/middleware-flexible-checksums/src/NODE_REQUEST_CHECKSUM_CALCULATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/NODE_RESPONSE_CHECKSUM_VALIDATION_CONFIG_OPTIONS.ts
packages/middleware-flexible-checksums/src/configuration.ts
packages/middleware-flexible-checksums/src/constants.ts
packages/middleware-flexible-checksums/src/crc64-nvme-crt-container.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsInputMiddleware.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsMiddleware.ts
packages/middleware-flexible-checksums/src/flexibleChecksumsResponseMiddleware.ts
packages/middleware-flexible-checksums/src/getFlexibleChecksumsPlugin.ts
packages/middleware-flexible-checksums/src/resolveFlexibleChecksumsConfig.ts

adds missing api extractor configs and api annotation to the flexible checksums package

docs(middleware-flexible-checksums): add api annotations

---

packages/middleware-endpoint-discovery/package.json
packages/middleware-host-header/package.json

adds `extract:docs` scripts to packages that recently had api-extractor.json configuration added

docs: add missing extract:docs commands

---

packages/core/api-extractor.json
packages/core/package.json
packages/core/src/api-extractor-type-index.d.ts
packages/core/src/api-extractor-type-index.ts
scripts/validation/submodules-linter.js

fix the build step for the core package
the recently introduced `.d.ts` file was causing issues with the compilation inclusion set

chore(core): fix compilation build

---

lib/lib-storage/src/lib-storage.e2e.spec.ts

Internal JS-5789
increase timeout for hooks to allow proper resource creation for integ tests
```console
.
.
.
.
✓ src/lib-storage.e2e.spec.ts (60) 186035ms
✓ @aws-sdk/lib-storage (60) 186035ms
✓ requestChecksumCalculation: undefined (20) 62171ms
.
.
✓ ChecksumAlgorithm: CRC32C (4) 12920ms
✓ should upload in parts for input type bytes 2769ms
✓ should upload in parts for input type string 3673ms
✓ should upload in parts for input type Readable 2520ms
✓ should call AbortMultipartUpload if unable to complete a multipart upload. 1665ms
Test Files  1 passed (1)
Tests  60 passed (60)
Start at  20:15:48
Duration  186.78s
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

test(lib-storage): increase timeout for hooks calling getIntegTestResources

---

packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.ts
packages/nested-clients/package.json
packages/polly-request-presigner/src/getSignedUrls.ts
packages/types/src/function.spec.ts
packages/types/src/function.ts
packages/types/src/index.ts

https://github.com/aws/aws-sdk-js-v3/issues/6960
This corrects the type declaration of the resolved version of `client.config.credentials`.
Specifically, it restores the `MemoizedProvider` type, merging it with the type that had overwritten it from SRA ID&Auth. 
Added type assertion test

fix(core/httpAuthSchemes): fix type declaration of resolved credentials

---

packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.spec.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/resolveAwsSdkSigV4Config.ts
packages/credential-provider-node/src/credential-provider-node.integ.spec.ts

https://github.com/aws/aws-sdk-js-v3/issues/6954
After merging the "[client config object custody](https://github.com/aws/aws-sdk-js-v3/pull/6959)" feature, the fix to allow extensions to set credentials is to read credentials from the config object when creating the signer.
added integration test

fix(core/httpAuthSchemes): allow extensions to set signer credentials

---

private/aws-client-api-test/src/client-credentials-tests/client-credentials-force-refresh.spec.ts

https://github.com/aws/aws-sdk-js-v3/issues/6960
Adds integration test for credentials forceRefresh
CI
---

test(aws-client-api-test): integration test for credentials forceRefresh

---

scripts/turbo/index.js

Internal 5781
It enables full output logs only for the packages with errors during the Turbo build by changing the configuration from `output-logs=hash-only` to `output-logs=errors-only`.
Locally.
Build output before making the change if there is any error in a workspace:
```
@aws-sdk/cloudfront-signer:build: ERROR: command finished with error: command (/local/home/smilkuri/aws-sdk-js-v3/packages/cloudfront-signer) /tmp/xfs-45e744bc/yarn run build exited (1)
@aws-sdk/util-user-agent-node:build: cache hit, suppressing logs 250d8ac137df25a0
@aws-sdk/signature-v4-multi-region:build: cache hit, suppressing logs cc2e11db6290d72a
@aws-sdk/cloudfront-signer#build: command (/local/home/smilkuri/aws-sdk-js-v3/packages/cloudfront-signer) /tmp/xfs-45e744bc/yarn run build exited (1)
Tasks:    52 …
```

chore(ci): enable error output logging for turbo build

---

lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.ts
lib/lib-dynamodb/src/test/lib-dynamodb.e2e.spec.ts

closes https://github.com/aws/aws-sdk-js-v3/pull/6984
use args.input instead of command.input in lib dynamodb middleware
e2e tests have been updated to set and verify the input field ConsistentRead via middleware.

fix(lib-dynamodb): read input from middleware instead of command

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-5804
Bumps codegen version to 0.28.0
CI

chore(codegen): bump codegen version to 0.28.0

---

private/aws-util-test/package.json
private/aws-util-test/tsconfig.json
yarn.lock

relates to https://github.com/aws/aws-sdk-js-v3/pull/7001
The issue 7001 originally tried to fix is from the build step. aws-util-test does not take a dependency on weather because it only uses it in the integration test step. Integ tests run after everything is built, so no dependencies need to be declared for integ.spec.ts files.
The problem arises in that the tsconfig did not properly exclude the integration spec files from the build step, so the undeclared dependency would be inconsistently built by that time. The fix should be applied to the tsconfig file and not taking a dependency.

chore(aws-util-test): remove spec files from build

---

packages/middleware-flexible-checksums/src/middleware-md5-fallback.e2e.spec.ts
supplemental-docs/MD5_FALLBACK.md

- make middleware ordering relative to `flexibleChecksumsMiddleware`
- update instructions regarding the `DeleteObjects` command
E2E test to confirm removal and addition of relevant headers (uncomment logging in the test file to confirm the headers)
```console
[DeleteObjectsCommand] Headers before MD5 middleware: {
"content-type": "application/xml",
"content-length": "145",
"Expect": "100-continue",
"x-amz-sdk-checksum-algorithm": "CRC32",
"x-amz-checksum-crc32": "<signature>"
}
[DeleteObjectsCommand] Removing header: x-amz-sdk-checksum-algorithm
[DeleteObjectsCommand] Removing header: x-amz-checksum-crc32
[DeleteObjectsCommand] Added Content-MD5: <signature>
[DeleteObjectsCommand] Headers after MD5 middleware: {
"content-type": "application/xml",
"content-length": "145",
"Expect": …
```

test(middleware-flexible-checksums): update instructions for MD5 fallback

---

scripts/generate-clients/config.js

Brings in the fix from https://github.com/smithy-lang/smithy-typescript/pull/1559. 
No codegen diff.

chore(codegen): array flatten fix for operationContextParams

---

codegen/gradle.properties
private/aws-protocoltests-ec2/src/endpoints.ts
private/aws-protocoltests-json-10/src/endpoints.ts
private/aws-protocoltests-json-machinelearning/src/endpoints.ts
private/aws-protocoltests-json/src/endpoints.ts
private/aws-protocoltests-query/src/endpoints.ts
private/aws-protocoltests-restjson-apigateway/src/endpoints.ts
private/aws-protocoltests-restjson-glacier/src/endpoints.ts
private/aws-protocoltests-restjson/src/endpoints.ts
private/aws-protocoltests-restxml/src/commands/NestedXmlMapWithXmlNameCommand.ts
private/aws-protocoltests-restxml/src/endpoints.ts
private/aws-protocoltests-restxml/src/models/models_0.ts
private/aws-protocoltests-restxml/src/protocols/Aws_restXml.ts
private/aws-protocoltests-restxml/test/functional/restxml.spec.ts
private/aws-protocoltests-smithy-rpcv2-cbor/test/functional/rpcv2cbor.spec.ts
scripts/generate-clients/config.js

Internal - JS-5827
Upgrades smithy version to 1.55.0
CI
---

chore(codegen): update smithy to 1.55.0

---

lib/lib-dynamodb/src/baseCommand/DynamoDBDocumentClientCommand.ts

Removes the log function overrides set by the DynamoDBDocumentClientCommand abstract base class.
The overwriting of the log functions caused stale values to be logged under concurrent invocation.
The original reasoning for having the logging overrides does not apply to DynamoDB because it currently has no sensitive fields and is not likely to add any. Even if it did, it would not be inside a AttributeValue <-> JS Object mapping, so the base dynamodb client's log filter would still apply to the document client in such cases.

fix(lib-dynamodb): remove log filter overrides

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-5859
Bumps codegen version to 0.29.1
CI
---

chore(codegen): bump codegen version to 0.29.1

---

packages/signature-v4-multi-region/src/cloudfront-kvs-sigv4a.e2e.spec.ts

use long-lived resources for cloudfront key-value store e2e test (for sigv4a)
```console
✓ src/cloudfront-kvs-sigv4a.e2e.spec.ts (2) 11572ms
✓ src/eventbridge-sigv4a-put-api.e2e.spec.ts (2) 1051ms
Test Files  2 passed (2)
Tests  4 passed (4)
Start at  21:29:11
Duration  12.32s (transform 446ms, setup 0ms, collect 985ms, tests 12.62s, environment 0ms, prepare 178ms)
```
---

test(signature-v4-multi-region): long-lived resources for cfkvs sigv4a e2e test

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddProtocols.java

This change moves the AWS protocols to after the Smithy protocols.
This allows AWS builds to select the `AwsSmithyRpcV2Cbor` override of `SmithyRpcV2Cbor`.

fix(codegen): run aws protocols after smithy protocols

---

verdaccio/config.yaml

Internal JS-5879
This PR adds the `offline_publish: true` setting to the configuration in the Verdaccio config.yaml file. This change allows publishing the packages even when the registry is offline or when the npmjs uplink is not available.
CI
---

chore(verdaccio): enable offline publishing for packages

---

packages/core/src/submodules/httpAuthSchemes/aws_sdk/NODE_AUTH_SCHEME_PREFERENCE_OPTIONS.spec.ts
packages/core/src/submodules/httpAuthSchemes/aws_sdk/NODE_AUTH_SCHEME_PREFERENCE_OPTIONS.ts
packages/core/src/submodules/httpAuthSchemes/utils/getBearerTokenEnvKey.spec.ts
packages/core/src/submodules/httpAuthSchemes/utils/getBearerTokenEnvKey.ts

Internal JS-5860
Returns httpBearerAuth in authSchemePreference if token is set in env
Unit tests
---

chore(core): return httpBearerAuth in authSchemePreference if token is set in env

---

tests/e2e/ensure-test-stack.js

Internal JS-5881
Adds a 5-min waitTime for the ChangeSet waiter and adds a catch block for the error handling
CI
---

test(e2e): improve CloudFormation changeset error handling and timeout

---

.gitignore
scripts/turbo/index.js

Allows individual developers to use a `turbo.dev.json` file to override build settings.
I intend to use
```json
{
"concurrency": 4,
"outputLogs": "new-only"
}
```
which lowers the concurrency and increases the output logging for development.

chore(build): allow turbo dev config

---

scripts/validation/package-graph-analyzer.js

Update the package graph analyzer script.
The current output is:
```
@aws-sdk/cloudfront-signer: ---- NONE ----
@aws-sdk/crc64-nvme-crt: ---- NONE ----
@aws-sdk/dsql-signer: ---- NONE ----
@aws-sdk/ec2-metadata-service: ---- NONE ----
@aws-sdk/karma-credential-loader: -- devtool --
@aws-sdk/middleware-api-key: ---- NONE ----
@aws-sdk/middleware-http-debug-log: ---- NONE ----
@aws-sdk/middleware-sdk-sts: ---- NONE ----
@aws-sdk/middleware-token: ---- NONE ----
@aws-sdk/polly-request-presigner: ---- NONE ----
@aws-sdk/rds-signer: ---- NONE ----
@aws-sdk/s3-presigned-post: ---- NONE ----
@aws-sdk/s3-request-presigner: ---- NONE ----
@aws-sdk/signature-v4a: ---- NONE ----
@aws-sdk/smithy-client: ---- NONE ----
@aws-sdk/util-create-request: ---- NONE ----
@aws-sdk/util-dns: ---- NONE ---- …
```

chore(scripts): update package graph analysis script

---

private/aws-util-test/tsconfig.types.json

Internal JS-5932
The `.spec.ts` files had [already been excluded](https://github.com/aws/aws-sdk-js-v3/pull/7003) from the cjs tsconfig, due to an old non-deterministic build failure.
This also adds that exclusion to the types tsconfig.

chore(aws-util-test): exclude spec files from types build

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegration.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPluginsTest.java
codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AwsEndpointGeneratorIntegrationTest.java

fix some CI errors relating to unused import and deprecated test suite
we have additional backlog ticket to remove the class, which I'll leave for later.

test(codegen): unblock CI status check

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsSmithyRpcV2Cbor.java
packages/core/src/submodules/protocols/json/parseJsonBody.spec.ts
packages/core/src/submodules/protocols/json/parseJsonBody.ts

Our current awsQueryCompatibility implementations reads the `x-amzn-query-error` response header and places this value in the error object's `Code` field.
However, our error parsers read from the `code` field, missing that data.
For the end users, this can cause the thrown error to have a generic "ServiceException" type rather than a more specific type, but it will contain the same data fields. This affects clients for services running in awsQueryCompatibility mode (currently only SQS).
related: https://github.com/smithy-lang/smithy-typescript/pull/1597

fix(core/protocols): read error code case-insensitively

---

packages/cloudfront-signer/README.md

Fixed:- The second example has a typo "const cookies" instead of "const signedUrl".

docs(cloudfront-signer): Fixed typo in example code

---

lib/lib-dynamodb/src/test/lib-dynamodb.e2e.spec.ts

Internal JS-5881
This fix addresses the `TransactionCanceledException` errors in Dynamodb e2e test by reading each item after TransactWrite to ensure all transaction locks are released, preventing conflicts.
CI
---

test(lib-dynamodb): add consistent reads between transactWrite and transactRead

---

packages/middleware-flexible-checksums/src/middleware-md5-fallback.e2e.spec.ts

Internal JS-5881
This PR resolves the transient hook timed out error by increasing the beforeAll and afterAll hook timeout to 60 seconds in S3-md5-fallback test suite. 
CI
---

test(middleware-flexible-checksums): increase hook timeout to 60s

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-5961
Releasing 0.31.0
synchronized with https://github.com/smithy-lang/smithy-typescript/pull/1617
---

chore(codegen): bump codegen version to 0.31.0

---

packages/middleware-http-debug-log/README.md
packages/middleware-http-debug-log/src/getMiddlewareTimerPlugin.ts
packages/middleware-http-debug-log/src/index.ts

This adds a plugin for measuring the time spent in individual middleware functions.
The package is private and not released to NPM.

chore(middleware-http-debug-log): add middleware timer

---

Makefile
clients/client-s3-control/package.json
clients/client-s3-control/src/S3ControlClient.ts
clients/client-s3-control/src/models/models_1.ts
clients/client-s3-control/src/runtimeConfig.shared.ts
clients/client-s3-control/src/runtimeConfig.ts
clients/client-s3-control/test/S3Control.spec.ts
clients/client-s3/src/S3Client.ts
clients/client-s3/src/models/models_0.ts
clients/client-s3/src/models/models_1.ts
clients/client-s3/src/runtimeConfig.shared.ts
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3ControlDependency.java
packages/middleware-bucket-endpoint/src/NodeUseArnRegionConfigOptions.spec.ts
packages/middleware-bucket-endpoint/src/NodeUseArnRegionConfigOptions.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.spec.ts
packages/middleware-bucket-endpoint/src/bucketEndpointMiddleware.ts
packages/middleware-bucket-endpoint/src/bucketHostname.spec.ts
packages/middleware-bucket-endpoint/src/bucketHostname.ts
packages/middleware-bucket-endpoint/src/bucketHostnameUtils.ts
packages/middleware-bucket-endpoint/src/configurations.ts
packages/middleware-sdk-s3-control/src/configurations.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/getProcessArnablesPlugin.spec.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/getProcessArnablesPlugin.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/parse-outpost-arnables.ts
packages/middleware-sdk-s3-control/src/process-arnables-plugin/update-arnables-request.ts
tests/endpoints-2.0/endpoints-integration.spec.ts
yarn.lock

The client endpoint tests are now run through the client, including its full serializer behavior.
This also defers some legacy endpoint validations in S3 Control middleware to the endpoint rulesets.

 test(clients): run endpoint tests in client mode

---

packages/credential-providers/src/fromNodeProviderChain.ts

Fixes https://github.com/aws/aws-sdk-js-v3/issues/5150
This PR updates the link for `the default provider for Node.js SDK` on this [page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/Function/fromNodeProviderChain1/).

fix(docs): update broken link for NodeProviderChain

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-6010
Bumps codegen version to 0.31.1
CI
---

chore(codegen): bump codegen version to 0.31.1

---

codegen/gradle/wrapper/gradle-wrapper.properties

Upgrade gradle version to 8.13
Ran `./gradlew clean build` in codegen directory and also tested that are no changes in clients by running `yarn generate-clients --d`
---

chore: bump gradle to 8.13

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddDefaultAwsEndpointRuleSet.java
codegen/smithy-aws-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
scripts/validation/endpointRuleSet-structure-analyzer.js

This PR follows up with 
https://github.com/smithy-lang/smithy-typescript/pull/1589 adds default endpoint ruleset
https://github.com/aws/aws-sdk-js-v3/pull/7077
The smithy-ts default endpoint ruleset is equivalent to the "customEndpoint" deprecated plugin where an endpoint is **required** during client instantiation.
This PR overrides the default endpoint ruleset when the model is for an AWS service. It uses an alternate default endpoint ruleset patterned after **regional AWS services**. In this ruleset, endpoint input for the client is not required, since the endpoint may be derived from the region and service endpoint prefix.
This supports Amazon/AWS model builds that occur outside of our SDK release platform, which normally applies the default endpoint rulesets. This default does not …

fix(codegen): add default aws regional endpoints for generated clients

---

packages/xhr-http-handler/src/xhr-http-handler.spec.ts
packages/xhr-http-handler/src/xhr-http-handler.ts

Internal JS-5992
Support per-request timeouts if provided, fallback to the timeout provided in handler config.
```console
RUN  v2.1.9 /local/home/sidddsri/workspace/aws-sdk-js-v3/packages/xhr-http-handler
✓ src/index.spec.ts (1)
✓ src/xhr-http-handler.spec.ts (8) 314ms
Test Files  2 passed (2)
Tests  9 passed (9)
Start at  18:06:33
Duration  1.10s (transform 129ms, setup 0ms, collect 214ms, tests 317ms, environment 848ms, prepare 181ms)
```
Partner PR in smithy-ts: https://github.com/smithy-lang/smithy-typescript/pull/1636
---

feat(xhr-http-handler): add support for per-request/per-operation timeouts

---

codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/auth/http/integration/AwsSdkCustomizeHttpBearerTokenAuth.java

Internal JS-5860
Gets token from environment, if required
Done in JS-5860
---

chore(codegen): get token from environment if required

---

clients/client-cloudwatch/package.json
clients/client-cloudwatch/test/e2e/query-compatibility.e2e.spec.ts
clients/client-cloudwatch/tsconfig.json
clients/client-cloudwatch/tsconfig.types.json
clients/client-cloudwatch/vitest.config.e2e.ts
clients/client-cloudwatch/vitest.config.ts

Internal JS-6017
Implements smoke test equivalent for AmbiguousErrorResolution to ensure ResourceNotFound error code consistently maps to expected exception type,
Locally
```
RUN  v2.1.9 /local/home/smilkuri/aws-sdk-js-v3/clients/client-cloudwatch
✓ test/e2e/query-compatibility.e2e.spec.ts (1) 541ms
✓ CloudWatch Query Compatibility E2E (1) 541ms
✓ AmbiguousErrorResolution 535ms
Test Files  1 passed (1)
Tests  1 passed (1)
Start at  02:21:52
Duration  1.06s (transform 141ms, setup 0ms, collect 246ms, tests 541ms, environment 0ms, prepare 90ms)
```
---

test(client-cloudwatch): add query compatibility test for error shape ambiguity

---

codegen/gradle.properties
codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
private/aws-protocoltests-restjson-schema/src/schemas/schemas.ts
private/aws-protocoltests-restjson-schema/test/functional/restjson1.spec.ts
private/aws-protocoltests-restjson/test/functional/restjson1.spec.ts
private/aws-restjson-server/test/functional/restjson1.spec.ts
scripts/generate-clients/config.js

Upgrade smithy version to 1.59.0
---

chore(codegen): upgrade smithy version to 1.59.0

---

tests/e2e/delete-stale-changesets.js

Internal JS-5881
Modified `deleteStaleChangesets()` to only delete changesets older than 5 minutes to prevent deletion of changesets that are actively being processed by other test processes.
CI
---

fix(tests): prevent changeset race condition in parallel tests

---

packages/core/package.json
private/aws-protocoltests-restxml-schema/package.json
private/aws-protocoltests-restxml/package.json
scripts/generate-clients/config.js
yarn.lock

#7174
Update `fast-xml-parser` to support ESM
No new tests were created, but I was able to manually update the dependency in my local environment by adding the following to my package.json to force it to use version 5.2.5 and xml based web services continued to work in basic smoke testing.
```js
"overrides": {
"fast-xml-parser": "5.2.5"
}
```
This can reduce bundle size by ~18K if you use esbuild.
---

chore(deps): bump fast-xml-parser from 4.4.1 to 5.2.5

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-6058
Bumps codegen version to 0.33.0
N/A
---

chore(codegen): bump codegen version to 0.33.0

---

packages/signature-v4-crt/package.json
packages/util-endpoints/package.json

set sideEffects=true in signature-v4-crt and util-endpoints (AWS).
- signature-v4-crt has module-level code that injects the implementation to a dependency container that is checked in signature-v4-multi-region
- util-endpoints adds implementation functions to the core endpoints lib at the module level

chore(packages): set sideEffects metadata

---

packages/core/src/submodules/protocols/xml/XmlShapeDeserializer.ts

chore(core/protocols): fix for XML shape deser

---

packages/util-endpoints/src/env-endpoint.integ.spec.ts

Adds integ test for the AWS_ENDPOINT_URL feature.

test(util-endpoints): add AWS_ENDPOINT_URL integ test

---

.github/workflows/git-sync.yml

Internal JS-6078
Uses ssh private key for git sync
Referred documentation https://github.com/wei/git-sync
Once this commit is merged, we'll verify that git-sync is successful.
On success, we'll delete the following:
* Secret: `GIT_SYNC_SOURCE_REPO`
* Secret: `GIT_SYNC_SOURCE_SSH_PRIVATE_KEY`
* Secret: `GIT_SYNC_DESTINATION_SSH_PRIVATE_KEY`
* Deploy key on this repo: `git-sync-source-public-key`
* Deploy key on destination repo: `git-sync-destination-public-key`
The ssh key rotate instructions will be updated to populate private key in secret `GIT_SYNC_SSH_PRIVATE_KEY`
---

chore(scripts): use ssh private key for git sync

---

lib/lib-dynamodb/README.md

internal JS-6074
This adds a documentation example for performing a table scan using the `@aws-sdk/lib-dynamodb` wrapper client.
manual testing to confirm code example works

docs(lib-dynamodb): example for performing table scan

---

packages/cloudfront-signer/src/sign.spec.ts
packages/cloudfront-signer/src/sign.ts

* Internal JS-6008
* The implementation is similar to one in Ruby https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-cloudfront/lib/aws-sdk-cloudfront/url_signer.rb
Removes creation of URL object
CI
---

fix(cloudfront-signer): do not use URL Object

---

Makefile
package.json
tests/bundlers/Makefile
tests/bundlers/package.json
tests/bundlers/source.ts
tests/bundlers/test.spec.mjs
tests/bundlers/vite.config.ts
tests/bundlers/webpack.config.js
yarn.lock

n/a
PR adds a test to the e2e group, though it does not call AWS. 
The test generates two browser bundles of S3 with a single Command using both vite (rollup at the moment) and webpack. The test asserts that the bundle contents are properly tree-shaken, used the correct browser file-replacements, and are not excessively large.
running the test in the PR
sometimes subtle changes can cause treeshaking bailout, especially by webpack.
We have a size benchmark module, but it is non-blocking and hasn't updated many of its packages: https://github.com/aws/aws-sdk-js-v3/blob/main/benchmark/size/report.md

test(bundlers): add e2e test for bundler tree-shaking

---

packages/core/src/submodules/protocols/idempotencyToken.spec.ts
packages/core/src/submodules/protocols/json/JsonShapeSerializer.ts
packages/core/src/submodules/protocols/json/jsonReplacer.ts
packages/core/src/submodules/protocols/query/QueryShapeSerializer.ts
packages/core/src/submodules/protocols/xml/XmlShapeSerializer.ts

https://github.com/smithy-lang/smithy-typescript/issues/1600
Generate idempotency tokens in ShapeSerializers used by schema-serde.
New unit test

chore(core/protocols): generate idempotencyTokens in ShapeSerializers

---

private/aws-protocoltests-smithy-rpcv2-cbor-schema/test/functional/rpcv2cbor.spec.ts

The AWS equivalent of tests skipped in https://github.com/smithy-lang/smithy-typescript/pull/1663
Skip protocol tests which are failing in vitest 3.x
N/A, as it's codegen.
---

test(aws-protocoltests-smithy-rpcv2-cbor-schema): skip tests not working in vitest 3.x

---

private/weather/package.json
yarn.lock

Noticed when upgrading vitest in https://github.com/aws/aws-sdk-js-v3/pull/7270
Removes unused vitest dependency from weather client
* Verified that the client neither contains any tests nor the test config https://github.com/aws/aws-sdk-js-v3/tree/main/private/weather
* The dependency might have been added by mistake in https://github.com/aws/aws-sdk-js-v3/pull/5212
CI
---

chore(weather): remove unused vitest dependency

---

verdaccio/config.yaml

Internal JS-6154
Increase the verdaccio uplink timeout from 30s to 300s
CI
---

chore: increase Verdaccio uplink timeout to 300s

---

Makefile
scripts/build-only-unbuilt.js

none
Adds a script that builds only unbuilt packages. 
`make unbuilt` after running clean in a random client.
Scenario: e.g. some new clients have been added and I don't want to run a full build because I don't need every client to be up to date. Running a full client build is slow.

chore(scripts): script to build only unbuilt packages

---

packages/middleware-flexible-checksums/src/middleware-flexible-checksums.retry.integ.spec.ts

* Internal JS-5905
* Repeat of https://github.com/aws/aws-sdk-js-v3/pull/7277 which uses `requireRequestsFrom` utility for faking response.
Adds an integration test which confirms checksum is not recomputed on retries
* CI
* Dry run is successful
---

test(middleware-flexible-checksums): retry reuses the computed checksum

---

scripts/cli-dispatcher/index.js
tests/bundlers/Makefile
tests/bundlers/test.spec.mjs
tests/bundlers/vite.config.ts
tests/bundlers/webpack.config.js

none
Support multiple sequential commands in a short-form with the local CLI dispatcher devtool.
You can, for example, now run `b s3 - gen,b` to represent `cd clients/client-s3 && yarn generate:clients && yarn:build` instead of running two commands such as `b s3 - gen && b s3 - b`

chore(scripts): support multi-commands in cli dispatcher

---

packages/credential-providers/README.md

internal P283331082
Removes an unneeded and potentially confusing part of the credential providers documentation about STS headers.

docs(credential-providers): remove unnecessary STS header documentation

---

packages/middleware-sdk-s3/src/region-redirect-middleware.spec.ts
packages/middleware-sdk-s3/src/region-redirect-middleware.ts

#7304 
Fixes HeadBucket cross-region redirects for 400 responses for newer regions with `x-amz-bucket-region` header
Locally
```
RUN  v3.2.4 /local/home/smilkuri/aws-sdk-js-v3/packages/middleware-sdk-s3
✓ src/s3-express/classes/S3ExpressIdentityCache.spec.ts (2 tests) 5ms
✓ src/s3-express/classes/S3ExpressIdentityCacheEntry.spec.ts (1 test) 13ms
✓ src/s3-express/classes/S3ExpressIdentityProviderImpl.spec.ts (2 tests) 7ms
✓ src/region-redirect-middleware.spec.ts (4 tests) 5ms
✓ src/validate-bucket-name.spec.ts (3 tests) 5ms
✓ src/s3-express/classes/SignatureV4S3Express.spec.ts (1 test) 2ms
✓ src/check-content-length-header.spec.ts (6 tests) 6ms
✓ src/throw-200-exceptions.spec.ts (6 tests) 11ms
✓ src/s3-express/functions/s3ExpressMiddleware.spec.ts (1 test) 2ms
✓ src/s3Configuration.spec.ts …
```

fix(middleware-sdk-s3): handle cross-region redirects for HeadBucket with 400 status

---

lib/lib-storage/src/types.ts

#7311 
The Upload class uses PutObject, CreateMultipartUpload, UploadPart, and CompleteMultipartUpload operations internally, so the type should accept parameters for all of these commands.
Locally
```
RUN  v3.2.4 /local/home/smilkuri/aws-sdk-js-v3/lib/lib-storage
✓ src/chunks/getChunkUint8Array.spec.ts (6 tests) 7ms
✓ src/chunks/getDataReadableStream.spec.ts (4 tests) 161ms
✓ src/chunks/getDataReadable.spec.ts (3 tests) 161ms
✓ src/index.spec.ts (1 test) 2ms
✓ src/Upload.spec.ts (29 tests) 23777ms
✓ Upload > should add tags to the object if tags have been added multi-part  23724ms
Test Files  5 passed (5)
Tests  43 passed (43)
Start at  14:04:05
Duration  24.74s (transform 655ms, setup 0ms, collect 2.25s, tests 24.11s, environment 1ms, prepare 603ms)
```
- [n/a] If the PR is a feature, …

fix(lib-storage): update Upload params type to intersection of all S3 upload command inputs

---

packages/core/src/submodules/protocols/ProtocolLib.ts
packages/core/src/submodules/protocols/query/AwsQueryProtocol.ts

https://github.com/smithy-lang/smithy-typescript/issues/1600 (epic)
https://github.com/smithy-lang/smithy-typescript/pull/1681 - schema refactor includes adding a namespace string to all unwrapped schema objects, such that the `name` field contains only the short name.
Makes the SDK compatible with both pre and post merge of the above smithy-ts PR.
`make test-protocols` both with current code and changes from [1681](https://github.com/smithy-lang/smithy-typescript/pull/1681)

chore(core/protocols): add fallback for schema short name

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

Internal JS-6204
Bumps codegen version to 0.34.1
CI
---

chore(codegen): bump codegen version to 0.34.1

---

supplemental-docs/ERROR_HANDLING.md

https://github.com/aws/aws-sdk-js-v3/issues/7149
Explain that `instanceof` is once again a valid way to differentiate exceptions from service responses.

docs: update guidance on instanceof Exception checking

---

packages/polly-request-presigner/src/polly-request-presigner.integ.spec.ts

Internal JS-P293169653
The integration test was failing due to changes in the model.json, because the test assertions were too precise and expected 
exact values.
- Updated X-Amz-Date regex from `\d{8}T\d+Z` to `\d{8}T\d{6}Z` for precise timestamp format
- Updated X-Amz-Signature regex from `(.*?)` to `[a-f0-9]+` for hex signature validation
- Updated X-Amz-SignedHeaders regex to accept both 'host' and '%3Aauthority' values
**For existing model**
```
dev-dsk-smilkuri-1a-17aece6b % yarn test:integration
RUN  v3.2.4 /local/home/smilkuri/aws-sdk-js-v3/packages/polly-request-presigner
✓ src/polly-request-presigner.integ.spec.ts (1 test) 19ms
✓ polly-request-presigner > should sign URLs 18ms
Test Files  1 passed (1)
Tests  1 passed (1)
Start at  19:23:50
Duration  558ms (transform 130ms, setup …
```

test(polly-request-presigner): make polly presigner test compatible with model change

---

Makefile
packages/crc64-nvme-crt/src/CrtCrc64Nvme.ts
packages/middleware-flexible-checksums/src/getCrc32ChecksumAlgorithmFunction.ts
packages/middleware-flexible-checksums/src/stringHasher.ts
packages/middleware-sdk-ec2/src/fixture.spec.ts
packages/middleware-sdk-ec2/src/index.spec.ts
packages/middleware-sdk-rds/src/fixture.spec.ts
packages/middleware-sdk-rds/src/index.spec.ts
packages/middleware-signing/src/awsAuthConfiguration.spec.ts
scripts/validation/no-generic-byte-arrays.js

follows https://github.com/smithy-lang/smithy-typescript/pull/1696
Asserts that no dist-types contain Uint8Array with type parameters due to the change in TypeScript 5.7 and the use of inferred types. The validator runs in ~6s including all clients.
Runs during integration tests because by then all packages have been built.

chore(scripts): validate no Uint8Array with type parameters are generated by compiler

---

clients/client-cognito-identity/test/e2e/CognitoIdentity.e2e.spec.ts
clients/client-s3/test/e2e/S3.browser.e2e.spec.ts
clients/client-s3/test/e2e/S3.e2e.spec.ts
clients/client-s3/test/e2e/s3-object-features.e2e.spec.ts
lib/lib-storage/src/lib-storage.e2e.spec.ts
packages/middleware-flexible-checksums/src/middleware-flexible-checksums.e2e.spec.ts
packages/s3-presigned-post/src/createPresignedPost.e2e.spec.ts
private/aws-util-test/package.json
private/aws-util-test/src/e2e/getE2eTestResources.ts
private/aws-util-test/src/index.ts
yarn.lock

internal V1876217767
remove CF changeset calls from e2e tests. The e2e test stack can be set up manually, since it has not changed for years.
Running e2e in S3.

test: remove changesets calls from e2e tests

---

.github/workflows/pull-request-build.yml

n/a
execute a PR build on the PR `opened` event. `synchronized` appears not to include opening the PR.

chore: pull request build on PR opened event

---

packages/core/package.json
packages/core/src/submodules/protocols/ProtocolLib.ts
packages/core/src/submodules/protocols/json/AwsJson1_0Protocol.spec.ts
packages/core/src/submodules/protocols/json/AwsJsonRpcProtocol.ts
packages/core/src/submodules/protocols/json/AwsRestJsonProtocol.spec.ts
packages/core/src/submodules/protocols/json/AwsRestJsonProtocol.ts
packages/core/src/submodules/protocols/json/JsonShapeSerializer.ts
packages/core/src/submodules/protocols/query/AwsQueryProtocol.ts
packages/core/src/submodules/protocols/xml/AwsRestXmlProtocol.spec.ts
packages/core/src/submodules/protocols/xml/AwsRestXmlProtocol.ts
packages/core/src/submodules/protocols/xml/XmlShapeDeserializer.ts
packages/middleware-sdk-ec2/src/index.ts
packages/middleware-sdk-ec2/src/middleware-sdk-ec2.e2e.spec.ts
private/aws-client-retry-test/src/ClientRetryTest.spec.ts
private/aws-middleware-test/src/middleware-content-length.spec.ts
private/aws-middleware-test/src/middleware-serde.spec.ts
yarn.lock

https://github.com/smithy-lang/smithy-typescript/issues/1600
preparatory compatibility fixes for Schemas
Fixes for unreleased features.
- fix for applying the LazyJsonString adapter in cases where the input is a JSON object rather than a string
- change test assertions to ignore ordering of query parameters
- return early for unit schema in XML shape deserializer
- fix to fully populate error fields in AwsQuery protocol
- defer content length determination to the contentLengthMiddleware rather than protocol methods

chore(core/protocols): preparatory fixes for schemas

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts
lib/lib-storage/src/lib-storage.e2e.spec.ts

Internal JS-6196
- Adds validation to check total number of UploadPart requests the SDK has sent matches the expected number of parts.
- Adds validation to check the content length of each UploadPart request matches the expected part size.
Locally
`yarn test` and `yarn test:e2e` are successful
```
dev-dsk-smilkuri-1a-17aece6b % yarn test
RUN  v3.2.4 /local/home/smilkuri/aws-sdk-js-v3/lib/lib-storage
✓ src/chunks/getChunkUint8Array.spec.ts (6 tests) 7ms
✓ src/chunks/getDataReadableStream.spec.ts (4 tests) 168ms
✓ src/chunks/getDataReadable.spec.ts (3 tests) 167ms
✓ src/index.spec.ts (1 test) 2ms
✓ src/Upload.spec.ts (34 tests) 22888ms
✓ Upload > should add tags to the object if tags have been added multi-part  22807ms
Test Files  5 passed (5)
Tests  48 passed (48)
Start at  16:15:06 …
```

fix(lib-storage): add validation for partCount and contentLength for multipart upload

---

lib/lib-storage/src/Upload.spec.ts
lib/lib-storage/src/Upload.ts

#7379 
Fixes a bug where the `partSize` option in the Upload class constructor was completely ignored, causing all multipart uploads to use the calculated part size (max of 5MB and contentLength/10000) regardless of user preference.
Locally
```
dev-dsk-smilkuri-1a-17aece6b % yarn test
RUN  v3.2.4 /local/home/smilkuri/aws-sdk-js-v3/lib/lib-storage
✓ src/chunks/getChunkUint8Array.spec.ts (6 tests) 6ms
✓ src/chunks/getDataReadableStream.spec.ts (4 tests) 165ms
✓ src/chunks/getDataReadable.spec.ts (3 tests) 165ms
✓ src/index.spec.ts (1 test) 2ms
✓ src/Upload.spec.ts (35 tests) 23661ms
✓ Upload > should add tags to the object if tags have been added multi-part  23588ms
Test Files  5 passed (5)
Tests  49 passed (49)
Start at  21:53:02
Duration  24.66s (transform 849ms, setup 0ms, collect 2.15s, …
```

fix(lib-storage): respect user-provided partSize option for Upload

---

scripts/generate-clients/build-smithy-typescript.js

Internal JS-6252
Updates codegen of clients to perform git fetch only when necessary
* CI
* Done in JS-6252
---

chore(codegen): git fetch smithy-ts only when necessary

---

tests/bundlers/applications/NormalizedSchema.ts
tests/bundlers/applications/all-protocols.ts
tests/bundlers/applications/multiple-barebones-micg-sdk-clients.ts
tests/bundlers/applications/multiple-barebones-schema-sdk-clients.ts
tests/bundlers/applications/single-cbor-xml-protocol.ts
tests/bundlers/applications/single-json-protocol.ts
tests/bundlers/applications/single-xml-protocol.ts
tests/bundlers/runner/BundlerSizeBenchmarker.mjs
tests/bundlers/runner/run.mjs

Adds some entries to the bundle benchmark to test bundle sizes of core schema components and protocols

chore: add more bundle types to the benchmark

---

.github/workflows/codegen-ci.yml
scripts/generate-clients/config.js

https://github.com/smithy-lang/smithy-typescript/pull/1724
Uses gradle/actions/setup-gradle for setting up gradle
* codegen-ci was successful
* Extensive testing was done in https://github.com/smithy-lang/smithy-typescript/pull/1724
---

chore(ci): use gradle/actions/setup-gradle for setting up gradle

---

tests/bundlers/runner/BundlerSizeBenchmarker.mjs

prevent vite build from deleting the dist directory between builds, so build artifacts from different builds can be compared

chore: keep vite build directory contents between builds

---

codegen/CHANGELOG.md
codegen/build.gradle.kts
codegen/smithy-aws-typescript-codegen/build.gradle.kts
scripts/generate-clients/config.js

https://github.com/smithy-lang/smithy-typescript/pull/1734
Bumps codegen version to 0.36.1
CI
---

chore(codegen): bump codegen version to 0.36.1

---

codegen/build.gradle.kts

Internal JS-6275
Fix implicit dependency error and duplicate files in smithy-aws-typescript-codegen
- Add explicit dependsOn for set-aws-sdk-versions task
- Set duplicatesStrategy to EXCLUDE for META-INF files
Locally
```
./gradlew :smithy-aws-typescript-codegen:publish
Calculating task graph as configuration cache cannot be reused because file 'build.gradle.kts' has changed.
BUILD SUCCESSFUL in 2s
10 actionable tasks: 5 executed, 5 up-to-date
Configuration cache entry stored.
```
---
By submitting this pull request, I confirm that you …

chore(codegen): fix gradle task dependency and duplicate handling in sourcesJar
